### ISSUE TITLE
Provide an overview page that centralises various resources

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#1]
It would be good to offer a general overview page, with links to this github, the jenkins instance(s), the issue tracker here, downloadable images, installation instructions, status matrices, supported devices and so on.

**Comment by MerlijnWajer** [comment]
We could start with sphinx (or something) plus github pages. But we can also host it on a maemo subdomain.

**Comment by parazyd** [comment]
What are the advantages of sphinx compared to, let's say, plain markdown or rst?

**Comment by MerlijnWajer** [comment]
Just pick something that works, I don't care much. Preference for something restructured text. Sphinx is also rst.

**Comment by MerlijnWajer** [comment]
We can also use the github wiki.

**Comment by parazyd** [comment]
Shall I create a new repo called `documentation` and start writing something in rst? Perhaps we can try out sphinx later on with it...

**Comment by MerlijnWajer** [comment]
What about github pages with sphinx/pelican?

**Comment by MerlijnWajer** [comment]
http://docs.getpelican.com/en/3.6.3/tips.html

**Comment by MerlijnWajer** [comment]
Started with this: https://maemo-leste.github.io/

Need to fill various device pages with info, but I guess we'll do that once we actually have developer-worthy image. (which is, soon, I guess)
