### ISSUE TITLE
Create a wiki for Maemo Leste

### ISSUE THREAD

**Issue by dderby** [maemo-leste/bugtracker#101]
We should create a dedicated wiki to provide documentation for Maemo Leste.

Right now documentation is provided on https://maemo-leste.github.io/ and updates are made with pull requests.  This process can be slow and cumbersome if you only want to make a small edit.  It also creates a barrier for those that want to contribute but don't know how to use Git.

We already have https://wiki.maemo.org/ but this would need to be reworked drastically to indicate what information does not apply to Leste.  This is already an issue for Fremantle as there are some pages which only apply to Chinook, Diablo, etc. but nothing to indicate that.  It's a bit of a mess to be honest so I think it would be better to start afresh and create a brand new wiki, dedicated to Leste.

**Comment by MerlijnWajer** [comment]
If we pick a wiki, then presumably mediawiki is the right choice. The only problem I have with it is that I have set up (and run) multiple media wiki instances, and it's a real pain to manage spam (like: real problem).

(A big advantage of mediawiki is that it is well known AND you can use it directly with git, using git mediawiki)

I could set up a mediawiki instance, but I'd prefer someone else to do this.

**Comment by ollieparanoid** [comment]
From our experience, preventing spam is as easy as adding a question to the registration, that only people who know what the project is about can answer. That works with the on-board stuff from MediaWiki.

Example:
https://wiki.postmarketos.org/index.php?title=Special:CreateAccount&returnto=Main+Page
> To protect the wiki against automated account creation, we kindly ask you to answer the question that appears below (more info): Which distribution is pmOS based on 

You could ask the same question basically :smile: 
To whoever is setting up the wiki, please do not block tor users. I'm really having a hard time on the official Maemo pages because of that.

**Comment by MerlijnWajer** [comment]
Thank you - what plugin would that be? In this case I could set something up.

**Comment by MerlijnWajer** [comment]
I guess I misread - there is no plugin involved.

**Comment by ollieparanoid** [comment]
@MartijnBraam: do you know how we set that up again?

**Comment by MartijnBraam** [comment]
Yep its QuestyCaptcha, very easy to configure. For example:

```php
wfLoadExtension( 'ConfirmEdit' );
wfLoadExtensions([ 'ConfirmEdit', 'ConfirmEdit/QuestyCaptcha' ]);
$wgCaptchaQuestions = [
        'Which distribution is pmOS based on' => ['alpine','alpine linux'],
];
```

**Comment by dderby** [comment]
@MerlijnWajer, I don't mind setting up a MediaWiki instance if you'd rather work on other things.  Never done it before but I'm sure I'll figure it out.  I just need somewhere to install it to.

**Comment by sicelo** [comment]
I'm also available to assist with this if needed.

**Comment by MerlijnWajer** [comment]
@parazyd set one up: https://leste.maemo.org/Main_Page

**Comment by MerlijnWajer** [comment]
I'm hoping we can find one or two people who can take on working on the wiki. I'm available to help out and write some stuff, but preferrably do not want to think about how to structure the wiki, etc.
