### ISSUE TITLE
Droid4: confusing messages during flashing.

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#106]
I'm trying to get Droid4 to boot something non-android, but no success so far. I do have Safestrap 3.73 installed (and it seems to work ok , switching between Jolla and Cyanogenmod).

I used ddroid-2018-02-17.zip. Installation prodcues some warnings "no MD5 file found" -- I guess that's expected, but it is followed by ApplyParsedPerms: lsetfilecon of ... DroidSans.ttf: Operation not supported on transport endpoint (?!). Then it says "E: Error executing updater binary in zip.." and two other errors.

But the end result works. Good! :-). If errors are expected, it might be nice to note that on the device page.

**Comment by MerlijnWajer** [comment]
Hm, I am not sure if I have seen those errors before. I'll have to retry that. And yeah, we should note that. In fact, we should really get that wiki set up. :) 

Thanks for reporting.

**Comment by pavelmachek** [comment]
Actually, could I get your .config and diff against stable kernel? (Or
possibly could you put it on the web for download?)  I'm trying to get
Droid 4 to work, and that would help me a lot.

**Comment by MerlijnWajer** [comment]
This issue is probably helpful: https://github.com/maemo-leste/bugtracker/issues/49
Specifically, here's the patches we use - https://github.com/parazyd/arm-sdk/tree/master/extra/patches/linux-droid4-patches (against 4.14.19 iirc, but I assume anything 4.14.x works)

Also mind you that you need one X patch for X to work with rotation. It's in maemo-leste as well.

**Comment by MerlijnWajer** [comment]
@parazyd - I could not find the .config in the arm-sdk repo, but I'm probably bad a navigating it. Could you link it?

Btw @pavelmachek  - I tried the new patches against 4.16 some time ago and got the device to boot, but drm didn't work, and I don't know what I did wrong at the time, so if you get that to work, please let me know.

**Comment by dderby** [comment]
https://github.com/parazyd/arm-sdk/blob/master/boards/kernel-configs/droid4.config

**Comment by pavelmachek** [comment]
Thanks a lot; I was able to build a serial cable, and now my own
kernel builds work on the device.

-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html

**Comment by MerlijnWajer** [comment]
When you switch to 4.16 (or newer) and get it to work, please let us know. :)

**Comment by pavelmachek** [comment]
For the record, ddroid.zip flash procedure is: (You may want to put it
on the web page where images are downloaded...)

Boot options, select slot with Leste, Activate.

In main menu: Install, scroll down to select ddroid-....zip file,
swipe to confirm flash. You will get error, including
"ApplyParsePerms, set_metadata_recursive, Error executing updater
binary, Unable to mount. Red "failed" will appear.

But everything is okay, proceed by selecting "Reboot System", swipe to
confirm reboot.

Red motorola logo will appear, press search button to continue boot,
phone vibrates, then vibrates again, then green led comes on. After
about a minute, console appears, then disappears and X comes to life.

**Comment by pavelmachek** [comment]
Ok, so v4.16-rc5 is working for me. I'll sent details in email (m...n@w...p.org)

**Comment by MerlijnWajer** [comment]
We now also have a wiki, it might be useful to have this info on there somewhere: https://leste.maemo.org/Main_Page

**Comment by pavelmachek** [comment]
Thanks for pointer, I updated the wiki.

**Comment by MerlijnWajer** [comment]
With this documented, should we close this issue? I am not sure if we have a lot of control over the flashing process.

**Comment by MerlijnWajer** [comment]
Thanks for documenting this!
