### ISSUE TITLE
Wish: switch to ext3 filesystem for Droid4.

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#109]
When something breaks, it is nice to be able to mount filesystem from safestrap and repair stuff. I switched the root filesystem on the SD card to ext3, and that one can be mounted from safestrap for repairs.

**Comment by dderby** [comment]
I've confirmed that SafeStrap is capable of mounting my ext4 filesystem.  I don't remember how I formatted it, I think was probably on the device within SafeStrap (the e2fsprogs are probably old enough to not set those ext4 features by default).  I think disabling those ext4 features on image creation will fix it.

**Comment by MerlijnWajer** [comment]
@parazyd am I right in assuming that building a new droid4 image will already fix this issue (provide a compatible ext4?) Or was that only for the n900 image?

**Comment by dderby** [comment]
It was for the N900 image only:
https://github.com/maemo-leste/image-builder/blob/master/leste.config#L31

**Comment by parazyd** [comment]
Should I build new images for the Droid4 with the same ext4 options like N900 then?

**Comment by parazyd** [comment]
Applied in https://github.com/maemo-leste/image-builder/commit/7f9f9641d2b00bc56233c4bfa63b23bb011ee990
