### ISSUE TITLE
Droid4: Basic phone calls

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#110]
Related to #77. Let's see if we can get this to work.

We need a few patches on top of current linux kernel, possible some additional patches, change some alsamixer states, and we'll need to hack ofono to work with the modem.

@pavelmachek - do you have a working .config (and if it's not an issue) a list of patches that still need to be applied? It takes me a considerable amount of time to compile kernels and find the right patches, so if you have some pointers that'd be really sweet.

Also - @pavelmachek - what GUI do you use currently? `ofone`?

**Comment by pavelmachek** [comment]
Yes, that's the plan.

I have pushed my patches to kernel.org, you can also find .config
there. That's the right one for droid4. (You may want to s/=m/=y/)

To
git@gitolite.kernel.org:pub/scm/linux/kernel/git/pavel/linux-n900.git
   f44dbe2..48c1aab  all-v4.16 -> all-v4.16

Separating patches... would be some work at the moment.

Alsamixer is basically hardcoded in the current kernel hacks. Ignore
that for the moment. Outgoing audio will not work, and current
solution is crazy hack.

I currently use ofone from unicsy_demo, yes.

If you run into problems I can try to help, but no promises -- this is
work in progress.
-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html

**Comment by MerlijnWajer** [comment]
The tree looks good - separate patches are not required if there's a git tree we can use, that's even better. I will be busy for a few more days but hope to join in on the fun soon.

We can package ofono 1.23 for maemo-leste if you think it would be helpful.

**Comment by pavelmachek** [comment]
Ok, good.

I don't think packaging ofonod makes sense at this moment. ofonod from
debian works enough to expose AT commands. Patches will be needed for
better support, but someone has to write those, first.

-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html

**Comment by MerlijnWajer** [comment]
BTW, you probably saw this already, but: https://lkml.org/lkml/2018/12/16/231 - might be worth playing around with too.

**Comment by MerlijnWajer** [comment]
I have successfully tested phone calls with the latest image, using AT commands:

https://leste.maemo.org/Motorola_Droid_4#Phone_Call

**Comment by MerlijnWajer** [comment]
This now also works with ofono. I haven't been able to use the speakerphone (the one close to the ear) or the headphone output yet, though. Only speaker output works for audio during calls for me.

**Comment by IMbackK** [comment]
i dont know what "basic" means in this context, but phone calls with out ui work pretty mutch perfectly now with ofono and ucm2

**Comment by MerlijnWajer** [comment]
Agreed. Nice work everyone involved!
