### ISSUE TITLE
Something shuts down droid4 shortly after boot

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#112]
...and I don't know what it is. I have enough time to run one or two commands in the terminal, then it goes down. Syslog says:

Apr  3 19:43:24 devuan ofonod[2260]: oFono version 1.22
Apr  3 19:43:24 devuan ofonod[2260]: parse_devices_reply: found 1st battery device: /org/freedesktop/UPower/devices/battery_battery
Apr  3 19:43:25 devuan ntpd[2217]: error resolving pool 0.debian.pool.ntp.org: Temporary failure in name resolution (-3)
Apr  3 19:43:26 devuan ntpd[2217]: error resolving pool 1.debian.pool.ntp.org: Temporary failure in name resolution (-3)
Apr  3 19:43:27 devuan ntpd[2217]: error resolving pool 2.debian.pool.ntp.org: Temporary failure in name resolution (-3)
Apr  3 19:43:28 devuan ntpd[2217]: error resolving pool 3.debian.pool.ntp.org: Temporary failure in name resolution (-3)
Apr  3 19:43:40 devuan kernel: [   99.691864] cpcap-usb-phy cpcap-usb-phy.0: connected to USB host
Apr  3 19:43:44 devuan shutdown[2373]: shutting down for system halt
Apr  3 19:43:44 devuan init: Switching to runlevel: 0
Apr  3 19:43:46 devuan ofonod[2260]: Terminating
Apr  3 19:43:46 devuan ofonod[2260]: Exit
Apr  3 19:43:46 devuan ntpd[2217]: ntpd exiting on signal 15 (Terminated)
Apr  3 19:43:46 devuan NetworkManager[2160]: <info>  [1522784626.8736] caught SIGTERM, shutting down normally.
Apr  3 19:43:46 devuan NetworkManager[2160]: <info>  [1522784626.8953] exiting (success)
Apr  3 19:43:47 devuan DSME: removed exited process (pid 2129) from process wd
Apr  3 19:43:47 devuan maemo-invoker[1982]: died receiving bad marker 00000000 when expected e4170000 (INVOKER_MSG_EXIT)
Apr  3 19:43:47 devuan maemo-invoker[2038]: died receiving bad marker 00000000 when expected e4170000 (INVOKER_MSG_EXIT)
Apr  3 19:43:47 devuan DSME: Process '/usr/bin/hildon-status-menu' with pid 1982 exited with return value 1 and restarted with pid 2615
Apr  3 19:43:47 devuan maemo-invoker[1988]: died receiving bad marker 00000000 when expected e4170000 (INVOKER_MSG_EXIT)
Apr  3 19:43:47 devuan maemo-invoker[1984]: died receiving bad marker 00000000 when expected e4170000 (INVOKER_MSG_EXIT)
Apr  3 19:43:47 devuan DSME: Process '/usr/bin/hildon-desktop' with pid 1988 exited with return value 1 and restarted with pid 2616

On successful boots, green LED is lit. When it is going to shut down, no such LED. Is there some kind of watchdog I need to enable or disable?

**Comment by pavelmachek** [comment]
Aha, might this be duplicity of lifeguard reset? But dsme seems to do logging...

**Comment by freemangordon** [comment]
sorry, no idea.

**Comment by pavelmachek** [comment]
Hmm. After >5 attempts, I managed to do "sudo reboot" and this time it came up ok. Green light and stable machine. Interesting.

Does leste do any kind of "bootreason" detection? Are there watchdogs in use? Who does control the green led?

**Comment by MerlijnWajer** [comment]
@freemangordon - could it be related to DSME "user" state? (IIRC)

@pavelmachek - dsme will work with all watchdogs it can find, but I don't think it will be able to issue a normal shutdown if there are watchdog problems. That would likely just result in immediate reboot.

There are a few reasons that cause DSME to restart the device, main ones is stuff like X failing to start. But I think there is also a file that a certain state is written to once, to prevent it from rebooting. @parazyd - do you have this file in your image scripts somewhere?

**Comment by parazyd** [comment]
On Wed, Apr 04, 2018 at 02:48:29PM +0000, Merlijn Wajer wrote:
> There are a few reasons that cause DSME to restart the device, main ones is stuff like X failing to start. But I think there is also a file that a certain state is written to once, to prevent it from rebooting. @parazyd - do you have this file in your image scripts somewhere?

I haven't added any files. Do you mean `dsme/modules/lifeguard.c:80`?

```
#define FILE_REBOOT_OVERRIDE  "/etc/no_lg_reboots"

static char lg_reboot_enabled = 1;
```

**Comment by pavelmachek** [comment]
Maybe not solution but probably workaround:

After powering down Droid4 "hard" (power+down for 10 second) it tends
to boot with green light on and tends to stay up.

**Comment by pavelmachek** [comment]
Seems my reboots very linked to bad power sources. If it is plugged
into something, and green light is not on, it will power down. (It
would be really nice to print something in the syslog).

Plugging droid4 into an usb hub seems to trigger that quite often.

-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html

**Comment by parazyd** [comment]
What should we do with this ticket?

**Comment by pavelmachek** [comment]
Droid 4 needs a lot more work... and this one is old. I managed to get it to somehow work...
