### ISSUE TITLE
icd2: Add doxygen documentation

### ISSUE THREAD

**Issue by parazyd** [maemo-leste/bugtracker#114]
Doxygen data as to be added where applicable.

http://maemo.org/api_refs/5.0/5.0-final/icd2/index.html

**Comment by sicelo** [comment]
Please assign this issue/task to me, or it only allows assigning to people that are part of the organization on GH?

**Comment by MerlijnWajer** [comment]
Yeah, there doesn't seem to be an option to assign. Odd.

**Comment by spinal84** [comment]
https://github.com/maemo-leste/icd2/pull/10

**Comment by MerlijnWajer** [comment]
Thanks!
