### ISSUE TITLE
Issue with wl1251-cal/udev

### ISSUE THREAD

**Issue by sicelo** [maemo-leste/bugtracker#115]
On my device, when I install `wl1251-cal`, wlan0 no longer comes up when the device is booted, and even doing `/etc/init.d/eudev restart && /etc/init.d/networking restart` does not help.

With `wl1251-cal` installed, wlan0 **only** works when `/lib/udev/rules.d/49--firmware-wl1251.rules` is adjusted as follows:

``SUBSYSTEM=="firmware", ACTION=="add", ENV{FIRMWARE}=="*wl1251-nvs.bin", RUN:="/root/foo.sh /usr/bin/wl1251-cal --nvs-loading=/sys$env{DEVPATH}/loading --nvs-push-data=/sys$env{DEVPATH}/data"``

where `/root/foo.sh` contains the following:

``#!/bin/sh
strace -s 1024 -f -o /tmp/log-$$.txt $@``. 

This produces two logs (attached). However, the logs are only produced the very first time that eudev/networking are restarted. Even on a reboot they are not produced,  but wlan0 does come up.
[log-3013.txt](https://github.com/maemo-leste/bugtracker/files/1910241/log-3013.txt)
[log-3017.txt](https://github.com/maemo-leste/bugtracker/files/1910242/log-3017.txt)

**Comment by MerlijnWajer** [comment]
Version 1.2 of wl1251-cal should fix issues that people were seeing with it not always working. If this is still not the case, please report back. :)
