### ISSUE TITLE
maemo-security-certman-applet needs libcomapp-dev

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#119]
Seems that libcomapp-dev is closed, per https://talk.maemo.org/archive/index.php/t-79957.html

I have removed the dependency for now, which means that certificates currently cannot be imported in maemo-security-certman-applet

I don't really know what libcomapp-dev does, so I am not sure if we need to RE it.

**Comment by MerlijnWajer** [comment]
Also found this: https://mg.pov.lt/maemo-irclog/%23maemo.2015-12-14.log.html (search for libcomapp-dev)

**Comment by jonwil** [comment]
libcomapp-dev is 100% open, see http://repository.maemo.org/pool/maemo5.0/free/libc/libcomapp/

**Comment by MerlijnWajer** [comment]
I think we have it packaged now:

```
root@n900devuan:~# apt-cache search libcomapp
libcomapp-dev - OSSO LibComApp library development files
libcomapp0 - OSSO LibComApp library
libcomapp0-dbgsym - Debug symbols for libcomapp0
```

@parazyd - does the package now depend on this as well?

**Comment by MerlijnWajer** [comment]
Pretty sure this is fixed.
