### ISSUE TITLE
HW: ARM generic: Build a llvmpipe-enabled mesa

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#12]
It would be very nice to have some generic (software rendered) OpenGL(es) support, so that any device testing and bringup does not block on GPU, as that seems to be one of the more painful parts

**Comment by parazyd** [comment]
We are able to do this simply by forking the Debian package and changing the configure flags in `debian/rules` I believe.

**Comment by MerlijnWajer** [comment]
We tried this with a backported version for jessie and it didn't work. We're now aiming for ascii, so let's close this as ascii should already have an enabled version, at least for armhf.
