### ISSUE TITLE
startx does not work for non-root on Droid 4

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#120]
Adding

needs_root_rights=yes

to

/etc/X11/Xwrapper.config

solves that. I believe we should do it by default.

**Comment by MerlijnWajer** [comment]
I think that makes sense. @parazyd ?

**Comment by parazyd** [comment]
On Tue, Apr 17, 2018 at 08:54:57PM +0000, Merlijn Wajer wrote:
>    I think that makes sense. [1]@parazyd ?

Yes, indeed. Without elogind and the sorts we have to do it this way.
Already done in a couple of other derivatives too.

I'll commit it in the morning.

**Comment by parazyd** [comment]
Applied in https://github.com/maemo-leste/image-builder/commit/5ccc07ae29090fc1d1fcf22e847c2c43fe74939c

This will now be part of future image builds.
