### ISSUE TITLE
Droid 4: important keys are not available

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#122]
Keymap in X has some problems:

Shift-,. should produce ;:, but produces <>. I have not figured out way to produce ;:[]{}, escape. Ctrl+shift+letter combinations could be used for missing keys...?

OK seems to produce "OK" key, which is not too useful. Perhaps it could be mapped as another shift for window manager controls?

**Comment by MerlijnWajer** [comment]
Yes, this makes sense. I suppose there is simply no good X keymap for keyboard yet? Or should devicetree provide the proper abstraction?

How does pmos solve this?

**Comment by pavelmachek** [comment]
Devicetree tells us which keys exists, but it is up to userland to
define reasonable keymap, I'm afraid.

Not sure about pmos, I did not try it on Droid 4.

**Comment by MerlijnWajer** [comment]
#17 might be relevant/related. I will try it a bit later on the droid4, and also make sure it's in the next image release.

**Comment by MerlijnWajer** [comment]
(related, since it doesn't offer a proper hwkeyboard map)

**Comment by LaucianK** [comment]
This Android keymap could be a good start.
https://forum.xda-developers.com/droid-4/themes-apps/keylayout-hacker-keyboard-droid-4-t2901076

**Comment by eloydegen** [comment]
I *think* it would suffice to have an `~/.XCompose` file with all the missing keys, so the X.org keymaps doesn't have to be modified.

**Comment by dderby** [comment]
Ideally we'd create a new map to be added to the `xkb-data` package and then submit it [upstream](https://www.freedesktop.org/wiki/Software/XKeyboardConfig/).

**Comment by Suppresed** [comment]
Using tab as a third level switch seems to be convenient since shift lays below it. Then moving tab as a third level on Return.

**Comment by eloydegen** [comment]
I have created a keymap, will try to upstream it to xkeyboard-config this week.

The `OK` key seem to have a scancode that's above 256, so I wasn't able to bind it to something useful such as `Esc`

**Comment by eloydegen** [comment]
Currently, left CTRL seems broken. But quite a few keys should be working. Please let me know any feedback.

```
SYM + O = {
SYM + P = }
SYM + K = [
SYM + L = ]
SYM + D = \
SYM + Q = ~
SYM + W = `
SYM + U = ×
SYM + Y = ÷
Shift (caps lock button) + arrow up = PgUp
Shift (caps lock button) + arrow down = PgDn
Shift (caps lock button) + arrow left = Home
Shift (caps lock button) + arrow right = End
```

Download the current layout with:
```
wget https://eloydegen.com/xkb-data_droid4.deb
dpkg -i xkb-data_droid4.deb
setxkbmap -model droid4
```

@MerlijnWajer could you create xkb-data repo that I can create a PR for?

**Comment by buzztiaan** [comment]
that .deb works nicely, but still no : key?

**Comment by eloydegen** [comment]
@buzztiaan forgot to list them in my previous comment, you should be able to get `:` and `;` with the caps lock labeled shift + `.` or `,`.

**Comment by xsetiadi** [comment]
finally i can type :

**Comment by SimonIremonger** [comment]
@eloydegen I believe @MerlijnWajer is planning to port the debian xkeyboard-configuration salsa-gitlab into the maemo-leste github, and then we can PR/commit in there for testing on leste.  I certainly want to put it n900 keymap and work on it a bit more.    I reccomend upstreaming done once we have it better sorted-out on a few language variants and so-on.   I would definitely consider being the leste xkeyboard-configuration maintainer especially if I had a droid4 too!.

**Comment by MerlijnWajer** [comment]
@eloydegen 
 
> @MerlijnWajer could you create xkb-data repo that I can create a PR for?

Here you go: https://github.com/maemo-leste/xkb-data

**Comment by dderby** [comment]
These keymaps are useful for the [Devuan builds](https://files.devuan.org/devuan_ascii/embedded/) too, so perhaps this package should be forked in Devuan instead of Leste?  CC @parazyd

Slighty off-topic but kind of related... When a package like xkb-data is forked under the maemo-leste org, does it automatically get imported into Jenkins?

**Comment by MerlijnWajer** [comment]
I did fork it into jenkins, but didn't get it to build succesfully yet.

**Comment by dderby** [comment]
Okay, so it's a manual process.  Any plans to document this or possibilities to grant permissions for Jenkins access?

**Comment by MerlijnWajer** [comment]
Yeah, for sure. That should make it easier for everyone to get involved. This is I think on @parazyd 's plate. The docs for it aren't hard, but currently require SSH access, and we were hoping for something else. Several of us already have build/run privs, and I can give some more of those out, but the SSH access to the machine preferrably not, we just need a cleaner solution.

The SSH access is only required to sync our config.py with the Jenkins jobs - https://github.com/maemo-leste/jenkins-integration/

**Comment by MerlijnWajer** [comment]
AFAIK @parazyd made it work, so what needs to be done before this issue is resolved?

**Comment by eloydegen** [comment]
@MerlijnWajer what do you mean by "it"? I would say the issue can be closed when my PR is merged, which I'll try to submit tomorrow.

**Comment by MerlijnWajer** [comment]
I think that with virtual keyboard now working, and this issue open for the special character list for the virtual keyboard, do we still need this? (https://github.com/maemo-leste/bugtracker/issues/347)

**Comment by pavelmachek** [comment]
Even with virtual keyboard working, useful keyboard map is quite important. It is often faster to press a keyboard combination rather than go through on-screen  keyboard.

And... I'm not sure how this is supposed to work. I have terminal open. On n900, I'd press blue+sym to call on-screen keyboard with special characters. But droid4 has no such key, and there's no obvious icon I can press to get that functionality. I can enable virtual keyboard in settings, and get my special characters from there, but that is not compatible with using hardware keyboard.

**Comment by freemangordon** [comment]
What is needed for scv keyboard to appear is GDK_Multi_key. Somebody shall fix droid4 keymap so a combination of some  key (shift? tab?) and SYM to generate it.

**Comment by MerlijnWajer** [comment]
Please see https://github.com/maemo-leste/bugtracker/issues/347

**Comment by MerlijnWajer** [comment]
(It also includes x11 keymaps)
