### ISSUE TITLE
XFCE4's Thunar doesn't start with gtk+2.0-maemo

### ISSUE THREAD

**Issue by ollieparanoid** [maemo-leste/bugtracker#124]
We're using `gtk+2.0-maemo` in postmarketOS for the Hildon desktop. Currently it also gets installed for other desktops, such as XFCE4. In https://github.com/postmarketOS/pmbootstrap/issues/1380 it was discovered that XFCE4's file manager Thunar doesn't start with `gtk+2.0-maemo`, although it works with `gtk+2.0` (see that issue for details and logs).

In the future we will install the regular GTK+2 version with XFCE4, so this should not be a problem for the most time (only if someone wants to install both XFCE4 and Hildon).

On a side node: what would be the best way to package `gtk+2.0-maemo` on postmarketOS? [Right now](https://github.com/postmarketOS/pmbootstrap/tree/master/aports/maemo/gtk%2B2.0-maemo) we apply a patch file `hildonize-gtk-treeview.diff` on top of the official `gtk+2.0` source. But since you folks seem to maintain [these releases](https://github.com/maemo-leste/gtk/releases) nowadays it might be better to switch to them?

**Comment by parazyd** [comment]
For packaging, you can take and use our `maemo/ascii` branch. Latest git HEAD will work for packaging. Just make sure you apply the patches found in `debian/patches` directory.

**Comment by parazyd** [comment]
Closing as obsolete.
