### ISSUE TITLE
Can't SSH into 'user' account even with an SSH key

### ISSUE THREAD

**Issue by mijofa** [maemo-leste/bugtracker#126]
Normally even when an account has no password, openssh-server will still allow ssh in if using an authorised ssh key. This doesn't work out of the box on Leste.

After much investigation it turns out this doesn't work when UsePAM is set to "no", Debian's default is "yes" and that allows for much greater security control in PAM, so I don't know why it would be worth changing away from the defaults here.

The workaround for my issue was to simply change that option in sshd_config and now I can ssh in as the 'user' account. I think this should be the default here though.

**Comment by MerlijnWajer** [comment]
@parazyd did we fix this in the new image?

**Comment by parazyd** [comment]
I've reenabled PAM here: https://github.com/maemo-leste/image-builder/commit/d51c8fcc2863ceda73fa0db9a367c85d9594d375

Closing.
