### ISSUE TITLE
Networking: Investigate networkmanager plus shim

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#13]
Instead of trying to create a fully open source version of the current closed maemo fremantle network tools, we can attempt to just use networking manager and provide the right dbus shims to make the UI work like before.

**Comment by freemangordon** [comment]
I'd rather try to have current closed maemo blobs REed, there is more than just connections management in connui

**Comment by MerlijnWajer** [comment]
Agreed. Let's close this ticket now that icd2 is close?

**Comment by freemangordon** [comment]
I guess you meant icd2 is REed :). Yes, lets close it for now.
