### ISSUE TITLE
N900: Make vibration work (in mce?)

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#132]
Kernel support seems to be there and work. Tested using ``fftest` binary from `joystick` package.

API seems to have changed, so we might have write a new module for mce.

**Comment by MerlijnWajer** [comment]
See also https://www.kernel.org/doc/Documentation/input/ff.txt

**Comment by MerlijnWajer** [comment]
```
16:38 < spiiroin> Wizzup: sailfish uses ngfd (non graphical feedback) for vibration. ngfd support multiple backends, at least ffmemless(=evdev?) &
                  some android vibrator api
```

**Comment by MerlijnWajer** [comment]
See https://github.com/maemo-leste/mce/pull/9 - this is picked up by uvos.

**Comment by parazyd** [comment]
@MerlijnWajer Done?

**Comment by MerlijnWajer** [comment]
This one is done!
