### ISSUE TITLE
Look at supporting devuan ascii

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#15]

**Comment by parazyd** [comment]
Devuan Ascii should be released as `stable` and Jessie moved as `oldstable` by the end of this year.

**Comment by MerlijnWajer** [comment]
We have started with this, but ran into issues when building gtk2. We need to rebase some of our patches on the ascii gtk2.

**Comment by MerlijnWajer** [comment]
I think everything in ascii builds now, but has not been tested yet.

**Comment by MerlijnWajer** [comment]
With OpenRC and the right packages, I can boot to hildon-desktop with power vr acceleration on N900, on ascii. Also works on amd64 per @freemangordon 

Closing.

Awesome work guys!!! @parazyd  @freemangordon
