### ISSUE TITLE
Droid 4: ofonod works after some patches

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#150]
With some patches, it is possible to get ofonod to work on droid 4 (talking AT commands over USB). That's not optimal, but it is good enough to get working calls and SMSes with 10 hours of battery life. (Tony's gsmmuxing tool and mixer support patch in kernel is needed for working voice).

**Comment by MerlijnWajer** [comment]
Could you list the patch set here? I know it's on the linux-omap ML somewhere (and in my inbox), but if others want to try, it might be nice to have an overview. Or did you plan to pick this up later on?

**Comment by pavelmachek** [comment]
This probably needs to be switched to new interfaces, see "WIP Droid 4 voice calls, GNSS & PM with a TS 27.010 serdev driver" for details. Anyway this is what I'm using... 

```
user@devuan:/my/ofono$ cat  /etc/udev/rules.d/55-modem.rules
KERNEL=="ttyUSB4", ENV{OFONO_DRIVER}="g1"
```

Sometimes ofone crashes (after day or so of use), and sometimes SMSes are lost. Those may be related.

Diff is here. At least there's a backup if my uSD card dies.
[delme.txt](https://github.com/maemo-leste/bugtracker/files/2705917/delme.txt)

**Comment by pavelmachek** [comment]
I pushed my sources to github:

https://github.com/pavelmachek/ofono/branches

at branch is the "working" one... designed for ttyUSB4 as explained before.

d4 branch is "new" one. It does not yet work. It is designed to work with Tony's patches, on /dev/motmdm1.  It should have significant advantages w.r.t. power.

**Comment by MerlijnWajer** [comment]
As also emailed:

```

After installing http://maedevu.maemo.org/leste-devel/pool/droid4/o/ofono/

and reading

https://github.com/pavelmachek/ofono/blob/d4/README.d4

and setting the udev values, and running udevadm control --reload-rules
and running udevadm trigger, I now have a modem visible on dbus.

I am able to power and online it, but there doesn't seem to be a sim
manager interface. But maybe this is because I don't have a sim in there
yet (?).

Output below.

Cheers,
Merlijn

> root@devuan-droid4:~# mdbus2 -s org.ofono /motmdm_0
> [METHOD]   org.freedesktop.DBus.Introspectable.Introspect() -> (s:xml)
> [METHOD]   org.ofono.Modem.GetProperties() -> (a{sv}:properties)
> [METHOD]   org.ofono.Modem.SetProperty(s:property, v:value) -> ()
> [SIGNAL]   org.ofono.Modem.PropertyChanged(s:name, v:value)
> [METHOD]   org.ofono.MessageManager.GetProperties() -> (a{sv}:properties)
> [METHOD]   org.ofono.MessageManager.SetProperty(s:property, v:value) -> ()
> [METHOD]   org.ofono.MessageManager.SendMessage(s:to, s:text) -> (o:path)
> [METHOD]   org.ofono.MessageManager.GetMessages() -> (a(oa{sv}):messages)
> [SIGNAL]   org.ofono.MessageManager.PropertyChanged(s:name, v:value)
> [SIGNAL]   org.ofono.MessageManager.IncomingMessage(s:message, a{sv}:info)
> [SIGNAL]   org.ofono.MessageManager.ImmediateMessage(s:message, a{sv}:info)
> [SIGNAL]   org.ofono.MessageManager.MessageAdded(o:path, a{sv}:properties)
> [SIGNAL]   org.ofono.MessageManager.MessageRemoved(o:path)
> [METHOD]   org.ofono.VoiceCallManager.GetProperties() -> (a{sv}:properties)
> [METHOD]   org.ofono.VoiceCallManager.Dial(s:number, s:hide_callerid) -> (o:path)
> [METHOD]   org.ofono.VoiceCallManager.DialLast() -> ()
> [METHOD]   org.ofono.VoiceCallManager.DialMemory(u:memory_location) -> ()
> [METHOD]   org.ofono.VoiceCallManager.Transfer() -> ()
> [METHOD]   org.ofono.VoiceCallManager.SwapCalls() -> ()
> [METHOD]   org.ofono.VoiceCallManager.ReleaseAndAnswer() -> ()
> [METHOD]   org.ofono.VoiceCallManager.ReleaseAndSwap() -> ()
> [METHOD]   org.ofono.VoiceCallManager.HoldAndAnswer() -> ()
> [METHOD]   org.ofono.VoiceCallManager.HangupAll() -> ()
> [METHOD]   org.ofono.VoiceCallManager.PrivateChat(o:call) -> (ao:calls)
> [METHOD]   org.ofono.VoiceCallManager.CreateMultiparty() -> (ao:calls)
> [METHOD]   org.ofono.VoiceCallManager.HangupMultiparty() -> ()
> [METHOD]   org.ofono.VoiceCallManager.SendTones(s:SendTones) -> ()
> [METHOD]   org.ofono.VoiceCallManager.GetCalls() -> (a(oa{sv}):calls_with_properties)
> [SIGNAL]   org.ofono.VoiceCallManager.Forwarded(s:type)
> [SIGNAL]   org.ofono.VoiceCallManager.BarringActive(s:type)
> [SIGNAL]   org.ofono.VoiceCallManager.PropertyChanged(s:name, v:value)
> [SIGNAL]   org.ofono.VoiceCallManager.CallAdded(o:path, a{sv}:properties)
> [SIGNAL]   org.ofono.VoiceCallManager.CallRemoved(o:path)
```

**Comment by pavelmachek** [comment]
Replying here; can do email, too.

I'm not sure if I even implemented SIM management... Calls and SMSes
should work, don't expect much (if anything) else.

I'd recommend inserting pre-paid SIM card for experiments. PIN code
needs to be disabled. 
Attempting voice call is a good test.

With right debugging options (see README), you can see AT-like commands
being executed, and it should be possible to figure out what goes on.

Good luck :-).

**Comment by MerlijnWajer** [comment]
Tony did a lot of work here, I've packaged his latest version as of today, and it's available now in `beowulf-devel` component. SMS send/receive works, call start/pickup works, data connections work, sim interface seems to work.

**Comment by MerlijnWajer** [comment]
Going to close this issue, we'll build it for `maemo/beowulf` soon enough.
