### ISSUE TITLE
Droid 4: GPRS and GPS work over QMI

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#151]
In unicsy_demo, there are hacks that get GPRS/UMTS data and GPS to work... these do not use AT commands, but QMI (and patched qmiclient is needed for GPS). So yes, there's more work to do.

**Comment by pavelmachek** [comment]
First... LTE. It is on second modem, and it is useless in Europe. A
lot of work, and work someone else will need to do.

Yes, it would be nice if GPRS was activated over ofonod. But I'm
currently using AT commands for calls and QMI for activating
data... maybe it is possible to do using AT commands, too, but more
research and more work is needed.

**Comment by pavelmachek** [comment]
On Wed 2018-11-07 02:31:29, Merlijn Wajer wrote:
> I will start working soon on ofono plugin for icd2, and I'm wondering what the status is now. I will start with n900 probably. ofono should be able to work with qmi_wwan, should it not?
>

I'm not sure I understand the question.

For n900, there's no qmi, ofono just works. I guess it makes sense to
get that working, first.

For droid4, I'm using ofono with AT commands. Maybe it can do qmi, but
I did not get that to work.

-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html

**Comment by MerlijnWajer** [comment]
My question was (I guess) if the usage on the droid4 will be similar to this: http://musicnaut.iki.fi/txt/nokia_modem.txt

What do you mean "ofono with AT commands" - is this just patches to ofono itself, and then using some ofono driver?

Here you also commented about the ofono patches: https://github.com/maemo-leste/bugtracker/issues/110 - I was wondering if there was any moment. :)

**Comment by MerlijnWajer** [comment]
Thanks for clarifying. Yeah, it's quite a hack.. I will work with N900 first then. Is there a plan forward for the droid4?

**Comment by pavelmachek** [comment]
Yes, starting with N900 makes a lot of sense.

As for a way forward on Droid4... I guess that's complicated. First, I
may not have have time. Second... it would be good to have solution
with good power management properties, and that may be tricky.

But ultimately, I guess every phone needs to fit into ofono, and if it
does not, it needs to be fixed. Droid 4 just needs to be modified to
fit into the framework.

**Comment by MerlijnWajer** [comment]
I am going to close this issue, since it works with ofono on the droid4 now (with ofono from `maemo/beowulf-devel`), so the generic issue here now is this one: https://github.com/maemo-leste/bugtracker/issues/76
