### ISSUE TITLE
ukeyboard: Maybe merge history from old/dead upstream repo

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#156]
We have https://github.com/maemo-leste/ukeyboard

Maybe take history from: http://repo.or.cz/w/ukeyboard.git

Let me know if I should do it.

**Comment by pali** [comment]
+1

Ideally fully replace it (force push) without merging.

**Comment by freemangordon** [comment]
yes, please do

**Comment by MerlijnWajer** [comment]
I haven't done this yet because @freemangordon is replacing this entirely, AFAIU

**Comment by pali** [comment]
should I do it?

**Comment by MerlijnWajer** [comment]
Please do. Also note we have this now: https://github.com/maemo-leste/osso-applet-textinput

**Comment by MerlijnWajer** [comment]
I didn't do it, because @freemangordon asked me not to package ukeyboard in the repositories, so I figured he had a reason. Still, it would be good to have the history merged. I can confirm that the current state of ukeyboard repo builds and works (as far as I can tell)

**Comment by pali** [comment]
Done. I connected old history with current one (git replace and git filter-branch). force push happened so, you need to re-clone repository.

**Comment by MerlijnWajer** [comment]
Thanks!
