### ISSUE TITLE
X server not working after installing libgl1-mesa-glx

### ISSUE THREAD

**Issue by anonimo82** [maemo-leste/bugtracker#157]
Hello everyone.
As in subject, after installing libgl1-mesa-glx, X server won't start.
I'm attaching X11 log file, please note I did a clean installation and I only installed glx.
[Xorg.0.log](https://github.com/maemo-leste/bugtracker/files/2184201/Xorg.0.log)

Thanks for help.

**Comment by MerlijnWajer** [comment]
I assume that this is on the N900? You can't mix mesa and powervr that easily, definitely not with the current xorg ddx. So for now, the solution would be to not install this. In the future, when we use drm, and the dri3wsegl plugin and modesetting driver (if ever), then this could be an option.

**Comment by anonimo82** [comment]
Yes, it's on the n900.
So what can I do if glx is needed by any app?

**Comment by anonimo82** [comment]
I need libgl.so.1, where else could I have it?

**Comment by MerlijnWajer** [comment]
There is no libGL.so.1 for N900. If you disable all acceleration you can have software rendering, on an old 600Mhz CPU. glshim might work at some point.

**Comment by anonimo82** [comment]
I see, thanks.
Any plans?
By the way, I guess we can close this one.

**Comment by MerlijnWajer** [comment]
For me personally, on the N900, libGL.so.1 with glshim or the glshim fork is an after 1.0 priority. See the various N900 milestones and tickets, once we have working phone calls, good battery life, good audio switching, good usb slave/host UI and daemon, faster/more-stable powervr, *then* this might be interesting.

**Comment by anonimo82** [comment]
I see, so priority is given to provide a working system.
It's fair. Thanks.
