### ISSUE TITLE
Provide dd-able images of Maemo Leste

### ISSUE THREAD

**Issue by parazyd** [maemo-leste/bugtracker#16]
After we have the software in place for the three devices we're considering in #2 , it should be relatively easy to write a blend file for arm-sdk. This will allow us to host and provide dd-able images that people can use on their microsd cards.

For the blend(s) we can have a separate git repository with the actual blend file, kernel configs, and anything else that relates. (Also relates to #7 and #8 )

**Comment by aapo** [comment]
I think easiest way for new developer to try this out:
*Don't expect running/working/updated Fremantle, please (this means e.g. installed uboot)
1) Download image.dd + corresponding kernel (maybe in the same tarball)
2) dd image to the sd-card
3) boot (one shot) or install (permanently) kernel with flasher (or 0xFFFFFF)

**Comment by MerlijnWajer** [comment]
I think that's exactly right. We want dd-able images, that you can put on the sd card. Then you can either use u-boot of 0xFFFF to boot from SD card. Hopefully we'll have something ready in a week.

**Comment by MerlijnWajer** [comment]
With the hildon-meta package in place, this should be ready soon.

**Comment by parazyd** [comment]
Testing image for N900 is now live: http://maedevu.maemo.org/images/
Please try it out and report back, so we can fix any problems :)

**Comment by pkillnine** [comment]
I `dd`'d the image onto the sd card, but when i run `run sdboot` at the bootmenu, it loads the kernel but the screen is just blank (but lit up).

Is there a sample bootmenu entry to use?

**Comment by MerlijnWajer** [comment]
Give us one or two more days. The specific issue you are seeing should be fixed in the latest image, but there are a few more things to fix before it will boot to a hildon-desktop.

**Comment by parazyd** [comment]
I've just uploaded new images that should give you some console output at least on the N900 screen.

**Comment by pkillnine** [comment]
thanks, I can see now that it does successfully boot.

**Comment by MerlijnWajer** [comment]
Latest image has boots to hildon-desktop; with working keyboard (keymap) and touchscreen. We're working on making sure all the right init scripts boot. Powervr is also a bit bugged - it takes minutes to start hildon-desktop, but after that it is semi-usable. Any quick test runs would be cool.

**Comment by MerlijnWajer** [comment]
Note: I did not test this on a non-develmode device yet, but it should work.

**Comment by MerlijnWajer** [comment]
The latest image will now also work with lockswitch and other buttons if the meta package is upgraded (`apt-get upgrade hildon-meta`)

**Comment by pkillnine** [comment]
The latest SD card image still reboots for me when it tries to load X

**Comment by MerlijnWajer** [comment]
Yeah, so it takes a long time to start hildon-desktop, so dsme (I think) restarts the device. If you set the right flags with 0xFFFF, then it won't reboot.

**Comment by pkillnine** [comment]
What flags do I set and how do I set them?

**Comment by MerlijnWajer** [comment]
I think I did this:

```sudo ./0xFFFF -F no-lifeguard-reset,no-omap-wd,no-ext-wd```

**Comment by pkillnine** [comment]
Where do I run this? In the vanilla Maemo operating system?

**Comment by MerlijnWajer** [comment]
New images (up soon, parazyd will say when I guess) will no longer reboot: https://github.com/maemo-leste/dsme/commit/01f6cb1df488d1b58776a09bef155c9b592d382b

**Comment by MerlijnWajer** [comment]
I think the latest images should boot on a N900 without any devel flags enabled with flasher. Be patient, it takes several minutes to start H-D because of PowerVR issues/bugs. After that, it should work *OK* (not super fast, but good enough for now).

If you need network become root (password is `toor`; or just `sudo -i`) and set password with `wpa_supplicant` tool. You should probably do this from a Linux machine instead:

`wpa_supplicant ssid password >> /my/sd/mount/etc/wpa_supplicant/wpa_supplicant.conf` and boot the N900 again. It should appear on the network as `devuan`.

**Comment by MerlijnWajer** [comment]
Further info/instructions will follow on maemo-leste.github.com in the next few days (and also in issues of course)

**Comment by parazyd** [comment]
Confirmed :)

https://github.com/maemo-leste/image-builder/blob/master/rootfs-overlay/n900/etc/network/if-pre-up.d/00mac will also now prevent MAC address randomization after the initial boot.
