### ISSUE TITLE
Libgl1-mesa-glx

### ISSUE THREAD

**Issue by anonimo82** [maemo-leste/bugtracker#163]
Hello everyone.
I'm using Maemo-Leste (latest) on a Nokia N900.

I'm trying to use Blender, Mixxx and LibreOffice, but all of them require libgl1-mesa-glx installed.

Help.

**Comment by MerlijnWajer** [comment]
The OpenGL(ES) situation will be different per device. PowerVR devices will likely never have accelerated OpenGL. OpenGLES might, via EGL. The N900 doesn't seem a device that is capable of running blender, in hardware acceleration, let alone in software acceleration.

**Comment by MerlijnWajer** [comment]
Eventually when we get better integration of the powervr driver (using perhaps https://github.com/TexasInstruments/dri3wsegl) we can at least have a OpenGL sw fallback.

See also https://leste.maemo.org/Motorola_Droid_4/PowerVR

**Comment by anonimo82** [comment]
But here: https://leste.maemo.org/Nokia_N900 it's written powervr already have 3d acceleration, wip but already working

**Comment by mirh** [comment]
And OpenGL ES counts as hardware acceleration. 
In fact, all of the programs you mention should have [someway](https://bugs.launchpad.net/mixxx/+bug/1316402) [somehow](https://en.blender.org/index.php/User:AlexK/Gsoc2012/Building_Blender_with_GLES) [support](https://www.phoronix.com/scan.php?page=news_item&px=GTK3-Wayland-GL-Epoxy-LO).
