### ISSUE TITLE
Capture devices

### ISSUE THREAD

**Issue by anonimo82** [maemo-leste/bugtracker#164]
Hello everyone.
I'm using Maemo-Leste (latest) on a Nokia N900.

Camera and microphone aren't detected as ALSA/V4L devices, so they don't work.

Help.

**Comment by MerlijnWajer** [comment]
The microphone indeed also does not work well for me using arecord. I am not sure why.
I am not sure about the video/v4l camera devices, I think they require some special usage.

@pavelmachek - do you have any idea about arecord not working? I assume it does work in phone calls, so I am not sure where it is going wrong.

**Comment by pavelmachek** [comment]
Camera support... see "cheap complex cameras" recording on
youtube. Basically, way more work needs to be done before camera is
usable.

arecord should work. You may need to setup mixers to get useful
data. What errors are you getting?

**Comment by MerlijnWajer** [comment]
You're right. Indeed, arecord does work. I don't know why I recall it not working.
