### ISSUE TITLE
.desktop launch

### ISSUE THREAD

**Issue by anonimo82** [maemo-leste/bugtracker#165]
Hello everyone.
I'm using Maemo-Leste (latest) on a Nokia N900.

I copied .desktop files to  /usr/share/applications (confirm folder), but in the menu at the top left (six squares in 2 lines of 3), I can see the icons, but they won't load the associated app.
Is this just me?

Help.

**Comment by MerlijnWajer** [comment]
You should copy them to `/usr/share/applications/hildon` I believe.

If the icons do show up, then perhaps the applications simply fail to start?

**Comment by anonimo82** [comment]
Yes

**Comment by MerlijnWajer** [comment]
I found that in `.desktop` files need to contain the full path to the application, then it works.

This could be a problem in how hildon treats .desktop files.

**Comment by dderby** [comment]
It should be searching the `$PATH`.  You could run `cat /proc/<pid>/environ | tr '\0' '\n' | grep PATH` on the process that launches the `.desktop` file to see if `$PATH` was set.

https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables

**Comment by MerlijnWajer** [comment]
It should be, but the question is: does it? :)

**Comment by dderby** [comment]
Exactly.  Try the command I suggested to find out. ;)

**Comment by MerlijnWajer** [comment]
I don't think `execve` searches PATH at all, so if that is used then that won't tell me anything. I reopened the ticket because it was clear to me that what I expected to work wasn't working, and I'll have to look at the code.

**Comment by MerlijnWajer** [comment]
This code does seem to lookup something in path:

https://github.com/maemo-leste/hildon-desktop/blob/master/src/launcher/hd-app-mgr.c#L1421

**Comment by IMbackK** [comment]
works fine for me

**Comment by MerlijnWajer** [comment]
Please reopen if the problem persists.
