### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by anonimo82** [maemo-leste/bugtracker#166]
Hello everyone.
I'm using Maemo-Leste (latest) on a Nokia N900.

I have a suggestion which should improve usability.
There should be a toggle overlay of 3 mouse buttons and 3 keyboard keys, those are: left/middle/right mouse button and shift/control/alt keyboard keys.
When, in the overlay, a mouse button is selected (eg, the right mouse button), the next tap/swipe should behave as if it triggers the right mouse button.
Such overlays should be toggle as well, because I coiuld need to ctrl+shift+right mouse button.
I'm not sure if this should be sticky as well.

Help.

**Comment by MerlijnWajer** [comment]
Your question is how to send a right mouse click to applications?

**Comment by anonimo82** [comment]
Yes, middle too
