### ISSUE TITLE
Provide a virtual keyboard

### ISSUE THREAD

**Issue by parazyd** [maemo-leste/bugtracker#17]
Since the A33 tablets are missing a hardware keyboard unlike N900 and Droid4, we need to figure out a good way to provide a virtual keyboard. My guess is that the one from maemo is probably reusable for this task.

**Comment by freemangordon** [comment]
Will look at what is the status of hildon-im, most if not all of it should be FOSS/REed

**Comment by MerlijnWajer** [comment]
18:04  * parazyd would like a virtual keyboard soon tbh
18:04 < freemangordon> parazyd: you may start working on it, if you wish, most of the code is REed
18:05 < parazyd> where is it?
18:06 < freemangordon> https://github.com/community-ssu/hildon-input-method-plugins
18:06 < parazyd> thanks, i'll give it a look
18:06 < freemangordon> https://github.com/community-ssu/hildon-im-vkbrenderer3
18:06 < parazyd> anything i should know?
18:06 < freemangordon> and hildon-input-method itself, which should be FOSS, iirc
18:07 < parazyd> perhaps i'll ask jonwil too
18:07 < freemangordon> it was long time ago I REed that, cant recall anything specific
18:07 < parazyd> ack
18:07 < freemangordon> parazyd: also, http://repository.maemo.org/pool/fremantle/free/h/
18:07 < freemangordon> for hildon-input-method code
18:08 < parazyd> got it
18:08 < freemangordon> I think I have access to git repo as well, but don;t have time now

**Comment by MerlijnWajer** [comment]
hildon-input-method-framework-dev seems to be required too

**Comment by jonwil** [comment]
There are still quite a few bits of hildon-input-method and the input subsystem that aren't FOSS/in CSSU:
hildon-im-common-virtual-settings
hildon-im-keyboard-assistant
hildon-im-keyboard-assistant-scv
hildon-im-plugin-base-settings (contains no binaries)
hildon-im-virtual-keyboard-layouts (contains no binaries)
hildon-input-method-configurator
hildon-input-method-plugins-western (contains no binaries)
hildon-input-method-widgets (contains no binaries)
imengines-ezitext
libezitext
libimengines4
libimengines-wp4
libimlayouts0
maemo-input-sounds
osso-applet-textinput
ezitext-czech
ezitext-danish
ezitext-dutch
ezitext-english-gb
ezitext-english-us
ezitext-essential-plugins
ezitext-finnish
ezitext-french-ca
ezitext-french-fr
ezitext-german
ezitext-greek
ezitext-italian
ezitext-norwegian
ezitext-polish
ezitext-portuguese-pt
ezitext-russian
ezitext-spanish-es
ezitext-spanish-us
ezitext-swedish

We probably dont need the ezitext and all that word prediction stuff (unless we want word prediction and there are no alternative choices available) and we can probably get away without the control panel stuff for now but other stuff on that list looks important.

**Comment by freemangordon** [comment]
Maybe this one https://github.com/joaquimrocha/text-predictor-input-method worths looking at, as ezitext replacement

**Comment by dderby** [comment]
This may not be a priority but I'd like to have a virtual keyboard for the console.  I know of these two:
https://github.com/julianwi/fbkeyboard
https://github.com/postmarketOS/osk-sdl

**Comment by MerlijnWajer** [comment]
Right. Perhaps it'd be sensible to make a separate issue for that one? This one is about a keyboard in X.

Side note: If you want such a keyboard to unlock an encrypted partition, we are thinking about tackling that slightly different, much like google chromeos does, with dm-verity. Maybe we should make a separate ticket for that too.

**Comment by dderby** [comment]
Did the Nokia 770 or N800 come with a virtual keyboard we could use?

**Comment by dderby** [comment]
I've opened https://github.com/maemo-leste/bugtracker/issues/79 for the console virtual keyboard.

**Comment by MerlijnWajer** [comment]
Here are the steps/instructions for doing this on the raspi or n900, it's all WIP, and we'll try to have most of it packaged soon:

```

Packages:

* libimengines4
* hildon-im-fkb
* hildon-im-plugin-base-settings
* hildon-input-method-configurator
* hildon-input-method
* hildon-im-keyboard-assistant
* libhildon-im-vkbrenderer3
* osso-applet-textinput

Install them.

/etc/default/keyboard
  
    XKBMODEL="nokiarx51"

Copy /usr/share/keyboards from fremantle.
Copy /usr/share/hildon-input-method/himrc from fremantle.
Replace "sapwood" with "pixmap" in himrc (for now)

Run:

* hildon-input-method-configurator.bin (as root)

Reboot.

Start hildon-input-method as user
Open settings, text input, enable virtual keyboard

On n900, you currently need:

    gconftool --type bool -s /system/osso/af/keyboard-attached false
```

**Comment by MerlijnWajer** [comment]
I think we're getting pretty close. I've just created `hildon-input-meta` repo and will turn that into a meta package. That should help us with the next image.

**Comment by MerlijnWajer** [comment]
@parazyd - can you prepare arm-sdk with the few required 'hacks':

- /etc/default/keyboard
- copy /usr/share/keyboards from fremantle
- copy /usr/share/hildon-input-method/himrc from fremantle
- replace "sapwood" with "pixmap" in himrc

I've just made a `hildon-input-meta` package that you can use to get all the required packages installed.

**Comment by freemangordon** [comment]
It should be there before first boot actually

**Comment by MerlijnWajer** [comment]
I'll place them in the maemo leste image buulder on post package install then.

**Comment by MerlijnWajer** [comment]
Latest image-builder contains all the required input packages, as well as the files mentioned above. There is one thing preventing it from working. The controlpanel text applet segfaults because `available_languages` is not set to anything. I am not sure if that is a problem or not, but more than that, I am not sure what tool is supposed to set that key (is it set based on `/usr/share/keyboards`, and when?)

**Comment by MerlijnWajer** [comment]
Once I issued this, I was able to enter the controlpanel applet and enable vkb, after which it popped up nicely:

`gconftool --list-type string --type list -s /apps/osso/inputmethod '[fi_FI,en_GB,no_NO,da_DK,el_GR,it_IT,pt_PT,es_MX,nl_NL,fr_FR,fr_CA,bg_BG,sv_SE,pl_PL,en_US]`

**Comment by MerlijnWajer** [comment]
Another note. I added the required extra files -only- to the n900 rootfs-overlay, for now.

**Comment by MerlijnWajer** [comment]
With the new `hildon-input-meta` in place that depends on the package that provides this gconf key, now the only issue remaining is that on first boot, hildon-input-method-configurator is run, but somehow the keys are not yet reflected in the running (system) state. Rebooting the fresh image once it has booted will return in (on second boot) everything working as expected. gconf caching messing with us? Or is there something else running that doesn't re-read the keys?

**Comment by MerlijnWajer** [comment]
We should also have the piece of ke-recv in place to set the keyboard slide gconf key.

**Comment by parazyd** [comment]
What is the status of this?

**Comment by MerlijnWajer** [comment]
We still need keyboard slide monitoring (to change the slide value in gconf) and I think the device still needs a reboot after running the configurator things.

**Comment by MerlijnWajer** [comment]
As far as I can see there are a few things to do:

1. ke-recv-extra only checks once for attached (or not attached) keyboards. Once on startup. It needs to check on input/events. This is key `/system/osso/af/keyboard-attached`.
2. ke-recv currently doesn't read/check the slide state of the keyboard at all. It needs to monitor input devices that match certain caps and set the slide key when the slide state changes. This is key `/system/osso/af/slide-open`.

They could both share/use code from mce's `mce-io`, I suppose.

**Comment by MerlijnWajer** [comment]
That, and we also need to see if we can share the evdev / input-device matching and searching code.

**Comment by MerlijnWajer** [comment]
@spinal84 recently added slide monitoring code to `ke-recv`, and I think `keyboard-attached` monitoring is also in place. So perhaps we can actually close this ticket now?

cc @freemangordon @parazyd

**Comment by freemangordon** [comment]
There are some rough edges and missing features(only a  small amount of supported languages, no word prediction), but yes, now we have VKB, lets close the issue
