### ISSUE TITLE
Package uniscy_demo

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#174]
https://github.com/pavelmachek/unicsy_demo

Would be a useful tool to test various functionality/features. Pavel wrote:

```
Would it be possible to package unicsy_demo?
https://github.com/pavelmachek/unicsy_demo Right now it is useful for
driver debugging, for example it can estimate battery remaining even
when battery is not calibrated. It can also reboot / poweroff the
machine, and read various sensors... When ofono is integrated, it can
also initiate calls and handle SMSes...
```

And, regarding packaging:

```
It should go to /usr/share/unicsy, dependencies are python-gtk2 for UI
parts and python-dbus ofono for the phone stuff.

I can apply patches with the debian/ directory, or give you repository
access, or attempt to do it myself (but I may need some help).
```

**Comment by MerlijnWajer** [comment]
I tried to start unicsy_demo, and it doesn't quite work yet (either user or root):

<pre>
# python2 /usr/share/unicsy/startup/x_startup.py
Unicsy starting up
Not on debian
sudo: unable to resolve host n900devuan
Unicsy/root starting up
sudo: unable to resolve host n900devuan
sudo: unable to resolve host n900devuan
sudo: unable to resolve host n900devuan
sudo: unable to resolve host n900devuan
sudo: unable to resolve host n900devuan
sudo: unable to resolve host n900devuan
sudo: unable to resolve host n900devuan
sudo: unable to resolve host n900devuan
sudo: unable to resolve host n900devuan
mount: /dev/zero is already mounted or /sys/kernel/debug busy
       /dev/zero is already mounted on /sys/kernel/debug
sudo: unable to resolve host n900devuan
sudo: unable to resolve host n900devuan
sudo: unable to resolve host n900devuan
sudo: unable to resolve host n900devuan
sudo: unable to resolve host n900devuan
Fast charge on, 500 mA
sudo: unable to resolve host n900devuan
sudo: unable to resolve host n900devuan
sudo: unable to resolve host n900devuan
sudo: unable to resolve host n900devuan
ofono unavailable
Unicsy executing command  mate-terminal  --tab  -t 1_tefone -e 'sh -c "/usr/share/unicsy/demo/tefone; xmessage /usr/share/unicsy/demo/tefone failed; sleep 1h"' --tab  -t 2_battery -e 'sh -c "/usr/share/unicsy/monitor/batmond; xmessage /usr/share/unicsy/monitor/batmond failed; sleep 1h"' --tab  -t 3_monitor -e 'sh -c "/usr/share/unicsy/monitor/mond; xmessage /usr/share/unicsy/monitor/mond failed; sleep 1h"' --tab  -t 5_ofone -e 'sh -c "sudo /usr/share/unicsy/ofone/ofone --primary; xmessage sudo /usr/share/unicsy/ofone/ofone --primary failed; sleep 1h"' --tab  -t 0_panel -e 'sh -c "/usr/share/unicsy/desktop/panel.py; xmessage /usr/share/unicsy/desktop/panel.py failed; sleep 1h"'
sh: 1: mate-terminal: not found
</pre>

ofono is definitely running:

<pre>
# mdbus2 -s org.ofono
/
/bluetooth
/bluetooth/profile
/bluetooth/profile/dun_gw
/bluetooth/profile/hfp_ag
/bluetooth/profile/hfp_hf
/n900_0
</pre>

**Comment by MerlijnWajer** [comment]
Starting `ofone` gets me further:

<pre>root@n900devuan:/home/user/unicsy_demo/ofone# python2 ofone
Fell back to pygtk 2

(process:10306): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
Fell back to pygtk 2
Fell back to pygtk 2
Fell back to pygtk 2
Fell back to pygtk 2
Fell back to pygtk 2
Fell back to pygtk 2
Can't open events.json
(0, 'battery watchdog')
(1, 'phone watchdog')
(0, 'battery watchdog')
(1, 'phone watchdog')
(9, 'track ok')
Battery (3.71V) 3.86V (17%) 58% 96% 1326/1368 mAh Not charging Discharging -453 0 650/500 mA ??? 1326 ??? mAh
cat: /etc/alpine-release: No such file or directory
Setting main loop
<dbus.mainloop.NativeMainLoop object at 0xb54697b8>
done
Connecting modem /n900_0...
Traceback (most recent call last):
  File "ofone", line 449, in <module>
    mw = MainWindows()
  File "ofone", line 348, in __init__
    m.startup()
  File "/home/user/unicsy_demo/ofone/ofono.py", line 213, in startup
    m.online_modem()
  File "/home/user/unicsy_demo/ofone/ofono.py", line 247, in online_modem
    m.modem.SetProperty("Online", dbus.Boolean(1), timeout = 120)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.ofono.Error.Failed: Operation failed
</pre>

**Comment by MerlijnWajer** [comment]
Reboot got me further, but I forgot to disable/remove the PIN.

**Comment by MerlijnWajer** [comment]
Works, gtk2 style makes it look a bit weird :D 

![Ofone](https://wizzup.org/n900-ofone-initial.png "Ofone")

**Comment by MerlijnWajer** [comment]
Please let me know if you don't like the version bump for the repo. I think we can close this issue.
Thanks for doing most of the packaging work! I didn't see that you already did that before.

**Comment by pavelmachek** [comment]
Thanks for doing this!

I have merged your packaging changes back to my tree, and tagged
release "0.5" to be consistent with packaged version.

ofone is indeed most interesting entry-point. Just one copy should be
run with "-p" option -- meaning primary; that one will handle incoming
calls and sms-es. (It can also play ringtone -- but required file is not
likely to exist on Maemo lese -- see ./ofone/notify.py).

"Stock" gtk2 theme is probably caused by running ofone as root. It
should be possible to run it as a user (but setup is not trivial;
ofone needs to be able to do sudo and dbus needs to be configured to
allow ofone connection to non-root).

Another interesting entry-point is demo/demo.py, which can be used for
hardware testing.

**Comment by MerlijnWajer** [comment]
Good point about -p. I've already been able to receive and send sms. Calls not yet because I need to package/start libcmtspeech and the current SIM in there doesn't support calls (data only sim that can do sms)

**Comment by pavelmachek** [comment]
You don't really need "libcmtspeech" to test the calls... you'll just
not get audio :-).

**Comment by MerlijnWajer** [comment]
But I want audio :D and I want to package libcmtspeech.
I've already been able to start a call using mdbus2, so I want something more out of this. ;)
