### ISSUE TITLE
Droid 4: hildon-connectivity-meta package installed, but no communication possible

### ISSUE THREAD

**Issue by druk13** [maemo-leste/bugtracker#176]
wlan works without any problem over ifup und ifdown and configurations in /etc/network/interfaces with a updated system based on the image from 2018-04-25.

After reading in the fourth update 'Wifi integration in the images is now also completed, when using the latest Nokia N900 image (or any device, really),' and installing the hildon-connectivity-meta package, I can define wlan connections over the gui, get a internet address, get the wlan symbol in the status area but no communication over wlan is possible (name resolution and ?).

**Comment by sicelo** [comment]
maybe when thus connected, show the output of `ip route show` and `cat /etc/resolv.conf`

**Comment by MerlijnWajer** [comment]
Make sure that you empty your wpa_supplicant config and are fully up to date: `apt-get update` and `apt-get upgrade`.

**Comment by druk13** [comment]
ip route show:
default via 172.28.172.1 dev wlan0
172.28.172.0/24 dev wlan0 proto kernel scope link src 172.28.172.2

resolf.conf:
nameserver 172.28.172.1

After a restart of the Droid 4 and editing resolv.conf to googles ;( nameserver (8.8.8.8) name resolution is working. Could it be, that the resolv config will not be updated if I change the wlan net?

apt-get upgrade:
Errors were encountered while processing:
 mce
 osso-af-startup
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by druk13** [comment]
After installing from scratch based on the image from 2018-04-25 no apt upgrade errors any more :), but I'm sure, that the resolv.config will not be changed when changing the wlan e.g.

ip route show:
default via 10.99.98.254 dev wlan0
10.99.98.0/24 dev wlan0 proto kernel scope link src 10.99.98.41

resolf.conf:
nameserver 172.28.172.1

**Comment by MerlijnWajer** [comment]
This issue might be in the icd2 plugin that handles /etc/resolv.conf - maybe the ipv4 plugin?

**Comment by MerlijnWajer** [comment]
This this still a problem, @druk13 ?

**Comment by druk13** [comment]
No problems with maemo-leste from 23.03.2020.

Thank's to all of you for your commitment.

**Comment by MerlijnWajer** [comment]
Awesome - please let us know what you would like to see, what needs to be improved, what you like, what you don't like, and please ask questions if something is unclear!
