### ISSUE TITLE
mce: n900 LED patterns

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#186]
Currently, when the phone is charging, the yellow/orange LED is always on. This can be disabled like so:

`echo 0 > /sys/class/power_supply/bq24150a-0/stat_pin_enable`

Then, some patterns just work, like the communication one here: https://wiki.maemo.org/Phone_control#LED

Digging into mce.ini I was trying out the charging patterns, but they do not seem to be doing anything. 

We should:

1. Figure out why the charging patterns do not work.
2. Fire off / show the charging patterns and set the stat_pin_enable to 0 by default.
3. Figure out how to do this on other devices with LEDs.

**Comment by MerlijnWajer** [comment]
Actually, it seems that the charging patterns do work/trigger (after enabling them in gconf). It just doesn't show when the device is not in locked mode / closed... :)

**Comment by MerlijnWajer** [comment]
So: two things we need to do.

1. have this be 0 on boot: `/sys/class/power_supply/bq24150a-0/stat_pin_enable`
2. ensure that above mentioned patterns are all on by default.

@freemangordon  - any ideas about either?

**Comment by MerlijnWajer** [comment]
@spinal84 - I think we can close this one, right?

**Comment by spinal84** [comment]
> So: two things we need to do.
> 
> 1. have this be 0 on boot: `/sys/class/power_supply/bq24150a-0/stat_pin_enable`
> 2. ensure that above mentioned patterns are all on by default.

The first is done in mce startup code.

I'm not sure about the second point. I ran this command manually to enable appropriate LED pattern:
gconftool-2 -s --type boolean /system/osso/dsm/leds/PatternBatteryFull true

Probably need some digging on how defaults for gconf were set.

**Comment by MerlijnWajer** [comment]
Most of the patterns can be set/unset using the notification leds applet in settings, but one of them is missing - it might be the battery full one.

**Comment by MerlijnWajer** [comment]
I think the reason that we have to set it manually is that the RX-51 schema file from this package https://github.com/maemo-leste/osso-applet-notificationlight was never installed.

It looks like, because osso-product-info is missing, we installed RX-34, which defaults this to false, and @parazyd  change to remove the init script install also used RX-34, but we want RX-51, which defaults to true for Full.

https://github.com/maemo-leste/osso-applet-notificationlight/commit/802009bfb3221b42851ca040fc1f125774c94cec

**Comment by MerlijnWajer** [comment]
Fixed in `osso-applet-notificationlight`, closing this issue since everything else just works.
