### ISSUE TITLE
SW: Import osso-xterm

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#19]

**Comment by MerlijnWajer** [comment]
This is done, at least the initial port. Some things don't work:

* "Browser integration"
* Touching the dropdown menu does not work, but using a mouse does toggle it (bug in h-d)
* Theme is not quite OK yet

**Comment by MerlijnWajer** [comment]
Should we make separate tickets for this? None of them directly relate to a basic import of osso-xterm.

**Comment by parazyd** [comment]
@MerlijnWajer can you open an issue for "Theme is not quite OK yet"? I guess you can explain better what's missing.

**Comment by MerlijnWajer** [comment]
The theming is probably just an issue on my side
