### ISSUE TITLE
Install and set up pulseaudio

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#193]
We will likely need it for audio routing, for phone calls, bluetooth, switching between HP and Speakers...

**Comment by MerlijnWajer** [comment]
Right. Is it clever enough to set up mixers properly, when for example a headphone is plugged in? I don't know that much about cleverness in pulseaudio, but this is something we'll have to be able to work with, if we want to do the right thing on incoming phone calls, routing audio to BT, or FM.

**Comment by parazyd** [comment]
https://github.com/maemo-leste/maemo-audio

**Comment by parazyd** [comment]
@MerlijnWajer Should we close this and make new tickets for the specifics like policies, etc?

**Comment by MerlijnWajer** [comment]
Yes.
