### ISSUE TITLE
Figure out how we will run an "extras" like repository

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#194]
maemo.org has an 'extras' repository for fremantle, for community produced extra packages. Currently, we have only one repository, and it should probably only contain core packages. We should figure out where we will host these 'extras' packages - maybe a separate component in the same repository, or just a new repository. We'll also have to figure out how to set up Jenkins to deal with this, and manage Jenkins access control.

**Comment by android-808** [comment]
Are you aiming for a complete extras-devel>extras-testing>extras approach like Maemo or just extras on its own?

If it is more than just extras, something needs to be in place to try to restrict end-users just running the extras-devel equivalent.  At the moment this isn't really an issue given the current audience but further down the line it would be good to avoid the issues we've had in Fremantle.

**Comment by MerlijnWajer** [comment]
I am not sure we will need the complexity of extras-devel, extras-tesing,extras just yet - it also seemed a bit cumbersome to me, at least in the last couple of years. One of the things we'll have to solve is how to build packages for people with jenkins without requiring them to bug us. We could hand out jenkins permissions, but that would then in turn allow people to change any) code/package and rebuild (and automatically distribute) new pcakages/code, which might be a bit of a security risk...

**Comment by MerlijnWajer** [comment]
#202 might be related

**Comment by MerlijnWajer** [comment]
I've created https://github.com/maemo-leste-extras

and plan to give everyone from this organisation, plus other who want to do porting/patching access to it.

We'll make the required Jenkins changes to allow building from this repository, and have a different repository where the packages end up (`leste-extras` and `leste-extras-devel`)

cc @parazyd @freemangordon ?

**Comment by parazyd** [comment]
`leste-extras` has been set up in the infra now as well.

If `leste-extras-devel` is necessary, let me know. It should be fairly trivial as we can do the same thing as we did with `leste` and `leste-devel`.

ACK on organization access.

With regards to Jenkins access, this is something I will handle in due time.

**Comment by MerlijnWajer** [comment]
With regards to due time, it would be good not to have to wait for it too long -- it can be helpful for people to also try builds themselves, and fix issues that come up, instead of asking us every time to build something.

I guess jenkins access right now we can maybe give out relatively easily?

**Comment by parazyd** [comment]
Due time being this week.

I need to set up certain authentication mechanisms in order to do proper separation of users.

**Comment by parazyd** [comment]
This is done, and will be announced with the next blog post.
