### ISSUE TITLE
VM image under qemu only runs unaccelerated.

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#198]
`qemu-system-x86_64 maemo-leste-1.0-amd64-virtual-20181102.vdi` works ok, but it is too slow, as documentation mentions.

`qemu-system-x86_64 -machine accel=kvm maemo-leste-1.0-amd64-virtual-20181102.vdi` hangs after "loading initial ramdisk".

**Comment by MerlijnWajer** [comment]
This is what I use in qemu:

<pre>sudo qemu-system-x86_64 -hda maemo-leste-1.0-amd64-virtual-20181102.qcow2 -vga virtio -enable-kvm -cpu host -smp cores=2 -m 4096 -nic user,hostfwd=tcp:127.0.0.1:7722-:22 -display gtk
</pre>

**Comment by MerlijnWajer** [comment]
I use qemu `2.12.1`, btw.

**Comment by pavelmachek** [comment]
Thanks for working example. I ended up with `sudo qemu-system-x86_64
-hda maemo-leste-1.0-amd64-virtual-20181102.vdi -enable-kvm -cpu host
-smp cores=2 -m 1024`, other options were not known. I guess my qemu
is just old:

QEMU emulator version 2.1.2 (Debian 1:2.1+dfsg-12+deb8u7)

It is definitely too slow without KVM enabled, and it crashes even
without it. I guess I can just use virtualbox.

-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html

**Comment by MerlijnWajer** [comment]
It does sound like a problem in the older qemu (and not in our maemo leste images). Could you try using https://packages.debian.org/jessie-backports/qemu and let me know if it works? I can update the wiki to state that there is an issue with older QEMU versions.

**Comment by pavelmachek** [comment]
I guess this can be closed. But note about which qemu versions work
might be useful.

**Comment by MerlijnWajer** [comment]
OK, thanks for the report, I've made a change to the wiki here:

https://leste.maemo.org/index.php?title=Virtual_Machine&action=historysubmit&type=revision&diff=293&oldid=290

**Comment by jonsger** [comment]
I just changed the description in the wiki [a bit](https://leste.maemo.org/index.php?title=Virtual_Machine&type=revision&diff=320&oldid=319) as it just worked fine with QEMU 2.11.2 on openSUSE Leap 15.0.

**Comment by MerlijnWajer** [comment]
Thanks!
