### ISSUE TITLE
Create a new (possible/suggested) overview of Maemo Leste

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#199]
The Maemo wiki has this graph:

https://wiki.maemo.org/images/9/94/Top_level_architecture.png

It might be nice to have one like that for Maemo Leste. Several components that are marked as closed there are actually open, now, in Leste. And others replaced.

**Comment by MerlijnWajer** [comment]
If we leave the missing pieces empty or as gaps, it's also immediately obvious what is currently lacking, I guess.

**Comment by IMbackK** [comment]
closed as dupe
