### ISSUE TITLE
Handling device-specific packages

### ISSUE THREAD

**Issue by parazyd** [maemo-leste/bugtracker#20]
We also have to discuss what's the prefered way of handling packages that are applicable only for specific devices. Currently I have two options in mind:

1.  **Separate repo category**
We could make the specific package build for a specific category. A category is a repo subdirectory just like `main`, `contrib`, and `non-free` are. So for example in the case of Nokia N900, we would have a category called `n900`. Users would have to append `n900` to their `/etc/apt/sources.list` entry. We could use apt pinning to prefer packages from this category if it is enabled.

2. **Specific package name**
We could append the device name (like `-n900`) to the package name, and add `Provides`, `Conflicts`, and `Replaces` entries in `debian/control`. This would allow users to explicitly request this package and it would replace the existing one.

**Comment by MerlijnWajer** [comment]
Both work for me. Separate repo may be easier for specific hardware enablement, but yeah.

**Comment by parazyd** [comment]
In theory, option 1 would require less work for us, and anyone else maintaining packages.

**Comment by parazyd** [comment]
```
22:37 <Wizzup> Reprepro needs some configuration files:
22:37 <Wizzup>     conf/distributions to descibe the repository layout and the supported distributions and components
22:37 <Wizzup> that's where you add possible distributions
22:37 <Wizzup> er
22:37 <Wizzup> components
22:37 <Wizzup> (e.g. non-free free etc)
22:38 <  parazyd> components, right
22:38 <Wizzup> https://blog.sileht.net/create-a-smart-debian-repository-with-reprepro.html
22:38 <  parazyd> but i dunno how to force a package into a specific component
22:39 <  parazyd> maybe it has to be moved with reprepro (manually)
22:39 <  parazyd> in any case, having specific repo components would allow us to support different devices more easily
22:39 <Wizzup> right
```

**Comment by MerlijnWajer** [comment]
This seems to be working now, with http://maedevu.maemo.org/kawai/pool/n900/x/xserver-xorg-video-fbdev/ and others.
