### ISSUE TITLE
Look at calendar support

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#203]
`calendar-backend` seems to be open source, and there is the open source `qalendar`, and `calendar-home-applet` also has a replacement.

https://github.com/community-ssu/calendar-backend
http://talk.maemo.org/showthread.php?t=90820
http://talk.maemo.org/showthread.php?t=55018

We should try to build these (once Qt is in place?) and see what needs fixing.

**Comment by sicelo** [comment]
`calendar-backend` builds just fine in Leste. I only needed the following:

```
diff --git a/src/VCalConverter.cpp b/src/VCalConverter.cpp
index b14a778..ed4aafa 100644
--- a/src/VCalConverter.cpp
+++ b/src/VCalConverter.cpp
@@ -29,6 +29,7 @@
 #include <sstream>
 #include "CAlarm.h"
 #include "Common.h"
+#include "limits.h"
 
 /**
  * consttructor
```

Additionally, it produces a `calendarclt` application which can manipulate the calendar from the command line.

I also built http://maemo.org/packages/view/cal-home-widget/ but as of now, I haven't been able to make it show on the desktop.

There are other interesting tools (which don't need Qt) from Fremantle which can be tried once `calendar-backend` is up and running properly, such as http://maemo.org/packages/view/maecaltool/

**Comment by buzztiaan** [comment]
https://github.com/buzztiaan/calendar-backend builds on leste beowulf

**Comment by buzztiaan** [comment]
for qalender , i also needed libgq-gconf0 , which is here now ; https://github.com/buzztiaan/libgq

**Comment by buzztiaan** [comment]
qalender itself is at https://github.com/buzztiaan/qalendar but doesnt build yet and my Qt knowledge is pretty much absent :D

**Comment by MerlijnWajer** [comment]
> https://github.com/buzztiaan/calendar-backend builds on leste beowulf

Probably want to increase `debian/compat` from `4` to `5` at least.

**Comment by MerlijnWajer** [comment]
> qalender itself is at https://github.com/buzztiaan/qalendar but doesnt build yet and my Qt knowledge is pretty much absent :D

This is a pretty good target for more Maemo Qt work. The port will not be straightforward since it makes use of various things that are not ported over yet:

* Stacked windows
* Window orientation
* QMenu in the title bar

**Comment by MerlijnWajer** [comment]
I took Buzz' calendar-backend.

And I just got Qalendar to build locally, found a bug in my xcb-maemo qt-platform-plugin, but here it is.
![qalendar-1](https://user-images.githubusercontent.com/517897/93623216-a684d300-f9de-11ea-841d-44333e1604ba.png)
![qalendar-2](https://user-images.githubusercontent.com/517897/93623221-a7b60000-f9de-11ea-9345-231655a3d85a.png)
![qalendar-3](https://user-images.githubusercontent.com/517897/93623222-a84e9680-f9de-11ea-9e7e-08b28e1ebd7a.png)
![qalendar-4](https://user-images.githubusercontent.com/517897/93623227-a8e72d00-f9de-11ea-9753-90c3aa7269cb.png)
![qalendar-5](https://user-images.githubusercontent.com/517897/93623229-a97fc380-f9de-11ea-83eb-6599f6ecff74.png)
![qalendar-6](https://user-images.githubusercontent.com/517897/93623231-a97fc380-f9de-11ea-8180-f82fe88162d3.png)

**Comment by MerlijnWajer** [comment]
Current WIP is here: https://github.com/maemo-leste/qalendar

TODO:

* check calendar-backend changes, host our own fork, and package it
* see why root can see calendars, but user cannot
* make qalendar UI resizable
* port over scrolling
* figure out what to do with the `signal` being defined hack
* test syncevolution
* Add qt-platform-maemo fix for null ptr deref

**Comment by parazyd** [comment]
@MerlijnWajer Done?

**Comment by MerlijnWajer** [comment]
Not everything is done yet. Scrolling is slightly buggy still, everything else seems fine.

**Comment by MerlijnWajer** [comment]
Thanks to everyone who worked on this. We have Qalendar now.
