### ISSUE TITLE
mce doesn't start when /dev/input does not exist

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#204]
Perhaps a bit of a non-issue, but if we boot leste on a raspi with *no* input devices, connected, mce crashes on start, and dsme reboots the device, resulting in a boot loop. It errors because `/dev/input/` doesn't exist, but it wants to monitor it anyway.

**Comment by MerlijnWajer** [comment]
This is probably true as well now for ke-recv-extra.

**Comment by IMbackK** [comment]
this is fixed
