### ISSUE TITLE
Droid4 charger driver needs to be fixed

### ISSUE THREAD

**Issue by spinal84** [maemo-leste/bugtracker#206]
The driver doesn't generate uevents on charger connect/disconnect.
This leads to UPower not detecting when AC is on or off, so not providing userspace with such events.
Also UPower line-power "online" property isn't updated at all after daemon startup.
The value read from  /sys/class/power_supply/usb/online is always accurate.

We found that interrupt for charger connect/disconnect event is traced by the kernel.
It can be observed with "watch -n0.1 grep chrg_det /proc/interrupts" command.

Probably the issue could be fixed by adding irq handling to the driver. But we need a kernel hacker to do this job.

**Comment by pavelmachek** [comment]
If I knew what events to generate, I might try to do a patch. .. I guess n900 drivers work so I could be able to copy code from there?

**Comment by spinal84** [comment]
> If I knew what events to generate, I might try to do a patch. .. I guess n900 drivers work so I could be able to copy code from there?

If you have both devices (n900 and droid4), you may check what events are generated using "udevadm monitor" command. You just need to run that command on n900, attach/detach charger to see what events were produced. And then you need to make Droid4 charger driver to generate similar events, so UPower could handle them.

If you don't have a device, you may want to ask Merlijn Wajer to assist you.

**Comment by MerlijnWajer** [comment]
I think @spinal84 means these (on N900):

<pre>
KERNEL[4145.832793] change   /devices/platform/isp1707/power_supply/isp1704 (power_supply)
UDEV  [4145.877988] change   /devices/platform/isp1707/power_supply/isp1704 (power_supply)
</pre>

**Comment by spinal84** [comment]
I'm not sure, how exactly that should be fixed. It may be a DTS fix. Just a thought.

**Comment by pavelmachek** [comment]
Ok, I tried to deduce how it works on N900, and I don't have a clue.

My isp1704_charger.c does not seem to contain any hints of udev
communication. I guess this should be reported to kernel maintainers,
Sebastian Reichel (see MAINTAINERS) should be right person to talk to.

**Comment by pavelmachek** [comment]
Merlijn: you already explained to me what the patch is. I think it
will work :-).

**Comment by MerlijnWajer** [comment]
Do you mean calling `power_supply_changed` would/could work? (and if so: will you write/test that code? or are you asking me to do it - also fine?) @spinal84 doesn't have a droid4 yet, so it doesn't make sense to ask him to write/test it atm.

**Comment by pavelmachek** [comment]
It seems your suggestion indeed does work :-).

**Comment by MerlijnWajer** [comment]
If it works, when you have some time, can you share the fix and/or post it to linux-omap?

**Comment by pavelmachek** [comment]
Fix is this: ... and it seems to work for me. I'll submit it to
Sebastian...


commit 975de95b17479c2164e5d5423e0f6ae8aa173922
Author: Pavel <pavel@ucw.cz>
Date:   Sat Dec 15 21:03:36 2018 +0100

    cpcap-charger: generate events for userspace.

diff --git a/drivers/power/supply/cpcap-charger.c b/drivers/power/supply/cpcap-charger.c
index 9e8ff5c..7d8b4d5 100644
--- a/drivers/power/supply/cpcap-charger.c
+++ b/drivers/power/supply/cpcap-charger.c
@@ -576,6 +576,7 @@ static void cpcap_usb_detect(struct work_struct *work)
 			goto out_err;
 	}
 
+	power_supply_changed(ddata->usb);
 	return;
 
 out_err:

**Comment by MerlijnWajer** [comment]
Thanks. I'll watch the ML and sign off when I see it.

**Comment by spinal84** [comment]
Pavel, this fix is brilliant!
Could you please point me, how did you find where to insert that command?
I tried to understand how it's done in the module that cpcap_usb_detect() is run on interrupt, but didn't get how that macro from cpcap_charger_probe() works:
INIT_DELAYED_WORK(&ddata->detect_work, cpcap_usb_detect);

**Comment by MerlijnWajer** [comment]
Looks like patch will make it into next release, possibly also stable. Shall we close this issue, so keep it open until we build new kernel with the fix?

**Comment by MerlijnWajer** [comment]
(Also: thanks @pavelmachek)

**Comment by pavelmachek** [comment]
You are welcome :-). But I did not do majority of the work here. Anyway, I'd suggest cherry-picking the patch into our kernels... and then this can be closed.

**Comment by MerlijnWajer** [comment]
Which raises another point: we don't have a droid kernel repo/branch yet. We pick a stable release branch and apply a bunch of patches. I'd prefer to have a git repo here (or just branch) for now, since that makes life much easier, imho.

**Comment by spinal84** [comment]
I think we should test the fix first, using  at least "upower --monitor-detail", before closing the issue.
Did someone check it already?

**Comment by MerlijnWajer** [comment]
Pavel sent it to linux-omap and Tony acked it, so I think it'll be in mainline soon. Pretty sure it's already tested.

**Comment by pavelmachek** [comment]
You are overestimating kernel developers. I'm pretty sure noone but me
tested it.. and I'm not quite sure how much testing I did ;-).

OTOH... it is pretty obvious. We should be fine.

**Comment by MerlijnWajer** [comment]
Let's package a new droid kernel and then close this issue. Maybe we should also look at the bootloader situation soon. @pavelmachek  - how do you load new kernels on the droid currently?

**Comment by MerlijnWajer** [comment]
We have a new droid kernel packaged.
