### ISSUE TITLE
Import modest/tinymail (mail client)

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#207]
Should not depend on qt, but gtk2 only. Might be relatively easy port, and still a very functional piece.

https://github.com/community-ssu/modest
https://github.com/community-ssu/tinymail

**Comment by MerlijnWajer** [comment]
It might depend on microb-engine for html emails, though. That could be a problem...

**Comment by sicelo** [comment]
> It might depend on microb-engine for html emails, though. That could be a problem...

Maybe in the beginning, we could builld tinymail according to the following as mentioned in its README:

> Use --with-html-component=none to disable building any HTML component

**Comment by sicelo** [comment]
tinymail ... a bit of an update:

got it built (manually for now) with `./configure  --enable-gnome=no --with-html-component=none --with-platform=maemo --enable-tp=no --enable-demoui=no`

Needed the following changes to the source:

```
diff --git a/libtinymail-camel/camel-lite/libedataserver/e-data-server-util.h b/libtinymail-camel/camel-lite/libedataserver/e-data-server-util.h
index a533316..9bdb48a 100644
--- a/libtinymail-camel/camel-lite/libedataserver/e-data-server-util.h
+++ b/libtinymail-camel/camel-lite/libedataserver/e-data-server-util.h
@@ -24,9 +24,7 @@
 
 #include <pthread.h>
 #include <sys/types.h>
-#include <glib/gmacros.h>
-#include <glib/gtypes.h>
-#include <glib/gunicode.h>
+#include <glib.h>
 
 G_BEGIN_DECLS
 ```
and
```
diff --git a/libtinymail-camel/camel-lite/camel/camel-tcp-stream.h b/libtinymail-camel/camel-lite/camel/camel-tcp-stream.h
index 902f4d4..646b37a 100644
--- a/libtinymail-camel/camel-lite/camel/camel-tcp-stream.h
+++ b/libtinymail-camel/camel-lite/camel/camel-tcp-stream.h
@@ -24,7 +24,7 @@
 #ifndef CAMEL_TCP_STREAM_H
 #define CAMEL_TCP_STREAM_H
 
-#include <glibconfig.h>
+#include <glib.h>
 
 #ifndef G_OS_WIN32
 #include <sys/types.h>
```

**Comment by MerlijnWajer** [comment]
Also see https://github.com/0mark/modest4leste

**Comment by MerlijnWajer** [comment]
Closed, since it's available in the repos now.
