### ISSUE TITLE
user own files in /etc

### ISSUE THREAD

**Issue by spinal84** [maemo-leste/bugtracker#208]
Actually the owner of /etc is user.

devuan-n900 etc # find /etc ! -uid 0
/etc
/etc/expandcard.sh
/etc/wpa_supplicant
/etc/wpa_supplicant/wpa_supplicant.conf
/etc/default
/etc/default/keyboard
/etc/runlevels
/etc/runlevels/sysinit
/etc/runlevels/sysinit/zram
/etc/modprobe.d
/etc/modprobe.d/nokia-modem.conf
/etc/X11
/etc/X11/xorg.conf.d
/etc/X11/xorg.conf.d/99-calibration.conf
/etc/X11/xorg.conf.d/40-xkb.conf
/etc/network
/etc/network/interfaces
/etc/network/if-pre-up.d
/etc/network/if-pre-up.d/00mac
/etc/osso-af-init
/etc/osso-af-init/locale

devuan-n900 etc # ls -ld /etc /etc/runlevels/
drwxr-xr-x 111 user user 4096 Dec 13 12:15 /etc
drwxr-xr-x   9 user user 4096 Dec 13 12:18 /etc/runlevels/

**Comment by MerlijnWajer** [comment]
I'm assigning @parazyd ; knowing that he's on vacation for a couple of weeks. If this is important, we can fix it in arm-sdk. Otherwise, let's leave it for him.

**Comment by parazyd** [comment]
Fixed in https://github.com/maemo-leste/image-builder/commit/87a70e67d438867b4a16fcee61fb01cacf2e79c8

Will be applied on future image builds.
