### ISSUE TITLE
Port gtk2 to beowulf

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#209]
gtk2 needs to be ported to beowulf - I tried but didn't rebase the extra patches yet (which are there in files, so they need to be applied in git, rebased, and then generated again with format-patch I guess)

<pre>
19:34 < Wizzup> freemangordon: why are the patches in the gtk repo patches and not just commits?
20:31 < freemangordon> Wizzup: so it will be easier to apply against the next gtk version ;)
20:36 < Wizzup> freemangordon: is that the case though?
20:37 < Wizzup> freemangordon: I was looking at the buster/beowulf gtk, and they have a slightly newer minor version, and I thought it might be easier if they were as commits as well, but it doesn't really matter
20:52 < freemangordon> Wizzup: gtk is (or should be) tar.gz
</pre>

**Comment by MerlijnWajer** [comment]
Manually applied patches on top of gtk 2.24.32, found the following:

```
gtk beowulf/buster:

all patches apply, except for:

container failed
treeview failed partially (see postmarketos?)

patches 0001-0003 seems to have been applied upstream
patches/065* seems applied
patches/099*
```

So it should be pretty trivial to make this work.

**Comment by MerlijnWajer** [comment]
I forward ported the two patches, untested, but I think I made the right calls:

```
# cat 0001-wip-forward-port-patches.patch | curl -F 'sprunge=<-' http://sprunge.us
http://sprunge.us/SnOrxr
```

(It's wip.)

It might make sense for @freemangordon to review the rejects that I fixed/changed. I used `git format-patch` to generate the new diff files, but it doesn't make the diffs a lot more clear...

**Comment by MerlijnWajer** [comment]
jfyi, I fixed some other things and will pick this up. Will report when it's done, and what I had to change (very little in the end)

**Comment by MerlijnWajer** [comment]
Just writing what I wrote in IRC here as well:

```
11:55 < Wizzup> parazyd: I prepped beowulf gtk
11:55 < Wizzup> https://github.com/maemo-leste/gtk/commits/maemo/beowulf-prep - and just add our patches at the end of the debian 'series' file
11:55 < Wizzup> I didn't import the beowulf gtk source (yet) because I wanted to preserve freemangordon's history/changes
11:55 < Wizzup> freemangordon: the only noteworthy change is in gtk-container, here:
                https://github.com/maemo-leste/gtk/commit/0240047964d29c1c9000c4dc20dffe950e598613#diff-9939a5fa079a59ff606b974709c8d4eeL167
11:56 < Wizzup> new gtk calls 'return' on invalid coordinates, but hildon patches seem to do something with the invalid coords patch, so I simply
                stripped the return
11:56 < Wizzup> (yes, it's a diff of a diff)
```

**Comment by MerlijnWajer** [comment]
```
13:45 < Wizzup> regarding gtk, this is the only change that didn't apply cleanly
                https://github.com/maemo-leste/gtk/commit/c76d63d6069c80d1768714efbba6ac1444f562a1#diff-9939a5fa079a59ff606b974709c8d4eeL167
13:45 < Wizzup> I removed the if statement that was added if coords are not valid (added by upstream/patches), since maemo code did things even if
                coords were not valid
13:46 < freemangordon> put that somewhere in the TODO, I wanna finnish connui first
13:47 < Wizzup> I am not sure if you got what I said
13:47 < Wizzup> I think I finished it
13:47 < Wizzup> I am just pointing you towards the only thing I wasn't sure of
13:47 < Wizzup> but I'll make a note of it
```

Assigning to @freemangordon so that he can look at my changes when he has time.

**Comment by parazyd** [comment]
Was this finished?

**Comment by MerlijnWajer** [comment]
Yes. It was still pending review by FMG, but maybe it's just been too long.
