### ISSUE TITLE
PowerVR kernel bug

### ISSUE THREAD

**Issue by spinal84** [maemo-leste/bugtracker#212]
The bug triggers kernel hanging when doing poweroff. So if watchdogs are disabled, the kernel will hang forever and the user will be forced to remove the battery from device to be able to boot again.

drivers/gpu/pvr/sysutils.c: vdd2_pre_post_func()
It's assumed that the first time this function is called it will have
event == CPUFREQ_PRECHANGE, but in reality it's often happens (on boot)
that frequency change is in progress, so the first call to this function is with
event == CPUFREQ_POSTCHANGE.
That triggers the bug in drivers/gpu/pvr/pvr_bridge_k.c:81

The workaround is having these lines in init script:
echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  # disable freq changes
... module loading ...
echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  # set ondemand governor back

Having such a workaround is not that good. If we have an init script that changes default governor, or if something changes in kernel, this can break things. So it's better to fix the bug in the kernel driver of powervr.

We probably need a kernel hacker for this job.

**Comment by spinal84** [comment]
Here's the trace that kernel leaves in dmesg:
[   35.349578] SGX clock rate 96 MHz
[   35.369171] ------------[ cut here ]------------
[   35.372528] kernel BUG at drivers/gpu/pvr/pvr_bridge_k.c:81!
[   35.375701] Internal error: Oops - BUG: 0 [#1] PREEMPT ARM
[   35.378906] Modules linked in: pvrsrvkm vfat fat radio_platform_si4713 mousedev joydev hsi_char ir_lirc_codec lirc_dev ir_rx51 rc_core arc4 isp1704_charger gpio_keys pwm_omap_dmtimer smc91
x mii wl1251_spi crc7 wl1251 mac80211 sha256_generic omap3_isp videobuf2_dma_contig v4l2_fwnode videobuf2_memops videobuf2_v4l2 cfg80211 videobuf2_core si4713 adp1653 tsc2005 tsc200x_core v4l
2_common videodev leds_lp5523 bq27xxx_battery_i2c bq2415x_charger leds_lp55xx_common bq27xxx_battery media tsl2563 rtc_twl twl4030_vibra ff_memless lis3lv02d_i2c omap_ssi lis3lv02d input_poll
dev hsi ti_soc_thermal
[   35.400146] CPU: 0 PID: 40 Comm: kworker/0:2 Not tainted 4.15.7+ #1
[   35.403900] Hardware name: Nokia RX-51 board
[   35.407623] Workqueue: events dbs_work_handler
[   35.411529] PC is at pvr_dev_unlock+0x3c/0x40 [pvrsrvkm]
[   35.415313] LR is at vdd2_pre_post_func+0x3c/0xc4 [pvrsrvkm]
[   35.418945] pc : [<bf32a8a8>]    lr : [<bf33b8f8>]    psr: 60030113
[   35.422607] sp : ce441e38  ip : bf343870  fp : c0a035e0
[   35.426300] r10: 00000001  r9 : ffffffff  r8 : 00000000
[   35.429992] r7 : ce441ec8  r6 : 00000001  r5 : 00000000  r4 : 00000001
[   35.433685] r3 : 00000000  r2 : 00000000  r1 : 00000001  r0 : bf343318
[   35.437408] Flags: nZCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
[   35.441162] Control: 10c5387d  Table: 8b098019  DAC: 00000051
[   35.444976] Process kworker/0:2 (pid: 40, stack limit = 0xa18fc4da)
[   35.448852] Stack: (0xce441e38 to 0xce442000)
[   35.452728] 1e20:                                                       ffffffff c0140170
[   35.456695] 1e40: c2a65b18 c2a65b0c 00000000 00000001 ce441ec8 c01405b0 00000000 00000001
[   35.460662] 1e60: ce441ec8 0007a120 ce441ec8 c2a65b04 ce466c00 00000120 00000000 c01405e0
[   35.464660] 1e80: 00000000 00000001 ce441ec8 c054a4a4 00000001 ce466c00 ce441ec8 00000000
[   35.468719] 1ea0: c2a65b04 00000000 00000000 0007a120 ce40dc98 c054a654 00000002 ce466c00
[   35.472839] 1ec0: 00000000 c054af14 00000000 000927c0 0007a120 00000021 ce466c00 ce29ce00
[   35.477020] 1ee0: 006b8f28 007aecc0 ce29c700 ce29ce00 ce5122c0 c054cf24 ce29ce30 00000000
[   35.481231] 1f00: ce29ce04 c0a33ac8 cfcbf100 00000000 c0a18380 c054d348 ce40dc80 ce29ce30
[   35.485473] 1f20: c0a12148 00000000 cfcbf100 c0139758 ce40dc80 ce29ce30 ce40dc80 ce440000
[   35.489685] 1f40: c0a12148 c0a12148 ffffe000 c0a1215c c0a18380 c013a49c ce40dc80 60000113
[   35.493835] 1f60: ce318000 ce437440 ce433240 ce440000 ce40dc80 c013a198 00000000 ce06fee4
[   35.497924] 1f80: ce437458 c013eb28 ce440000 ce433240 c013ea04 00000000 00000000 00000000
[   35.501922] 1fa0: 00000000 00000000 00000000 c0106ec8 00000000 00000000 00000000 00000000
[   35.505798] 1fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[   35.509521] 1fe0: 00000000 00000000 00000000 00000000 00000013 00000000 00000000 00000000
[   35.513214] [<bf32a8a8>] (pvr_dev_unlock [pvrsrvkm]) from [<ffffffff>] (0xffffffff)
[   35.516754] Code: e3a02001 e3a01003 e49de004 ea388a8e (e7f001f2)
[   35.520263] ---[ end trace 1366b387e04d6469 ]---
[   35.526947] mtdoops: ready 54, 119 (no erase)

**Comment by freemangordon** [comment]
fixed by https://github.com/maemo-leste/n9xx-linux/commit/35587731bfb9faa8a751b8e163608bd2b1fda5ef

**Comment by spinal84** [comment]
Did you check that initializing the SGX clocks while CPU frequency transition in progress is safe?

**Comment by spinal84** [comment]
Reopening: your approach is not a fix, but workaround.

**Comment by spinal84** [comment]
A user can run some commands in parallel, for example:

echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor &
modprobe omaplfb

The second command can trigger a wrong behaviour, if the module initialization happens at the same time the CPU frequency scaling transition in progress. After these commands the CPU will be locked at one frequency because of performance scaling governor. So the function vdd2_pre_post_func() will be called only once with event == CPUFREQ_POSTCHANGE. With your "fix" that will be just silently ignored.

**Comment by spinal84** [comment]
Could you please explain your point of view, why the function vdd2_pre_post_func() will not be called at all?

If transition is in progress, while the module is loaded, the function will be called with event == CPUFREQ_POSTCHANGE when transition is complete. No?

**Comment by spinal84** [comment]
The transition can be done after module init functions get current clock rate and after notifier is registered.
Why do you exclude this case?

**Comment by spinal84** [comment]
Just to be clear. The sequence that will trigger a bug with your fix:
1) CPU freq transition starts
2) SGX modules initializes with old CPU frequency
3) SGX driver registers notifier
4) CPU freq transition complete -> notify SGX driver with CPUFREQ_POSTCHANGE
5) Nothing happens in SGX driver, because of your fix
6) CPU frequency is locked after transition complete so SGX driver has no chance to know that it was initialized with wrong CPU frequency.

**Comment by freemangordon** [comment]
yep, this is clear (besides that CPU frequency must be locked as well). However, consider the following sequence:

1. SGX module initializes with current CPU frequency
2. CPU freq transition starts
3. CPU freq transition completes
4. SGX driver registers transition notifier

This will lead to exactly the same result as with what you describe.

That is why I said that notifier must be registered BEFORE current frequency is get. Then we will have correct frequency set no matter what. Also, my patch is not dealing with incorrectly set clock rates - it just prevents driver from raising a BUG() if the notifier is registered mid-transition.

So, to assume - the fix is correct for what it is fixing, nothing more. If there are more problems in the driver (which is for sure) then those problems have to be fixed in separate patches, not as a part of the patch fixing the current issue.

Also, keep in mind that before starting to fix that imaginary wrong clock rates issue, we have way bigger problem to dealt with - bad performance of the 3D graphics compared to Fremantle or Nemo.

**Comment by spinal84** [comment]
In the case you just described, my approach with locking CPU frequency, while the module is loaded, will still be better than your fix, right?

**Comment by MerlijnWajer** [comment]
I think this is dealt with.
