### ISSUE TITLE
Try out newer dsme/mce from mer project

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#213]
<pre>
01:48 < spiiroin> https://git.merproject.org/spiiroin/mce-dev/tree/maemo-leste-hacking
01:48 < spiiroin> ^ no changes were needed -> branch just for convenience
01:48 < spiiroin> https://git.merproject.org/spiiroin/libdsme/tree/maemo-leste-hacking
01:48 < spiiroin> https://git.merproject.org/spiiroin/libiphb/tree/maemo-leste-hacking
01:48 < spiiroin> ^ mostly just get debian build working
01:49 < spiiroin> https://git.merproject.org/spiiroin/dsme/tree/maemo-leste-hacking
01:49 < spiiroin> ^ disable systemd, upstart, ... ; add lifeguard
01:49 < spiiroin> https://git.merproject.org/spiiroin/mce/tree/maemo-leste-hacking
01:49 < spiiroin> ^ different dbus services etc
01:50 < spiiroin> https://github.com/spiiroin/mce-plugin-libhybris/tree/maemo-leste-hacking
01:50 < spiiroin> ^ optional; disable all android hal related features -> leaves sysfs leds
01:50 < spiiroin> Wizzup: that should be what I have now
01:55 < spiiroin> Wizzup: "obvious" gotchas: no sensorfwd -> mce does not see als/ps etc; mce settings are handled via mce dbus interface -> ui
                  that uses gconf/something will be defunct (mcetool can be used though)
01:56 < spiiroin> Wizzup: also: if device has escape key (r-pi), it functions as power key while display is off / tklock is active
</pre>

**Comment by IMbackK** [comment]
i think changes to our mce have made this bug obsolte, our mce has less common code with Fremantle  than mers now

i think we should drop dsme entirely, but again this is but is obsolte

**Comment by MerlijnWajer** [comment]
I am inclined to agree that specifically trying out newer versions might not be necessary, but there's probably still a lot out there that we could use.
