### ISSUE TITLE
hildon-desktop does not render properly if screen width < screen height

### ISSUE THREAD

**Issue by freemangordon** [maemo-leste/bugtracker#214]
( 0,08,19) TheKit: https://github.com/maemo-leste/hildon-desktop/blob/master/src/mb/hd-comp-mgr.h#L190 - it is due to effect of this check, but I could not debug why

**Comment by freemangordon** [comment]
maybe we should trace client in https://github.com/maemo-leste/hildon-desktop/blob/bab369db0be57bca9366fe9e1a7cde0c40fffbb5/src/mb/hd-app.c#L30

**Comment by MerlijnWajer** [comment]
I can reproduce this in QEMU too. It enters landscape mode, and then only half of the screen (or so) is rendered, and the entire right side of the screen falls off. (Just resize qemu on startup to something that has height > width)

I think this is also what blocks the N9, N950, Nexus 5, PinePhone and other devices starting h-d normally.

**Comment by dderby** [comment]
Are those devices (Nexus 5 and PinePhone) using fbdev or DRM?  How well does rotation work on them?  On the N950 under Hildon, it locks up the display.

**Comment by PureTryOut** [comment]
They use DRM. The rotation sensors work, not sure if Hildon actually rotates though.

**Comment by dderby** [comment]
Thanks.  My experience on the N950 was that rotating the screen with xrandr would cause Hildon to hang, but it worked fine under other WMs/DEs.

**Comment by MerlijnWajer** [comment]
I think portrait mode is just broken ATM. Having h-d always enter landscape mode in `src/main.c` seems to take care of this problem and also renders just fine on portrait-mode displays. Just as a note, I didn't see the check mentioned by NotKit being called at all in my (albeit rushed) tests.

Just using this in src/main.c at least makes it OK on displays where h>w:

```
#if 0
  /* Check if orientation is locked to portrait or the device is in vertical position. */
  if (hd_orientation_lock_is_locked_to_portrait ()
          || (!hd_orientation_lock_is_enabled () && hd_home_is_portrait_capable ()))
    {
      hd_render_manager_set_state (HDRM_STATE_HOME_PORTRAIT);
      if (hd_util_change_screen_orientation (wm, TRUE))
        hd_util_root_window_configured (wm);
    }
  else
    {
#endif
      /* Move to landscape for safety. */
      if (hd_util_change_screen_orientation (wm, FALSE))
        hd_util_root_window_configured (wm);
#if 0
    }
#endif
```

**Comment by MerlijnWajer** [comment]
The older hildon-desktop with older libclutter (https://github.com/spinal84/hildon-desktop and https://github.com/spinal84/clutter-0.8/) does allow for 'normal' rotating, at least on the droid4. It has some other quircks, but the rotation seems to work at least. Wonder if it's related to clutter changes or hildon-desktop changes. cc @freemangordon

**Comment by freemangordon** [comment]
could somebody try https://pastebin.com/rBBv0Z6G ?

**Comment by xc-racer99** [comment]
> could somebody try https://pastebin.com/rBBv0Z6G ?

With this diff based on the maemo/ascii branch of hildon-desktop, my display changes from
![2019-09-08-222018_480x800_scrot](https://user-images.githubusercontent.com/5898714/64495339-8eb43400-d24d-11e9-933b-9ef4613a811a.png)
to
![2019-09-08-222502_800x480_scrot](https://user-images.githubusercontent.com/5898714/64495344-9a075f80-d24d-11e9-813f-529a6378b9a9.png)

Note that I'm not using a Leste supported device - I'm using the Droid 4 image (with xorg.conf.d configs removed and a different kernel) on a first-gen Galaxy S device which uses DRM.  The display is in the portrait orientation and is 480x800.  I didn't purposefully rotate either of the screenshots, this is the orientation that scrot took them in.

**Comment by MerlijnWajer** [comment]
I also did some tests, reported those on IRC. Freemangordon said there's more work to be done. For me, I get just a black screen - issue seems to be that clutter renders in the wrong place/offset, so most of the desktop is not visible.

**Comment by MerlijnWajer** [comment]
I think we can close this now. There might still be some issues related to the app launcher menu.

@freemangordon - what do you think?

**Comment by MerlijnWajer** [comment]
(To be clear: the latest `hildon-desktop` in `leste-devel` should take care of most of the issues)

**Comment by freemangordon** [comment]
Yes, lets close it, if there are more issues, lets open more specific tickets
