### ISSUE TITLE
Ensure that powervr fixes end up in the Alpha

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#218]
@spinal84 has various fixes for powervr that make it insanely more usable on the N900. Performance is like on Maemo fremantle, and there are no hangs on startup. We should get this work merged in before we release the Alpha.

**Comment by parazyd** [comment]
I have tested this on the N900 as well and it seems to work.

Do we know if the fixes affect other devices in any way though?

**Comment by MerlijnWajer** [comment]
There's a lot of work to do - see the mails to our ML https://lists.dyne.org/lurker/thread/20190227.172156.0bcd12be.en.html

**Comment by MerlijnWajer** [comment]
Apart from hildon-desktop, I think we have most of it.

**Comment by MerlijnWajer** [comment]
Repos are here - https://github.com/spinal84/clutter-0.8/ && https://github.com/spinal84/hildon-desktop

Let's try to build them in jenkins, and have them just end up in the n900 component. If that's not possible, we can do a manual build (I can do that) and import them with the right epoch/version into the n900 component?

**Comment by MerlijnWajer** [comment]
This is now the case.
