### ISSUE TITLE
Droid4: Provide deb package for droid4-linux

### ISSUE THREAD

**Issue by parazyd** [maemo-leste/bugtracker#220]
https://github.com/maemo-leste/droid4-linux

Once ready, we should make a deb package for the Droid4 kernel.

**Comment by dderby** [comment]
Does it make sense to have a separate tree specifically for Droid 4?  Right now the patches for the Droid 4 consist of DSI and TI LMU/backlight changes.  The DSI patches are also needed for other OMAP devices which use DSI, like thee N950 and N9.

The DRM drivers for OMAP are being reworked and have seen a lot of changes recently.   Here you'll find Sebastian's latest patches which have been re-based on top of [omapdrm/bridge/next](https://git.linuxtv.org/pinchartl/media.git/log/?h=omapdrm/bridge/next):

https://git.kernel.org/pub/scm/linux/kernel/git/sre/linux-n900.git/log/?h=omapdrm/bridge/next-with-dsi

Perhaps there should be a shared tree for omapdrm that we can use for the Droid 4, N950 and N9.

**Comment by MerlijnWajer** [comment]
Yes, I think it makes sense. It makes sense from a packaging point of view. And we spoke with Tony, and he'll prepare a 5.0 + any patches he has once 5.0 is released, so we can use that as a starting point.

**Comment by MerlijnWajer** [comment]
For n900 we are also not using omapdrm. And for n950/n9, well... I think you're the only one who has one that's actively doing anything with Leste atm. :)

**Comment by MerlijnWajer** [comment]
This has been done, we now provide kernel 5.0 with patches. You need the latest kexecboot.
