### ISSUE TITLE
Kernel packages need -dev versions

### ISSUE THREAD

**Issue by parazyd** [maemo-leste/bugtracker#223]
We need to package kernel headers, etc. so external kernel modules can be built on the devices.

This should be achieved by modifying the existing *-linux repos to build additional packages.

**Comment by spinal84** [comment]
Could you please give an example of package that depends on kernel headers that can't be built currently?

**Comment by dderby** [comment]
Other than ZFS which I already mentioned, some of the PVR kernel code should (eventually) be moved out-of-tree and built with DKMS.  It enables non-free software so it should be separated from the main kernel code.  In the Debian release model, it would be categorised as "contrib".

**Comment by MerlijnWajer** [comment]
We're planning to mainline powervr kernel space. So that might not be necessary. But yeah, let's have -dev packages for packages that violate Linux kernel license. ;)

**Comment by MerlijnWajer** [comment]
(That was a serious remark btw, sorry if it came off snarky)

**Comment by dderby** [comment]
Didn't think it was snarky.  Yeah, I've been following the mainline PVR threads.  It would be great if everything can be mainlined.  I was under the impression that some parts (other than the blobs) might not be accepted/mainlinable, but you know more about it than me.  ;)

In any case, I vote against the proposal to save some memory by disabling symbols exported by the kernel.  The ability to build kernel modules on the device is incredibly useful in my opinion.

**Comment by MerlijnWajer** [comment]
Agreed. I think we don't need to specialise kernel config too much now. Feels like premature optimisation.

**Comment by dderby** [comment]
Agreed, especially when we're not yet even in the alpha phase.  Some optimisations, like stripping out anything that may help with debugging don't make much sense right now.  I am however, in favour of a better way to manage the kernel configs and will soon push the work I've done on this, which includes most of @spinal84's optimisations, to my personal GitHub account to get some feedback from yourself and @parazyd.

**Comment by MerlijnWajer** [comment]
Spinal has been working on this.

**Comment by parazyd** [comment]
All kernels that we're packaging now also provide headers. Closing.
