### ISSUE TITLE
N900: SD card image no longer works for me

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#225]
I'm booting using already-installed u-boot on N900. maemo-leste-1.0-armhf-n900-20181103.img.xz works ok in my config, maemo-leste-1.0-armhf-n900-20190315.img.xz does not boot.

I'm just uncompressing img.xz on the SD card, with no modification to the internal flash. I have U-Boot 2013.04 (Apr 20 2013). "External SD Card" option works for me with 201811 image.

**Comment by MerlijnWajer** [comment]
cc @parazyd @spinal84 - any clue what happened? I cannot test before tomorrow.

**Comment by pavelmachek** [comment]
Standby. I may have a clue.

**Comment by spinal84** [comment]
Pavel, please try image from http://maedevu.maemo.org/images/n900/20190225/

**Comment by pavelmachek** [comment]
Ok, I think I have an explanation.

With back cover removed, boot halts at "mmcblk1: p1 p2 p3"

With back cover replaced, userland boots, and things seem to work.

I believe solution is to comment out line
cd-gpios = <&gpio6 0 GPIO_ACTIVE_LOW>; /* 160 */

in the omap3-n900.dts file.

        /* For debugging, it is often good idea to remove this GPIO.
	   It means you can remove back cover (to reboot by
	   removing battery) and still use the MMC card. */
			      

-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html

**Comment by MerlijnWajer** [comment]
@spinal84 - didn't you send a patch to Tony regarding this? Did that break this?

**Comment by spinal84** [comment]
@MerlijnWajer the behaviour @pavelmachek saw was expected.
The kernel is trying to prevent damage to device/microsd card.
In that case it avoids booting the device from microsd card when N900 back cover is open.
IIRC Maemo Fremantle works the similar way - it unmounts microsd card if user opens the cover.

The patch you are talking about is fixing the issue with wrong GPIO polarity of MMC detect. Before it was applied a user couldn't boot from MMC card with back cover closed.
Check commit message for details: https://github.com/torvalds/linux/commit/ac9c908eecde3ed252cb1d67fc79b3c1346f76bc

**Comment by MerlijnWajer** [comment]
Hm. OK, I often work with back cover open though. I guess people who do that will have to patch their kernel/dts?

**Comment by spinal84** [comment]
I prefer to just close the cover :)

**Comment by pavelmachek** [comment]
I understand what the intention was, but it does not work: if you boot
with the back cover, then remove it, SD card stays mounted, so the
"protect the SD card" functionality does not work while the "break
boot" functionality does.

That's why I'm suggesting disabling the cover detection for now.

-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html

**Comment by dderby** [comment]
I'm not a fan of the idea of repeatedly opening and closing the cover, just to satisfy a boot condition.  The plastic isn't that durable and I've already had one of the cover legs break off due to excessive use.

If I recall correctly, Fremantle also removes the device nodes when the cover is open.  My guess is that if you boot with the back cover and remove it later, it probably still tries to umount it but it fails as the root device is in use.  Perhaps we should add a check to see what device the OS was booted from attempting to unmount it.  If it's the SD card, don't do anything.  If it's the eMMC, then we can umount the SD card.

On second thought, I'm not sure how easy it would be to make this portable as the device node names would differ, so maybe we should just disable it altogether. :D

**Comment by spinal84** [comment]
From kernel documentation:

> Card detection:
> If no property below is supplied, host native card detect is used.
> Only one of the properties in this section should be supplied:
>   - broken-cd: There is no card detection available; polling must be used.
>   - cd-gpios: Specify GPIOs for card detection, see gpio binding
>   - non-removable: non-removable slot (like eMMC); assume always present.

The source: Documentation/devicetree/bindings/mmc/mmc.txt

So we can try to use "non-removable" setting for this.

P.S. I'm not sure if there will be no issues if Maemo Leste is installed in EMMC, and a user will try to access/work/replace external mmc card.

**Comment by pavelmachek** [comment]
Removing cd-gpios is easiest (and known good) solution. Card is
removable; I guess "non-removable" would work, too, but I don't see
how it is better.

**Comment by spinal84** [comment]
Should be fixed in the latest kernel image available in Maemo Leste repository. Please check.

**Comment by MerlijnWajer** [comment]
@pavelmachek  Can you retry with https://maedevu.maemo.org/images/n900/20190728/ ?
