### ISSUE TITLE
N900: udev configuration missing for ofonod

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#226]

**Comment by pavelmachek** [comment]
/etc/udev/rules.d/10-nokia-modem.rules needs to be provided and ssi_protocol.ko, cmt_speech.ko, nokia-modem.ko modules need to be inserted in order for ofonod to work. I'm not sure how to handle the modules automatically, but providing .rules file by default should be easy.

**Comment by freemangordon** [comment]
those should be loaded by board DTS IIUC

**Comment by MerlijnWajer** [comment]
@freemangordon - where is this documented?

**Comment by pavelmachek** [comment]
Well, first, I believe we should install the udev.d configuration. That does not 
cost us anything.

For the modules, normally they are autoloaded when they are needed. This apparently
does not happen in n900 modem case. I believe we should just load them at boot.

**Comment by MerlijnWajer** [comment]
I think that the modules do (or at least: did) get loaded for me automatically, what kernel are you on?

**Comment by MerlijnWajer** [comment]
Is this still the case on the latest image? I think it should be ok now?

**Comment by pavelmachek** [comment]
I installed maemo-leste-1.0-armhf-n900-20191020.img.xz and then did apt update/upgrade. /etc/udev/rules.d/10-nokia-modem.rules still does not exist. It should contain:

```
# Export GPIOs for nokia-modem
DRIVER=="nokia-modem", RUN+="/bin/ln -sf /sys/bus/hsi/devices/n900-modem /dev/cmt"

# Tag modem device for ofono
SUBSYSTEMS=="hsi", ENV{OFONO_DRIVER}="n900", ENV{OFONO_ISI_ADDRESS}="108"
KERNEL=="phonet*", ENV{OFONO_DRIVER}="n900", ENV{OFONO_ISI_ADDRESS}="108"

```

**Comment by MerlijnWajer** [comment]
https://github.com/maemo-leste/image-builder/commit/823e994728cbbbb1d34a9f57f5fc4a06a8da115a

**Comment by MerlijnWajer** [comment]
Will build new images tonight. We don't have a package that owns the udev rule atm, so we'll just dump it in the image for now.
