### ISSUE TITLE
Home screen does not work

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#227]
Home screen does not seem to work (except top part): there's no wallpaper and icons can not be placed on the home screen. I'm using maemo-leste-1.0-armhf-n900-20190315.img .

**Comment by pavelmachek** [comment]
(If possible, it would be nice to place at terminal and settings on home screen by default.)

**Comment by MerlijnWajer** [comment]
This was related to bad permissions on `/home/user`, next image build will fix this.

**Comment by MerlijnWajer** [comment]
Should be fixed in https://maedevu.maemo.org/images/n900/20190728/
