### ISSUE TITLE
N900: Audio does not seem to work

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#228]
I'm using maemo-leste-1.0-armhf-n900-20190315. On fresh installation, trying to run aplay fails with "cannot find card '0'". UI does not seem to produce any sounds, either.

**Comment by MerlijnWajer** [comment]
Sounds like I need to try the latest image. Anything in kernel?

**Comment by sicelo** [comment]
audio is working for me on the latest kernel 5.0.9 in repos, after upgrading from maemo-leste-1.0-armhf-n900-20190225.
