### ISSUE TITLE
Create some kind of "release notes" / "welcome application"?

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#229]
Currently, Maemo Leste does not work too well out of the box. You probably want to expand filesystem to full SD card, ifconfig usb0 so that usb connection can be used. Perhaps you want to install phone support that is not included by default, and it would be nice to have some kind of release notes. About dialog would not hurt, either.

I see few possibilities:

1) Creating terminal-based application asking "enter a to expand your filesystem". Few KB.

2) Using terminal-based dialog utility. Should fit under 900KB with dependencies.

3) Using gtk-based dialog utility using "zenity". Would look better, but zenity needs 86MB with dependencies.

4) Creating simple python / gtk based application. Cca 17MB with dependencies.

5) Rust application. A bit more work, probably would fit in 5MB with dependencies.

6) C application. Even more work, but potentially even a bit smaller.

I guess I could create simple python / gtk based application easily, and it might not even look too bad. Would you be willing to include it in default installation?

**Comment by MerlijnWajer** [comment]
It might make sense to make use of hildon/gtk when using python or C, as that should be available by default.
And there are also examples available.

Liking the suggestions!

**Comment by MerlijnWajer** [comment]
https://wiki.maemo.org/PyMaemo/Using_Python_in_Maemo

**Comment by MerlijnWajer** [comment]
http://wiki.maemo.org/PyMaemo#Tutorials

**Comment by MerlijnWajer** [comment]
And http://wiki.maemo.org/PyMaemo/UI_tutorial/Getting_started

**Comment by pavelmachek** [comment]
Thanks for link, but it begins with

"This document is outdated and will not work for Maemo 5
(fremantle)". (And indeed "import gtk" from python2 will not work on
freshly installed 

If Python2 + gtk is acceptable dependency for pre-installed stuff,
I'll try to code something.

-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html

**Comment by MerlijnWajer** [comment]
On Sun, 24 Mar 2019, Pavel Machek wrote:

> Thanks for link, but it begins with
> 
> "This document is outdated and will not work for Maemo 5
> (fremantle)". (And indeed "import gtk" from python2 will not work on
> freshly installed

I think was true for the first link, not for the other links?  (I
deleted the first link)

> If Python2 + gtk is acceptable dependency for pre-installed stuff,
> I'll try to code something.

I'd say it's probably fine.

**Comment by android-808** [comment]
Is python2 a good choice though given the end of its support for python2.7 in 9 months? Python3 has pygtkcompat as part of PyGObject which would allow it (hopefully) to run a PyGTK code but it also notes there is some breakage in GTK2.

https://wiki.gnome.org/Projects/PyGObject/IntrospectionPorting

**Comment by pavelmachek** [comment]
python2 vs. python3 does not matter much for trivial programs, and
python2 has significantly better performance on N900... Unfortunately
the difference is big even on trivial programs.

-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html

**Comment by pavelmachek** [comment]
> > If Python2 + gtk is acceptable dependency for pre-installed stuff,
> > I'll try to code something.
> 
> I'd say it's probably fine.

Ok, first shot... what about this?

https://github.com/pavelmachek/unicsy_demo/blob/master/demo/about

-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html

**Comment by spinal84** [comment]
- "Close" button is excessive.
- Why the name is "about"? I thought it should be something like "Welcome".
- I think it's better to use gtk2 interface for password entry. Like WiFi dialog does.
- Some kind of image, like Maemo Leste emblem or something (possibly at the top of page) would be nice.
- There's no Maemo Leste version yet (or it's something like pre-alpha), so it's better to remove this line now ("Version 20190324"). Maybe we should have a package to add lsb_release. So this could be dynamically retrieved by the script.
- I don't see the message "Welcome to the Maemo Leste..." that is found in the source of the script. Did you want to make "About" button instead of "Close" with that message appear?
- It's better to have separate paragraph for each section of your message to improve readability: "Grow SD Partition...", "Set passwords...", "USB networking..."

**Comment by freemangordon** [comment]
sorry for being late to the party, but what about reusing https://github.com/community-ssu/libcpaboutcssu ?

**Comment by pavelmachek** [comment]
I did rename and few other tweaks.. and can change/improve this further.

But I wanted to know... is this acceptable due to dependencies? Who can merge it to the image?

Can it stay in unicsy_demo repository, or should I create separate repository for it?

**Comment by spinal84** [comment]
Hello, Pavel.
It's better to create separate repository.
We can merge your program to the image when it's ready.
Please take a look at the freemangordon's question above. He's important Maemo Leste developer.

**Comment by MerlijnWajer** [comment]
I think it should have a separate repository, just add the barebones debian/ directory with the source and we can try to build it in Jenkins.

I'm glad to see someone use the Python API, and I'm not sure if the cssu applet can be used per se - I'd prefer to have an application rather than an applet in the settings.

Or is libcpaboutcssu a status applet? I thought it was a setting applet. (Sorry, in air, hard to check ATM)

**Comment by MerlijnWajer** [comment]
Indeed, libcpaboutcssu is a control panel applet, not an application. I think that is not well suited as a 'welcome' application.

**Comment by MerlijnWajer** [comment]
@pavelmachek - alternatively we could package it with unicsy_demo, if you have it install the right `.launch` files in the right place. But probably a separate repo is easier/better for others.

**Comment by pavelmachek** [comment]
I agree separate repository is easiest. Let me make one on github...





-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html

**Comment by pavelmachek** [comment]
I put code into separate project at github.

https://github.com/pavelmachek/welcome-leste

I'm pretty sure debian packaging will need some fixes.

It is possible that layout needs some work, too. Tested on desktop,
not leste.

Patches welcome!

(And sorry, I was quite busy in last months).

-- 
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blog.html

**Comment by MerlijnWajer** [comment]
I tried it, it starts if invoked from terminal `/usr/share/welcome/welcome`:

http://wizzup.org/leste-welcome-0.1.png

**Comment by MerlijnWajer** [comment]
See - https://talk.maemo.org/showthread.php?p=1563667#post1563667

Once those are in the repo, we can probably a more hildonized welcome app.

**Comment by IMbackK** [comment]
We have salutem now
