### ISSUE TITLE
Create SOPine/Anakin & PinePhone images

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#230]
Need to sort out kernel builds, u-boot build(s), lima/mali driver, etc.

**Comment by parazyd** [comment]
Pinephone stuff is committed and we currently have a testing image served on maedevu:

https://maedevu.maemo.org/images/pinephone-dontbeevil/

**Comment by parazyd** [comment]
These have been built and seem to be working.
