### ISSUE TITLE
Theme switching does not work

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#233]
I am not able to switch themes using hildon-desktop/hildon-home ui (nothing happens).

Changing the symlink in `/usr/share/themes/default` to `alpha` or `beta` does the trick after reboot, though.

**Comment by Juesto** [comment]
Late once again but I believe I did notice this issue a while ago. I was not able to perform theme changes using gtk utilities either... And the built-in themes selector just wouldn't work.

**Comment by MerlijnWajer** [comment]
This is fixed now, with https://github.com/maemo-leste/hildon-control-panel-personalisation
