### ISSUE TITLE
Disable armel builds?

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#235]
13:15 < Wizzup> do we want to keep armel builds?
13:15 < Wizzup> cc freemangordon
13:15 < Wizzup> cc spinal84
13:15 < Wizzup> cc dderby
13:15 < spinal84> i don't think so
13:16 < Wizzup> we can always enable them again at some point, but I wonder if we really need it.
13:16 < spinal84> I doubt someone will use them, because of lack of powervr userspace drivers
13:19 < Wizzup> spinal84: I also think there is no device that has to be armel
13:19 < Wizzup> everythin can support armhf
13:20 < parazyd> Yes
13:20 < parazyd> There is only Raspberry Pi 1 (the oldest one) that needs armel.
13:20 < parazyd> We don't support it officially anyway.

**Comment by parazyd** [comment]
Let's disable it once migration is done, and if the need arises, we can just enable it again easily.

**Comment by parazyd** [comment]
Related: https://github.com/maemo-leste/bugtracker/issues/92

**Comment by MerlijnWajer** [comment]
Sounds like we can just nuke the armel target from all our current jenkins jobs.

**Comment by parazyd** [comment]
Disabled armel builds by default and reconfigured existing jobs.
