### ISSUE TITLE
Display brightness UI slider doesn't follow finger

### ISSUE THREAD

**Issue by spinal84** [maemo-leste/bugtracker#236]
1. Run "Settings" application
2. Tap "Display"
3. Press the regulation slider with your finger and move left to the right without releasing.
4. The slider doesn't follow finger.

**Comment by MerlijnWajer** [comment]
See #232.

**Comment by MerlijnWajer** [comment]
Or am I confusing what you're saying?

**Comment by spinal84** [comment]
The bug is probably related to GTK2+ port.

**Comment by clort81** [comment]
If it helps, this video documents the state of usability for simple brightness applet for me.  Multiple taps at various positions of the bar.  Random brightness.

Video: H265, 640x480, 659kB
temporarily available here: [http://0x0.st/-4ki.mkv](http://0x0.st/-4ki.mkv)
[maemo-leste-d4-brightness_app_usability_test.mkv.zip](https://github.com/maemo-leste/bugtracker/files/6948825/maemo-leste-d4-brightness_app_usability_test.mkv.zip)

**Comment by IMbackK** [comment]
im going to open a new bug that makes it clear that this is every gtk2 slider not just the brightness one
