### ISSUE TITLE
osso-xterm/hildon-desktop: Dropdown menu in osso-xterm touch broken

### ISSUE THREAD

**Issue by parazyd** [maemo-leste/bugtracker#24]
The dropdown menu in osso-xterm cannot be opened by touching it. Using a mouse it works. Bug in hildon-desktop?

**Comment by freemangordon** [comment]
Yes, bug (or rather missing full touch support) in hildon-desktop, will check it soon(tm)

**Comment by MerlijnWajer** [comment]
I do not think this is broken anymore. It works for me.
