### ISSUE TITLE
Jenkins has problem building amd64 version of libhildon

### ISSUE THREAD

**Issue by spinal84** [maemo-leste/bugtracker#242]
Tried 2 times with same result:
https://phoenix.maemo.org/job/hildon-binaries/architecture=amd64,label=amd64/3/console
- armhf and arm64 were built fine
- I have successfully built amd64 version of the package on localhost (debian).

**Comment by MerlijnWajer** [comment]
@parazyd - can you take a look when you have time?

**Comment by MerlijnWajer** [comment]
New run is here: https://phoenix.maemo.org/job/libhildon-binaries/architecture=amd64,label=amd64/1/console

Could it be that you locally have some gtk docbook packaged installed that the build machine lacks?

**Comment by spinal84** [comment]
I doubt gtk docbook is somehow connected to the issue. I think the problem is this line (from the build log):
 > dh_install: Cannot find (any matches for) "=>" (tried in "." and "debian/tmp")

The source of this "=>" is here:
 https://github.com/maemo-leste/libhildon/blob/master/debian/libhildon1-examples.install

For me it seems like dh-exec is not able to proceed libhildon1-examples.install file in build machine. The reason is not know to me as I don't have the access to build machine. It maybe Devuan issue or build machine configuration.

As I stated above, I was able to build the package on Debian amd64 system with no problem.

**Comment by MerlijnWajer** [comment]
Maybe if you take a new/fresh debian install and try to build it you may run into similar issues?

**Comment by MerlijnWajer** [comment]
Why do you think that having `=>` in that file is valid? From the sparse documentation that I have found online, this is not allowed. What if you just remove the `=>` ?

**Comment by MerlijnWajer** [comment]
I have removed `=>` and it seems to build now. I did a search for `=>` in all of our repos' `.install` files and this file was the only match. I can only assume it's a mistake. Please check if the built package is OK now.

**Comment by spinal84** [comment]
This "=>" was added by me. It's needed to rename the file while installing. You shouldn't remove it, because without "=>" you will have directory created instead of file renamed.
Check this man page for usage: https://manpages.debian.org/jessie/dh-exec/dh-exec-install.1.en.html

About Debian version I'm using:
```
$ cat /etc/debian_version 
9.9
```

**Comment by parazyd** [comment]
@spinal84 Was this fixed?

**Comment by spinal84** [comment]
I did a workaround mentioned above.
Closing this ticket now.
