### ISSUE TITLE
Missing status menu icons for 4G networks

### ISSUE THREAD

**Issue by dderby** [maemo-leste/bugtracker#244]
Fremantle never ran on 4G devices so Leste won't display the correct icons when connected to LTE (3.9G) and LTE Advanced (4G) networks:

https://github.com/maemo-leste/connui-cellular/blob/master/status-menu-item/status-item.c#L85-L103

**Comment by freemangordon** [comment]
Yeah, I was thinking the same when porting status-menu-item to the REed connui-cellular, however, I guess can use android ones.

In general, we have a bigger problem with themes, we should find someone to volunteer to create a FOSS 'leste' theme so we'll be able to not use Nokia ones.

**Comment by parazyd** [comment]
https://github.com/sicelo/osso-icons/commit/a9aed093e6cc874ebfbdec3f1f8b77cc030cc2e1#diff-5e89e7e4644e5873117ca1788f18b479

**Comment by parazyd** [comment]
@MerlijnWajer Should we merge this? https://github.com/maemo-leste/osso-icons/pull/1
