### ISSUE TITLE
Nokia n9 file '.tar.gz' extraction error 

### ISSUE THREAD

**Issue by 1Mike1** [maemo-leste/bugtracker#245]
hey there,

I tried to install this but I got stuck with file extraction part.

I used the same procedure of sailfish port... I flashed ubiboot_2_3.9, everything was going fine but the extraction part stopped me...

please help me guys how to deal with this issue ...is I am doing something so please guide me.

Thank you

**Comment by MerlijnWajer** [comment]
@dderby and @parazyd - can one of you check this out?

**Comment by dderby** [comment]
I downloaded and extracted the 20190315 tar.gz file and ran into no issues.

@1Mike1, please verify the SHA256 checksum of the zip file matches what's printed in the .sha file.
If the checksum matches and the extraction is still failing, I suspect you have uncorrectable errors on your eMMC device.  The output `dmesg` should show the errors if there are any.

**Comment by 1Mike1** [comment]
hi dderby,

I followed the same step of sailfish installation for partition and check the type of partition which is ext4 only as recommended for Maemo-laste, after that, I untar ubiboot_035_sailfish and flash the with latest ubiboot i.e 3.9 (having the image of Maemo in it). but whenever I try to extract the Maemo file in n9 it gives me an error that invalid magic of tar.

the command which I used in my N9 is : tar --numeric-owner -xvf Maemo-laste-----.tar.gz -C /maemo (/maemo is my mounted partition)

I tried to extract it my mac as well it starts extracting but at the end gives me an error.

Will you please guide me if I am doing something wrong.

Thank you

**Comment by dderby** [comment]
It's a gzipped tarball.  Make sure you use the `tar` command's `z` switch to decompress the archive (if your version of tar supports it), otherwise you can use use `gzip` command to decompress it first.

**Comment by 1Mike1** [comment]
Hi dderby,
I tried on my Mac as well, I have the utility of gzip on my Macbook but still got extraction error at the end.

Thank you.

**Comment by 1Mike1** [comment]
I booted successfully but seems like it is very laggy. and screen orientation is not proper, need to fix it.

**Comment by MerlijnWajer** [comment]
Hi @1Mike1 - please open en issue for the screen orientation not being proper.

As for it being laggy, it doesn't have powervr driver yet, so that makes it slow.

**Comment by dderby** [comment]
@MerlijnWajer, there is already an open issue for that: https://github.com/maemo-leste/bugtracker/issues/183
