### ISSUE TITLE
some commands take longer to execute with no internet connection

### ISSUE THREAD

**Issue by Suppresed** [maemo-leste/bugtracker#246]
Steps to reproduce:

- install emacs-nox
- remove internet connection
- issue emacs on X Term

This is terminal independent.

**Comment by MerlijnWajer** [comment]
This might be related to DNS resolves timing out, but I'm not sure if this if a Leste specific problem. I've also noted this for example with `sudo`.

**Comment by MerlijnWajer** [comment]
This is probably caused by the system hostname not matching the entry in `/etc/hosts` - please make sure they match (we'll make sure to make that's the case in new images too). If that doesn't help, please re-open the bug. Thanks!
