### ISSUE TITLE
conndlgs - problems with lib paths

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#251]
conndlg loads plugins from /usr/lib/conndlgs, but since we migrated to newer debian standards, most plugins get installed to /usr/lib/HOSTARCH/conndlgs, and the code doesn't look here at all, so the dialogs as a result simply don't show anymore...

`dir = g_dir_open("/usr/lib/conndlgs", 0, NULL);` 

in osso-connectivity-ui-conndlgs.c

We should either have the code look in both places or migrate all packages to the newer path and look only in the newer path.

**Comment by MerlijnWajer** [comment]
cc @parazyd @freemangordon

**Comment by MerlijnWajer** [comment]
I've currently committed this, please review @freemangordon - https://github.com/maemo-leste/connui-common/commit/66248116719d1b465917efdaa81f1715ecdc8e7a

**Comment by MerlijnWajer** [comment]
This ended up being the actual fix (C macros are hard) https://github.com/maemo-leste/connui-common/commit/30bbece81c39060954b5b1a209d010aa49c4b2e6 - please review ;)

**Comment by parazyd** [comment]
LGTM

**Comment by sicelo** [comment]
confirming that it works now

**Comment by MerlijnWajer** [comment]
Should be in non leste-devel as well, closing.
