### ISSUE TITLE
Extra packages for images / meta packages

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#252]
This needs to be added in any case: `connui-conndlgs-wlan`

Maybe just to the main connui dialogs package.

These four can be added, but are still in development:

* `connui-cellular-settings`
* `connui-home-cellular`
* `connui-iapsettings-gprs`
* `connui-statusbar-cellular`

**Comment by parazyd** [comment]
Added it in https://github.com/maemo-leste/hildon-connectivity-meta/commit/09f55d5704291d0969f93ae49549f93079266c0e and left a note for the future four packages.
