### ISSUE TITLE
conndlg doesn't allow clicking until wifi scan finishes

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#253]
The connection conndlg doesn't allow clicking a network until after the scan is finished. This is circumvented when you add different network that finishes 'scanning' instantly, like the dummy one.

This will 'fix' the problem:

```
apt install libicd-network-dummy
gconftool-2 -s -t string /system/osso/connectivity/IAP/DUMMY/type DUMMY
gconftool-2 -s -t string /system/osso/connectivity/IAP/DUMMY/name 'Dummy network'
/etc/init.d/icd2 stop
/etc/init.d/icd2 start
```

**Comment by MerlijnWajer** [comment]
See https://github.com/maemo-leste/connui-internet/pull/1

**Comment by sicelo** [comment]
This issue would appear to still be there (at least if the libicd-network-dummy 'fix' isn't applied)

**Comment by MerlijnWajer** [comment]
I think this only happens when `libicd-network-ofono` is installed and it's blocking on search. Can you verify?

**Comment by sicelo** [comment]
You're right

**Comment by MerlijnWajer** [comment]
I think we can close this
