### ISSUE TITLE
Package newer droid4 kernel with modem and drm improvements

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#255]
Info here:

https://lists.dyne.org/lurker/message/20190729.083409.273ac82d.en.html

Branch here:

https://git.kernel.org/pub/scm/linux/kernel/git/tmlind/linux-omap.git/log/?h=droid4-pending-v5.2

We should probably make sure we include the defconfig changes too. I can try to build this locally if that makes sense before attempting packaged builds.

**Comment by MerlijnWajer** [comment]
Latest `leste-devel` has a newer `linux-image-droid4` with lots of improvements. It needs a bit more packaging work to work well with kexecboot, but otherwise we're in good shape!

**Comment by parazyd** [comment]
Is this one done since we've built one for `leste` yesterday?

**Comment by MerlijnWajer** [comment]
Yes. Let's close it. I need to do some udev rules for the modem, but this can be closed. TY
