### ISSUE TITLE
Im(port) hildon-games-wrapper

### ISSUE THREAD

**Issue by android-808** [maemo-leste/bugtracker#259]
Needed to bring Blocks and Marble to Leste.

I have uploaded an initial WIP to https://github.com/android-808/hildon-games-wrapper based on the Fremantle version.  The debian directory needs updating and history/commits are missing if available elsewhere.

**Comment by MerlijnWajer** [comment]
This is now done! https://github.com/maemo-leste/hildon-games-wrapper
