### ISSUE TITLE
HE: Provide kernel tree+config for droid4

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#26]
Preferrably with LCD and HDMI enabled

**Comment by parazyd** [comment]
I've built images with:
* https://github.com/parazyd/arm-sdk/blob/master/boards/kernel-configs/droid4.config
* https://github.com/parazyd/arm-sdk/tree/master/extra/patches/linux-droid4-patches

The patches are applied on top of the 4.14 mainline git tree.

First stab at droid4 images is here (named droid4 obv.): http://maedevu.maemo.org/images/

Keep in mind droid4 is still using llvmpipe (I think), so don't expect it to be fast in any way.

Will wait for reports and check what needs to be done for further enablement.

**Comment by MerlijnWajer** [comment]
I think we can close this -- this works now. There's another ticket open with some final things that should be fixed, but that's for later.
