### ISSUE TITLE
hildon-home wakes up every couple of seconds with failing inotify

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#264]
hildon-home expects `/usr/share/applications/hildon-home` to exist, and while it doesn't it tries to call inotify every couple of seconds. Probably not good for power management.

Let's just make sure the directory exists?

```
[pid  2498] inotify_add_watch(16, "/usr/share/applications/hildon-home", IN_MODIFY|IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF|IN_UNMOUNT|IN_ONLYDIR) = -1 ENOENT (No such file or directory)
```

**Comment by MerlijnWajer** [comment]
Looks like commit `25afa37dc1b19defd3f9b12416c47a74e6ae922f` did that for a similar dir, so let's do it for this one too.

**Comment by MerlijnWajer** [comment]
The same seems to be true for `/usr/lib/hildon-desktop/loaders` ?

**Comment by MerlijnWajer** [comment]
@freemangordon - any thoughts?

**Comment by freemangordon** [comment]
can't we just create that dir from the $package.dirs in debian/ directory?

**Comment by freemangordon** [comment]
which repo is commit 25afa37dc1b19defd3f9b12416c47a74e6ae922f in?

**Comment by MerlijnWajer** [comment]
https://github.com/maemo-leste/hildon-home/commit/25afa37dc1b19defd3f9b12416c47a74e6ae922f

**Comment by MerlijnWajer** [comment]
Fixed in https://github.com/maemo-leste/hildon-home/commit/57df930261f1462d16c454cf2002c0b97086b5bd
