### ISSUE TITLE
Temporarily import/build our own glib

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#268]
We need this glib fix: https://github.com/GNOME/glib/pull/29/files

It's causing our packages not to build / pass tests (in this case: pygtk) - and it's a bug on amd64 and arm64. Let's get this built for our repos, but also try get upstream debian to at least issue a fix release?

You /might/ have to running disable tests on glib - as they failed for me when I tried them on amd64. (Sigh)

Once the package is in, we should re-enable tests for pygtk, and rebuild it.

**Comment by parazyd** [comment]
Waiting to see if Debian will backport a version that contains this patch.

**Comment by parazyd** [comment]
Debian has backported this to stable.
