### ISSUE TITLE
Call/Phone support

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#27]
Let's discuss what paths we have, what a sane choice might be, etc.

**Comment by ollieparanoid** [comment]
Not sure if this is about getting the modem going or the high level interface in maemo (on top of ofono?). But regarding modem stacks, this might be helpful: https://github.com/postmarketOS/pmbootstrap/issues/598

**Comment by NotKit** [comment]
This will be useful to check as well - https://sailfishos.org/wiki/Telephony, as SailfishOS call middleware is opensource and shared by Nemo.

**Comment by MerlijnWajer** [comment]
Looks good.

Regarding the droid4 modem, this is what sre wrote:

> Regarding phone calls: Mainlining of the audio codec is still WIP.
> Once that and display support landed I planed to have a look at it.
> Basically establishing a phone call is a few QMI calls telling the
> modem to start the call and configuring the audio codec properly.
> I don't expect many problems and once its working it should work
> quite good, since audio data does not have to go through cpu (as
> implemented on N900).

Doesn't seem like this path would share a lot with the other proposed paths.

**Comment by NotKit** [comment]
In terms of software it'll likely would. It's usually ofono who is responsible for talking to modem. In case of Android adaptations, ofono RIL driver is used to talk with Android RIL daemon instead of modem directly, and for Droid 4/mainline it will likely be "qmimodem" driver. Telepathy stack and other middleware besides ofono is optional, but Maemo used Telepathy to integrate SIP/other services besides modem itself.

It seems that https://git.merproject.org/mer-core/voicecall can talk both to Teleparhy and oFono directly, so not sure if the first is needed to get it working.

**Comment by pavelmachek** [comment]
If you want phone calls to work on N900, one possible path is:
a) Get ofonod to run. It has config for N900. Worked in postmarketOS at some point. Gives you GPRS data. There were bugs, so choose version 
b) Get working audio.
c) Voice call support -- https://gitlab.com/libcmtspeechdata/libcmtspeechdata -- audio quality could be improved.
d) Gui. Available in unicsy-demo package in postmarketos. You can get SMS support etc. Voice calls should work, too. Python, so rather slow.

Demo is here: https://www.youtube.com/watch?v=AEXOuOfxjVc

**Comment by MerlijnWajer** [comment]
I think it's time we (leste) have a new droid kernel. Ours doesn't even have voice yet. Should we use your tree? And what branch? Are your ofono patches also online somewhere? (I think you shared them by email once)

**Comment by pavelmachek** [comment]
New droid kernel... I am using 4.18. I have updates for v4.20, too, but I'm not really using/testing them. This would be good choice: https://git.kernel.org/pub/scm/linux/kernel/git/pavel/linux-n900.git/log/?h=all-v4.18 If it works, this might be good choice, too... https://git.kernel.org/pub/scm/linux/kernel/git/pavel/linux-n900.git/log/?h=m-v4.20-rc2.9-7

**Comment by pavelmachek** [comment]
So... 5.2 should be quite interesting kernel for Droid 4. No voice
support yet, but at least display + backlight should work. (But the
sysfs interfaces may not be stable yet).

**Comment by IMbackK** [comment]
this bug is obsolete we have ofono, sphone etc working now to various degrees on various devices and other bugs covering remaining shortcomings
