### ISSUE TITLE
Droid 4: Start from scratch with "maemo-leste-1.0-armhf-droid4-20190227.img" image - unable to resolve host, signature expired

### ISSUE THREAD

**Issue by druk13** [maemo-leste/bugtracker#270]
Used the Christmas time and started with a clean install on SD-card.

While using "sudo apt-get update" I got the the following messages:
... sudo: unable to resolve host devuan-droid4
...
... Get:4 http://maedevu.maemo.org/leste leste InRelease [47.6 kB] 
... Err:4 http://maedevu.maemo.org/leste leste InRelease
       The following signatures were invalid: EXPKEYSIG 545FEC4E0927F6FD spam1@wizzup.org

While using "sudo apt-key net-update" I got:
... sudo: unable to resolve host devuan-droid4

Please can anyone help me, to get the actual repositories for the Droid 4?

**Comment by SimonIremonger** [comment]
I understand some new images may be created soon which won't have this issue. However...
I think you can:-

wget https://maedevu.maemo.org/testing-key.asc
apt-key add testing-key.asc

**Comment by druk13** [comment]
See also:
http://talk.maemo.org/showpost.php?p=1564140&postcount=4

**Comment by eloydegen** [comment]
Note that new images have been released, including for the Droid 4: https://maedevu.maemo.org/images/droid4/20200112/

**Comment by druk13** [comment]
Post (http://talk.maemo.org/showthread.php?t=100922) from 14.01.2020:

"What a wonderful day to test "maemo-leste-1.0-armhf-droid4-20200112.img.xz".
But after choosing "Maemo Leste" on KEXECBOOT, the screen stays black and no boot status or GUI is shown."

**Comment by MerlijnWajer** [comment]
Does this happen when you retry booting?

**Comment by druk13** [comment]
Yes, its always black in black.

**Comment by MerlijnWajer** [comment]
if you plug in usb after a bit, do you see usbnet on your host PC?

**Comment by druk13** [comment]
I only have a german linux system, but it says
"usb0: Error reading interface markers: no suitable device found
SIOCSIFADDR: no suitable device found
usb0: Error reading interface markers: no suitable device found"

**Comment by druk13** [comment]
I've also just testet the usb port:
- I've startet android
- I've activated Developer mode
- I've typed "adb devices" in terminal and got my devicenumber
- I've typed "adb shell" and I was in the file system of the android partition

**Comment by MerlijnWajer** [comment]
I don't know what that interface markers error means, but it seems like the device does power on, so maybe the brightness is just set. Can you try to connect? https://leste.maemo.org/Status/USB_Peripheral

**Comment by druk13** [comment]
This text
"usb0: Error reading interface markers: no suitable device found
SIOCSIFADDR: no suitable device found
usb0: Error reading interface markers: no suitable device found"
was the output of the command
"ifconfig usb0 up 192.168.42.1"

**Comment by MerlijnWajer** [comment]
What if you replug the cable a few times? Does anything show up in dmesg? `ifconfig -a`?

**Comment by druk13** [comment]
sudo dmsg -> shows the XT894 as usb device
sudo lsusb -> shows nothing
sudo ifconfig -a -> shows hso0, lo, wlp2s0
sudo ifconfig usb0 up 192.168.42.1 -> shows the text from above

**Comment by druk13** [comment]
I've had no time to build a serial cable to look at the kernel messages during boot.

Thats why I've installed the Android System "98.72.188.XT894.Verizon.eb.US", kexecboot (Version 08.03.2020) and the new maemo-leste logo.

I've no idea why, but after this procedure my SD-Card booted correctly into maemo-leste (Version 23.03.2020) on my Droid 4.
