### ISSUE TITLE
Get volume_status_menu_item from maemo-statusmenu-volume

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#271]

**Comment by sicelo** [comment]
https://github.com/maemo-leste/maemo-statusmenu-volume

**Comment by MerlijnWajer** [comment]
https://github.com/maemo-leste/maemo-statusmenu-volume/blob/master/src/volume_steps_update

**Comment by MerlijnWajer** [comment]
@freemangordon - how did you configure pulseaudio? System wide mode?

**Comment by MerlijnWajer** [comment]
I'm getting the various pulse packages in place, so this should hopefully work relatively soon.
