### ISSUE TITLE
Import osso-mahjong

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#275]
See https://github.com/maemo-leste/bugtracker/issues/238#issuecomment-570806474

Also see https://github.com/maemo-leste-extras/osso-mahjong

We need to decide what graphics we use (libre or standard) and see if we can fix the rendering bug that @android-808 mentions.

**Comment by MerlijnWajer** [comment]
mahjong is in the repo now, but we need to import one of the graphics and sounds packages.

**Comment by IMbackK** [comment]
please reopen in extras if desired
