### ISSUE TITLE
Import  Osso-chess-ui

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#277]
http://maemo.org/packages/package_instance/view/fremantle_ssu_pr1-2_armel/osso-chess-ui/1.8.3-1+0m5/

Relies on gnuchess, so should not be super hard.

**Comment by MerlijnWajer** [comment]
@android-808 - where would I find the source of osso-chess-ui (and maemoblocks for that matter) ?

**Comment by android-808** [comment]
http://repository.maemo.org/pool/fremantle/free/o/osso-chess-ui/

http://repository.maemo.org/pool/fremantle/free/m/maemoblocks/

Not sure if commit history is available anywhere.

**Comment by android-808** [comment]
Might also want http://repository.maemo.org/pool/fremantle/free/g/gnuchess/

**Comment by MerlijnWajer** [comment]
I've managed to mostly make it build, but I can't get it to add `-shared` to the `src/plugin` binary. Will upload sources tomorrow. With a quick hack it also hangs like this:

```
user@devuan:~$ chessui.launch
The font "-*-*-bold-*-normal--*-200-*-*-*-*-iso8859-1" does not support all the required character sets for the current locale "en_US.UTF-8"
  (Missing character set "KOI8-R")
  (Missing character set "JISX0208.1983-0")
  (Missing character set "KSC5601.1987-0")
  (Missing character set "GB2312.1980-0")
  (Missing character set "JISX0201.1976-0")
```

**Comment by MerlijnWajer** [comment]
Pushed most of my fixes. The one remaining build issue is that automake refuses to add `-shared` when linking in `src/plugin/`.

**Comment by IMbackK** [comment]
please reopen in extras if desired
