### ISSUE TITLE
Import debhelper-maemo-package-icons ?

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#282]
At least mypaint seems to want it. I don't know if we still want to keep it around, though.

https://github.com/maemo-leste-extras/mypaint/commit/b182c116309275555ec249f9c0879578465d9055
https://github.com/maemo-leste-extras/mypaint/commit/f192bb816d20751325d6c265d170432d6e755302

**Comment by parazyd** [comment]
Is this equivalent to `dh_maemo_icon` we now have in `maemo-system-services-dev`?

**Comment by parazyd** [comment]
Closing, as dh_maemo_icon is fine and works well.
