### ISSUE TITLE
Finish hildon-application-manager-settings-standard

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#285]
```
14:00 < Wizzup> parazyd: for hildon-application-manager-settings-standard - can we package it and add leste-devel which is disabled by default ?
14:00 < Wizzup> parazyd: is there a reason not to package now? ^^
14:02 < Wizzup> parazyd: this might need attention still
                https://github.com/maemo-leste/hildon-application-manager-settings-standard/blob/master/defaults
```

I guess we want to maybe also add `leste-devel` and disable it by default.

**Comment by MerlijnWajer** [comment]
@parazyd - I think we have something like this now packaged, the only trouble is that we have duplicate entries of the repos, both in the HAM sources.list.d and in our own.

Once we fix that, I think we can close this ticket?

**Comment by parazyd** [comment]
The dupes aren't an issue in new images anymore.

At some point I will port all the repos to HAM catalogues, but out of scope for this.
