### ISSUE TITLE
Document creating maemo sd card image

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#29]
15:38 < Wizzup> freemangordon: guess I will make pali 4.9 kernel soon, do you boot maemo with it by just loading the kernel through u-boot and then
                using the bootargs from the normal boot?
15:40 < freemangordon> yes
15:40 < freemangordon> but maemo itself needs some tweaks
15:40 < freemangordon> like installing bme replacement
15:41 < freemangordon> also, everything from cssu-devel has to be installed, iirc
15:41 < Wizzup> Oh. Have you ever ran maemo on sd card?
15:41 < freemangordon> yes
15:41 < Wizzup> (Because it sounds like it would be easy to have such a maemo env ddable)
15:42 < freemangordon> Pali even has a script to copy maemo to uSD
15:42 < freemangordon> Pali: ^^^ where was that?
15:42 < Wizzup> you can see I miss a lot of years of maemo dev :)
15:42 < freemangordon> here http://bazaar.launchpad.net/~pali/+junk/maemo_M32GB/files
15:43 < Pali> yes, that is it
15:43 < freemangordon> not sure about the order though :)
15:43 < freemangordon> but that copies root to emmc, right?
15:44 < Pali> it copies / to /home/maemo5
15:44 < Pali> M32GBinit.sh
15:45 < Pali> and then there is M32GBboot.sh which create bootmenu entry
15:45 < freemangordon> Wizzup: so, you don;t even need uSD for that memo
15:45 < freemangordon> *maemo

**Comment by parazyd** [comment]
What is the status of this?

**Comment by MerlijnWajer** [comment]
This was for pvr testing, I don't think we need this any time soon.

**Comment by parazyd** [comment]
Closing then.
