### ISSUE TITLE
Droid 4 - Package bluetooth firmware files

### ISSUE THREAD

**Issue by sicelo** [maemo-leste/bugtracker#290]
The BT chip on the Droid 4 needs the firmware file https://github.com/TI-ECS/bt-firmware/blob/master/TIInit_10.6.15.bts
We should see if we can package and distribute it.

**Comment by sicelo** [comment]
Hope this is a step in the right direction? https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949161

**Comment by MerlijnWajer** [comment]
If they take too long we can package it as well. Perhaps mention it on the droid4 image too.

**Comment by dderby** [comment]
This is also now needed for Wi-Fi to work: #296

**Comment by spinal84** [comment]
> Hope this is a step in the right direction? https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949161

This will be denied. They will refuse to package an additional single file that didn't go to upstream.
The proper way to do have it fixed is described here: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/about/

After this is done Debian/Devuan will have the needed firmware automatically, when they pull it from upstream.

**Comment by sicelo** [comment]
Thank you

**Comment by spinal84** [comment]
> The proper way to have it fixed is described here: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/about/

If someone wants to contribute, this one is a good starter.
