### ISSUE TITLE
Droid 4: Compass Support

### ISSUE THREAD

**Issue by sicelo** [maemo-leste/bugtracker#294]
The Droid 4 has a compass, and it seems fully supported in mainline, http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/iio/magnetometer/ak8975.c

We probably can just enable the corresponding config.

**Comment by MerlijnWajer** [comment]
Maybe also mention this in the droid4 image issue.

**Comment by pavelmachek** [comment]
There will still need to be some userland code to actually use the compass ;-). But yes, enabling the driver is good first step.

**Comment by MerlijnWajer** [comment]
Assuming it's a generic (gyroscope) interface, like on the N900, this shouldn't be too much work.

**Comment by MerlijnWajer** [comment]
@parazyd - can we enable this in one of the next builds?

**Comment by parazyd** [comment]
Added to https://github.com/maemo-leste/droid4-linux/commit/58c3aac889bb8e3bd8869f8605eaca4700b296af temporarily. Let's see if we can upstream it.

**Comment by MerlijnWajer** [comment]
Ok, I can confirm it works.

I also compared to the Nokia N900.

MCE uses a `/sys` node on the N900 that no longer has it's values exposed, for the simple reason that the N900 now exposes it (properly?) via `/dev/input`:

```
# evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	TWL4030 Keypad
/dev/input/event1:	ST LIS3LV02DL Accelerometer
/dev/input/event2:	twl4030:vibrator
/dev/input/event3:	twl4030_pwrbutton
/dev/input/event4:	TSC2005 touchscreen
/dev/input/event5:	gpio_keys
/dev/input/event6:	RX-51 AV Jack
Select the device event number [0-6]: 1
Input driver version is 1.0.1
Input device ID: bus 0x19 vendor 0x0 product 0x0 version 0x0
Input device name: "ST LIS3LV02DL Accelerometer"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 307 (BTN_NORTH)
    Event code 308 (BTN_WEST)
    Event code 309 (BTN_Z)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value    -25
      Min    -2304
      Max     2304
      Fuzz      18
      Flat      18
    Event code 1 (ABS_Y)
      Value     60
      Min    -2304
      Max     2304
      Fuzz      18
      Flat      18
    Event code 2 (ABS_Z)
      Value   1055
      Min    -2304
      Max     2304
      Fuzz      18
      Flat      18
Properties:
Testing ... (interrupt to exit)
Event: time 1585567515.979664, type 3 (EV_ABS), code 0 (ABS_X), value -27
Event: time 1585567515.979664, type 3 (EV_ABS), code 2 (ABS_Z), value 1052
Event: time 1585567515.979664, -------------- SYN_REPORT ------------
Event: time 1585567516.032305, type 3 (EV_ABS), code 0 (ABS_X), value -29
Event: time 1585567516.032305, type 3 (EV_ABS), code 2 (ABS_Z), value 1054
Event: time 1585567516.032305, -------------- SYN_REPORT ------------
Event: time 1585567516.086564, type 3 (EV_ABS), code 0 (ABS_X), value -26
Event: time 1585567516.086564, type 3 (EV_ABS), code 2 (ABS_Z), value 1051
Event: time 1585567516.086564, -------------- SYN_REPORT ------------
Event: time 1585567516.198468, type 3 (EV_ABS), code 1 (ABS_Y), value 63
Event: time 1585567516.198468, -------------- SYN_REPORT ------------
Event: time 1585567516.251842, type 3 (EV_ABS), code 0 (ABS_X), value -28
Event: time 1585567516.251842, type 3 (EV_ABS), code 1 (ABS_Y), value 60
Event: time 1585567516.251842, type 3 (EV_ABS), code 2 (ABS_Z), value 1053
Event: time 1585567516.251842, -------------- SYN_REPORT ------------
Event: time 1585567516.307473, type 3 (EV_ABS), code 0 (ABS_X), value -25
Event: time 1585567516.307473, type 3 (EV_ABS), code 2 (ABS_Z), value 1050
Event: time 1585567516.307473, -------------- SYN_REPORT ------------
Event: time 1585567516.362464, type 3 (EV_ABS), code 2 (ABS_Z), value 1053
Event: time 1585567516.362464, -------------- SYN_REPORT ------------
Event: time 1585567516.416783, type 3 (EV_ABS), code 2 (ABS_Z), value 1055
Event: time 1585567516.416783, -------------- SYN_REPORT ------------
Event: time 1585567516.471652, type 3 (EV_ABS), code 1 (ABS_Y), value 63
Event: time 1585567516.471652, -------------- SYN_REPORT ------------
Event: time 1585567516.527528, type 3 (EV_ABS), code 0 (ABS_X), value -27
Event: time 1585567516.527528, type 3 (EV_ABS), code 1 (ABS_Y), value 60
Event: time 1585567516.527528, -------------- SYN_REPORT ------------
Event: time 1585567516.583739, type 3 (EV_ABS), code 0 (ABS_X), value -29
Event: time 1585567516.583739, type 3 (EV_ABS), code 1 (ABS_Y), value 63
Event: time 1585567516.583739, type 3 (EV_ABS), code 2 (ABS_Z), value 1052
Event: time 1585567516.583739, -------------- SYN_REPORT ------------
Event: time 1585567516.637052, type 3 (EV_ABS), code 0 (ABS_X), value -26
Event: time 1585567516.637052, type 3 (EV_ABS), code 1 (ABS_Y), value 60
Event: time 1585567516.637052, type 3 (EV_ABS), code 2 (ABS_Z), value 1054
Event: time 1585567516.637052, -------------- SYN_REPORT ------------
Event: time 1585567516.693477, type 3 (EV_ABS), code 0 (ABS_X), value -28
Event: time 1585567516.693477, -------------- SYN_REPORT ------------
Event: time 1585567516.748956, type 3 (EV_ABS), code 0 (ABS_X), value -25
Event: time 1585567516.748956, type 3 (EV_ABS), code 2 (ABS_Z), value 1051
Event: time 1585567516.748956, -------------- SYN_REPORT ------------
Event: time 1585567516.802238, type 3 (EV_ABS), code 1 (ABS_Y), value 63
Event: time 1585567516.802238, -------------- SYN_REPORT ------------
Event: time 1585567516.857198, type 3 (EV_ABS), code 1 (ABS_Y), value 60
Event: time 1585567516.857198, -------------- SYN_REPORT ------------
```

So my guess is that we will want the Droid 4 to do the same (in kernel), and then write a generic backend for mce that uses `evdev`.

**Comment by MerlijnWajer** [comment]
looks like the n900 driver just creates a joystick - https://github.com/torvalds/linux/blob/master/drivers/misc/lis3lv02d/lis3lv02d.c#L437
https://github.com/torvalds/linux/blob/master/drivers/misc/lis3lv02d/lis3lv02d.c#L672

Probably not too hard to enable/port that on/to AK8975

**Comment by pavelmachek** [comment]
I'm pretty sure accelerometer is _not_ a joystick, and neither is
magnetometer. I'd say that kernel will move away from that in future.

So first, both accelerometer and magnetometer have absolute units, and
it may be interesting to know the absolute values. ("I wonder if my
sports car can accelerate at 2g?" "I wonder how strong this magnet
is?")

Plus, magnetometer really needs some kind of calibration, because
you'll probably want it to point you to the north.. and that's
unlikely to be good match for evdev.

**Comment by MerlijnWajer** [comment]
It looked like the Nokia N900 uses a sysfs interface before, but now it no longer offers that, and instead offers an input device. In this case a joystick. I have a joystick at home that can report three axes, so I think it kind of makes sense.

I didn't know they had to be calibrated.

Have you tried to run `evtest` on the N900? If you pick the right input device, you'll see all the values come in. I think they have ways to report absolute units.

**Comment by clort81** [comment]
Since Neverball works now and has accelerometer code.   Accelerometer on Droid4 (Possibly with magnetometer for help with absolute orientation) would be fun.  

Is this a doable thing to enable for next kernel update?  Currently I have.
```
Linux droid4 5.7.0 #1 SMP PREEMPT Mon Jul 27 19:03:46 UTC 2020 armv7l GNU/Linux
Available devices:
/dev/input/event0:      cpcap-pwrbutton
/dev/input/event1:      Atmel maXTouch Touchscreen
/dev/input/event2:      4a31c000.keypad
/dev/input/event3:      pwm-vibrator
/dev/input/event4:      gpio_keys
```

**Comment by IMbackK** [comment]
this is doable in userpace using uinput, i plan on making a iio -> uinput proxy at some point so simulate a js device using the accel

**Comment by clort81** [comment]
> this is doable in userpace using uinput, i plan on making a iio -> uinput proxy at some point to simulate a js device using the accel. how did you get neverball to work? 

Hours of mucking-about.
![leste-neverball](https://user-images.githubusercontent.com/51511737/91670816-49090f00-eb21-11ea-99d5-f810076e2fad.jpg)
[Neverball Video, 5MB webm](http://0x0.st/iYGQ.webm)
Great framerates too.

**Comment by IMbackK** [comment]
thanks to iio-uinput and the latest kernels this can be closed
