### ISSUE TITLE
Add Tun.ko.gz module to the kernel

### ISSUE THREAD

**Issue by rikkemans** [maemo-leste/bugtracker#295]
When connecting with OpenVPN the following error:

ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
Thu Jan 16 16:29:26 2020 Exiting due to fatal error

**Comment by MerlijnWajer** [comment]
@rikkemans - sorry for the slow response. What device would this be?

cc @spinal84

**Comment by spinal84** [comment]
Fixed in https://github.com/maemo-leste/n9xx-linux/commit/dec53c681944b20e6e4e59bbb0d40bbc7d7f6b11

The updated kernel will be uploaded to the repository soon.

**Comment by rikkemans** [comment]
@MerlijnWajer N900

@spinal84 Great (:

**Comment by sicelo** [comment]
The TUN module is once again not present in latest images/kernels for both N900 and Droid 4.

**Comment by sicelo** [comment]
Latest N900 kernel has it again :)
