### ISSUE TITLE
Port Maemo Leste to Beowulf

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#299]
Below is a list of all packages in Maemo Leste. We need them all ported to `beowulf` / `buster`. Where it makes sense, we should also port the package to debhelper 10. See https://github.com/maemo-leste/bugtracker/issues/234 on that.

This issue is here keep track of the porting progress.

- [x] libcal
- [x] iphbd
- [x] gtk - https://github.com/maemo-leste/bugtracker/issues/209
- [x] libmatchbox2
- [x] mce-dev
- [x] libhildonmime
- [x] cityinfo
- [x] clockd
- [x] libosso
- [x] icd2-osso-ic-dev
- [x] libconic
- [x] osso-systemui-dbus-dev
- [x] libdsme
- [x] statusbar-alarm-dbus-api
- [x] libhildon ( https://github.com/maemo-leste/libhildon/commit/dcd97611b5e335151a4ed30f3ceff9f90e4dc4a5 ; https://github.com/maemo-leste/libhildon/commit/ec26eeb6bc021b0ac5c79fa00ec984029de88a0c ; https://github.com/maemo-leste/libhildon/commit/ae67cb1dd13025600ab4cfa57b89c3500d8aa255 )
- [x] maemo-system-services
- [x] osso-af-utils
- [x] osso-af-startup
- [x] hildon-initscripts ( https://github.com/maemo-leste/hildon-initscripts/commit/8eb37797fa7a101bdd0bccf4bb8228f9bad26375 ; https://github.com/maemo-leste/hildon-initscripts/commit/104ae6e710e17493d1600d281ecfcc064075af22 ; https://github.com/maemo-leste/hildon-initscripts/commit/8eb413193ff8476779aedadc8bfecf83f6fc7c48 )
- [x] osso-af-settings ( https://github.com/maemo-leste/osso-af-settings/commit/c7fd62aade11765be1f539d2e26bcdd65a2f35dd ; https://github.com/maemo-leste/osso-af-settings/commit/8622c0f0584df448afca2f328d67e7cd4f5ed483 ; https://github.com/maemo-leste/osso-af-settings/commit/546b04fbdfea92296cec87dac7449d7d94dd132d )
- [x] ke-recv-extra ( https://github.com/maemo-leste/ke-recv-extra/commit/c78dacbea5a5bd4d0db2ce91ba7a1a0a4787dff1 ; https://github.com/maemo-leste/ke-recv-extra/commit/ce16b0e4cdab386c004113fd1e4f0599abaa3355 ; https://github.com/maemo-leste/ke-recv-extra/commit/3b37f732c0612e3f3e72d9284262fa206a853cf6 ; https://github.com/maemo-leste/ke-recv-extra/commit/370bfd014f5f50d457f69abc44925af81688e8de )
- [x] clipboard-manager ( https://github.com/maemo-leste/clipboard-manager/commit/fec5f6d63444fbfd6077dbe3626ffcc43242c37c ; https://github.com/maemo-leste/clipboard-manager/commit/b2cd18a988dd50ca84804ea4dc682c23af01c576 ; https://github.com/maemo-leste/clipboard-manager/commit/0ebaa463283f9cde61ce2183840bf191493f7fe1 )
- [x] libhildondesktop ( https://github.com/maemo-leste/libhildondesktop/commit/d191a83474de40df6b60929527b7ae52b2475b0b ; https://github.com/maemo-leste/libhildondesktop/commit/11758bd7fd6678f652e63c58b8fe6930001b8049 ; https://github.com/maemo-leste/libhildondesktop/commit/ed93d58cdf88ed65314a71d03da5e88e9b285a90 ; https://github.com/maemo-leste/libhildondesktop/commit/91e51fb645f1aaf5b4b95c9483f4ed25aab7f2d2 ; https://github.com/maemo-leste/libhildondesktop/commit/be4c6d0b3315914248254c8d5a25c75f2792e72c ; https://github.com/maemo-leste/libhildondesktop/commit/4787e407e20920891c2e4e218b5eb81ce1719e34 ; https://github.com/maemo-leste/libhildondesktop/commit/260b01db33a16ecf2215c45f63b1b91bb296d1ff ; https://github.com/maemo-leste/libhildondesktop/commit/1b1fc890f8c73fbc5f372ac232848686b8bd7ef3 ; https://github.com/maemo-leste/libhildondesktop/commit/128322da60d12ab442b03efc14b796b946a2c6ac ; https://github.com/maemo-leste/libhildondesktop/commit/12c3a3a688ab220a3ecfba1247e973b752215ae6 ; https://github.com/maemo-leste/libhildondesktop/commit/cbed197947cf04e379fc3c64effc85bf3002663a ; https://github.com/maemo-leste/libhildondesktop/commit/c9ca2f7afc46748a84c2b47a99f8eec70f531ff3 ; https://github.com/maemo-leste/libhildondesktop/commit/8c852f49415ed65ec72eeca0b8576ed77178f152 ; https://github.com/maemo-leste/libhildondesktop/commit/b62de8e2590a179ad068a33fe64f7b95a80b4860 ; https://github.com/maemo-leste/libhildondesktop/commit/5762304482e58a8d9a8588abdaac8c207c5ac0f3 ; https://github.com/maemo-leste/libhildondesktop/commit/ee909e003efc195990c5d85007b7ebe165439753 ; https://github.com/maemo-leste/libhildondesktop/commit/e98fb02cc7ec9d0e950733bf4d8941935afb840d ; https://github.com/maemo-leste/libhildondesktop/commit/f88b24dbb328fa9c806a745b25f590a00829da1c)
- [x] alarmd ( https://github.com/maemo-leste/alarmd/commit/8fea705a752af1d48d48480d6bf5b6d9f5ff4178 ; https://github.com/maemo-leste/alarmd/commit/8cf79d458714e13ce2a4527ee79a12715e2c5f02 _
- [x] maemo-launcher (see https://github.com/maemo-leste/bugtracker/issues/298) ( https://github.com/maemo-leste/maemo-launcher/commit/ce4a1dc553a2c21c3c83dcc5918e0f7ee2178dc5 ; https://github.com/maemo-leste/maemo-launcher/commit/8e047945c20f530321f17b678363fa1851a52cd0 ; https://github.com/maemo-leste/maemo-launcher/commit/67ede235b2ac45fc7e841fe20119b04ccc81280a )
- [x] profiled ( https://github.com/maemo-leste/profiled/commit/40d45d29e371ed4191b88552fae57df17064f6a8 )
- [x] sapwood
- [x] hildon-theme-cacher ( https://github.com/maemo-leste/hildon-theme-cacher/commit/07cbaef1589ce03ec19f002a494216a2465123d7 ; https://github.com/maemo-leste/hildon-theme-cacher/commit/d6851bfd878b7fc6d6334320aae512bd7720cb6f )
- [x] osso-icons
- [x] dsme (see https://github.com/maemo-leste/bugtracker/issues/297)
- [x] osso-systemui
- [x] osso-systemui-powerkeymenu
- [x] osso-systemui-tklock
- [x] osso-systemui-modechange
- [x] osso-systemui-devlock-dev
- [x] osso-systemui-splashscreen-dev
- [x] osso-systemui-modechange-dev
- [x] libdevlock
- [x] osso-app-killer ( https://github.com/maemo-leste/osso-app-killer/commit/af69221a36a9a638a997385efd722bc8790ab55a ; https://github.com/maemo-leste/osso-app-killer/commit/0e00457150e58bd5a4a349d684f7f88e5ec14f41 )
- [x] codelockui
- [x] hildon-control-panel ( https://github.com/maemo-leste/hildon-control-panel/commit/808a00f99eef9a61be03de5e3db7c54a3a85d0cf ; https://github.com/maemo-leste/hildon-control-panel/commit/a9839cd4cf3c375ae911acc6bebf397155ad56d0 ; https://github.com/maemo-leste/hildon-control-panel/commit/03bbfeb27957b8f7d12ecef48a31b5a8371b35b9 ; https://github.com/maemo-leste/hildon-control-panel/commit/65cc37e76e1fa30c8895769dc78e4154654ba932 ; https://github.com/maemo-leste/hildon-control-panel/commit/b93fc0e0d4279842fa5c8560519d0a4541f4ea48 ; https://github.com/maemo-leste/hildon-control-panel/commit/b598337c4a294aa8c0c790d685d914301ae30d9a ; https://github.com/maemo-leste/hildon-control-panel/commit/75a914b28749a611fa5721ea2f9e58d337ca8aa5 ; https://github.com/maemo-leste/hildon-control-panel/commit/5ceef4cacf34fbf012fdfa1cc99267bb06287bfa ; https://github.com/maemo-leste/hildon-control-panel/commit/e0dffd6e2e249b4ac02acf56221f3bad81f264d9 ; https://github.com/maemo-leste/hildon-control-panel/commit/d83d17745a73ced893595552d5368881d3fefbc0 )
- [x] osso-applet-display
- [x] libplayback
- [x] hildon-plugins-notify-sv (https://github.com/maemo-leste/hildon-plugins-notify-sv/commit/bfb1cd9ddd5ded60a4d0db85721960bade5a6a95 ; https://github.com/maemo-leste/hildon-plugins-notify-sv/commit/74f3746a743de600984ee81b5f67beb618e47f91 ; https://github.com/maemo-leste/hildon-plugins-notify-sv/commit/3cd18b36a8ef581e4ef1c3599b891985740f47c6 ; https://github.com/maemo-leste/hildon-plugins-notify-sv/commit/1a7de010642ebb80ea3b218bb8a99e04743da40a ; https://github.com/maemo-leste/hildon-plugins-notify-sv/commit/6b2cddb6d537830fc7622e47731bc509ee81dc19 ; https://github.com/maemo-leste/hildon-plugins-notify-sv/commit/09350ef73f62d2824ab868e26c86ba5edd2d46e8 ; https://github.com/maemo-leste/hildon-plugins-notify-sv/commit/b6e981761d592069dfdb6a0607c750bd94531f5a)
- [x] osso-systemui-alarm
- [x] mce
- [x] osso-bookmark-engine
- [x] epeg
- [x] hildon-thumbnail (https://github.com/maemo-leste/hildon-thumbnail/commit/1232c0615a068a457e5309795c2d113687b4ee61 ; https://github.com/maemo-leste/hildon-thumbnail/commit/e95a1fb48f05e9ad1554249ea57bf72e34e03cc6)
- [x] libhildonfm (https://github.com/maemo-leste/libhildonfm/commit/e619f98c3a62413c5b6624c7015f2de08f63e11c ; https://github.com/maemo-leste/libhildonfm/commit/c4d1e04eb10bb0201995318a47550f619dde91bd )
- [x] hildon-home (https://github.com/maemo-leste/hildon-home/commit/113c979b2f5d35c0f7c7ca6c9b588e5aa799ad65 ; https://github.com/maemo-leste/hildon-home/commit/476072a2ec659e03edb699878964b0c317604d3c )
- [x] hildon-desktop
- [x] osso-applet-notificationlight
- [x] osso-applet-devicelock
- [x] hildon-status-menu (https://github.com/maemo-leste/hildon-status-menu/commit/bceded46bfef102c5ae3abadc37f5811e7168c11 ; https://github.com/maemo-leste/hildon-status-menu/commit/422eeca0aee32feb9f80e47f7d8119c86f88a1ae )
- [x] osso-xterm
- [x] icd2
- [x] hildon-meta
- [x] hildon-connectivity-meta
- [x] status-menu-applet-profiles ( https://github.com/maemo-leste/status-menu-applet-profiles/commit/7cc69b7811cca84db009cf79b8b1821d67a00d8f ; https://github.com/maemo-leste/status-menu-applet-profiles/commit/372704a284e4b848f78b761b0173a2f68608c233 )
- [x] xorg-server
- [x] status-area-applet-battery ( https://github.com/maemo-leste/status-area-applet-battery/commit/ac74afcb7ea563f3bdb20ea8521ef2ae837b3df8 ; https://github.com/maemo-leste/status-area-applet-battery/commit/3aae075c86d7f64012313e7816b08525bfba8be0 ) + (https://github.com/maemo-leste/status-area-applet-battery/commit/88696aad11f9db2cb26cec8f9eaf30f0abd11b95 ; https://github.com/maemo-leste/status-area-applet-battery/commit/b2a71481dac4242810200dc5c58d44565668b522 ; https://github.com/maemo-leste/status-area-applet-battery/commit/ff2bbf1e361de5e8a832f33f7af22b4270257a3e )
- [x] ofono
- [x] ofono-d4
- [x] connui-common
- [x] maemo-security-certman (https://github.com/maemo-leste/maemo-security-certman/commit/0121c4e0613b9b3f7c906b8dcefe0bee7a513c01 ; https://github.com/maemo-leste/maemo-security-certman/commit/7d7f8d598c2258ac7b5a34af9bedb06f2530aae5 ; https://github.com/maemo-leste/maemo-security-certman/commit/a25965d9ff4e29fdecc47dc48ee00556abd757be)
- [x] libcomapp ( https://github.com/maemo-leste/libcomapp/commit/ada20f434909f8bf2cb28dc0f3234e136e734006 )
- [x] maemo-security-certman-applet ( https://github.com/maemo-leste/connui-internet/commit/f0c64dac3a57c638663379a2d64ec78f8dff43c9 )
- [x] connui-internet ( https://github.com/maemo-leste/connui-internet/commit/f0c64dac3a57c638663379a2d64ec78f8dff43c9 )
- [x] hildon-status-bar-usb ( https://github.com/maemo-leste/hildon-status-bar-usb/commit/6068b1b9424fbabbe17a480949fc1982d996877a ; https://github.com/maemo-leste/hildon-status-bar-usb/commit/3291953a7258b562a9af795a6c446942cb3f58b0 )
- [x] libicd-network-dummy
- [x] libicd-network-usb
- [x] icd2-settings-default
- [x] libusbgx (https://github.com/maemo-leste/libusbgx/commit/2d188e49503c07b74ff029b4c44098849c917971)
- [x] wl1251-cal
- [x] maemo-multimedia-tone-generator
- [x] libicd-network-ipv4
- [x] libconbtui
- [x] connui-wlan
- [x] libicd-network-wpasupplicant
- [x] status-area-orientationlock-applet
- [x] n9xx-linux
- [x] upower
- [x] libscconf
- [x] hildon-input-method-framework
- [x] hildon-input-method ( https://github.com/maemo-leste/hildon-input-method/commit/a883d7ed476d355850f19eda561e9e8fc7311f57 )
- [x] libimlayouts ( https://github.com/maemo-leste/libimlayouts/commit/78c78b7f041877bbfb9dc74fdff4082665559149 )
- [x] libimengines
- [x] hildon-im-vkbrenderer3
- [x] hildon-input-method-configurator
- [x] hildon-input-method-plugins
- [x] osso-applet-textinput
- [x] hildon-input-meta
- [x] mafw
- [ ] mafw-shared
- [ ] mafw-iradio-source
- [ ] mafw-upnp-source
- [x] hildon-usb-gadgets
- [x] ke-recv
- [x] mesa
- [ ] osso-calculator-engine
- [x] unicsy_demo
- [ ] libcmtspeechdata
- [x] droid4-linux
- [x] pine64-kernel
- [ ] rtl8723cs
- [x] ti-omap3-sgx
- [x] xf86-video-pvrsgx
- [x] connui-cellular
- [ ] libofono
- [x] libicd-network-ofono
- [x] libglibutil
- [x] libgofono
- [x] hildon-notify
- [x] statusbar-alarm ( https://github.com/maemo-leste/statusbar-alarm/commit/9418fa58a8076a5b4ef3ca5e8e48d2ed5abd09a5 ; https://github.com/maemo-leste/statusbar-alarm/commit/eb4f5c45b5b0b005f5cb04a42ac2edd9d5f60698 ; https://github.com/maemo-leste/statusbar-alarm/commit/a8dfcd25ac1475cf959b55fd0a34bc2de7fea189 ; https://github.com/maemo-leste/statusbar-alarm/commit/235c827300a5efcde9c7833197cbcb3472b83987 )
- [ ] rtcom-eventlogger
- [x] pygtk
- [x] python-hildon
- [x] python-osso
- [x] python-hildondesktop
- [x] hildon-application-manager
- [x] hildon-application-manager-settings-standard
- [x] osso-pdf-viewer
- [x] libsdl
- [x] sdlgles
- [x] osso-games-startup
- [x] hildon-games-wrapper

**Comment by MerlijnWajer** [comment]
As of right now, I have `hildon-desktop` and `hildon-home` running in a beowulf VM. mce is not yet in the repo since it depends on a patched upower (well, it doesn't depend on it, but for correct functionality, we do)

**Comment by MerlijnWajer** [comment]
Well, it was pretty smooth sailing until I hit `libcomapp`, which depends on `libgnomevfs-2.0`, which has been nuked entirely from buster: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893922

We will either have to port various packages, or see if we can import `libgnomevfs-2.0` for now, create an issue for it, and deal with it later.

**Comment by spinal84** [comment]
I think, if libgnomevfs is gone from Debian, there was a good reason. We shouldn't depend on it.

**Comment by MerlijnWajer** [comment]
Agreed - we will just have to port a few packages to `GIO`.

**Comment by MerlijnWajer** [comment]
upower and mce now done thanks to @spinal84 porting our upower patches (thanks!)

Will try to pick up the GIO porting soon (others are welcome to help!) and finish the job.

**Comment by MerlijnWajer** [comment]
For GIO porting, the commits here are probably very useful:

https://github.com/maemo-leste/libhildonfm/commits/master?after=c4d1e04eb10bb0201995318a47550f619dde91bd+34

Starting from https://github.com/maemo-leste/libhildonfm/commit/27346e8531ff93bedeb09f7be6bd3389707b83d8

**Comment by spinal84** [comment]
According to wikipedia gnome-vfs was deprecated by gvfs:
https://en.wikipedia.org/wiki/GnomeVFS

**Comment by spinal84** [comment]
libcomapp is ported

**Comment by MerlijnWajer** [comment]
maemo-security-certman-applet ported but not yet tested, see commit message.

**Comment by MerlijnWajer** [comment]
As an update, it boots reliably to hildon-desktop now for me. `ke-recv` is still missing, and `osso-pdf-reader` and `hildon-application-manager` use gnome-vfs quite a bit (meh), so I might remove them from the meta for a few days, to get at least everything else done.

First issues I'm seeing now is that many hildon status applets install to /usr/lib/hildon-desktop and not /usr/lib/<arch>/hildon-desktop and there are no symlinks, so we'll have to look at the connui stuff and make it all work in a similar manner.

**Comment by MerlijnWajer** [comment]
I've ported `hildon-status-bar-usb`, `status-menu-applet-profiles` and `status-area-applet-battery` to dh10 and autotools, and now they all show up / work.

**Comment by spinal84** [comment]
Not directly connected to Beowulf porting, but should be mentioned here. This change can be useful while we are working on debian/rules files: https://github.com/spinal84/alsa-policy-enforcement/commit/2ca052bd7ca7f4f754cda67c15ce4c4751ee932e

This should remove a lot of debian build system warnings, and I think it could save some system resources (memory/cpu) while launching apps.

Of course, it should be tested that this change doesn't break deb package building (just in case). Please report if you find some issues with it.

**Comment by freemangordon** [comment]
Yes, we should use -Wl,--as-needed as much as possible. However, adding export DEB_LDFLAGS_MAINT_APPEND = -Wl,--as-needed to debian/rules is not enough (and for some reason it didn't work when I tried it), https://github.com/maemo-leste/status-menu-applet-profiles/commit/20bc72e5d69567bfab39282c99fed433961bc95b is what makes it work for sure in combination with https://github.com/maemo-leste/status-menu-applet-profiles/commit/828aa5f44c0bb9a0c10abc8b3bc77e3a5a2524a5#diff-c949f93d03f44a4217d7a138f9e2e54aR13 - mind the order,  -Wl,--as-needed must be first, otherwise it seem to be ignored

**Comment by MerlijnWajer** [comment]
I `apt upgrade`'d the `20200112` n900 image and it upgraded live and everything seems OK after a reboot. There's more to port, per above list, but we're so close. I'd build images but arm-sdk is giving me a hard time.

**Comment by spinal84** [comment]
> Yes, we should use -Wl,--as-needed as much as possible. However, adding export DEB_LDFLAGS_MAINT_APPEND = -Wl,--as-needed to debian/rules is not enough (and for some reason it didn't work when I tried it),

Which package did you try to implement it?

**Comment by freemangordon** [comment]
Can't remember, however, maybe it needs both DEB_LDFLAGS_MAINT_APPEND = -Wl,--as-needed and dh_autoreconf --as-needed to work. The latter is needed when libtool is used.

**Comment by spinal84** [comment]
> Can't remember, however, maybe it needs both DEB_LDFLAGS_MAINT_APPEND = -Wl,--as-needed and dh_autoreconf --as-needed to work. The latter is needed when libtool is used.

Tell me when you have problems with DEB_LDFLAGS_MAINT_APPEND  = -Wl,--as-needed.
I'll help you to resolve it. From my experience adding this line should be enough (if configure.ac and Makefile.am files are properly written).

**Comment by freemangordon** [comment]
seems I am missing something - how is configure.ac related?

**Comment by spinal84** [comment]
I'm not sure how. It's about practicing, not talking. I may be wrong.

**Comment by MerlijnWajer** [comment]
I am going to close this, as we've taken care of all the relevant packages. The few ones left out can be added when we need them.

Congratulations everyone involved!
