### ISSUE TITLE
dsme has -Werror removed for now - fix this later

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#30]
While trying to get everything to build for devuan ascii, I ran into an error in dsme that I was unable to easily fix. _BSD_SOURCE is defined by something included by glib.h; and /usr/include/features.h issues a #warning that _BSD_SOURCE is deprecated - I don't think there is a specific -Wno-error-... for this warning, since it seems to be a generic warning.

Happy to be proven wrong, didn't spend a lot of time on it.

https://github.com/maemo-leste/dsme/commit/743253ce430abce6ba5466cceeb46b77f9001f82

**Comment by freemangordon** [comment]
fixed in commit 428c0c469aa482bc4e9339ef9c382bf6ff9121af and commit facdcc596d0104f498979bbb41d6f3318c9327a6
