### ISSUE TITLE
profiled: question regarding beowulf

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#300]
@spinal84 and @freemangordon -- I just ported profiled to dh10 locally, but it doesn't install libraries into `/usr/lib/<arch>/` since it doesn't use `autotools`. Do we also want to fixup custom-Makefile projects like this, or do we defer that and do it later, not part of beowulf-porting or dh10-porting?

https://github.com/maemo-leste/profiled/commit/40d45d29e371ed4191b88552fae57df17064f6a8 (only in maemo/beowulf atm)

**Comment by spinal84** [comment]
No need to waste a lot of time on that package. If it works, just leave it.

**Comment by MerlijnWajer** [comment]
Closed with https://github.com/maemo-leste/profiled/commit/40d45d29e371ed4191b88552fae57df17064f6a8
