### ISSUE TITLE
FOSDEM 2020 To-Do list

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#303]
1. Beowulf port done (?)
2. connui-cellular in some working state (with or without pinentry, home and status menu)
3. libicd-network-ofono should set up data connection with ip and such
4. pinephone image(s)
5. make some games work on the pinephone

**Comment by MerlijnWajer** [comment]
Glorious would be if we can get accelerated hildon-desktop to work on the droid4 in some form.

**Comment by MerlijnWajer** [comment]
Having something like this would be nice too: https://github.com/maemo-leste/bugtracker/issues/199

**Comment by dderby** [comment]
Maybe a maemo.org homepage replacement would be nice to have in time for FOSDEM, even if it's just replacing it with the content from https://maemo-leste.github.io/ for now.  See #147 for discussion.

**Comment by MerlijnWajer** [comment]
Regardless of what actually worked, this bug can be closed.
