### ISSUE TITLE
Import Themes control panel applet

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#306]

**Comment by sicelo** [comment]
This one? http://maemo.org/packages/package_instance/view/fremantle_extras-devel_free_armel/theme-customizer/0.9-77/

Depends on Qt :-(

**Comment by MerlijnWajer** [comment]
No, just the default one in Fremantle.

**Comment by MerlijnWajer** [comment]
Seems to be a part of `hildon-control-panel-personalisation`

**Comment by MerlijnWajer** [comment]
This is mostly done, btw.

**Comment by MerlijnWajer** [comment]
Initial version is now in the repos. Some things remain to be finished, but it's operational now.

**Comment by MerlijnWajer** [comment]
MOSTLY works -- looks like existing GTK apps do not yet update their menu theme yet, so that will have to be fixed before this is closed.

**Comment by MerlijnWajer** [comment]
Fixed in 1.0.1!
