### ISSUE TITLE
osso-xterm: enter in tmux via ssh doesn't work

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#308]
Not sure what part of my environment this relates to, maybe it's not a Leste bug (although it works on Fremantle), but when log in to my server over ssh, Run `tmux attach`, then run `ctrl-a + s` (if you use default keybindings, this is `ctrl-b + s`).
Then I can select between my tmux sessions, I can move to the other one with arrow keys, but pressing enter doesn't work. `ctrl+m` does work.

**Comment by spinal84** [comment]
1. I coulnd't reproduce it on localhost. Doing `ssh root@localhost` on Nokia N900.
2. Try removing this line from mapping and rebooting:
https://salsa.debian.org/installer-team/console-setup/blob/master/Keyboard/ckb/symbols/nokia_vndr/rx-51#L426
The file is /usr/share/X11/xkb/symbols/nokia_vndr/rx-51

**Comment by MerlijnWajer** [comment]
Doing that makes enter just not work. ;)

**Comment by spinal84** [comment]
Try replacing it with:
`key <RTRN>	{ [	Return    ] };`

**Comment by MerlijnWajer** [comment]
That ... works!

**Comment by MerlijnWajer** [comment]
Although it does trigger the vkb currently.

**Comment by spinal84** [comment]
> Although it does trigger the vkb currently.

In that case we should remove vkb triggering/toggling by Enter keypress from hildon input method framework.
Hm... That is a serious change. Should we ask @freemangordon and all Maemo people around what they think about it? :)

**Comment by spinal84** [comment]
I can remove the specific code that triggers vkb toggling on Enter keypress (it's a pre-n900 devices legacy).

The problem can be fixed the other way. Currently hildon input method doesn't receive keyboard slide state from an external program. If it detects, the vkb should not appear. The paths it listens are:
```
/system/osso/af/keyboard-attached
/system/osso/af/slide-open
```

**Comment by MerlijnWajer** [comment]
Right, so we want this: https://github.com/maemo-leste/bugtracker/issues/17#issuecomment-528497018

**Comment by spinal84** [comment]
> Although it does trigger the vkb currently.

Should be fixed with https://github.com/maemo-leste/hildon-input-method/pull/1

**Comment by freemangordon** [comment]
Is this issue still valid?

**Comment by spinal84** [comment]
With the mapping from the following comment it should be fine now:
https://github.com/maemo-leste/bugtracker/issues/263#issuecomment-581042462

**Comment by MerlijnWajer** [comment]
But that mapping will break enter with vkb, won't it? (will try a bit later)

**Comment by spinal84** [comment]
Should be fixed by https://github.com/maemo-leste/xkb-data/pull/1 and recent changes to hildon-input-method.

**Comment by spinal84** [comment]
@MerlijnWajer, does it work for you?

**Comment by MerlijnWajer** [comment]
Yes, I think this can be marked as solved.
