### ISSUE TITLE
N900 will not power down when battery is empty

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#312]
I left N900 sitting on a table (powered on) by mistake. When I came back, it was in a reboot loop, as battery ran out. It is hard to charge device from such state (especially if battery is new). It would be down to power device down, so battery is not depleted completely.

**Comment by pavelmachek** [comment]
(May be duplicate of #171 )

**Comment by IMbackK** [comment]
mce battery-guard fixes this

**Comment by MerlijnWajer** [comment]
Let's close when it's merged (real soon).

**Comment by IMbackK** [comment]
its merged
