### ISSUE TITLE
We rely on MicroSD, which is not reliable

### ISSUE THREAD

**Issue by spinal84** [maemo-leste/bugtracker#313]
I'm pretty sure there are some ext4 features or alternative filesystems that allow us to handle MicroSD errors and failures. Checksums, journaling and all this stuff.

BTW, I'm still not assured that MicroSD uses wear leveling (I/O errors are suspiciously common). If it does not, we should pay attention on specialised journaling file systems.

**Comment by eloydegen** [comment]
If we would do so, I think F2FS is one of the best available options for flash friendly filesystems. It's supported in mainline and actively maintained.

**Comment by dderby** [comment]
I agree, F2FS would be a good choice.  I noticed last week that it's currently not enabled for the N900 kernel (and possibly other devices too, I haven't checked).  It would be a good start to enable it.

**Comment by spinal84** [comment]
Added F2FS support to the latest kernel available from leste-devel repository.
If someone wants to test F2FS on Nokia N900, please upgrade.
The kernel will go to the stable repository in a week or two.

**Comment by MerlijnWajer** [comment]
The reason we went for ext4 with specific degraded options was for people to allow mounting the SD card from fremantle. If you want to handle data checksums, why not go for btrfs?

**Comment by MerlijnWajer** [comment]
But to be honest, personally I'd like to stick to ext4 for a bit, btw. btrfs is fun, but I think ext4 should be the default for now. f2fs sounds cool, I've never used it before, though.

**Comment by eloydegen** [comment]
Btw, F2FS doesn't seem to support online resizing. That makes it incompatible with #229.

**Comment by spinal84** [comment]
> f2fs sounds cool, I've never used it before, though.

Same here. Did anyone check if MicroSD uses wear leveling?
If it uses, we don't need F2FS.

**Comment by MerlijnWajer** [comment]
Yes. MicroSD cards use wear levelling and other sophisticated techniques. They often contain much more storage than they advertise, too. ext4 is not a bad choice for microsd cards, although they sometimes get optimised for more simple file systems like vfat.

**Comment by spinal84** [comment]
In this case we don't need to have F2FS support compiled in kernel.
I will make it as a module. Did anyone transit to F2FS on root filesystem?

**Comment by MerlijnWajer** [comment]
I would like to have BTRFS compiled in, if not already. It does live compression, snapshots, subvolumes and I plan to use it by default on my personal devices.

**Comment by dderby** [comment]
Most distros build filesystems as modules which are loaded automatically.  Compiling them in will increase the kernel footprint for everyone, even if they will never use those particular filesystems.  I don't think it's a good idea to compile them in as we are supporting devices with very limited memory.  For this reason, I think it's preferable to compile all filesystems as modules.

**Comment by spinal84** [comment]
@dderby, we currently don't use initrd, that's why root filesystems should be compiled in.

**Comment by dderby** [comment]
True.  Maybe we should use an initrd.

**Comment by MerlijnWajer** [comment]
Or include only the few useful FSes in the kernel, and the rest as modules. :)

**Comment by dderby** [comment]
Who defines which filesystems are useful?  I'd argue that if the kernel supports them, it's because they are useful, therefore all filesystems should be available (as modules) at boot time. Maemo is an OS suitiable for hackers, so we shouldn't limit flexibility by not using an initrd.  Memory footprint reduction would make it worthwhile alone IMO.  :)

**Comment by MerlijnWajer** [comment]
I wouldn't argue that the minix filesystem is as useful as ext4 and btrfs. Do you think people will use Minix, CIFS or ISO9660 as a root filesystem for Maemo?

**Comment by MerlijnWajer** [comment]
I don't mean to be difficult, but I think it's silly to state all filesystems are equal. And I personally am not in favour of an initrd, unless we want to use it for full disk encryption, which I do want eventually.

Having an initrd is fine, relying on it for basic rootfs mount is annoying and makes the dev and debug cycle harder, IMHO.

**Comment by dderby** [comment]
> I wouldn't argue that the minix filesystem is as useful as ext4 and btrfs. Do you think people will use Minix, CIFS or ISO9660 as a root filesystem for Maemo?

Perhaps not.  I haven't explored the intricacies of MINIX FS, but I'll take your word for it.

Let's not forgert that Btrfs is not just a filesystem, but also a volume manager.  That sounds like a code to be adding to the default kernel footprint.  I think we should at least compare the footprint with and without Btrfs to quantify the impact it would have on memory constrained devices like the N900, before deciding to compile it in.

> And I personally am not in favour of an initrd, unless we want to use it for full disk encryption, which I do want eventually.

Full disk encryption would be another use case.  So it sounds like using initrd is on the table. :)

> Having an initrd is fine, relying on it for basic rootfs mount is annoying and makes the dev and debug cycle harder, IMHO.

No arguments here for compiling in the default rootfs (ext4) and making initrd optional.  I'd like to think that once initrd is working, it aught not to cause much effect on the dev and debug cycle.  Should it cause a problem, you should just be able remove it from the U-Boot config and boot the kernel directly.

**Comment by MerlijnWajer** [comment]
I've been using btrfs for years on pretty much all my machines and it's invaluable for debugging. It allows you to make the most risky changes and revert them with the snap of a finger (as opposed to ext4, either rsyncing stuff, or even re-dding an image). The argument that it would somehow have any significant impact on the memory footprint is not one I buy. But if you really must know, I can compile a kernel with and without, and compare the size.

**Comment by SimonIremonger** [comment]
Main point I would make is just how wildly uSD cards are in quality, I suspect this is much of the 'unreliaility' right-there, in poor (or incompatible) cards...  +1 to supporting more FS'es and options, check RAM usage etc.   Also bear-in-mind good to be able to support an SD-card swap (which simply may be needed in certain circumstances, even if not used routinely).

**Comment by spinal84** [comment]
> I would like to have BTRFS compiled in, if not already. It does live compression, snapshots, subvolumes and checksumming of data and I plan to use it by default on my personal devices.

Done in linux-image-5.1.21.3, the image is uploaded to maemo/ascii repository.

**Comment by IMbackK** [comment]
we can close this ext4 is fine and uSD cards are not fundamentally unreliable
