### ISSUE TITLE
/etc/hildon/theme is no longer created

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#314]
Probably a regression caused by some dh 10 porting.

**Comment by MerlijnWajer** [comment]
@parazyd - is this fixed now with the new meta packages? Also in `ascii` ?

**Comment by parazyd** [comment]
It's fixed both in Beowulf and Ascii with this package: https://github.com/maemo-leste/theme-default-settings/

The installation of hildon-meta automatically pulls this one.
