### ISSUE TITLE
Hildon-input-method further fixes needed  [key-swap, vkb key control]

### ISSUE THREAD

**Issue by SimonIremonger** [maemo-leste/bugtracker#316]
Hildon-Input-Method (as used by osso-xterm) has traditionally worked with the X11 keymap for the N8xx and N9xx, swap around Return<>KP_Enter for a number of historic/original reasons, notably the N8xx D-pad button and other old decisions described as a "Broken UI Spec".  This swap is shortly removed in Leste rx-51/n900 keymap, and also not applicable to other devices (e.g. droid4, VMs, ...).

**NB** Turns out, that H-I-M, is designed also, to swap around Return <> Enter in presenting keys to hildon applications, which traditionally 'un-did' the swappiness of the old X11 keymap.
This second-swap basically needs removing too!.

For example, ncurses applications can tell the difference between Return and Enter, for example install "tf5", launch osso-xterm, run tf5, and press enter, you may get warning about nkpEnt not mapped!.  This is because this second return/kp_enter swapping needs removing.  This does not happen with tf5 in normal xterm.

As such, 3 issues of further fixes/improvement to sort out for hildon-input-method.
1)  Return/Enter swapping in H-I-M needs removing (certainly for osso-xterm.).
2)  Likely related to issue that Enter-presses may not work if osso-xterm started quickly after boot.
3)  Related issue that pressing enter or return may be part of procedure to activate the VKB on some devices, likely this needs changing to be a selectable key-combination?

This is, however, less-urgent, as immediate blocking issues have been resolved already!.

**Comment by spinal84** [comment]
Please write a step-by-step instruction how to reproduce the issues you have.

**Comment by SimonIremonger** [comment]
OK, problem #1 reproduction:   open osso-xterm, then  "dmesg | less"  then "/test"  then try to press n900 enter, you will get silly "ESCOM" or so, as H-I-M isn't sending proper code through.
Alternatively, "apt-get -y install tf5" then in osso-xterm run "tf5" and try to press enter, complains about nkpEnt !.
These problems do not occur on desktop linux, nor on n900-fremantle (where the double swap is functional).

This must be because H-I-M is still 'swapping' Enter and Return keys still, as per original broken spec...

**Comment by SimonIremonger** [comment]
problem #2 reproduction was done by @spinal84  saying "For this, one should start osso-xterm as fast as possible after system boots (use the stylus not to miss). If he does so, the remapped Enter key will stop working. Ctrl-Enter will work as expected. On Droid4 it's pretty hard to reproduce because of slow UI, but on Nokia N900 it can be done reliably.".

**Comment by SimonIremonger** [comment]
problem #3 is not really an issue for me as-yet, but in clearing up any Enter/Return key behaviours in H-I-M  will need to sort out how to configure any keys needed in activating VKB on different leste-supporting devices.

**Comment by SimonIremonger** [comment]
I can confirm #1 is fixed and assured #2 is fixed.  Possibilities of popping-up vkb is another matter -- apparently configurabble to any key now, via /usr/share/hildon-desktop/shortcuts.ini.leste ...
In short, this bug can be closed now too!.
