### ISSUE TITLE
N900 and Droid 4 power management

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#317]
The Motorola Droid 4 and the Nokia N900 have OMAP SoCs in there with sophisticated power management.

We should try to get that working well on the devices.

Tony wrote this OpenRC init script for the Droid 4: https://github.com/tmlind/droid4-pm/

With minor changes it can mostly work on the Nokia N900 too.

We probably want to mount debugfs via /etc/fstab for now (cc @parazyd )

I tried some of this on the N900, and on 5.5 with minimal config and almost no modules loaded, it works well. But certain modules make the device not go into power saving.

The droid4-pm lists a few of those modules. On the N900, the touchscreen module (at least on mainline) also prevents any entering of deeper sleep states. Perhaps the PowerVR changes that we have do something like that as well. I am slowly going to add modules and userspace to see if I can come up with a list of all things that block idle.

I will provide some instructions for the N900 later here on this ticket.

@freemangordon - any preferences for how we set up kernel-level pm? Stuff like timeout in ms, control to auto, that kind of stuff. It feels to me like a init script could do the trick, but maybe we want it in userspace instead?

**Comment by spinal84** [comment]
On Maemo Fremantle it was /etc/pmconfig with settings for kernel power management.
This file was read by /sbin/preinit, which seemed to initialize device PM, R&D and ACT_DEAD modes. /etc/pmconfig was analyzed using /sbin/read_cfg.awk. And this awk scipt does acutal PM settings to the kernel.

**Comment by spinal84** [comment]
However, I don't see what tool launches /sbin/preinit

**Comment by MerlijnWajer** [comment]
I don't think we need to worry too much about what Fremantle does. The init script just needs to configure autosuspend via `/sys` and `/sys/kernel/debug`. No parameters should be required, it should all just work once the drivers and userspace behave.

**Comment by MerlijnWajer** [comment]
What Tony made seems to do the job, and it's already a neat and simple init script.

**Comment by spinal84** [comment]
I'm just looking at how it was done if Fremantle. Thought you will be curious too. Sorry :)

**Comment by MerlijnWajer** [comment]
Sure, more info is always good.

**Comment by MerlijnWajer** [comment]
If it's a problem for systemd-as-init, we could also create the script in /usr/sbin and have the init scripts just call the script.

**Comment by sicelo** [comment]
[results.log](https://github.com/maemo-leste/bugtracker/files/4199488/results.log)

**Comment by Suppresed** [comment]
I have issues running droid4-pm. I don't seem to have /sys/kernel/debug/pm_debug. So it fails at line 108

**Comment by spinal84** [comment]
> I have issues running droid4-pm. I don't seem to have /sys/kernel/debug/pm_debug. So it fails at line 108

From IRC logs:
`<tmlind> Wizzup: care to add mounting debugfs by default to /etc/inittab? Something like: none /sys/kernel/debug debugfs defaults 0 0`

**Comment by MerlijnWajer** [comment]
On my Droid 4 I am currently seeing about `80-140mW` with droid4-pm enabled, and latest ascii-devel kernel. Can still be better, but that is without removing touchscreen module, and SGX  working.

**Comment by MerlijnWajer** [comment]
```
# sleep 20 && /etc/init.d/droid4-pm status
 * SoC idle RET:62144, power consumption 146 mW
```

**Comment by pavelmachek** [comment]
I tried power management on Droid4, 20200323 version. And battery lasted more than 9 hours, but less than 17. That was without modem and without any tweaks. If 146mW power consumption is right, I should be getting 49 hours of battery life or something.

(IIRC battery is 1.8Ah, at 4V and assuming 146mW consuption:)

1800*4 / 146
49

**Comment by MerlijnWajer** [comment]
So what I did was two things:

* disable or remove touchscreen (currently `rmmod atmel_mxt_ts`, but we are one more MCE pull request away from doing it properly)
* rmmod `phy_cpcap_usb`

**Comment by MerlijnWajer** [comment]
and of course, you need the MCE patches that also enable DPMS on the X11 screen -- will try to get that all pushed and built tonight.

**Comment by MerlijnWajer** [comment]
So I did three things, really. I did keep wifi on.

**Comment by MerlijnWajer** [comment]
I can get the device to idle with modem on at about 65mW now. This should be the same for all Maemo Leste users. Let's close this ticket and open ones for specific power management problems.
