### ISSUE TITLE
hildon-home - Replace GSimpleAsyncResult with GTask

### ISSUE THREAD

**Issue by parazyd** [maemo-leste/bugtracker#32]
On Devuan Ascii glib version, we have deprecated calls which lead to build failures since -Werror is enabled.

-Werror is disabled. Reenable it when this bug is closed.

```
20:52 <  parazyd> hd-background-info.c:370:3: error: 'g_simple_async_result_is_valid' is deprecated [-Werror=deprecated-declarations]
20:52 <  parazyd> glib
20:53 <  parazyd> hold on, i'll paste the build log
20:53 <freemangordon> just a sec
20:53 <freemangordon> ok
20:53 <  parazyd> https://ptpb.pw/C0TS
20:53 <  parazyd> near the bottom
20:54 <  parazyd> worst case we disable -Werror
20:55 <freemango> parazyd: yep, disable -Werror and create an issue "Replace GSimpleAsyncResult with  GTask"

```

**Comment by MerlijnWajer** [comment]
This is still an issue for beowulf porting too. BTW, I would recommend not disabling `-Werror`, but rather the specific warning, with `-Wno-deprecated-declarations`.

**Comment by parazyd** [comment]
Closing, as this is still a deprecation.

When we need actual porting (probably for Devuan Chimaera), we should have a separate ticket that encompasses each software that needs updating.
