### ISSUE TITLE
Repository organisation

### ISSUE THREAD

**Issue by spinal84** [maemo-leste/bugtracker#320]
What we currently have: multiple repositories for a single distribution.
What I propose to have: a single central repository for all our work.

Let's take a look at http://ftp.debian.org/debian/
We can see 2 repository folders there: dists and pool.
In "pool" directory, we can find all .deb files structured by a component: main, contrib, non-free.

The interesting part is what we can find in "dists" folder.
There we can see a single directory for every Debian release.

I propose to have a similar structure to what Debian team does.
Here I will try to show clearly how it may look.

Currently, we have these four repositories:
https://maedevu.maemo.org/leste  <- for ascii
https://maedevu.maemo.org/leste-devel <- for ascii
https://maedevu.maemo.org/leste-extras <- for ascii
https://maedevu.maemo.org/bayamo <- for beowulf

What we may have:
https://maedevu.maemo.org/leste <- a single well structured repository for everything

The directory structure may look like this:
https://maedevu.maemo.org/leste/dists/ascii
https://maedevu.maemo.org/leste/dists/ascii-devel
https://maedevu.maemo.org/leste/dists/beowulf

And a nice single pool structured by components:
https://maedevu.maemo.org/leste/pool/main
https://maedevu.maemo.org/leste/pool/extras
https://maedevu.maemo.org/leste/pool/non-free
https://maedevu.maemo.org/leste/pool/n900
https://maedevu.maemo.org/leste/pool/droid4
https://maedevu.maemo.org/leste/pool/pinephone
etc.

If we are going to support Debian, it will be just a matter of adding two folders:
https://maedevu.maemo.org/leste/dists/stretch
https://maedevu.maemo.org/leste/dists/buster

**Comment by spinal84** [comment]
Here's how the irrational organisation look like in the code:
https://github.com/maemo-leste/jenkins-integration/blob/19e3e0a1bf23d161da7c5e0ab1d355ff1c35aa05/debian_glue#L117

`http://maedevu.maemo.org/${release} ${release} main contrib non-free`
Why was this double ${release} ${release} needed? It could be just:
`http://maedevu.maemo.org/ ${release} main contrib non-free`

What I propose, is using:
`http://maedevu.maemo.org/${release} ${distribution} main contrib non-free`

Actually, the release can be omitted, and we get this:
`http://maedevu.maemo.org/leste ${distribution} main contrib non-free`

**Comment by spinal84** [comment]
Nice bonus: we will have to set only one parameter in Jenkins when building a job.
It will be distribution. For now it could be:
beowulf, ascii, ascii-devel

Much easier than remembering pairs (which can be error prone):
leste/ascii, leste-devel/ascii-devel, bayamo/beowulf

**Comment by MerlijnWajer** [comment]
This sounds good. I would also like 'symlinks' if possible, like `stable -> stretch` and `unstable` -> `buster`. (for example)

**Comment by spinal84** [comment]
Update
---
Instead of having **_extras_** as a component, we should make it as a separate repository.

The summary
---
Directory structure:
https://maedevu.maemo.org/leste/dists/ascii
https://maedevu.maemo.org/leste/dists/ascii-devel
https://maedevu.maemo.org/leste/dists/beowulf
https://maedevu.maemo.org/leste-extras/dists/ascii
https://maedevu.maemo.org/leste-extras/dists/beowulf

Symlinks:
https://maedevu.maemo.org/leste/dists/stable -> ascii
https://maedevu.maemo.org/leste/dists/unstable -> beowulf
https://maedevu.maemo.org/leste/dists/devel -> ascii-devel

**Comment by parazyd** [comment]
Alright. I think I made this work. The repositories are now at http://maedevu.maemo.org/leste/ and http://maedevu.maemo.org/extras/ . I haven't tested extras, so there might be possible glitches that I'm unaware of. We'll see when the time comes.

As for the commits that implement this:
* https://github.com/maemo-leste/jenkins-integration/commit/9885a1c0c002a7663cac3a406ea609459b32b033
* https://github.com/maemo-leste/jenkins-integration/commit/1dd25a72a1962205a24923ebdc71a61e6560822e

`/etc/apt/sources.list` will how have to contain

```
deb http://maedevu.maemo.org/leste ascii main contrib non-free
```

**Comment by MerlijnWajer** [comment]
With this pretty much in place, shall we post a news update telling people how to switch, and also roll new images? We can probably fix some droid4 bugs now.

**Comment by spinal84** [comment]
@parazyd, thanks!

If I understand correctly, currently we should use these pairs in Jenkins when starting a build job:
```
leste/ascii
leste/ascii-devel
leste/beowulf
extras/ascii
extras/beowulf
```

The next step may be making 'release' variable which can have two values - leste and extras - to be autodetected. So we will need to only enter distribution name when scheduling a build job.

**Comment by spinal84** [comment]
> With this pretty much in place, shall we post a news update telling people how to switch, and also roll new images? We can probably fix some droid4 bugs now.

It's almost the end of month now. So we can tell people about this reorganisation and other interesting things in the current monthly update.

Releasing new images with fixes is reasonable.

**Comment by parazyd** [comment]
@spinal84 With the Python scripts, we can now build jobs with:

```
# Build for /leste
run-job.py -j package -d ascii
# Build for /extras
run-job.py -j package -d extras
```

My reasoning for this is because we will most probably not be experimenting with extras, but only ever support a single dist with it.

**Comment by parazyd** [comment]
> @parazyd, thanks!
> 
> If I understand correctly, currently we should use these pairs in Jenkins when starting a build job:
> 
> ```
> leste/ascii
> leste/ascii-devel
> leste/beowulf
> extras/ascii
> extras/beowulf
> ```
> 
> The next step may be making 'release' variable which can have two values - leste and extras - to be autodetected. So we will need to only enter distribution name when scheduling a build job.

This is now correct.

We could try to do something regarding autodetection. The difference between the two is the URL of the git repository that gets cloned.

**Comment by parazyd** [comment]
Closing. This is finished, and if we want to improve/change, we should have a separate bug, or just a pull request.

Thanks!
