### ISSUE TITLE
Droid 4 screen dies while in vt

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#322]
While in vt if the phone sits idle for a while the screen blanks as per usual with the old school terminal blanking. However nothing the user can do turns the screen back on after this happens.

**Comment by spinal84** [comment]
Do you mean the vt in osso-xterm or text mode console of Linux without hildon-desktop running?
Could you please give a step-by-step instruction how to reproduce the bug?

**Comment by IMbackK** [comment]
Reproduction:
1. boot phone to hildon-desktop
2. open osso-xterm
3. aquire root
4. "chvt 3"
5. log in
6. wait several min
7. screen blanks
8. no key will wake screen
9. ssh works fine
10. I have not yet tried to unblank the console via ssh

**Comment by MerlijnWajer** [comment]
Hehe. There's a few reasons not to:

1. hildon-input-method only works in X, so you'll have a different keymap, and miss out of other features for input
2. It's going to get faster with working PVR (which is coming)
3. Maemo never really let you go to a different tty, so there's probably a lot that is untested.

I assume the power key also didn't help waking the device up?

**Comment by MerlijnWajer** [comment]
I think that if you full screen osso-xterm, it's supposedly a little faster.

**Comment by MerlijnWajer** [comment]
Is this still relevant with latest image?

**Comment by IMbackK** [comment]
I cant test this bug currently because with omapdrm my device hardlocks on chvt with current image

**Comment by IMbackK** [comment]
no longer repoduces in current version
