### ISSUE TITLE
hildon-desktop: default to GLES2 in Xsession script

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#324]
Should we default to GLES/EGL in `/etc/X11/Xsession.post/20hildon-desktop` ?

The pinephone (and probably other lima devices) need this to work. [1]
Most of the devices we support will support EGL and GLES2, but not necessarily GL.

```
export COGL_RENDERER=egl_xlib
export COGL_DRIVER=gles2
```

[1] `hildon-desktop` segfaults without it, but `hildon-desktop.launch` does not, but eh.

cc @freemangordon and @parazyd

**Comment by parazyd** [comment]
This was implemented in https://github.com/maemo-leste/hildon-desktop/commit/cce2bb500f7f2f0eb0526aacc2e2a4165af485b7 and is configured by `leste-config` packages where needed.
