### ISSUE TITLE
Missing bluetooth firmware package for Pinephone.

### ISSUE THREAD

**Issue by BigET** [maemo-leste/bugtracker#327]
I have installed the image for pinephone and the bluetooth firmware seams to be missing.

Searching for the missing file reported in the dmesg output, it was "rtl8723cs_xx_fw.bin"

I have found this project that provides a [deb](https://gitlab.com/a-wai/firmware-rtl8723cs) for it.

after installing the firmware and reboot, I have a working bluetooth.

I can connect my K480 keyboard to my phone.

**Comment by MerlijnWajer** [comment]
Thank you for reporting bug, sorry it took over 6 days to respond.

Do you know if that the authoritative place for that firmware file?

**Comment by BigET** [comment]
Nope.
But I can confirmed that after this firmware and instalation of "bluetooth" packages.
I can use bluetoothctrl command to pair devices.

**Comment by dderby** [comment]
This might be the authoritative place: https://github.com/anarsoul/rtl8723bt-firmware

Vasily Khoruzhick (anarsoul) added the driver and DT bindings to the pine64 kernel but they haven't landed in mainline yet.

**Comment by norayr** [comment]
there is ready to use repository, already debianized, from ubports:

https://github.com/ubports/linux-firmware-pine64-rtl8723-bt

it is only necessary to build it and add to default pinephone image.

also, all devices need user 'user' to be member of the bluetooth group.

**Comment by IMbackK** [comment]
firmware can be taken from https://github.com/ubports/linux-firmware-pine64-rtl8723-bt
but figure out where upstream is please

**Comment by MerlijnWajer** [comment]
This is solved for now, package is `linux-firmware-pine64-rtl8723-bt`, see https://github.com/maemo-leste/linux-firmware-pine64-rtl8723-bt
