### ISSUE TITLE
Repository organisation: further simplifications

### ISSUE THREAD

**Issue by spinal84** [maemo-leste/bugtracker#328]
I propose to make Jenkins use maemo/${distribution} branch only when it's available.
It may use master branch as a fallback if maemo/${distribution} is absent.

This approach could allow us to only have maemo/${distribution} branches on packages that really need these.

The Jenkins plugin that allows this setup is called "Alternative build chooser".

**Comment by spinal84** [comment]
The fallback chain can even be like this: maemo/ascii -> maemo -> master
With such implementation we will be able to have a single branch for kernel packages from which our distributions will be built.
It will be useful because master branch is already occupied by Linus and I would rather leave it as it is.

**Comment by parazyd** [comment]
On 4 March 2020 09:40:35 CET, "Arthur D." <notifications@github.com> wrote:
>Jenkins should use maemo/${distribution} branch only when it's
>available.
>It should use master branch as a fallback if maemo/${distribution} is
>absent.
>
>This will allow us to only have maemo/${distribution} branch on
>packages which really need this.
>
>The possible implementation:
>https://plugins.jenkins.io/git-chooser-alternative/

I'd rather not. The branches are a good identifier of what's happening with a package, and them being optional would just make a mess because we wouldn't be enforcing a standard throughout our software/packages.

With kernel branches, have a look at how I did the droid4 or pine64 packages with maemo/* as orphan branches, if that's what worries you.

**Comment by MerlijnWajer** [comment]
I also kind of like the explicit requirement of a branch, it enforces a certain consistency.

Any particular reason you'd like to change it?

**Comment by spinal84** [comment]
@parazyd  The orphan branch for kernel is fine. What I propose doesn't enforce us to remove branches from every package we have. It's just a new convenient way to maintain repositories.

@MerlijnWajer It's about time saving and reducing error prone.

Currently it's a burden for developers to constantly synchronize 2-4 branches, instead of spending their time on doing some useful work.

If we could make symlinks in git like maemo/ascii -> master, maemo/beowulf -> master, and just push changes to master, I think everyone could be happy. But we can't do it.

Time saving is really important for all of us. But it doesn't seem like a valuable with our current approach.

Pros:
* Easier understanding of how to work with Maemo Leste community and develop software for it. All the complications we are used to can and will frighten newcomers
* Time saving and simple approach
* Reduced error prone
* Less burden

Cons:
* ...?

**Comment by spinal84** [comment]
Some quotes from our irc log:

```
<freemangordon> parazyd: also, is there a way to make things easier with git now we
have beowulf branch for every package as well. I mean - I have to push to 4 branches
for every change I do
...
<parazyd> fmg said it's getting too annoying to push to 4+ branches
<parazyd> So I was thinking of starting doing the same like we have with our kernel
repos/packages (orphan debian branches)
<Wizzup> What are those 4 branches?
<freemangordon> ascii/ascii-devel/beowulf/master
<Wizzup> We won't have to worry about ascii anymore soon
<freemangordon> still, our current workflow is error-prone
<freemangordon> for example ke-recv master is missing commits in ascii-devel
<Wizzup> Yes, this is true
```

```
<Wizzup> marmistrz: sorry, gimme a sec
<Wizzup> marmistrz: no, you're on the wrong branch -- this is very confusing
<Wizzup> marmistrz: I will test your PR locally
...
<marmistrz> Wizzup: I'm on master.
```

```
<freemangordon> Wizzup: I lost what is the status of -devel branches
<freemangordon> when they are supposed to be merged to master and ascii and
put in jenkins?
<Wizzup> what do you mean?
<freemangordon> because I fixed couple of nasty bugs in icd2, but pushed in -devel
branch
<Wizzup> I think maemo/ascii doesn't have to follow master, but maemo/ascii-devel
probably does
<Wizzup> if you think the fixes are good for ascii, just push em to ascii from
ascii-devel
<freemangordon> ah, so I should have push in master?
<Wizzup> we have no real workflow
<Wizzup> master for new code, maemo/ascii for new stable release, maemo/ascii-devel
for new test builds
<Wizzup> I sometimes just psuh to maemo/ascii if I feel like -devel makes no sense
<freemangordon> hmm
<freemangordon> I'll just make all 3 branches equal
<Wizzup> sure
<Wizzup> just make sure someone runs the jenkins build
<Wizzup> we could have it poll the repos perhaps
<freemangordon> O.o
<freemangordon> "Your branch is ahead of 'origin/maemo/ascii' by 57 commits."
```

```
<Wizzup> parazyd: aaaerghl we really need maemo/ascii stuff merged to master :D
```

```
<freemangordon> Wizzup: https://github.com/maemo-leste/connui-internet/commit/
b73e5bd71578d7f5228901b7a6b8a587b9e51591
<freemangordon> I added a tag as well
<freemangordon> could you please spin a build?
<Wizzup> will do now
<Wizzup> was trying to figure out the libhildonfm bug
<Wizzup> freemangordon: you didn't update maemo/ascii
<freemangordon> ah, yeah
<freemangordon> wait, will do
<freemangordon> Wizzup: done, sorry about that
```

```
<freemangordon> the fuck? getting merge conflict when trying to merge beowulf with
master
<Wizzup> which repo?
<freemangordon> libhildondesktop
<Wizzup> what is teh conflict?
<freemangordon> https://pastebin.com/hm4uLNUM
<Wizzup> are you on latest master and latest maemo/beowulf?
<freemangordon> and https://pastebin.com/6Vf4z3ux
<freemangordon> yes
<freemangordon> I just pushed to maemo/beowulf
<freemangordon> user@devuan:~/maemo/crash/libhildondesktop$ git checkout master
<freemangordon> Your branch is up-to-date with 'origin/master'.
<freemangordon> I cloned the repo few hours ago :)
<freemangordon> maybe git behaves
<freemangordon> no, it is not git
<Wizzup> git diff master..maemo/beowulf ?
<freemangordon> ok, master seems to be broken
<freemangordon> it has some "GTK3 port" commit
<Wizzup> ah, right, didn't we remove that long ago?
<Wizzup> if that's still the case, please just nuke master with maemo/beowulf
<Wizzup> it's been a bother for too many times
<Wizzup> far too often*
<freemangordon> care to do that?
<Wizzup> sure.
<Wizzup> did you push to beowulf?
<freemangordon> yes
<Wizzup> done
<freemangordon> did you push?
<Wizzup> yes
```

```
<freemangordon> parazyd: Wizzup: could you rebuild libimlayouts?
<freemangordon> maybe I should finally get access and stop pestering you for those
rebuilds
<freemangordon> but it is so much easier to pester :p
...
<parazyd> freemangordon: Which branch?
...
<freemangordon> parazyd: all of them?
```

```
<Wizzup> e.g. I fix a bug in beowulf hildon-desktop
<Wizzup> now I need to update the old and soon to be deprecated ascii branches to
<Wizzup> too
```

```
<Wizzup> hm, master on mce is behind maemo/ascii
<Wizzup> argh
```

```
<freemangordon> parazyd: could you please build https://github.com/maemo-leste/iso-
codes-locale-resolver
<parazyd> One sec
<parazyd> freemangordon: Want it in leste or leste-devel?
<freemangordon> want it in all repos
```

```
<freemangordon> Wizzup: could you please rebuild and test master branch of
hildon-input-method-configurator
```

```
<freemangordon> I have to work on master branch,right?
<Wizzup> yes
```

```
<freemangordon> parazyd: could your rebuild hildon-input-method,
hildon-im-vkbrenderer3, hildon-input-method-plugins
<freemangordon> only master branch is up-to-date
```

```
<Wizzup> freemangordon: parazyd: I just spent 20 minutes figuring out what Halftux
ran into a while ago, and then freemangordon ran into as well. libhildondesktop
master branch is not the right branch, it'
<Wizzup> it's some half-finished gtk3 port
<Wizzup> leading to errors like hd-home-plugin-item.c:242:3: error: unknown type
name ‘GdkRGBA’; did you mean ‘GdkGC’?
<Wizzup> let's fix that please
```

**Comment by MerlijnWajer** [comment]
I am not sure if it will reduce errors, or increase errors. The last quote in your message is from master being SNAFU. Some other quotes that you pasted are not relevant to the branches, but about backporting patches and support two releases: ascii and beowulf. Another quote you paste is about using Jenkins to build, rather than about branches.

I don't find it that complicated to sync the branches to what I want them to be.

I am not strongly opposed to this change, but I find that the branches offer clarity - it's clear what the latest version in ascii is, if I want to check, I just look at the branch.

Doesn't Debian do it this way, too?

**Comment by spinal84** [comment]
One more example not from IRC I forgot to mention: https://github.com/maemo-leste/bugtracker/issues/234#issuecomment-478344662

@MerlijnWajer What I meant was that SNAFU was impossible with the approach I proposed. Some other quotes were related to a simple thought which I'll try to explain. When I ported packages to Beowulf I noticed that there was nothing preventing me from building ASCII package from the same updated sources. The only reason I didn't do it was because I didn’t want to switch my attention from development to synchronization of branches. I suspect that for the same reasoning we might see that maemo/beowulf was ahead of master and maemo/ascii branch in several repositories.

I felt that working with several branches was time consuming and stupid complication since the beginning. And I thought we were forced to work this way because of some limitations. And now I propose to get rid of this rudiment.

> Another quote you paste is about using Jenkins to build, rather than about branches.

What I meant was @freemangordon asked to propagate his changes from master branch to all others and then build. I understand why he didn't want to do this work himself. And that's why I thought it was connected to my proposal somehow.

What we can do is developing in maemo/ascii-devel branch and just propagating changes to master branch from which we can easily build all distributions we have.

Or we can leave our current approach which is roughly: we develop in maemo/ascii-devel, then we propagate changes to master, then we propagate changes to maemo/ascii and/or maemo/beowulf and only then we build the packages. With the hope that we didn't forget something and didn't screwed up in branches stuff. Of course if you forget something or you have a hotfix, you are forced to go this way from the beginning.

If you don't feel this like a stupid hard and non-sense work which can be just abandoned, fine, let's leave it as it is.

**Comment by MerlijnWajer** [comment]
Let's see what @freemangordon thinks. Like I said: no strong opposition, but I don't just see upsides to it, either.

**Comment by spinal84** [comment]
I'd like to mention explicitly, that what I propose doesn't break things we currently have.
It just gives us more freedom in how we can organise our repositories.

We have some repos supported and developed by dedicated people. I think it's fine to allow the maintainer to choose how branches should be organised in his package. For example, if you like having a lot of branches in your maintained package, no one forces you to reduce it. But if someone wants to simplify his repository organisation, we shouldn't force him not to do this as well. That's my point of view.

I doubt that if you find only the master branch in a repository, you will be guessing what is the latest version in ascii and what is the latest version in beowulf. Obviously, they are the same. Or not?

**Comment by parazyd** [comment]
Let's revisit this after we move to beowulf soon. Would like to know what @freemangordon has to say as well.

**Comment by parazyd** [comment]
Closing. We're happy with the current layout.
