### ISSUE TITLE
locale.gen needs to contain all supported locales

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#332]
Currently we only have `en_US.UTF-8` in `/etc/locale.gen`.

But if we change `/etc/osso-af-init/locale` to contain something like:

```
export LC_MESSAGES=nl_NL.UTF-8
export LANG=nl_NL.UTF-8
export LC_TIME=nl_NL.UTF-8
```

The Dutch language will not work, until it is added to `/etc/locale.gen`.

Then it works:

https://wizzup.org/leste-nl_NL-1.png
https://wizzup.org/leste-nl_NL-2.png

Also, there are even more locales here:

http://maemo.org/packages/search/?org_maemo_packages_search%5B1%5D%5Bproperty%5D=name&org_maemo_packages_search%5B1%5D%5Bconstraint%5D=LIKE&org_maemo_packages_search%5B1%5D%5Bvalue%5D=n900-locales-extras&org_maemo_packages_search%5B2%5D%5Bproperty%5D=title&org_maemo_packages_search%5B2%5D%5Bconstraint%5D=LIKE&org_maemo_packages_search%5B2%5D%5Bvalue%5D=same

**Comment by parazyd** [comment]
Is there way to automatically figure out which locales we support so I can script this easily?

**Comment by MerlijnWajer** [comment]
We have a certain set in the repos now, so let's start with these?

```
# apt-cache search hildon-common-strings-l10n
hildon-common-strings-l10n-cscz - language files for hildon-common-strings (cs_CZ)
hildon-common-strings-l10n-dadk - language files for hildon-common-strings (da_DK)
hildon-common-strings-l10n-dede - language files for hildon-common-strings (de_DE)
hildon-common-strings-l10n-engb - language files for hildon-common-strings (en_GB)
hildon-common-strings-l10n-enus - language files for hildon-common-strings (en_US)
hildon-common-strings-l10n-eses - language files for hildon-common-strings (es_ES)
hildon-common-strings-l10n-esmx - language files for hildon-common-strings (es_MX)
hildon-common-strings-l10n-fifi - language files for hildon-common-strings (fi_FI)
hildon-common-strings-l10n-frca - language files for hildon-common-strings (fr_CA)
hildon-common-strings-l10n-frfr - language files for hildon-common-strings (fr_FR)
hildon-common-strings-l10n-itit - language files for hildon-common-strings (it_IT)
hildon-common-strings-l10n-mr0 - hildon-common-strings marketing release package
hildon-common-strings-l10n-nlnl - language files for hildon-common-strings (nl_NL)
hildon-common-strings-l10n-nono - language files for hildon-common-strings (no_NO)
hildon-common-strings-l10n-plpl - language files for hildon-common-strings (pl_PL)
hildon-common-strings-l10n-ptpt - language files for hildon-common-strings (pt_PT)
hildon-common-strings-l10n-ruru - language files for hildon-common-strings (ru_RU)
hildon-common-strings-l10n-svse - language files for hildon-common-strings (sv_SE)
```

**Comment by parazyd** [comment]
This commit in image-builder should implement this https://github.com/maemo-leste/image-builder/commit/4e182dd7d721fe92611d7fba00f413dde9f57f90

Do we need any changes to /etc/osso-af-init ?

**Comment by MerlijnWajer** [comment]
Debian has a `locales` package that can be used with `dpkg-reconfigure`, wonder if we can leverage it somehow. I would like to solve this in a package, not in the image overlay, if at all possible.

**Comment by MerlijnWajer** [comment]
Or otherwise just some postinstall is fine by me too, I guess...

**Comment by parazyd** [comment]
It's usually used interactively.

We could do this in hildon-meta or hildon-base, but I'm not sure if it's at all allowed (in general standards(?)) to use apt-cache in a postinst file.

**Comment by MerlijnWajer** [comment]
Would prefer less magic - so no apt-cache in postinst. Rather have a hardcoded list somewhere in a debian package.

**Comment by MerlijnWajer** [comment]
@parazyd - can this be closed?
