### ISSUE TITLE
buster/beowulf doesn't ship with GLES v1 headers anymore

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#333]
For some reason, the mesa gles v1 headers are not available in buster/beowulf.

The actual mesa implementation libraries are still available, but the development headers are not.

I think that's insane. Mesa supports the API just fine. Shall we just roll our own mesa?

I can't build brainparty, for example. It needs GLES headers.

cc @parazyd

**Comment by parazyd** [comment]
What are the exact headers you're missing? Perhaps they've moved to a different package?

**Comment by MerlijnWajer** [comment]
No, they're gone. Debian removed them on purpose.

**Comment by MerlijnWajer** [comment]
Mesa supports it just fine, but Debian apparently decided that GLESv1 is no longer a standard that should be supported.

**Comment by parazyd** [comment]
Ok. Do you want me to rework our existing mesa package and have (the same) mesa-20 everywhere?

**Comment by MerlijnWajer** [comment]
I am not sure about the number,but perhaps we can just match beowulf/buster, but with different options? Or do you suggest we build the latest regardless?

**Comment by parazyd** [comment]
I'm suggesting to build the same mesa everywhere, in order to avoid maintaining two repositories. And yeah, this would imply using the same version that we build for lima support (which does not track beowulf/buster).

**Comment by spinal84** [comment]
For armhf we have mesa-gles1-dev provided by ti-omap3-sgx-dev which should allow to build the packages for mobile platforms. amd64 packages should be built using plain OpenGL (without ES), like it's done in hildon-desktop / libmatchbox2 / clutter-1.2.
imho.

**Comment by MerlijnWajer** [comment]
Brainparty uses GLES 1.x. Why would we spend the time porting that to OpenGL (1.4, 2.1, 3.3!?), when all amd64 desktop drivers support GLES?

All we need to do is undo the debian f'up and provide the one package they don't want to provide to developers because they don't want people to use OpenGLES 1.x.

All I want to do is build brainparty with the API that is universally supported on all our platforms and devices, and Debian Buster removed the package I need for that, so let's please just do that. I don't want to port brainparty to any other OpenGL or OpenGLES API. If I had time to spare, I'd make it work on other non-N900 resolutions as a starter.

**Comment by MerlijnWajer** [comment]
Sorry I am come off annoyed, I'm really just annoyed at Debian removing this package. @parazyd - if you want to use the very latest mesa everywhere because it makes your life easier, I guess I can live with it. Might be "more stable" to use just Debian version and undo their removal of the dev package, since we'd then otherwise match Debian, also binary compat wise.

**Comment by parazyd** [comment]
@MerlijnWajer I'll build mesa-20 for Beowulf then, and if we start experiencing any issues, then we can downgrade to whatever version matches Beowulf upstream.

**Comment by spinal84** [comment]
We already have issues almost everywhere.
I suggest to avoid inventing new ways for possible issues from the beginning.
Fixing issues afterwards is more difficult than eliminating them in advance.

**Comment by MerlijnWajer** [comment]
I don't understand what you're trying to say.

**Comment by spinal84** [comment]
It was a reply to "... if we start experiencing any issues, then we can downgrade ..."

**Comment by dderby** [comment]
FWIW, the headers have returned in bullseye under the package `libgles-dev`:

https://packages.debian.org/bullseye/armhf/libgles-dev/filelist

**Comment by MerlijnWajer** [comment]
What are they even doing. :D

**Comment by MerlijnWajer** [comment]
> It was a reply to "if we start experiencing any issues, then we can downgrade"

Mhm - I thought about this again, and libGL* has ABI compat, so it shouldn't matter much what mesa we pick. All VMs use sw accel anyway, so we should be good, if the new mesa doesn't have some crazy libLLVM dependencies, either version is fine.

**Comment by MerlijnWajer** [comment]
We have new (our own) mesa now, so this should be fixed at this point.
