### ISSUE TITLE
Image builds with no kernel

### ISSUE THREAD

**Issue by javiplx** [maemo-leste/bugtracker#337]
I'm following procedure from https://leste.maemo.org/Image_Builder for pinephone, and the produced image is not bootable. Comparing with the published image, It is missing kernel and other files (in particular config-5.4.0 Image.gz-5.4.0 sun50i-a64-pinephone.dtb System.map-5.4.0 and symlinks).
Is there any manual step required for pinephone?

**Comment by MerlijnWajer** [comment]
@parazyd -- any idea if you forgot to push something that would cause it not to work for @javiplx 
?

**Comment by javiplx** [comment]
The changes I've needed to build a working image are those from parazyd/arm-sdk#6 and maemo-leste/image-builder#6, as well as the patch below for https://git.devuan.org/sdk/libdevuansdk, which cannot fork.
These changes make use of 5.5.x kernel from https://gitlab.com/pine64-org/linux/, and produced an image that boots the phone.

```
From 3a68f840688c9c20fc91930c15f30ec6d3731823 Mon Sep 17 00:00:00 2001
From: Javier Palacios <javiplx@gmail.com>
Date: Fri, 20 Mar 2020 18:54:01 +0100
Subject: [PATCH] BUGFIX: missing key for leste repositories

---
 zlibs/bootstrap | 1 +
 1 file changed, 1 insertion(+)

diff --git a/zlibs/bootstrap b/zlibs/bootstrap
index 419b655..a673637 100644
--- a/zlibs/bootstrap
+++ b/zlibs/bootstrap
@@ -118,6 +118,7 @@ bootstrap_config_thirdstage() {
 
 	cat << EOF
 #!/bin/sh
+wget -O - http://maedevu.maemo.org/testing-key.asc | apt-key add -
 apt-get update
 debconf-set-selections /debconf.set
 
-- 
2.20.1
```

**Comment by parazyd** [comment]
This was fixed in arm-sdk, fwiw.
In Maemo Leste, we provide an actual kernel deb package.
