### ISSUE TITLE
Idling the touchscreen on the droid4

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#340]
Looks like we need to figure out how to properly idle the touchscreen.

X and MCE usually have touchscreen open at all times. X for input, mce for mode management/datapipes.

On the N900, we (<s>used to</s>) have a patch that adds a `/disabled` property to sysfs, that will effectively disable the touchscreen entirely. But this code was removed from mainline.

We can either add such a patch to the droid4 touchscreen driver and have MCE write to the `/disabled` attribute, or have mce *remove* the relevant touchscreen modules, and probe them again when the device is activated.

cc @tmlind

**Comment by pavelmachek** [comment]
Removing and reinserting kernel modules is a bad idea. Closing the device from MCE should be enough (and would be prerequisite for removing the modules).

**Comment by freemangordon** [comment]
Right, and we already rejected it, see https://github.com/maemo-leste/mce/commit/de7cd3d067a7c23e9f7e1abc9b2bb1453211eefb

**Comment by MerlijnWajer** [comment]
While this is not the final/correct implementation, this will ensure that neither X nor mce hold the touchscreen open:

https://github.com/maemo-leste/mce/pull/7/files

**Comment by MerlijnWajer** [comment]
I've merged this code. It relies on latest kernel from Tony (packaged), and latest mce (currently packaged in `maemo/beowulf-devel`.
