### ISSUE TITLE
Problem to Connect With Hidden AP

### ISSUE THREAD

**Issue by xsetiadi** [maemo-leste/bugtracker#341]
still cannot connect to hidden wifi,

using select connection menu (when clicking battery applet) its scan the hidden wifi, but when I'm  going to connect, it's only asking the password, usually its asking ssid first then password to connect

and input manual via setting > connections not work too
usually config in settings marked with checklist beside the ssid name, but the hidden config not even show up on the scan network

**Comment by sicelo** [comment]
superseded by #489
