### ISSUE TITLE
/etc/X11/Xsession.d/04devlock-blocker prevents n900 images booting to GUI

### ISSUE THREAD

**Issue by u0d7i** [maemo-leste/bugtracker#343]
All Maemo Leste n900 images affected, tested with 3 different n900 devices.
2 of the 3 devices have lock code set, 1 has not lock code set.
Default image starts booting but ends up in blank screen.
After commenting out line in /etc/X11/Xsession.d/04devlock-blocker , all devices boots to GUI succesfully.

**Comment by MerlijnWajer** [comment]
@freemangordon - do you know what would need to implemented to enter the lock code? Or should we just not call devlock-blocker for now?

**Comment by freemangordon** [comment]
hmm, this is supposed to work, no idea why it doesn't. iiuc  devlock-blocker shall display dialog to enter the code.

**Comment by MerlijnWajer** [comment]
I looked at the code, and I think devlock-blocker is just waiting for something else to unlock the device. So some UI is missing, and devlock-blocker will just wait for the UI interaction.

So we likely need another piece.

**Comment by MerlijnWajer** [comment]
It looks like we don't have package `osso-systemui-devlock` which contains `/usr/lib/systemui/libsystemuiplugin_devlock.so` to unlock the device.

Once we have that, we also have to make sure we start systemui before `04devlock-blocker`, like Fremantle does in `03osso-systemui`

**Comment by MerlijnWajer** [comment]
@freemangordon @parazyd  - I wonder if, until we get `osso-systemui-devlock` in place, we should remove `04devlock-blocker` from the xsession.

**Comment by parazyd** [comment]
> @freemangordon @parazyd - I wonder if, until we get `osso-systemui-devlock` in place, we should remove `04devlock-blocker` from the xsession.

Yes, I think this is fine to do temporarily.

**Comment by MerlijnWajer** [comment]
In beowulf-devel this bug is now fixed; I managed to enter the code `12345` the default lock code. Currently in maemo/beowulf-devel.

**Comment by parazyd** [comment]
Promoted the package to main today, so an update should pick it up.

**Comment by parazyd** [comment]
Is this solved?

**Comment by freemangordon** [comment]
you mean for stable?

**Comment by parazyd** [comment]
Yeah. I built the latest package for main two weeks ago.

**Comment by freemangordon** [comment]
The problem should be fixed so I will close the issue, if there is a need we'll simply reopen.
