### ISSUE TITLE
Droid4: Support special keys virtual keyboard

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#347]

**Comment by MerlijnWajer** [comment]
So maybe we map KEY_OK to KEY_RIGHTALT ?

**Comment by MerlijnWajer** [comment]
I have changed `KEY_OK` to `KEY_RIGHTALT`, but that doesn't get me there yet.

Looking at this piece now, in N900 keymap (`/usr/share/X11/xkb/symbols/nokia_vndr/rx-51`):

```
 // Fn+Ctrl virtual symbol table (Multi_key)
 // Ctrl+Space switches between 1st and 5th level (hardcoded in hildon)
 key <LCTL>  {
     type[Group1] = "FOUR_LEVEL",
     symbols[Group1] = [     Control_L,      Control_L,      Multi_key,      Multi_key       ]
 };
 modifier_map Control { Control_L };

 // Fn key (right alt) switches to 3rd level
 include "level3(ralt_switch)"
```

Will resume later today.

**Comment by MerlijnWajer** [comment]
With DTS change as documented above, and the following commands, I do get symbol virtual keyboard:

```
# xmodmap -pm
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x42)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Alt_R (0x6c),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)

# xmodmap -e 'clear mod1'

# xmodmap -e 'add mod1 = Alt_L' # restore Alt_L

xmodmap -e 'keysym Alt_R = Multi_key' # Map Alt_R to Multi_key
```

Now press "Shift" (on keyboard, mapped to Ctrl_L), and then "OK" (on keyboard right alt).

Then it shows up.

**Comment by sicelo** [comment]
The same can be achieved without dts change, by first doing:

1. Create `/etc/udev.d/hwdb.d/50-keyboard-modifiers.hwdb` with the following
```
evdev:input:b0019v0001p0001e0001-*
 KEYBOARD_KEY_3b=rightalt
```
2. Update hwdb
```
# udevadm hwdb --update
# udevadm trigger
```
At this point, the xmodmap lines in the above comment will pop the special keys

**Comment by sicelo** [comment]
The rendering for the scv will also need some updating to fit wider devices such as droid4

**Comment by MerlijnWajer** [comment]
I wonder if ultimately what we want might be what also happens on the N900, where you first have to click the "arrow" key (RIGHTALT), and then the sym/ctrl

**Comment by MerlijnWajer** [comment]
```
13:11 < Wizzup> sicelo: so this is a nicer solution I think:
13:11 < Wizzup> # xmodmap -e "keycode 64 = Alt_L Meta_L Alt_R Meta_L"
13:11 < Wizzup> # xmodmap -e 'keysym Alt_R = Multi_key' # Map Alt_R to Multi_key
13:11 < Wizzup> this will shift + sym result in alt_r, and alt_r is mapped to be the multi key
```

**Comment by MerlijnWajer** [comment]
_OK_.

First, there's a typo in @sicelo 's post earlier. The path needs to be `/etc/udev/hwdb.d/50-keyboard-modifiers.hwdb` - not `/etc/udev.d/hwdb.d/50-keyboard-modifiers.hwdb`.

I've used his trick to set KEY_OK to KEY_RIGHTALT.

Next, I did this:

`xmodmap -e "keycode 108 = ISO_Level3_Shift NoSymbol ISO_Level3_Shift"`

To make keycode 108 (right alt) become the "ISO_Level3_Shift" - like on the N900.

Finally, I added a "droid4" symbol group (as a test), that looks like this (I stuffed this in `/usr/share/X11/xkb/symbols/group`):

```
partial modifier_keys
xkb_symbols "droid4" {
    // Shift switches between current level and level+1
    key <LFSH>  {
        type[Group1] = "ONE_LEVEL",
        symbols[Group1] = [     Shift_L ]
    };
    modifier_map Shift { Shift_L };

    // Fn+Ctrl virtual symbol table (Multi_key)
    // Ctrl+Space switches between 1st and 5th level (hardcoded in hildon)
    key <LCTL>  {
        type[Group1] = "FOUR_LEVEL",
        symbols[Group1] = [     Control_L,      Multi_key,      Multi_key,      Multi_key       ]
    };
    modifier_map Control { Control_L };

    // Fn key (right alt) switches to 3rd level
    include "level3(ralt_switch)"
};
```

Also change:

`/usr/share/X11/xkb//rules/base`
`/usr/share/X11/xkb//rules/evdev`

to contain the droid4 line, around here:

```
! option        =       symbols
  grp:droid4            =       +group(droid4)
```

Activate using:

```
setxkbmap -model pc105 -layout us -variant intl -option grp:droid4
```

Result:

"OK" key on Droid 4 now functions like the blue arrow:

1. Pressing OK key twice results in "Fn in locked" message.
2. Pressing OK key and then "shift" (mapped to left control key) results in special keys dialog. And it is sticky too!

Next steps:

1. Create a proper xkb file for the droid4 for this hack, as opposed to resorting to the group hack.

**Comment by MerlijnWajer** [comment]
This should mostly do it:

```
# cat /etc/X11/xorg.conf.d/40-input.conf
Section "InputClass"
    Identifier "Motorola Droid 4 Keyboard"
    Driver "evdev"
    MatchDevicePath "/dev/input/event2"
    #MatchTag "4a31c000.keypad"

    Option "XkbModel" "pc105"
    Option "XkbLayout" "droid4"
    Option "XKbOptions" "grp:droid4"
EndSection
root@devuan-droid4:/usr/share/X11/xkb# diff -u symbols/us symbols/leste/droid4
--- symbols/us	2019-02-11 20:25:45.000000000 +0100
+++ symbols/leste/droid4	2020-06-06 15:40:09.618164946 +0200
@@ -30,7 +30,7 @@
     key <AD11> {	[ bracketleft,	braceleft	]	};
     key <AD12> {	[ bracketright,braceright	]	};

-    key <AC01> {	[	  a,	A 	        ]	};
+    key <AC01> {	[	  a,	A, asterisk, asterisk 	        ]	};
     key <AC02> {	[	  s,	S	        ]	};
     key <AC03> {	[	  d,	D	        ]	};
     key <AC04> {	[	  f,	F	        ]	};
@@ -49,11 +49,34 @@
     key <AB05> {	[	  b,	B	        ]	};
     key <AB06> {	[	  n,	N	        ]	};
     key <AB07> {	[	  m,	M	        ]	};
-    key <AB08> {	[     comma,	less	        ]	};
-    key <AB09> {	[    period,	greater	]	};
+    key <AB08> {	[     comma,	less, semicolon, semicolon	        ]	};
+    key <AB09> {	[    period,	greater, colon, colon	        ]	};
     key <AB10> {	[     slash,	question	]	};

     key <BKSL> {	[ backslash,         bar	]	};
+
+    include "leste/droid4(modifiers)"
+};
+
+partial modifier_keys
+xkb_symbols "modifiers" {
+    // Shift switches between current level and level+1
+    key <LFSH>{
+	type[Group1] = "ONE_LEVEL",
+	symbols[Group1] = [	Shift_L]
+    };
+    modifier_map Shift { Shift_L };
+
+    // Fn+Ctrl virtual symbol table (Multi_key)
+    // Ctrl+Space switches between 1st and 5th level (hardcoded in hildon)
+    key <LCTL>{
+	type[Group1] = "FOUR_LEVEL",
+	symbols[Group1] = [	Control_L,	Multi_key,	Multi_key,	Multi_key	]
+    };
+    modifier_map Control { Control_L };
+
+    // Fn key (right alt) switches to 3rd level
+    include "level3(ralt_switch)"
 };

 partial alphanumeric_keys
```

**Comment by MerlijnWajer** [comment]
I think what remains now:

1. Package this work
2. Create geometry file (load with `-geometry 'motorola(xt894)' with setxkbmap)
3. Assign useful third level keys
4. Check if we can tell what geometry to use in the dts (something in the n900 seems to know what the keyboard layout is, maybe it's just some debian config param, @parazyd probably knows)

**Comment by MerlijnWajer** [comment]
5. Fix special keys rendering to extend to non-n900 sized screens

**Comment by MerlijnWajer** [comment]
![image](https://user-images.githubusercontent.com/517897/83955822-7b270f80-a857-11ea-996e-83c09ead07d4.png)

![image](https://user-images.githubusercontent.com/517897/83955823-89752b80-a857-11ea-9913-1b3de66e9311.png)

**Comment by buzztiaan** [comment]
Could we get OK + ['] as Escape key aswell, please? 
I think with that one key added, we have practically everything needed on the droid4 keyboard

**Comment by MerlijnWajer** [comment]
5 = done

https://github.com/maemo-leste/hildon-input-method-plugins/pull/3

**Comment by MerlijnWajer** [comment]
-devel should now have xkb-data with our keymaps.

**Comment by MerlijnWajer** [comment]
If you're on devel, all you'll need is `apt install leste-config-droid4`. This will be pushed to non-devel soon, too.

**Comment by clort81** [comment]
Oh THANK YOU!

I can .Xmodmap to my preferences now.

**Comment by MerlijnWajer** [comment]
No, the photo just shows shift there.

**Comment by buzztiaan** [comment]
@clort81 did you even see https://leste.maemo.org/Motorola_Droid_4 , under Status?

**Comment by buzztiaan** [comment]
either way, geometry files are not keyboard layouts

**Comment by clort81** [comment]
> ```
> # udevadm hwdb --update
> # udevadm trigger
> ```

I had to run these commands to get 'ok' activated on a new sdcard installed from
maemo-leste-1.0-armhf-droid4-20200906.img.xz

The /usr/share/X11/xkb/geometry/motorola

and

/etc/udev/hwdb.d/50-keyboard-modifiers.hwdb.leste

installed from the img.gz were identical to the older working ones

**Comment by clort81** [comment]
I added functionkeys F1-F10 (OK + 1-0) and page-up/page-down (OK + a, z) to  
/usr/share/X11/xkb/symbols/motorola_vndr/droid4

Function keys tested and working for selecting stuff in alsamixer and other terminal apps (uxterm, osso-xterm).  Page-up / page-down in terminal requires shift-pgup/down which is currently too hard to combine. Could use a better solution.

Unfortunately these mappings, and our important 'Esc' key map don't work in SDL-based programs, but that's another issue.

[droid4.gz](https://github.com/maemo-leste/bugtracker/files/5714791/droid4.gz)

**Comment by MerlijnWajer** [comment]
Please submit a pull request our xkb-data repo.

**Comment by clort81** [comment]
I am not able to do that.  The 'create new pull request' button does nothing.

**Comment by MerlijnWajer** [comment]
When you find the time, start here: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

Then we'll see if we can include the keys.

**Comment by clort81** [comment]
Thanks for including.
