### ISSUE TITLE
Droid4: USB networking flakey/unusable in 20200323 version

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#348]
USB networking disconnects/reconnects so often that it is practically unusable. Sometimes I can configure the networking and connect using ssh, but interface disappears/reappears before I can do anything useful. I suspected bad cable, but I asked on IRC and it looks like I'm not the only one.

It seems that -next kernels have the same problem. I'm pretty sure USB networking was very solid on some older kernels.

**Comment by MerlijnWajer** [comment]
If you could bisect that, that would be useful. I noticed (I think) that sometimes I have to plug in usb, then serial, and then usb for it become more reliable.

**Comment by clort81** [comment]
I have noticed that my usb networking is usable after disabling usb-powersaving on the host side.
```
echo 2 | sudo tee /sys/bus/usb/devices/*/power/autosuspend >/dev/null
echo on | sudo tee /sys/bus/usb/devices/*/power/level >/dev/null
```

**Comment by antonizoon** [comment]
I can confirm that on the latest june build, I am able to use both an unpowered USB host and powered USB Y-cable to use mouse and keyboard peripherals without any modifications, and without any issues on the Droid 4. (didn't yet test usb networking)

Hopefully someone else can confirm too.

**Comment by clort81** [comment]
Hi,

news for pcsx-rearmed-mld4 (PCSX-ReARMed, Maemo Leste Droid4)

It's pretty happy now. Runs well for me. Sadly the latest builds don't seem to work with HLE for some reason. So you need PCSX Bios SCPH1001.BIN or maybe SCPH5000.BIN for euro/pal.

I have made progress with debianization; i can get an installable .deb now. I haven't figured out how to get start menu icon, or install configs properly to /home/user/.pcsx.

* Created icons for various sizes in ./data and ./hicolor. - made a desktop file in ./data, but I don't get a menu entry. I don't understand why.

* Made almost working ./debian (creates a .deb) but apparently you can't use debian rules to make a proper ~/.pcsx ... There might be a way to use /etc/skel to copy-in configuration files to the user's home. For now you can cp -r ./.pcsx to your home dir.

* Created a github repository with changed files but the submodule libpicofe isn't integrated. You need to tar xzf libpicofe.tgz to create the files.

* After untarring libpicofe.tgz, you should be able to compile a working pcsx binary with ./configure && make
https://github.com/clort81/pcsx_rearmed_mld4

If anyone knows how to get the debianianization and hildon-menu stuff straightened out, that would be needed before integrating into maemo-leste. I'll keep plugging away at it though.

**Comment by MerlijnWajer** [comment]
I think this message should go somewhere else?

> Hi, news for pcsx-rearmed-mld4 (PCSX-ReARMed, Maemo Leste Droid4) It's pretty happy now. Runs well for me. Sadly the latest builds don't seem to work with HLE for some reason. So you need PCSX Bios SCPH1001.BIN or maybe SCPH5000.BIN for euro/pal. I have made progress with debianization; i can get an installable .deb now. I haven't figured out how to get start menu icon, or install configs properly to /home/user/.pcsx. * Created icons for various sizes in ./data and ./hicolor. - made a desktop file in ./data, but I don't get a menu entry. I don't understand why. * Made almost working ./debian (creates a .deb) but apparently you can't use debian rules to make a proper ~/.pcsx ... There might be a way to use /etc/skel to copy-in configuration files to the user's home. For now you can cp -r ./.pcsx to your home dir. * Created a github repository with changed files but the submodule libpicofe isn't integrated. You need to tar xzf libpicofe.tgz to create the files. * After untarring libpicofe.tgz, you should be able to compile a working pcsx binary with ./configure && make https://github.com/clort81/pcsx_rearmed_mld4 If anyone knows how to get the debianianization and hildon-menu stuff straightened out, that would be needed before integrating into maemo-leste. I'll keep plugging away at it though.

**Comment by clort81** [comment]
> I think this message should go somewhere else?

I thought editing the Re: line would send it to the list without associating it with the USB bug. Sorry!

**Comment by parazyd** [comment]
@MerlijnWajer @pavelmachek Is this still an issue?

**Comment by IMbackK** [comment]
yes usb on the mapphones is currently buggy

**Comment by pavelmachek** [comment]
I'm getting this:

[155068.957035] usb 1-1: Manufacturer: Foo Inc.
[155068.957040] usb 1-1: SerialNumber: 0123456789
[155068.966189] cdc_ether 1-1:1.0 usb0: register 'cdc_ether' at
usb-0000:00:1d.7-1, CDC Ethernet Device, ce:d5:ee:3e:0f:ef
[155069.968378] usb 1-1: USB disconnect, device number 70
[155069.968822] cdc_ether 1-1:1.0 usb0: unregister 'cdc_ether'
usb-0000:00:1d.7-1, CDC Ethernet Device
[155070.224102] usb 1-1: new high-speed USB device number 71 using
ehci-pci
[155070.368335] usb 1-1: New USB device found, idVendor=1d6b,
idProduct=0104
[155070.368344] usb 1-1: New USB device strings: Mfr=1, Product=2,
SerialNumber=3
[155070.368350] usb 1-1: Product: Bar Gadget
[155070.368354] usb 1-1: Manufacturer: Foo Inc.
[155070.368359] usb 1-1: SerialNumber: 0123456789
[155070.374253] cdc_ether 1-1:1.0 usb0: register 'cdc_ether' at
usb-0000:00:1d.7-1, CDC Ethernet Device, ce:d5:ee:3e:0f:ef
[155071.416929] usb 1-1: USB disconnect, device number 71
[155071.417407] cdc_ether 1-1:1.0 usb0: unregister 'cdc_ether'
usb-0000:00:1d.7-1, CDC Ethernet Device
[155072.268108] usb 1-1: new high-speed USB device number 72 using
ehci-pci
[155072.408347] usb 1-1: New USB device found, idVendor=1d6b,
idProduct=0104
[155072.408355] usb 1-1: New USB device strings: Mfr=1, Product=2,
SerialNumber=3
[155072.408360] usb 1-1: Product: Bar Gadget
[155072.408365] usb 1-1: Manufacturer: Foo Inc.
[155072.408370] usb 1-1: SerialNumber: 0123456789
[155072.420450] cdc_ether 1-1:1.0 usb0: register 'cdc_ether' at
usb-0000:00:1d.7-1, CDC Ethernet Device, ce:d5:ee:3e:0f:ef
[155075.963567] usb 1-1: USB disconnect, device number 72
[155075.964242] cdc_ether 1-1:1.0 usb0: unregister 'cdc_ether'
usb-0000:00:1d.7-1, CDC Ethernet Device

Repeated cycles may have something to do with battery being full and
charger going on and off...

Sometimes I'm able to ifconfig it up, but ping did not work.

-- 
http://www.livejournal.com/~pavelmachek
