### ISSUE TITLE
N900: Look at libinput at some point for TS

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#35]
We are currently using/forcing evdev since calibration works so much better with it

**Comment by ollieparanoid** [comment]
We use `libinput` with [this udev rule](https://github.com/postmarketOS/pmbootstrap/blob/e203c42d5b574f4fc487cda7ebfdeab90d3951a7/aports/device/device-nokia-n900/udev/90-touchscreen-dev.rules) for the N900. Calibration was done with `weston-calibrator` (in Weston).

**Comment by IMbackK** [comment]
i looked at it and we now use libinput for all devices except n900. it works fine on n900 but there is no calibration ui for x11 which is needed on the n900's drifty ts.
