### ISSUE TITLE
Pinephone: 20200323 image written to eMMC failing to boot, stuck on "random: crng init done"

### ISSUE THREAD

**Issue by stoehraj** [maemo-leste/bugtracker#350]
I used `dd` to write the image from [here](https://maedevu.maemo.org/images/pinephone/20200323/) onto the eMMC on my Pinephone, and when I try to boot from it it gets stuck at "random: crng init done."  I let it sit there for about 15 minutes before I reset it.  I tried a few more times and it hit the same issue every time.

**Comment by MerlijnWajer** [comment]
Hi!

I think most of us have tested it on the microsd card instead. I would not be surprised if all you have to do is edit the `/etc/fstab` file on the eMMC to have the right device as `/` (root) mount.

**Comment by stoehraj** [comment]
Hey there!

That's a good thought -- I went in and looked at `/etc/fstab` and it was looking at the wrong device (`/dev/mmcblk0p1` rather than `/dev/mmcblk2p1` for `/boot`) so I updated that.

The contents of `/etc/fstab` are now as follows:
```
# fstab for arm system
none /sys/kernel/debug debugfs defaults 0 0
/dev/mmcblk2p1 /boot ext2 defaults 0 1
```
Unfortunately I'm still seeing the same issue.

**Comment by MerlijnWajer** [comment]
@stoehraj -- right. You probably need to change the kernel command line too. That will be on the first partition `p1`. I am not sure if it is in a `boot.scr` or `boot.txt` file. If it is in `boot.scr` file, you will need to create a `boot.txt` file and use `mkimage` to generate a `boot.scr`

cc @parazyd

**Comment by stoehraj** [comment]
That did the trick -- I was able to boot.  Thanks for the help.

**Comment by MerlijnWajer** [comment]
@stoehraj - I'd be delighted if you can document some of this on our wiki https://leste.maemo.org/PinePhone

I've recently been focussing on generic userspace and some kernel parts of the Droid 4, but I hope we can get Pinephone in better shape, too.

We can also offer two images, one for eMMC and one for the sdcard.

And -- please let us know how it goes, what you find missing, etc. It's pretty alpha, but a lot of will get more smooth quickly.

Reopening because I would like @parazyd 's opinion on having two images.

**Comment by stoehraj** [comment]
@MerlijnWajer -- I'd be happy to add some information to the wiki.  I will when I have a chance to.

I personally think offering two images would be a good solution for now, but I haven't been involved in the project until this point so I'm not sure how well that fits with your standards/practices.

I will let you know, though it's been a smooth experience overall initially.  Are the [forums](https://talk.maemo.org/forumdisplay.php?f=66) the right place for feedback?

**Comment by MerlijnWajer** [comment]
Either the forums, or our mailing list, or IRC. :)

**Comment by stoehraj** [comment]
Great!  I added some info to the wiki.

**Comment by parazyd** [comment]
I don't see the solution for two different images, because I don't know how to dd directly to the eMMC. However, we could provide some `install_to_emmc.sh` that takes care of this and copies the running OS from uSD to the eMMC and tweaks what's necessary.

**Comment by parazyd** [comment]
Closing, and continuing in #550
