### ISSUE TITLE
Droid 4: USB OTG Works only with a Powered Y-cable, and crashes when unplugged

### ISSUE THREAD

**Issue by lvw5264** [maemo-leste/bugtracker#355]
In the latest build of Maemo Leste, USB OTG now works on Droid 4 which is a major improvement, but only with a powered USB OTG Y-cable. 

It is buggy and devices don't work properly when used with an unpowered USB OTG cable:  the Droid 4 eventually crashes when a USB device is plugged in.

Another thing is that with the powered USB OTG Y-cable, usb devices work quite fine such as a Yubikey or a USB mouse or anything really: right up until the USB device is unplugged from the Y-cable, where the Droid 4 immediately crashes and turns off the display. 

I then have to hard shutdown by holding the power button and volume down button for 20 seconds and then reboot, where the USB OTG Y-cable and device can be plugged in again, but the Droid 4 crashes and turns off the display again when the USB device is unplugged from the Y-cable again.

Give these a shot and its likely to be reproducible.

**Comment by MerlijnWajer** [comment]
I have seen mce crash on input device removal, but that should have been fixed. I assume your image is fully up to date?

**Comment by lvw5264** [comment]
Yes, I've been using the latest 20200323 and had updated it with apt upgrade 4 days ago.

**Comment by clort81** [comment]
> In the latest build of Maemo Leste, USB OTG now works on Droid 4 which is a major improvement, but only with a powered USB OTG Y-cable.

Can you suggest a particular usb cable or hub that would work with otg function?  This one maybe?
![otg](https://user-images.githubusercontent.com/51511737/80374678-53777b80-8897-11ea-9bb2-1fb57efc08cb.png)

**Comment by IMbackK** [comment]
works fine now
