### ISSUE TITLE
Rendering Performance Issues Thread

### ISSUE THREAD

**Issue by clort81** [maemo-leste/bugtracker#357]
I'm opening this to provide a space to share results from experiments with rendering performance of Leste + Xorg + Hildon-Desktop - currently on the Motorola Droid 4.

![hase-leste-performance](https://user-images.githubusercontent.com/51511737/78794290-d487d500-79b3-11ea-9c42-169e07ab4a23.jpg)

**Comment by MerlijnWajer** [comment]
What if you actually run the application in fullscreen mode (might need the libsdl patches that are still blocking on mesa/pvr dependency mess), and disable compositing?

**Comment by clort81** [comment]
SDL is (attempting to) disable compositing.   Fullscreen flag is set in sdl but it's not creating fullscreen window in openbox or hildon-desktop

sdl-config --version
1.2.15

If there's a particular libsdl that i should be using please tell me.

I see libsdl-haa1.2-1 and libsdl-gles1.2-1 with apt search 

I can apt download libsdl-gles1.2-1
I cannot apt download libsdl-haa1.2-1
E: Can't find a source to download version '1.1.0' of 'libsdl-haa1.2-1:armhf'

Here are today's results for drnoksnes with varying windowmanager, bpp and scaler backend.

![leste-dns-performance](https://user-images.githubusercontent.com/51511737/78811508-4539ec00-79ca-11ea-98ee-1d66ec56e3f4.png)

**Comment by clort81** [comment]
Today's results for es2gears on droid 4 with powervr drivers. No SDL involved.

![leste-es2gearsperformance](https://user-images.githubusercontent.com/51511737/78815529-b11f5300-79d0-11ea-889f-b87b64126996.jpg)

(The brief jump to 400fps happened when screen went blank for powersaving)

**Comment by clort81** [comment]
Another comparison - Hurrican using SDL/Opengl -> gl4es
![maemo-leste-hurrican-render](https://user-images.githubusercontent.com/51511737/80560079-f3402100-89df-11ea-8384-868d50dc28ef.png)

**Comment by clort81** [comment]
I found time to get picodrive built with opengl-es backend, but hildon doubles the Xorg cpu use.
![picodrive1](https://user-images.githubusercontent.com/51511737/86855299-5920e700-c0ba-11ea-9a82-3f809ed31853.png)

**Comment by clort81** [comment]
I'll just request restoring 16bpp mode support in leste xorg here.  
I can't get it working now.  I don't know what happened.

unless I am confused, this 99-omap.conf should work 
```
# X.Org X server configuration file

Section "Device"
        Identifier      "Video Device"
        Driver          "omap"
        Option          "Debug"         "false"
EndSection

Section "Screen"
        Identifier      "Screen"
        Monitor         "Monitor"
        DefaultDepth    "16"
        Device          "Video Device"
```
Thanks

**Comment by MerlijnWajer** [comment]
We cannot move to 16bpp mode until driver bugs regarding status applet rendering are resolved. Last time we checked, we found it to be a driver bug with no known workarounds.

**Comment by MerlijnWajer** [comment]
Feel free to change the value for your device locally to "16".

**Comment by IMbackK** [comment]
this issue is obsoleted by the ddk1.16
