### ISSUE TITLE
Import status-area-applet-battery

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#36]
https://github.com/community-ssu/status-area-applet-battery

**Comment by MerlijnWajer** [comment]
Will need porting to upower first it seems.

**Comment by MerlijnWajer** [comment]
Should this just mostly be similar to mce code for upower?

**Comment by MerlijnWajer** [comment]
I took out the hal code, replaced it with stubs, and now it at least runs: https://wizzup.org/n900-initial-battery.png

Next up is adding the upower code -- but for some reason all the upower device (all four of them...) seem to be report a percentage of 0 -- at least on the n900.

**Comment by MerlijnWajer** [comment]
Pushed the stub entry code here, should be buildable: https://github.com/maemo-leste/status-area-applet-battery/tree/hald-removal

Will look at adding gconf again; and adding a upower backend.

**Comment by MerlijnWajer** [comment]
There's a functional prototype in this branch: https://github.com/maemo-leste/status-area-applet-battery/commits/upower

I slashed a lot of code away, so some of it will be needed to be added again. Important one is the rx-51_battery reading (I guess?)

upower seems to lag behind a lot with some values, and outright doesn't show others. `time_to_` values are available in `/sys` and work; but upower shows  them as `0`.

Same is true for the 'State' of the battery. I have yet to see it move to 'Discharging'. It stays at 'PENDING_CHARGE'.

Anyway - those are issues to resolve in upower, not in our applet.

**Comment by MerlijnWajer** [comment]
Pushed some more code, charging animation works again, and as do the notifications.

I'm sure there's a lot of fix still, but it seems to work. Adding mAh remaining is next. Why is that not in Wh?

**Comment by sicelo** [comment]
> Why is that not in Wh?
If you mean 'why the applet uses mAh,' isn't that because that's how such batteries are typically specified?

**Comment by freemangordon** [comment]
Usually the charge is in A/h (or mA/h), not W/h (not to say this is energy, not charge). Could be because of historical reasons (automotive), but still.

**Comment by MerlijnWajer** [comment]
I've pushed initial working code to master. Perhaps we can package it.

@parazyd  ?

**Comment by MerlijnWajer** [comment]
As a note, there are at least a few things to look at later:
* mAh calculation (currently based on Wh + current voltage; so that's bad) - let's see if we can get what /sys gives us
* upower is slow and inaccurate, let's figure out why (values in /sys respond fast and accurately)
* charging/discharging detection is slow/bad, against because of upower.
* TimeToEmpty and TimeToFull are often 0 or non sensical, but they are fine in /sys (again: wtf)
* idle_time and active_time need to be implemented properly (in applet)

Once UPower is better, it's easier to fix/detect issues that I might have introduced when porting code.
