### ISSUE TITLE
Dillo browser for Leste

### ISSUE THREAD

**Issue by clort81** [maemo-leste/bugtracker#367]
Dillo Web Browser, is my go-to browser for search engines and text-centric pages without javascript. 

The load times are the fastest I've seen, and with custom CSS, we can set colors and other options to suit preference.
 
Below is an animated png UI mockup that sums up my design ideas.  
Allow a few seconds for each frame of the animation.

![ndillolayoutani](https://user-images.githubusercontent.com/51511737/80104179-bb1b8700-8576-11ea-8cbc-40d14168c312.png)

**Comment by clort81** [comment]
More discussion about UI lead to revision 11:  zoom buttons are now on thumb, right side, and 'go back' is any click on the left edge of the displayed page (circa 32 pix wide).
![newdillolayout11](https://user-images.githubusercontent.com/51511737/80291984-abf13080-8752-11ea-947c-3b2539068a62.png)

**Comment by IMbackK** [comment]
not relevant/close
