### ISSUE TITLE
hildon-desktop - needs a restart to pickup new desktop widgets

### ISSUE THREAD

**Issue by sicelo** [maemo-leste/bugtracker#368]
After installing `personal-ip-address` widget from the repos, I expected it to immediately be available for selection via the hildon-desktop configuration menu (on the cog wheel). This did not happen until I rebooted the device (I suppose restarting h-d would have worked).

Perhaps this is something that should be done in the postinst of the widget, or it's a bug in h-d

**Comment by sicelo** [comment]
This might give clues - https://bugs.maemo.org/show_bug.cgi?id=9370

**Comment by freemangordon** [comment]
Actually it should be immediately available on the desktop, fixed by https://github.com/maemo-leste/libhildondesktop/commit/b672af1a60fadbf0453befb908ebf4fc74312b8d.

Please test and close as appropriate
