### ISSUE TITLE
Import status-area-orientationlock-applet

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#37]
https://github.com/community-ssu/status-area-orientationlock-applet

**Comment by MerlijnWajer** [comment]
I've fixed the `debian/control` file and `src/Makefile` and now the package compiles. The icon doesn't seem to be loaded - we might be using the wrong theme?

https://github.com/maemo-leste/status-area-orientationlock-applet

**Comment by freemangordon** [comment]
Icons are part of the package itself and copied to /usr/share/icons/hicolor/XxX/hildon, so I don;t think it is the theme, unless I am missing something

**Comment by MerlijnWajer** [comment]
Well, it does call this: https://github.com/maemo-leste/status-area-orientationlock-applet/blob/master/src/lib-orientation-lock-status-menu-widget.c#L72

But I don't know enough about gtk2 theming, yet.

**Comment by MerlijnWajer** [comment]
Seems that a reboot fixed the icon issue.

**Comment by MerlijnWajer** [comment]
So I think we can add this to jenkins; I don't know how to test it, though, since we don't seem to do orientation yet.

**Comment by MerlijnWajer** [comment]
Imported.
