### ISSUE TITLE
Increase range for droid4 backlight

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#370]
Currently we only have the values `0-7`, per this commit:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=10dc62d0ae41

Maybe we can just use the whole range, this will likely make ALS adjustments better.

I will test this weekend, and if it works, send a RFC to the LKML to see what the proper way would be to upstream, if useful and working.

**Comment by clort81** [comment]
Using the brightness-UI applet I would like to have more levels between "4" (usually fine) and "5" (full brightness).  

Having looked at the simple-brightness-applet, I did not see a simple way to get more brightness levels, or user-configurable brightness levels for each of the 5 steps.

I am using shell and 'echo' to set brightness now.

**Comment by IMbackK** [comment]
im going to close this as wontfix, as i dont currently have the intention of changeing mainline here
