### ISSUE TITLE
Lockscreen failing to unlock.

### ISSUE THREAD

**Issue by clort81** [maemo-leste/bugtracker#371]
I've noticed problems with unlocking sometimes on Droid 4
using maemo-leste-1.0-armhf-droid4-20200323.tar.gz

Screen shows 
![badlockscreensnp](https://user-images.githubusercontent.com/51511737/81438989-eead0280-916d-11ea-845b-6dc1e37aeffb.jpg)

Scrot shows
![badlockscreen](https://user-images.githubusercontent.com/51511737/81439018-008ea580-916e-11ea-9129-a1a597074e0c.png)

**Comment by MerlijnWajer** [comment]
This is powervr related. You can still swipe and it'll unlock.

**Comment by MerlijnWajer** [comment]
This will be solved with the next batch of mce changes; or at least worked around.
