### ISSUE TITLE
"user" has no permissions to write to org.ofono on system bus by default

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#372]
We need to add this:

```
  <policy user="user">
    <allow send_destination="org.ofono"/>
  </policy>
```

to the right place here `/etc/dbus-1/system.d/ofono.conf `.

Perhaps we can make another fine there, and extend the ofono behaviour?

cc @parazyd @pavelmachek

**Comment by IMbackK** [comment]
we should probably avoid hard coding permissions to a user name if possible and provide permissions based on groups instead.

**Comment by MerlijnWajer** [comment]
On Maemo the user is always called `user`, so I am not sure if that makes sense.

**Comment by MerlijnWajer** [comment]
There are a lot of scripts and daemons that still start/run as `user`, for example.

**Comment by MerlijnWajer** [comment]
Like, in general I agree, but let's not make that an issue here. ;)

**Comment by IMbackK** [comment]
ok maybe we should open a seperate issue somewhere else. anyways not introducing new dependacnys on the username will make later migration easyer. most of the stuff currently started via ini scripts explicetly as user should be started by a session manager.

**Comment by MerlijnWajer** [comment]
Well, yeah. But I think that should probably be a separate issue and I'd personally not be ready to tackle it until I have phone that is usable as daily driver. ;)

**Comment by pavelmachek** [comment]
ofono.conf seems like good place to fix this. I suggest simply
commiting this.

**Comment by MerlijnWajer** [comment]
The problem with that approach is that we only package a special ofono for the Droid 4. We don't for the VMs and for the N900. So then we have to fork ofono for all platforms.

**Comment by pavelmachek** [comment]
Not sure what the best solution is. This is really Maemo-specific
adaptation of ofono, and we'll need it on N900, too. Can that be done
from some kind of maemo-adaptation package?

**Comment by pavelmachek** [comment]
Hi!

I'm not sure, but creating

/etc/dbus-1/system.d/ofono-maemo.conf

containing:

<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus
Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
 <busconfig>

  

  <policy user="user">
      <allow send_destination="org.ofono"/>
        </policy>

</busconfig>

could do the trick.

**Comment by MerlijnWajer** [comment]
I think so too. We're working on this, and also doing it for some other device specific configs.

**Comment by MerlijnWajer** [comment]
Fixed in https://github.com/maemo-leste/leste-config/commit/780adae3eda13a52463afba8555b9c5fc48345e2

In a day or so (max), `apt install leste-config-<DEVICE>` will fix this problem.
