### ISSUE TITLE
Add droid 4 calibration config to the repo

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#374]
ready to build deb packages:
https://github.com/IMbackK/ti-utils
https://github.com/IMbackK/droid4-wlanconfig

**Comment by IMbackK** [comment]
now https://github.com/IMbackK/ti-utils-wilink6
also we must add NL80211_TESTMODE to our d4's kconfig

**Comment by IMbackK** [comment]
unsurprisingly it works fine on vm

**Comment by MerlijnWajer** [comment]
Packaged both in the main repos. All we need now is an init script of some kind, plus a dependency on the scripts in the droid4 meta package.

**Comment by IMbackK** [comment]
Also consider a hook to recallibrate when ti-connectivity is installed/updated

**Comment by MerlijnWajer** [comment]
My inclination would be to run the calibrate script on start. Anything else will be painful as it means we have to stop `icd2`, kill `wpa_supplicant`, calibrate, and start `icd2.

**Comment by buzztiaan** [comment]
After doing calibration manually and rebooting droid4, wifi just broke completely
Wizzup suspected it was because wlan0 was now called wlan1 :)

By request, the udev created file is here : http://space.nurdspace.nl/~buzz/70-persistent-net.rules

**Comment by buzztiaan** [comment]
After deleting the wlan0 entry with old mac address, and naming the wlan1 one wlan0, wifi worked again. Actually it probably worked fine as wlan1 aswell, but : 
`18:07:20 < Wizzup> buZz: btw, yes, libicd-network-wpasupplicant assumes wifi is wlan0
`

**Comment by buzztiaan** [comment]
These calibrations are awesome btw, 100% of my previous 'weak positions' for droid4 wifi now all have fine range :D

**Comment by MerlijnWajer** [comment]
@buzztiaan - can you test this from -devel on a recent image and let us know if it just works? Then we can move it to non-devel and close the ticket.

**Comment by buzztiaan** [comment]
alright

* wrote maemo-leste-1.0-armhf-droid4-20200624.img.xz to SD
* added -devel , apt update&upgrade
* installed ti-utils-wilink6 and droid4-wlanconfig
* rebooted
* ran maserati-calibrate as root
* rebooted

wifi is now calibrated and called wlan0 and my DHCP ip matches what i had on previous install after calibration \o/
