### ISSUE TITLE
Change geometry file for Droid4 keyboard a tiny bit.

### ISSUE THREAD

**Issue by buzztiaan** [maemo-leste/bugtracker#383]
The geometry currently is ; 

![image](https://user-images.githubusercontent.com/940336/83975781-f8a15d00-a8f5-11ea-8db0-7b66562b3edb.png)

Although this is very close, its just a bit too triggering for my OCD. :)

**Comment by clort81** [comment]
Hello buzztiaan.  Thank you for the layout image.  It is helpful.

It does not match what my current keyboard map is from Leste - is this a proposal from you?

Current map differs from your picture in that: 
- Shift mapped to Caps_Lock (good) 
- Caps_Lock is mapped to Shift (good)
- my OK key does nothing 
Your picture loses Ctrl in favor of Caps_Lock.  This would be a loss.

While xev shows Meta_L is mapped with shift+SYM, I don't see the use for it.  Can you tell me what software would use Meta_L plus something? 

For general purpose linux computing,  we are DIRELY missing these keys:
- Esc
- []
- ";" ":"
- Function keys

I could add missing keys with ~/.Xmodmap if we had  "OK" key mapped to a modifier.

How can I get "OK" key working as a modifier?

Thank you.

**Comment by buzztiaan** [comment]
Actually, the image was from the leste-config-droid4 package which includes a new keyboard layout ;)
See here : https://github.com/maemo-leste/bugtracker/issues/347#issuecomment-640127353

**Comment by clort81** [comment]
![maemo-leste-droid4-kbd-2021-07](https://user-images.githubusercontent.com/51511737/127316550-0026160e-5bb3-4f0e-b7cb-55325b0390e4.png)

This is current layout, published at [https://leste.maemo.org/Motorola_Droid_4#Notes](https://leste.maemo.org/Motorola_Droid_4#Notes)

I think this issue can be closed.
