### ISSUE TITLE
hildon-desktop blocks on client processes

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#384]
Hildon desktop blocks on child processes somtimes, locking on a stoped/frozen process until it responds or is killed. A wm should never become unresponsive because a client dosent respond. when this happens seams random

**Comment by buzztiaan** [comment]
I havent seen this happen yet, do you have any reproduction method?

**Comment by IMbackK** [comment]
have a processes stoped (im my case firefox-esr) and use the phone, especially exercising hildon. hildon will lock up at some point sometimes after a very long period being fine. Then you can ssh into the fine and observe that only the firefox-esr process is in T state. Resuming the  firefox-esr process via kill will then make hildon come out of lock.

**Comment by buzztiaan** [comment]
why did you close it? is it no longer happening?

**Comment by IMbackK** [comment]
cant reproduce anymore ill reopen if it happens again

**Comment by buzztiaan** [comment]
ah, was just curious ;)
