### ISSUE TITLE
Provide web interface to Maemo Leste repositories

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#395]
I think it would be nice to have a web frontend to the Maemo Leste repositories.

This would allow users to browse our repository (as opposed to just github repos), search the repository, and we could also make the `-extras` one slightly more fancy, rendering the icons and other description.

Debian's code is here: https://salsa.debian.org/webmaster-team/packages/-/blob/master/INSTALL

The Devuan folks have this: http://git.katolaz.net/d1pkgweb/ and http://git.katolaz.net/d1pkgweb-query/

It needs some work, though. It doesn't properly parse all long descriptions, and it also doesn't provide links to packages as specified in the dependencies, which Debian does do.

But this (`d1pkgweb`) might be relatively easy to modify to our needs.

**Comment by MerlijnWajer** [comment]
It'd be nice to also point to our git repositories, and maybe even specific tags that correspond to the package versions.

**Comment by MerlijnWajer** [comment]
![image](https://user-images.githubusercontent.com/517897/85467541-a4f86a00-b5ab-11ea-802c-ce19354c0455.png)

**Comment by parazyd** [comment]
Now running at https://maedevu.maemo.org/pkgweb/

Eventually we will implement also listing of files in the debs, but I think this is fine for now as it is.
