### ISSUE TITLE
Droid 4 - RTC support

### ISSUE THREAD

**Issue by sicelo** [maemo-leste/bugtracker#399]
The droid 4 (or at least mine) has considerable time drift if the NTP service is stopped for extended periods. Perhaps part of the issue is that we do not have the RTC enabled. Attempting to save time to the RTC device results in:
```
root@devuan-droid4:~# hwclock -w
hwclock: ioctl(RTC_SET_TIME) to /dev/rtc0 to set the time failed: Numerical result out of range
```

We have the required module in Leste, `rtc-cpcap` (https://git.kernel.org/pub/scm/linux/kernel/git/abelloni/linux.git/commit/?h=rtc-next&id=dd3bf50b35e3e111d6325207177b12af88aec824 and https://elektranox.org/droid4/ ) and it can be loaded cleanly.

However, the error above persists

**Comment by IMbackK** [comment]
this has been fixed by sre in the next kernel release.

**Comment by MerlijnWajer** [comment]
FWIW the mail is a patch that will need to be merged, but yeah. We can carry it in `droid4-linux`.

**Comment by IMbackK** [comment]
yup i doubt that it wont be merged tho.

**Comment by MerlijnWajer** [comment]
Should be `beowulf-devel` now.

**Comment by MerlijnWajer** [comment]
Works for me in `beowulf-devel` kernel, shall we build for `beowulf` and close this issue?

**Comment by parazyd** [comment]
I'm fine with this. However, what should we do about the current fake-hwclock setup? Can it coexist?

**Comment by MerlijnWajer** [comment]
I think so. I don't think the rtc is on a battery, is it?

**Comment by IMbackK** [comment]
depends on if you count the main battery as user removeable
