### ISSUE TITLE
Pulseaudio integration

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#402]
We need PA for various audio features. Most of the Maemo userspace also relies on it.

Fremantle runs PA like this, as user `pulse`:

```
/usr/bin/pulseaudio --system --high-priority -log-target=syslog
```

Launched from `/etc/event.d/pulseaudio`. We should make an OpenRC init script for this, probably look at the gentoo one.

And then, we want `user` and `root` to be in group `pulse-access` (also in `audio`, I suppose, if they aren't already)

```
audio:x:29:user,pulse
pulse-access:x:112:user,root
```

More info will be posted here. Like required sink names, extra properties, etc.

**Comment by MerlijnWajer** [comment]
There is now a `maemo-audio` package that installs a pulseaudio init script and sets up the user groups. It will also pull in pulseaudio as a package.

This is only the bare minimum, but it's a start.

**Comment by clort81** [comment]
Now   
```
hildon-connectivity-base hildon-connectivity-wlan
```
pull in pulseaudio.  And pulseaudio breaks mpv and mplayer playback among other applications.

Can you remove pulseaudio as a dependency?

**Comment by freemangordon** [comment]
we can't remove nor stop PA, too many core maemo services depend on it

**Comment by MerlijnWajer** [comment]
mpv and mplayer work just fine with pulseaudio.

**Comment by clort81** [comment]
In case anyone reads this needing help getting working sound:

With pulse installed, i had to change the amixer command to specify cardnumber in /etc/rc.local
This gets me configured sound on boot. 
```
amixer -c 0 cset numid=22 HiFi      #set left speaker to HiFi
amixer -c 0 cset numid=21 HiFi      #set right speaker to HiFi
amixer -c 0 cset numid=26 HiFi      #set left headset to HiFi
amixer -c 0 cset numid=25 HiFi      #set right headset to HiFi
amixer -c 0 cset numid=1  50%       #set HiFi volumes to 50%
```
Since keyboard _has no F6 key **yet**_ to change sound card in alsamixer, I add to .bashrc an alias to select the alsa sound card on invocation:
```
alias alsamixer="alsamixer -c 0"
```
To make mplayer use pulseaudio I edited the file ~/.mplayer/config to include the line:
```
ao=pulse
```
