### ISSUE TITLE
Droid4 20200624 image doesnt kick hwdb for the new keyboard layout

### ISSUE THREAD

**Issue by buzztiaan** [maemo-leste/bugtracker#404]
As in title :) Installed from the image, tried keyboard in xterm but couldnt use [OK] + p for the pipe symbol.

**Comment by buzztiaan** [comment]
Whats needed in postinst is the udev commands from https://github.com/maemo-leste/bugtracker/issues/347#issuecomment-609884872

**Comment by parazyd** [comment]
Fixed in https://github.com/maemo-leste/leste-config/commit/c6f5f81170f3d9a8253243d68896dd136970e77d
