### ISSUE TITLE
Droid 4: automatic power off

### ISSUE THREAD

**Issue by druk13** [maemo-leste/bugtracker#416]
Battery fully loaded and if the phone is not used, the system powers roughly after 30 minutes off.

**Comment by druk13** [comment]
This also happens, when the phone is connected to power adapter.

**Comment by parazyd** [comment]
We're already trying to trace this down to a kernel issue, so hopefully this is the solution https://lore.kernel.org/linux-omap/20200706183338.25622-1-tony@atomide.com/T/#u

**Comment by druk13** [comment]
If I understand it right, than the poweroff is a thermal problem while the power adapter is connected?

But I have observed this behavior even without connected power adapter.

**Comment by MerlijnWajer** [comment]
There should be a kernel upgrade in `-devel` - you might want to try it and see if it makes the problems go away.

**Comment by druk13** [comment]
After installing kernel 5.7 from 8. July, the phone does not power off during usage.

The bad thing is, that the following does not work:
1. No sound in hildon-desktop, but sound in applications e.g. rhythmbox.
2. Connecting the power adapter an loading of the battery want work.

**Comment by MerlijnWajer** [comment]
The kernel change cannot have broken sound. There are other things in `-devel` that change sound. pulseaudio is now installed by default. I still have sound with pulseaudio.

**Comment by parazyd** [comment]
@druk13 Have you updated recently? I think most issues are fixed.
