### ISSUE TITLE
Hildon dosent parse the .desktop Exec line correctly

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#417]
arguments starting with % are to be parsed by the .desktop launcher. Hildon dosent do this, it instead passes a literal %* to the application, confusing it. As hildon has no reason to ever use these arguments it should just remove them from the exec line before performing the launch.

relevant .desktop spec:
https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html

**Comment by parazyd** [comment]
It should however accept parameters, so let's not just use the binary path :)

**Comment by IMbackK** [comment]
no why would hildon ever launch an application with a % parameter?
