### ISSUE TITLE
status-area-orientationlock-applet installs into /usr/lib/hildon-desktop - not in /usr/lib/<arch>/hildon-desktop

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#419]

**Comment by parazyd** [comment]
Fixed with https://github.com/maemo-leste/status-area-orientationlock-applet/commit/32e46e8372fd7e721600b4006f19d07fd2d617a8 and https://github.com/maemo-leste/status-area-orientationlock-applet/commit/1bd642221bdb9ca85342892f9195a28aa60e8d27
