### ISSUE TITLE
Finish connui

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#42]
https://github.com/community-ssu/connui

**Comment by dderby** [comment]
Have you considered replacing connui with Intel's connman?  Unlike connui, connman has solid upstream support and already integrates with oFono and neard (NFC).  Sooner or later, these components will need to be integrated into Leste.

connman packages are already available in Devuan.  I've frequently used the CLI client on the N900 under Debian and have had a good experience with it.

**Comment by MerlijnWajer** [comment]
We have had quite some discussions about it. The tl;dr is that connui is pretty much REd at this point, and it's the easiest path to get us close to what Maemo has. And it also makes it possible for us to drop in the Fremantle data and voice binaries (on armel anyway) if we would ever want to attempt that. (Not saying we want to, but could be a fun attempt).

I don't think Ofono integration would be that hard.

We discussed alternatives, like networkmanager and connman, and wicd, etc. Bottomline was that connui is pretty "proven" and also AFAIK did better power management, iirc. I don't recall the full discussion.

Personally I'd really like to continue with the current path, so we have usable wifi (and perhaps 3g soon). Then, if there is someone particularly enthousiastic about another path forward, he/she can port to connman/networkmanager/wicd/etc and we can see if it's a better alternative.

**Comment by MerlijnWajer** [comment]
I think this can be closed. Yay!
