### ISSUE TITLE
Workaround: Get working Speakers on Boot

### ISSUE THREAD

**Issue by clort81** [maemo-leste/bugtracker#420]
amixer sset "Speaker Left" "HiFi"
amixer sset "Speaker Right" "HiFi"
amixer -c 0 set HiFi 65%

in /etc/rc.local

gets me sound on boot.  

hifi set this way yields "47" in alsamixer which is a safe volume for my device

**Comment by druk13** [comment]
All information available at:
[https://leste.maemo.org/Motorola_Droid_4](url)

**Comment by clort81** [comment]
Oh even better, simultaneous headphone and speaker! Thanks!
