### ISSUE TITLE
User-Disable of USB Charging 

### ISSUE THREAD

**Issue by clort81** [maemo-leste/bugtracker#424]
Droid4 attached to USB automatically charges the battery.

After battery is full, it continually starts and stops charging.

This is undesireable for situations when I need to keep device attached to PC for e.g. usb-networking:  the device reports 'charging' every few seconds and plays the charging sound.

How can users disable usb-charging to prevent constant charging messages?

Alternatively, perhaps the charging logic could be set to only begin charging again after a certain minimum voltage threshold is crossed?

Thanks!

**Comment by clort81** [comment]
Today's update of kernel and mce seens to yield much less frequent charging notifications!  Thanks!  

Would still like a command to disable charging though!

**Comment by IMbackK** [comment]
The correct way to solve this is to improve cpcap-charger.

i say this bug is invalid

**Comment by clort81** [comment]
I don't know why, but charging with constant-connected usb is working great now!  It only shows the charging popup once every few minutes.  This indicates a very sensible 'topping up' of charge cycle, afaict.

hooray.
THANKS!
