### ISSUE TITLE
UAE4All poor performance on Droid 4 as compared to N900

### ISSUE THREAD

**Issue by Suppresed** [maemo-leste/bugtracker#425]
I have recently caught up again with trying to make UAE4All work on the Droid 4. Simply copying the binaries provided on maemo.org and creating a symbolic link from /lib/ld-linux-armhf.so.3 to /lib/ld-linux.so.3 was enough to be able to execute it, but it would glitch out showing only half the screen even with patched SDL1.2.13 from https://github.com/maemo-leste/bugtracker/issues/18 . Disabling fullscreen made it work just as Milkytracker did work with fullscreen disabled. They work as expected. The only thing is that graphics seem to be slower than those on the N900. Switching to fullscreen also shows this, even though the screen is bugged. Sounds seem to take a little while to get to run smoothly but it does get more stable than on the N900, graphics don't. As asked, I am leaving here the Kick.roms. Kick.rom is the one I am running right now and these are placed inside ~/MyDocs.

[firekicks.zip](https://github.com/maemo-leste/bugtracker/files/4934627/firekicks.zip)

**Comment by MerlijnWajer** [comment]
Thank you! I will try to investigate soon.

**Comment by IMbackK** [comment]
this presumably was because of the extra copies ddk1.9 did
