### ISSUE TITLE
Changing the display timeout dosent work on Droid 4

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#428]
Display timeout is allways  dosent work, even after reboot, the timeout is always aprox 1 min.

Repo:
1. change display timeout to 10sec
2. have display stays lit while charging off
3. have lock screen automaticlly on
4. save settings
5. wait 10 sec.
6. nothing happens
7. wait 60 sec
8. screen turns off
9. reboot
10. screen still dosent turn off after 10 sec

maybe related to the problems with the touchscreen virbation people on irc are haveing.

tested on droid 4 with -devel

**Comment by sicelo** [comment]
It's not related to vibration. It has always been there and to the best
of my knowledge, only Droid 4 is affected. The timeout works fine on
N900.

**Comment by IMbackK** [comment]
this is fixed by https://github.com/maemo-leste/mce/pull/12
