### ISSUE TITLE
import iio-sensor-proxy as a core package

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#429]
https://github.com/IMbackK/iio-sensor-proxy

upsteam iio-sensor-proxy, changed to compile current git & get its source from the repo because the stable version of iio-sensor-proxy depends on systemd (this will be fixed in the next upstream stable release of iio-sensor-proxy)

iio-sensor-proxy abstracts away the different ways the kernel exposes different accelerometer, compass, proximiry and light sensor devices and provides a dbus interface to them.

iio-sensor-proxy replaces mce modules with the same goals while being much more robust and supporting devices/kernels other than the n900 and its obsolete vendor kernel.

**Comment by MerlijnWajer** [comment]
Done, thanks!
