### ISSUE TITLE
Hildon desktop not starting after battery depletion on Droid 4

### ISSUE THREAD

**Issue by dousha** [maemo-leste/bugtracker#435]
After system shutdown due to battery depletion, the desktop won't start after the battery is recharged.

When booting, the boot message would display. After starting X, the display would go blank. The backlight is still on and the device could be powered off by holding the power button for a few seconds. The device does respond when plugging into the wall and could charge the battery. Rebooting manually does not resolve the problem.

This behavior only shows when the device ran out of battery. Manual rebooting is fine.

Here are some log files:
Xorg.0.log: https://pastebin.com/gXV2Dewu
Kernel log: https://pastebin.com/HXiLEdU0
`/var/log/messages`: https://pastebin.com/bK1Ayp3M

**Comment by MerlijnWajer** [comment]
@dousha - I completely missed this message. I'd like to help you walk through this.

Could you try the latest image to start?

**Comment by IMbackK** [comment]
if you (@dousha) means that booting with the battery low and usb plugged in resulting in a eventual kernel hang during boot, this is known and sadly pretty hard to debug as nothing appears in pstore and uart cant be used for obv. reasons. It seams to only happen on some devices, one of my d4's has this problem the other dose not. tmlind also menditond seeing this on his device in the past.

needs investigation

**Comment by IMbackK** [comment]
this is fixed in devel
