### ISSUE TITLE
[N900] Speaker can't be automatically switched off when earphone is plugged

### ISSUE THREAD

**Issue by limingchina** [maemo-leste/bugtracker#442]
The speaker doesn't automatically switched off when earphone is plugged. The earphone seems to be working while the speaker is still playing. I have to manually use "amixer" to switch the speaker on and off.
Switch off:
```amixer -c 0 cset numid=101 0```
Switch off:
```amixer -c 0 cset numid=101 1```

Expected behavior: When earphone is plugged, the speaker is automatically switched off. When it's unplugged, the speaker is automatically switched on.

Quote from IIRC:
"One of the problems is that we need a UCM file for the n900, and then hopefully pulse will be able to act on the jack plug event
but the whole audio setup is pretty primitive at the moment anyway"

**Comment by limingchina** [comment]
After installing acpid, I've tried something like what's described here: https://bbs.archlinux.org/viewtopic.php?id=141910. It seems it can detect the plug/unplug and invoke the script that I want to use.

**Comment by limingchina** [comment]
Hmm, now, for some reason, the headphone doesn't have sound now. Looks like it's independent from this acpid script control. :-(
Has anyone got headphone working?

**Comment by MerlijnWajer** [comment]
Looks like this could also be done with Pulse: https://unix.stackexchange.com/questions/342556/pulseaudio-auto-switch-sink-when-headphones-connected

Then again, our audio routing might ultimately end up being more complex - if we want to support suspending sinks, and switching audio routing for phone calls (speaker, earpiece, headphone, headset, etc)

**Comment by sicelo** [comment]
this can probably be closed now that UCM is used
