### ISSUE TITLE
Hack: Disable charging and "disconnect charger" notification banners

### ISSUE THREAD

**Issue by clort81** [maemo-leste/bugtracker#443]
Hi!

.. since i usually work with device on-usb and the notification banners interfere with my fun and rendering, i wanted to disable them.  (the green notification LED is all i need to see charging status)

Maybe others might find this useful?

apt-get source status-area-applet-battery
apt install libupower-glib-dev

in status-area-applet-battery.c  comment out any notifications and sounds you don't like
```
status-area-applet-battery-1.5.3$ grep -in clort status-area-applet-battery.c
344:// clort  hildon_banner_show_information(GTK_WIDGET(plugin), NULL, dgettext("osso-dsm-ui", "incf_ib_battery_charging"));
345:// clort  battery_status_plugin_play_sound(plugin, "/usr/share/sounds/ui-charging_started.wav", FALSE);
351:// clort hildon_banner_show_information(GTK_WIDGET(plugin), NULL, dgettext("osso-dsm-ui", "incf_ib_disconnect_charger"));
398:// clort   hildon_banner_show_information(GTK_WIDGET(plugin), NULL, dgettext("osso-dsm-ui", "incf_ib_battery_full"));
```
dpkg-buildpackage -rfakeroot
and dpkg -i the .deb

I'm not a hater of banners in general, but for my 'desktop companion' use-case, using them to show the constantly changing charging status is inappropriate.

**Comment by parazyd** [comment]
This is a very specific usecase and it won't be applied in the applet.

However, if you wish, feel free to document this on our wiki ( https://leste.maemo.org )
