### ISSUE TITLE
Provide virtual machines (amd64) usable for developers.

### ISSUE THREAD

**Issue by parazyd** [maemo-leste/bugtracker#45]
This should be achievable using the same blend files in https://github.com/maemo-leste/image-builder and using http://github.com/parazyd/vm-sdk

**Comment by MerlijnWajer** [comment]
There is some interest in this on talk.maemo.org

**Comment by pkillnine** [comment]
will Virtualbox-compatible virtual machines be provided?

**Comment by parazyd** [comment]
@pkillnine Yes, a vdi is created at one point in the build process of VMs. We will also provide a qcow2, and if requested - Vagrant, since they are all built from the same process.

**Comment by parazyd** [comment]
All three are provided as of today. There's a readme file on the downloads page, that explains what they are.
