### ISSUE TITLE
Ensure that user directories and MyDocs are set up properly

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#453]
```
21:24 < freemangordon> MyDocs mount?
21:24 < uvos> yes
21:24 < freemangordon> I know, thats why the trickery
21:25 < uvos> well in this case it dosent work on my end
21:25 < freemangordon> Wizzup: do you remember the details? I think it was spinal that did something?
21:25 < freemangordon> uvos: yeah, looks like
21:28 < Wizzup> there was something about env vars
21:28 < freemangordon> uvos: do you have MyDocs folder in your $HOME?
21:30 < uvos> freemangordon: no
21:30 < uvos> freemangordon: addig it makes "file system" work in strange manner
21:31 < uvos> freemangordon: someone should check if this is missing in the image or if i deleated it by accident
21:33 < freemangordon> also, create .config/user-dirs.dirs with content https://pastebin.com/vUkb8GNM
```

**Comment by IMbackK** [comment]
https://github.com/maemo-leste/bugtracker/issues/426 is related

**Comment by freemangordon** [comment]
and the content is:

XDG_DOCUMENTS_DIR="$HOME/MyDocs/.documents"
XDG_MUSIC_DIR="$HOME/MyDocs/.sounds"
XDG_PICTURES_DIR="$HOME/MyDocs/.images"
XDG_VIDEOS_DIR="$HOME/MyDocs/.videos"
NOKIA_CAMERA_DIR="$HOME/MyDocs/DCIM"
NOKIA_MMC_CAMERA_DIR="/media/mmc1/DCIM"

Also, make sure those dirs exist

**Comment by parazyd** [comment]
@freemangordon `NOKIA_MMC_CAMERA_DIR="/media/mmc1/DCIM"` should be owned by `user`, right?

**Comment by IMbackK** [comment]
idk if setting it to that is sensible at all /media should only contain mounts, if a mmc is not available (or the concept makes no sense for the device) we should use some subdirectory to $HOME.

**Comment by parazyd** [comment]
Applied in leste-config.
