### ISSUE TITLE
New update blogpost

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#455]
TODO:

* Finish initial clock-ui (could have some bugs, but mostly usable)
* <s>Finish initial Qalendar (could have some bugs, but mostly usable, requires Werror fix in calendar-backend)</s>
* Finish dbus-scripts code and examples
* <s>Merge mce led-sw and iio-accelerometer and test them</s>
* Add qt-platform-maemo bugfix (experienced in Qalendar)
* ...

**Comment by IMbackK** [comment]
* Test new mce paths on PP
   * Write device specific mce config file for PP
* Test new mce paths on N900
   * Write device specific mce config file for N900
* Import iio-uinput into repo

**Comment by MerlijnWajer** [comment]
* Ensure that qt environment variables are set properly

**Comment by MerlijnWajer** [comment]
* https://github.com/maemo-leste/bugtracker/issues/415

**Comment by MerlijnWajer** [comment]
* web interface/ui

**Comment by IMbackK** [comment]
* implement a, possibly temporary, solution to ts rotation

**Comment by MerlijnWajer** [comment]
* qt environment variables.
