### ISSUE TITLE
Discuss fullscreen hack in libmatchbox

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#458]
https://github.com/maemo-leste/libmatchbox2/blob/564fb3e51fee69898ff7cd920ac7c655e4ea24f3/matchbox/core/mb-wm-client-window.c#L621

It seams this quite terrible hack is no longer relevant. why should we care about applications that want to be full screen but fail to set _NET_WM_STATE_FULLSCREEN? let them have the status bar above the window... i dont know what terrible hacky things the browser or the n900 camera app did in the passt but we dont care about those either.

**Comment by clort81** [comment]
IMbackK's point seems valid to me.  We do not have a large library of apps ported from legacy maemo that fail to set proper X11 fullscreen flag.
