### ISSUE TITLE
Translations: migrating to in-package format and allow for changes

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#460]
In Maemo-Leste, we have currently imported `<pkg-name>-l10n-<langcode>` packages from Fremantle.

We can do this, since the packages are hosted on the same server, and IIUC that is not a legal problem.

However, we cannot edit these packages currently, since they are `_all` packages, and we don't have the source. The translations themselves are easily converted using `msgunfmt`.

The question is: how do we move to a situation where we can modify the translations, extend them, replace them, etc. It seems that most packages in Debian just provide all translations directly with the package. Given that we're now 10 years after the last Maemo (5) release and disk space has increased a lot, I think this is not a problem for us.

So we could move translations into the package they are for, and add a `Replaces` and `Conflicts` for the `-l10n-mr0` packages, but I am not sure how lines like this would look in the future (taken from hildon-application-manager):

```
Depends: ${shlibs:Depends}, maemo-launcher, hildon-application-manager-l10n-mr | hildon-application-manager-l10n-mr0, hildon-libs-l10n-mr | hildon-libs-l10n-mr0, hildon-fm-l10n-mr | hildon-fm-l10n-mr0, hildon-common-strings-l10n-mr | hildon-common-strings-l10n-mr0, hildon-application-manager-settings-standard
```

What would provide `hildon-libs-l10n-mr` ? Should we just have one common package with common maemo translations, and then install application-specific translations with packages?

I believe that from a technical point of view, with the Replaces+Conflicts we could gradually start moving translations over, and then eventually remove all the old translations from our repository.
https://www.debian.org/doc/manuals/developers-reference/pkgs.en.html#replacing-or-renaming-packages

But we cannot actually remove the `Replaces` lines ever, until we figure out how to change the `Depends:` line as provided above. I wonder if we could merge `hildon-common-strings-l10n-mr0`, `hildon-libs-l10n-mr0`, `hildon-fm-l10n-mr0` and some others...

We could then move some translations into weblate (
https://hosted.weblate.org/ + https://docs.weblate.org/en/latest/index.html) and use that to allow others to contribute translations.

Related issue: https://github.com/maemo-leste/bugtracker/issues/311

**Comment by IMbackK** [comment]
the licensing issues make me uncomfortable.. other should be able to host our packages

**Comment by parazyd** [comment]
Done, weblate and @maemo-leste-translations
