### ISSUE TITLE
Figure out what to do about orphan files in leste images

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#461]
Every file in the images should belong to a package, except in /home. This is need to alow us to change/delete/move these files as necessary without breaking apt

**Comment by IMbackK** [comment]
@parazyd whats the status of this?

**Comment by parazyd** [comment]
@IMbackK There is still a few more files:

On every image:
* `/etc/fstab` (Configured specifically per-image)
* `/etc/rc.local` (Configured to generate ssh keys on boot)
* `/etc/ssh/sshd_config` (Configured to allow root login with password)
* `/etc/expandcard.sh` (Script to expand filesystem)
* `/etc/runlevels/sysinit/zram` (Symlink to /etc/init.d/zram, should probably be ran as a command in the build process instead)

Bionic/Droid4:
* `/boot/boot/boot.cfg` (The kexecboot menu config)

raspi2/3/4:
* `/boot/config.txt` (Leste-specific config for more VRAM alloc and 3D accel)

**Comment by IMbackK** [comment]
for the purposes of this bug i would say the following are justified to stay orphaned:

- /etc/fstab
- /boot/boot/boot.cfg

**Comment by IMbackK** [comment]
furthermore i would simply drop /etc/rc.local and use /etc/ssh/sshd_config from debian.

root logon is a bad idea anyways and its not a real bother to activate this while it still is sensible for development.
i expect people who use ssh are familiar with generating keys

**Comment by parazyd** [comment]
> for the purposes of this bug i would say the following are justified to stay orphaned:
>     * /etc/fstab
>     * /boot/boot/boot.cfg

Okay. I would also add the Raspberry Pi's config.txt files to this list since they have to reside on a FAT filesystem, and symlinks are unsupported, so we can't utilize leste-config here.

> furthermore i would simply drop /etc/rc.local and use /etc/ssh/sshd_config from debian.
> 
> root logon is a bad idea anyways and its not a real bother to activate this while it still is sensible for development.
> i expect people who use ssh are familiar with generating keys

I agree with the sshd_config. This configuration was here since we began since it was very convenient for development, where lots of images were flashed very often so it was basically plug-and-play. You're right in thinking this is unnecessary anymore.

Regarding rc.local, we still need a way to generate SSH host keys upon first boot. Unfortunately the Debian initscript that gets installed isn't smart enough to do this on its own.

**Comment by IMbackK** [comment]
/boot/config.txt being orphan rubs me the wrong way. while /boot/boot/boot.cfg and /etc/fstab contain information totaly specific to the installation which should never be changed by the package manager, /boot/config.txt contains things that we might realistically want to change

**Comment by parazyd** [comment]
On Raspberry Pi users often change this on their own in (sometimes strange) ways so I don't think it's a big deal.

It could be possible to add just a plain config.txt (not a symlink) to leste-config, but then we'd probably silently override users' changes at some point.

**Comment by parazyd** [comment]
I replaced the `rc.local` modification with this: https://github.com/maemo-leste/hildon-base/commit/2621441d38e89143dc095599b2c4092bf79035fa
It also includes creation of `XDG_RUNTIME_DIR` mentioned in #426

Also moved `expandcard.sh` from image-builder to hildon-base: https://github.com/maemo-leste/hildon-base/commit/682593c21bdd2023093c89615301927d07b930ef

**Comment by parazyd** [comment]
Latest hildon-base will now set a password for the user `user`. I will update the documentation and the Getting Started page on our wiki (https://leste.maemo.org/Getting_Started) accordingly.

Following this, we won't maintain (or change) `sshd_config` from its default except on the VM. This implies that root login with password will be disabled further on. On the system, the user "user" has NOPASSWD sudo set up, so it is still convenient enough to log in as user and then escalate to root with sudo if necessary.

The mapphone/kexecboot boot.cfg will stay maintained in `image-builder`, as will the Raspberry Pi's config.txt.
