### ISSUE TITLE
Import python-gconf

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#469]
Our packages need it. It's in stretch, but not in buster.

I just downloaded the stretch deb, and it worked. But we might want to build it ourselves?

**Comment by MerlijnWajer** [comment]
@parazyd any idea what makes the most sense?

**Comment by parazyd** [comment]
@MerlijnWajer Ideally we could split it out of the whole package and just build `python-gconf`. I've already imported `gnome-python` some time ago: https://github.com/maemo-leste-upstream-forks/gnome-python

IIRC you mentioned you managed to build something similar by taking a component out of the whole package?

**Comment by parazyd** [comment]
Built for beowulf main.
