### ISSUE TITLE
Fork and change syncevolution

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#472]
We should import the debian syncevolution and at least apply the following changes.

One to not build akonadi (breaks compilation).

The other one to enable the maemo backend, and to include the dbus-1 pkg-config flags.

Better patch for dbus-1 for them is welcome - I can upstream.

```
user@devuan:~/dev$ diff -r syncevolution-1.5.3/ syncevolution-1.5.3_good/ | grep -v 'Only in'
diff -r syncevolution-1.5.3/debian/rules syncevolution-1.5.3_good/debian/rules
29c29
< 		                --enable-kwallet --enable-akonadi \
---
> 		                --enable-kwallet \
31c31,32
< 		                --enable-oauth2
---
> 		                --enable-oauth2 \
> 		                --enable-maemocal
diff -r syncevolution-1.5.3/src/backends/maemo/maemo.am syncevolution-1.5.3_good/src/backends/maemo/maemo.am
18,19c18,19
< src_backends_maemo_syncmaemocal_la_LDFLAGS = -module -avoid-version
< src_backends_maemo_syncmaemocal_la_CXXFLAGS = $(SYNCEVOLUTION_CXXFLAGS) $(SYNCEVO_WFLAGS)
---
> src_backends_maemo_syncmaemocal_la_LDFLAGS = -module -avoid-version `pkg-config dbus-1 --libs`
> src_backends_maemo_syncmaemocal_la_CXXFLAGS = $(SYNCEVOLUTION_CXXFLAGS) $(SYNCEVO_WFLAGS) `pkg-config --cflags dbus-1`
```

**Comment by parazyd** [comment]
I've imported it here: https://github.com/maemo-leste/syncevolution and it built successfully for beowulf-devel.

I'm not sure in which sense a better patch would be needed. Something with configure.in rather than maemo.am?

**Comment by MerlijnWajer** [comment]
Yeah, in configure.ac rather than maemo.am, to at least check for dbus-1 early on if Maemo is enabled.

**Comment by MerlijnWajer** [comment]
@parazyd - think we can close this
