### ISSUE TITLE
droid4: droid4-wlanconfig dosent get installed by the image or devel upgrade, nor dose it run on boot

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#474]

**Comment by parazyd** [comment]
Added as a dependency here https://github.com/maemo-leste/hildon-meta/commit/d006ef8c4fc81a8db60c4f50aa7890b4e81d0342

As for running on boot, does it have to be ran only once or on every boot?

In both cases, you could write an initscript that runs, and in the former, make the initscript remove itself from the runlevel after running.

**Comment by parazyd** [comment]
Initscript added here: https://github.com/maemo-leste/droid4-wlanconfig/commit/3ec83310a3b28a11f29e1232f045fde2d363fa87

Closing.
