### ISSUE TITLE
n900: mac address changes randomly on every boot

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#475]

**Comment by parazyd** [comment]
This is the way the actual wifi driver works on the N900. IIRC the actual MAC is saved in cal and it could be read in some way eventually.

**Comment by dderby** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/net/wireless/ti/wl1251/main.c?id=562da3a39cb78ffaba44511ec39d8c245023a02f

**Comment by parazyd** [comment]
Probably relevant: https://github.com/maemo-leste/leste-config/issues/3

**Comment by parazyd** [comment]
@IMbackK was this fixed with https://github.com/maemo-leste/leste-config/commit/9cb84067714902cea3bfe75cca48656a93a74fbd
