### ISSUE TITLE
SURF2 Browser: Add keyboard toggle for urlbar, fullscreen 

### ISSUE THREAD

**Issue by clort81** [maemo-leste/bugtracker#485]
Feature request to add a keyboard toggle for displaying urlbar (setuptoolbar()).  

+Also remap keyboard toggle for fullscreen (F11) to something available on n900/droid4 (perhaps ctrl+enter).

**Comment by parazyd** [comment]
Added here: https://github.com/maemo-leste/surf2/commit/7c9ec694239162eff5062790176bb1e2e960cd9e
