### ISSUE TITLE
X Terminal reboot droid4-20201129

### ISSUE THREAD

**Issue by FFranciska** [maemo-leste/bugtracker#487]
In vertical mode start X Terminal
Open the screen keyboard
Put the phone in horizontal mode
Put in vertical
(Repeat)
And the phone will reboot :c
(Purple ligth)

I think that hildon crashes
I change the language from english to mexican spanish and change the terminal colors and never update

Sorry but i dont have a especial usb cable for debug

**Comment by IMbackK** [comment]
yeah this is a known issue, we are currently in the process to migrating to a new graphic driver, that will hopefully solve this. However changes to this driver and its closed source nature make this is difficult at this time.

**Comment by clort81** [comment]
How can we disable rotation until that is fixed?

**Comment by IMbackK** [comment]
its not rotation per say sometimes creating surfaces just crashs x for some reason. You can observe the same thing with gtk3 drop down menus. So disabling rotation only removes one case where this is triggerd. If for some reason you still want to disable rotation you can unload the iio-accelerometer mce module or use the rotation inhibit applet

**Comment by clort81** [comment]
thanks, i also get crashes with testing builds of ManaPlus opengl or opengl-es mode.

**Comment by MerlijnWajer** [comment]
This should be solved in the latest images. Thanks for the report, sorry it took so long. :-)
