### ISSUE TITLE
add macchanger in every new image

### ISSUE THREAD

**Issue by FFranciska** [maemo-leste/bugtracker#488]
Thanks to all the people for this great project :3

I think that in order to improve privacy it would be a good idea to integrate macchanger to be able to change the mac of compatible devices

I tried macchanger on my droid4 and it works

Now you can also add it to the wiki or integrate my little hack into the /etc/rc.local file

```
##Mac random
ifconfig wlan0 down
macchanger wlan0 -e -a
ifconfig wlan0 up
```

Thanks to all of you

**Comment by IMbackK** [comment]
the default is fine as is, users can install this if they want, maybe you could add a page to the wiki explaining how
@MerlijnWajer close this pls

**Comment by MerlijnWajer** [comment]
@FFranciska - can you please add this to the wiki? That would be nice.

**Comment by MerlijnWajer** [comment]
https://leste.maemo.org/Tricks Maybe here?

**Comment by parazyd** [comment]
I've added `macchanger` to future images. It's not part of any metapackage, but it's a useful tool and if you actually need it,
you probably want it to be available on the system **before** actually broadcasting your address.
