### ISSUE TITLE
wifi signal applet - ui input problem causes high cpu use

### ISSUE THREAD

**Issue by clort81** [maemo-leste/bugtracker#496]
- Tried increasing wifi signal applet polling interval.
- Text input box didn't accept keyboard input, resulting in an empty field.
- Upon next boot dbus + icd were using full cpu and device got hot.

Looks like wifi signal applet got a zero stored for delay between probes, leading to constant probing.

**Comment by IMbackK** [comment]
this is a known problem and i have been trying to catch it in the act with gdb for the last few days.

It actually happens during wifi scanning.

**Comment by IMbackK** [comment]
im quite sure this is https://github.com/maemo-leste/bugtracker/issues/502

**Comment by clort81** [comment]
Can't recreate the problem with new leste image.  Closing for now.
