### ISSUE TITLE
Installing leste on devuan should be a bit more smooth than it is right now

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#5]
Currently we have to issue more than a few commands manually, that might ideally be done by the packages that are being installed.

We have a current 'install script' somewhere, we should find the most recent one and start looking at that.

**Comment by parazyd** [comment]
The install script should be done as a metapackage, and enable users to simply `apt-get install maemo-leste` or something similar.

**Comment by MerlijnWajer** [comment]
I'll try to pick this up soon.

**Comment by MerlijnWajer** [comment]
Can we also have a new image once this is done?

**Comment by parazyd** [comment]
Yes, of course.
Previously I've successfully done arm-sdk builds on Jenkins as well, so once we have some blend files (build recipes for arm-sdk) in place, we can even try that.

**Comment by MerlijnWajer** [comment]
This is almost done now, with the meta package in place. We just need to do a few arm-sdk test runs now.

**Comment by MerlijnWajer** [comment]
I think this is OK now - there is a ticket for ddable images, and we have the meta package.

One thing to worry about perhaps is installing dsme when starting from a plain image, that will cause device reboots. (Because debian wants to autostart ALL THE THINGS)
