### ISSUE TITLE
Vim is not usable inside screen / tmux sessions

### ISSUE THREAD

**Issue by ilya-bystrov** [maemo-leste/bugtracker#500]
I run `vim` and press _i_ and _Enter_, after that I get the following:

```
M<CURSOR>

```

Cursor stays on the same line, there is M char (ascii code - 77) behind, and newline.

It **always** happens inside **screen / tmux sessions**.

And this issue leads to inability of using `vim command mode`. I have to finish any command with _Enter_ but it not works as expected. So, there is know way to execute even ':q'.

Inserting newlines in `nano` editor works fine.

I run `maemo-leste-1.0-armhf-n900-20201227.img`,
but I observed this behavior in `maemo-leste-1.0-armhf-n900-20200323.img` also.

Probably, it's known issue with known workaround.

**Comment by IMbackK** [comment]
i assume you mean in the default termial: osso-xterm. otherwise there really is nothing that should affect this being different than plain devuan.

I can not reproduce on droid 4, using vim in osso-xterm in a screen session works just fine for me, i can pres 'I' and instert whatever inc. newlines. I can also exit insert mode and type ":q!" to exit just fine.

**Comment by MerlijnWajer** [comment]
@IMbackK - I believe the N900 and Droid 4 enter/return keys might be different?

**Comment by IMbackK** [comment]
possibly, the enter key handling in osso-xterm is also pretty funky to the benefit of the n770, it may be the result of this redirection. if so it would not affect plain xterm.
i removed this here https://github.com/maemo-leste/hildon-input-method-framework/pull/2 and https://github.com/maemo-leste/hildon-input-method/pull/5

**Comment by sicelo** [comment]
@ilya-bystrov in the meantime, Ctrl+M should work for what you need

**Comment by ilya-bystrov** [comment]
> please test if it works with the us layout or with the vkb or in plain xterm

Yes, I used osso-xterm.

I've got only us layout (also checked with `setxkbmap -query`). 
In plain xterm and with the vkb - the similar issue in screen / tmux sessions.

> @ilya-bystrov in the meantime, Ctrl+M should work for what you need

Yeah, it does the trick for both of them (osso-xterm and xterm).

**Comment by MerlijnWajer** [comment]
The latest `beowulf-devel` should have the fixes from @IMbackK - I no longer have this problem.

**Comment by SimonIremonger** [comment]
I concur, fixed too due to removing the Return<>KP_Enter swap in keymap (xkb-data) has corrected this perfectly in beowulf-devel!.  This bug can be closed.
