### ISSUE TITLE
icd2 gets stuck in icd_scan_listener_notify

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#502]
This is what happens:
Somehow https://github.com/maemo-leste/icd2/blob/80c00b75e2a20ae2dbc16a7190b8788c582c9453/icd/icd_scan.c#L356 ends up in a state where l == l->next, l->data contains total crap, module is  libicd-network-wpasupplicant and module->scan_listener_list is NULL. So somehow module->scan_listener_list gets deleted and set to NULL while icd_scan_listener_notify is traversing the list, memory corruption somewhere seams likely

one can not run icd in valgrind, because on arm it uses instructions regarding crypto that valgrind dosent support
on x86 i cant repo because it needs wifi scanning to happen

**Comment by freemangordon** [comment]
Should be fixed by https://github.com/maemo-leste/icd2/commit/78f694909c29898bc3863d7cb32efcdd25c744f2, please test with the new version (should hit devel in a minutes)
