### ISSUE TITLE
Feature Request:  Way to get to console when gui fails to start.

### ISSUE THREAD

**Issue by clort81** [maemo-leste/bugtracker#505]
I'm requesting a means to get to a shell or console on booted maemo-leste device.

Some ways this might be done:

- Virtual terminal switch like on PC (e.g. mapped to Ctrl-Alt 1, 2)
- Some way to bring-up wlan to ssh-in to device when device has no working GUI
- Some way to boot device to console-only mode then start gui manually.

I saw MerlijnWajer mention that he could log-in to a device with broken gui.  I would like this capability also.

Thanks!

**Comment by parazyd** [comment]
Try creating this file to avoid reboots: https://github.com/maemo-leste/dsme/blob/master/modules/lifeguard.c#L80

Regarding the rest, it's up to you as a user to handle it. You can log in using serial and bring up what you need, or
you could even write fallback scripts to act if hildon-desktop fails to start.

**Comment by IMbackK** [comment]
you can also boot with the rescue runlevel

**Comment by clort81** [comment]
I see /etc/inittab has
# The default runlevel.
id:2:initdefault:

What runlevel is the rescue runlevel?

**Comment by IMbackK** [comment]
```
user@maserati:~$ ls /etc/runlevels/
boot  default  nonetwork  off  recovery  shutdown  sysinit
```

**Comment by clort81** [comment]
I don't see a rescue runlevel in /etc/runlevels.  

What do I change to boot to console, without Xorg and hildon gui?

**Comment by IMbackK** [comment]
its recovery you just need to select recovery via softlevel in the kernel command line

@MerlijnWajer  pls close this

**Comment by parazyd** [comment]
@clort81 Did you manage?

**Comment by clort81** [comment]
> its recovery you just need to select recovery via softlevel in the kernel command line

Thanks for the reply IMbackK

- What do I need to set to get 'softlevel' in kernel command line?
- How can I add that as a secondary boot option in the kexec boot menu, so I can select non-gui boot before booting?

**Comment by IMbackK** [comment]
> > its recovery you just need to select recovery via softlevel in the kernel command line
> 
> Thanks for the reply IMbackK
> 
>     * What do I need to set to get 'softlevel' in kernel command line?
> 
>     * How can I add that as a secondary boot option in the kexec boot menu, so I can select non-gui boot before booting?

you can find the bootloader documentation here https://github.com/kexecboot/kexecboot/wiki

**Comment by IMbackK** [comment]
@parazyd @MerlijnWajer after https://github.com/maemo-leste/image-builder/pull/8 we should consider this closed, even though it wont apply to old installs

**Comment by IMbackK** [comment]
a boot entry is now in all new images.
