### ISSUE TITLE
Feature: Infinite backlight timeout

### ISSUE THREAD

**Issue by parazyd** [maemo-leste/bugtracker#506]
We should probably have 0 (zero) as an option so that the screen never goes off if requested.
This already exists as an option while charging, but I think it'd be nice to have it at any point.

https://github.com/maemo-leste/osso-applet-display

**Comment by MerlijnWajer** [comment]
Try this? https://maedevu.maemo.org/pkgweb/search?q=simple-brightness-applet

**Comment by MerlijnWajer** [comment]
Or do you want it in the settings?

**Comment by parazyd** [comment]
Selectable in the display applet

**Comment by parazyd** [comment]
Implemented with:
* https://github.com/maemo-leste/mce/commit/3968dea57212065dec5c3ed9d147ce1a1f423c0b
* 
* https://github.com/maemo-leste/osso-applet-display/commit/a2edfb5f3674e5dbc9591178fe156e96d321aabf

Had to run this because they don't automatically get set with upgrade:
```
gconftool -s --type list --list-type int /system/osso/dsm/display/possible_display_dim_timeouts '[0, 10, 30, 60, 120]'
gconftool -s --type list --list-type int /system/osso/dsm/display/possible_display_blank_timeouts '[0, 30, 60, 120, 300]'
```
