### ISSUE TITLE
Droid 4: Reboots every few hours.

### ISSUE THREAD

**Issue by clort81** [maemo-leste/bugtracker#508]
Hi,  is the 'reboot every few hours' issue on Droid 4 is still being experienced by other users?

I haven't found a workaround and AFAICT it happens on all my Droid 4s.  Using kernel 5.10.0 #1 currently.

I don't see another thread for this issue so I created one.

**Comment by freemangordon** [comment]
(11,56,46) tmlind: https://lore.kernel.org/linux-omap/YFIBUPmiPfDA0SCU@atomide.com/

**Comment by clort81** [comment]
Thank you.  Haven't had a crash since keeping a ping running. 

If/when this patch is included in an updated kernel I think we happily close the issue.

Thanks tmlind for everything!

**Comment by IMbackK** [comment]
this is fixed @MerlijnWajer

**Comment by clort81** [comment]
And how do i get the fix?
