### ISSUE TITLE
Droid4: Add updated hw keyboard map to leste image.

### ISSUE THREAD

**Issue by clort81** [maemo-leste/bugtracker#510]
I tested:
maemo-leste-1.0-armhf-droid4-20210330.img.xz  (kernel Linux devuan-droid4 5.10.4 #1)

It seems to be missing the OK+ special keys which are essential for shell and vi work.

(also lots of unwanted reboots with this image)

**Comment by IMbackK** [comment]
[11:37] <uvos> udevadm hwdb --update
[11:37] <uvos> udevadm trigger

dose that help? ^^

yeah there is something else wrong with that image, plase try 5.11 in devel and report back

**Comment by clort81** [comment]
That fixes it!  Thanks!

Trying to get 5.11 from devel i changed /etc/apt/sources.list.d/hildon-application-manager.list to:
`deb https://maedevu.maemo.org/extras beowulf main contrib non-free droid4
deb-src https://maedevu.maemo.org/extras beowulf main contrib non-free droid4
deb https://maedevu.maemo.org/extras beowulf-devel main contrib non-free droid4
deb-src https://maedevu.maemo.org/extras beowulf-devel main contrib non-free droid4`

Then to prevent HAM from overwriting it i made it immutable.
`chattr +i /etc/apt/sources.list.d/hildon-application-manager.list`

Then I apt update && apt-get linux-image-droid4 but this returns
`linux-image-droid4 is already the newest version (5.10.8-1+2m7)`

What did I do wrong?

**Comment by IMbackK** [comment]
dont modify hildon-application-manager.list

modify /etc/apt/soruces.list by appending 
deb https://maedevu.maemo.org/leste beowulf-devel main contrib non-free droid4

**Comment by clort81** [comment]
New linux-image-droid4 connected to wlan shortly after bootup.  Prior to this i had to retry connecting for 10-20 minutes. 

After installing leste-config-common and leste-config-droid4, i lost the menu which used to appear after clicking power button once (the menu including switch device off).

Reboot didn't fix.

**Comment by MerlijnWajer** [comment]
Can this be closed?

**Comment by buzztiaan** [comment]
FYI, even still in maemo-leste-1.0-armhf-droid4-20230430.img.xz  , the OK+keys are disabled until you manually do these udev steps
