### ISSUE TITLE
Tklock is not a secure lock screen

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#536]
Tklock must grab x11 keyboard input via XGrabKeyboard otherwise any client can break  and bypass the lock screen by Issuing XGrabKey or setting input focus to itself.

This is also a security issue as it allows you to interact with applications beneath the lock screen.

additionaly Tklock must fail to lock the display if XGrabKeyboard fails with AlreadyGrabbed as if tklock atempts to lock the screen with a override_redirect and XGrabKeyboard  window shown the device will end up in an unrecoverable state where the device is locked but it is impossible to interact with it to unlock it. this is also required to inform the user that locking is impossible as another x client allready has a keyboard grab, by failing to lock.

**Comment by MerlijnWajer** [comment]
How would this work for applets like the volume applet? Being able to change the volume while the device is locked is something we want to support at least.

**Comment by IMbackK** [comment]
There is no good solution.

1.  You can send a synthetic event to the applet window but then you need to know the wid of the applet in tklock
2. You can temporally ungrab the keyboard and send a sythetic or xtest event but then you need to deal with some other client grabing the kbd in the mean time, which is a security problem again because pressing buttons might unlock the device
3. You can ajdust the volume at some lower level than x, like in mce.
4. You can switch to wayland

**Comment by freemangordon** [comment]
> How would this work for applets like the volume applet? Being able to change the volume while the device is locked is something we want to support at least.

I second that. Current tklock behaviour is the best compromise between security and functionality IMO. Lets not over-engineer what has been good enough for Fremantle users.

**Comment by MerlijnWajer** [comment]
@freemangordon - tklock currently has problems in the case that was laid out in the first post of the bug report, and we'll need to adress that somehow. Currently the lock screen will crash and reboot the device is a app uses libsdl from -devel.

**Comment by freemangordon** [comment]
what about this https://github.com/maemo-leste/osso-systemui-tklock/blob/master/gp-tklock.c#L72 ?

**Comment by freemangordon** [comment]
BTW, support for volume buttons etc is already there, see https://github.com/maemo-leste/osso-systemui-tklock/blob/master/gp-tklock.c#L213. So, the question is why gdk grab failure case does not work, could be a bug introduced by REing

**Comment by IMbackK** [comment]
the grab dosent work. period. even when no other client is holding a rab tklock isent holding one either.

I see from the code that the solution taken by nokia was to have tklock process the input iteslf and push the event via dbus, thats not great but corrisponds to solution 1 more or less

**Comment by freemangordon** [comment]
ok, lets then see why it doesn't work. I'd rather continue using gdk/gtk once we fix it, than introducing yet another dependency on x11 API

**Comment by freemangordon** [comment]
> @freemangordon - tklock currently has problems in the case that was laid out in the first post of the bug report, and we'll need to adress that somehow. Currently the lock screen will crash and reboot the device is a app uses libsdl from -devel.

May you provide instruction/notes how to simulate the crash?

**Comment by freemangordon** [comment]
Ok, to make it clear - it is not about tklock in general, but about visual tklock. Code currently removes grabs on visual tklock enable. this shall be fixed though.

**Comment by freemangordon** [comment]
Should be fixed by https://github.com/maemo-leste/osso-systemui-tklock/commit/76edf4ddc55dad06b79993da68e6df1f23b7b912, please close once new version hits the repo and fix is verified to be the correct one
