### ISSUE TITLE
Certain ways of invoking the connection dialog result in connection failure

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#539]
Requesting a connection via `python-conic` seems to work, as the UI to select a network is shown, but no matter what network is selected, it always fails immediately (upon selection) with the banner "No saved connections available", and then shows the UI again.

I believe this also happens when connecting to a Wifi network (also when launched from the status applet) fails initially - if you then click "Yes" when it asks to retry, it never works.

Reproduce with:

1. `apt install python-conic`
2. Download https://github.com/maemo-leste/python-conic/blob/master/tests/test_connect.py
3. `python test_connect.py`
4. Click on UI as above

I don't think this bug is in python-conic; since it also happens in other interactions.

**Comment by IMbackK** [comment]
i think this is fixed
