### ISSUE TITLE
Look into gps (gpsd) support

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#57]
I do not recall the current state, but the elinux page has an overview: https://elinux.org/N900

We should figure out what is required to make this work, at some point anyway.

It's pretty separate from most other tasks, so might be a fun project for new comers too.

**Comment by pavelmachek** [comment]
Yep, GPS is relatively easy ... once GSM modem is online. I'm not sure what the exact requirements are... anyway, first steps may be gps2.c (from tui project, gitlab.com/tui/tui), which does not have gpsd integration.

**Comment by MerlijnWajer** [comment]
Nice! Thanks for the info. I do not intend to pick this up right now, but this is very useful going forward.

**Comment by MerlijnWajer** [comment]
So I took the repo from @pavelmachek as mentioned by @ollieparanoid and it seems to work. I got a pretty accurate lock within a minute or so (after bringing the modem online). I suggest to pick this up when we start with the ofono integration (sms and calls). Probably a month from now. But if someone ants to pick this up sooner, feel free.

**Comment by jonwil** [comment]
For full GPS support on the N900 (including SUPL server) we should do the things I put in this post
http://talk.maemo.org/showthread.php?t=100363 (if need be, feel free to copy that list from the post in here)

**Comment by jonwil** [comment]
We have limited reverse engineering for some GPS functionality although per the post I made, its not quite complete and its not 100% accurate (we have the actual structures and constants used when talking to the cellular modem thanks to the pn_location_isi.h mentioned in the above linked thread, lets use that info :)

**Comment by parazyd** [comment]
I'm working on the following:

https://github.com/maemo-leste/liblocation
https://github.com/maemo-leste/location-control
https://github.com/maemo-leste/status-area-applet-location

My current RE of liblocation is still missing the SUPL/Network/Bluetooth specifics, but most of it is in place.

Further, will be looking into location-daemon (and perhaps location-proxy) to figure out next steps.

**Comment by parazyd** [comment]
Closing, as it works now.

There's still some UX stuff that has to be finished, should be in further tickets.
