### ISSUE TITLE
N900 won’t display desktop

### ISSUE THREAD

**Issue by Richard-Rogalski** [maemo-leste/bugtracker#571]
Hello everyone, I’ve had an N900 for quite some time but every time I’ve tried leste I’ve had this weird problem. Just tried again first time in a few months with the latest version (sep 12) and still happening. I boot up, and then a black screen. If I wait long enough before turning the screen on, the lock screen shows up but very wonky. Unlocking returns to a black screen. I’m lost on where to start without being able to switch into tty. 
At boot, when it was setting the date, I did notice it set it to march 2020 for some reason, idk why. Sorry I don’t have much more information for you guys. Thanks for your time

https://user-images.githubusercontent.com/77848941/133005838-af0ded80-94e0-45d7-bba9-dbb60f9a9f9c.MOV

**Comment by IMbackK** [comment]
looks like pvr and /or hildon is crashing. i did relatively recently install the latest image and that did work (i think the image of 2 weeks ago)

**Comment by Richard-Rogalski** [comment]
Just tried the august 29th image, still same problem. This device has always had this problem with leste. Fremantle and postmarket(i3) work fine. I flash it, I boot, and hildon does this. Are there any useful logs etc stored on the device I could post here?

**Comment by IMbackK** [comment]
since those images work fine on other deivces, that really suggests that your device is of an unusual revision or there is hw failure sutch as memory corruption that happens to land in the pvr memory on the leste kernel.

Another possibility is that some cal parameter is causing an issue sutch as device lock or anything else that is shared between fremantle and leste.

please provide kern.log and daemon.log from /var/log

**Comment by MerlijnWajer** [comment]
Maybe this image solves your problems: https://maedevu.maemo.org/images-devel/n900/20220205/

**Comment by Richard-Rogalski** [comment]
I apologize, I completely forgot that I opened this issue!  

I took out this N900 and tried it, and hildon works! However, WiFi doesn't work, and it wasn't when I was running postmarket on it too. Although it works on fremantle.  

This N900 has some really weird hardware problems I'm guessing, although they're only apparent when not on fremantle. 

Thanks for keeping hildon up to date still! You can mark this as closed, I already tried a bunch of WiFi troubleshooting with the postmarket folks to no avail.
Feb 5, 2022, 18:30 by ***@***.***:
