### ISSUE TITLE
N900: Audio is completely quiet

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#58]
Aplay seems to do something, but machine is quiet. Perhaps mixers need to be set up? PostmarketOS has working mixer configuration for N900. I used maemo-kawai-1.0-armhf-n900-20180205 version.

**Comment by parazyd** [comment]
You can see some of the mixer configuration in this doc: https://parazyd.cf/pub/N900/merlijnsdocs.txt

Search for "Audio-out".

Also note that for me `aplay` generated only white noise, but `mpv` could play FLAC and mp3 just fine. Maybe it's something to do with the bitrate.

**Comment by dderby** [comment]
Speaking of audio, what's the current state of PulseAudio in the N900 port of Leste?  Does Leste use the same PA version as Fremantle so that we can use all of the PA modules which haven't yet been RE'd?  Most importantly, is the xprot module already integrated so we can play audio without fear of blowing up our speakers?

**Comment by MerlijnWajer** [comment]
Right now we don't ship any special version of pulseaudio. @freemangordon probably knows best about the current state. And yes, currently, be careful not to blow up your speakers.

**Comment by freemangordon** [comment]
well, the state is the same as it was 3 years ago: https://notabug.org/freemangordon/pulseaudio-nokia/src/fremantle 

However, xprot module should be functional, though it most-probably will need porting to PA version in ascii

**Comment by dderby** [comment]
Thanks for clearing this up.  Sorry for hijacking this issue.  I've opened #62  so we can take the discussion there.

**Comment by MerlijnWajer** [comment]
@parazyd - we can just ship an alsa state file with at least HP enabled? Don't want to enable speakers until we have xprot.

**Comment by MerlijnWajer** [comment]
@parazyd can you pick this one up (at some point)?

**Comment by MerlijnWajer** [comment]
@parazyd I think you just need to ship https://raw.githubusercontent.com/pavelmachek/pmbootstrap/c2ee57f1085a4f4b4fafe277023e5e670c6c1fae/aports/device/device-nokia-rx51/asound.state in `/var/lib/alsa/asound.state`. I've verified that at least then the speakers work. Would like to have HP work too, but that's a lot of settings.

**Comment by pavelmachek** [comment]
HP is headphone -- configuration for making calls?

I have config for that, too :-).

playback.call should be the right one, from
https://github.com/pavelmachek/unicsy_demo/tree/master/audio/nokia-n900
.

**Comment by MerlijnWajer** [comment]
For making calls, or just for porting music player at some point. I assume it is also possible to enable both speakers and headphone at the same time - and then when I get to testing calls, disable speaker?

Thanks for the link. :)

**Comment by parazyd** [comment]
I have committed the asound.state file here: https://github.com/maemo-leste/image-builder/commit/fab7f7df405d7d4eaaceca287dcee9abf35426ca

So we should have it in future images.

**Comment by MerlijnWajer** [comment]
@parazyd - shall we close this issue then?

**Comment by MerlijnWajer** [comment]
I have confirmed that it works fine in the latest images.
