### ISSUE TITLE
icd2 cellular requires accesspointname in gconf to match ofono's

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#585]
I am not sure how they get out of sync, but if they are not in sync, activating through the UI just doesn't seem to work.

**Comment by sicelo** [comment]
i guess fmg squashed this one with https://github.com/maemo-leste/libicd-network-ofono/commit/920429ada67a8ffe7a5384169a8a9ab3c28fa5a8, https://github.com/maemo-leste/libicd-network-ofono/commit/5fb917945ecd85d654ff1f688bac8f3622514a08, and https://github.com/maemo-leste/libicd-network-ofono/commit/ffa7b91ce39fd9e35fbf8db715ff.

close?
