### ISSUE TITLE
osso-xterm selects, instead of scrolling in portrait mode.

### ISSUE THREAD

**Issue by norayr** [maemo-leste/bugtracker#586]
in portrait mode, if you try to touch and scroll up, osso-xterm instead selects text.

**Comment by IMbackK** [comment]
cant reproduce on droid 4

**Comment by MerlijnWajer** [comment]
I also can't reproduce this. However, note that this is a feature if the 'mouse' icon is clicked, or if there is no scroll back.

**Comment by MerlijnWajer** [comment]
Please re-open if you find a way to reproduce this.
