### ISSUE TITLE
Hildon fails to load theme on newer Droid 4 images

### ISSUE THREAD

**Issue by James-Hanson** [maemo-leste/bugtracker#599]
The 2021-12-26 and 2021-12-19 Droid 4 images (from https://maedevu.maemo.org/images/droid4/) fail to load many UI elements (see pictures). Also, osso-pdf-viewer fails to load entirely. I was able to get the 2021-9-26 image working correctly on this device, so I haven't tested any other images.

![PXL_20220101_191445221](https://user-images.githubusercontent.com/75217681/147862503-11ee68d8-d7e6-426b-8cfd-640b5e6eb96a.jpg)

![PXL_20220101_212635875](https://user-images.githubusercontent.com/75217681/147862506-71dd88cd-cc39-4d6e-9fdc-e3cab36e5fb5.jpg)

**Comment by MerlijnWajer** [comment]
Thanks for the bug report. We're aware of the problem and have traced it down recently to a problem in QEMU (or Linux) where readdir() fails to read certain directories, which causes the mime database to not be generated properly, which in turn causes glib to not recognize PNG files.

As a remedy I have set up a 32 bit image builder machine to work around the problem. @parazyd will help one of these days to take into commission and re-generate the images.

**Comment by MerlijnWajer** [comment]
You can (probably) fix most of the problems on your image if you run `update-mime-database` as root.

**Comment by MerlijnWajer** [comment]
I've confirmed this is fixed now on the `bionic` image. The `droid4` will be built over the next few hours. (Don't use the one built on `2022-Jan-02 05:51`, wait for the new one).

Thanks for the bug report, let me know if we can help in any other way(s).

**Comment by MerlijnWajer** [comment]
This one should work: https://maedevu.maemo.org/images/droid4/20220102/
