### ISSUE TITLE
N900: ofonod segfaults

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#61]
(This may be bug in upstream ofonod).

After inserting modules, and providing symlink for ofonod:

```
root@devuan:/home/user/my/ofono/test# rmdir /dev/cmt
root@devuan:/home/user/my/ofono/test# ln -s /sys/bus/hsi/devices/n900-modem/ /dev/cmt
root@devuan:/home/user/my/ofono/test# ofonod -n -d
```

It segfaults:

```
ofonod[3762]: plugins/udev.c:add_isi() interface phonet0
ofonod[3762]: src/modem.c:ofono_modem_register() 0x55b918
ofonod[3762]: src/modem.c:get_modem_property() modem 0x55b918 property Interface
ofonod[3762]: src/modem.c:get_modem_property() modem 0x55b918 property Address
ofonod[3762]: plugins/n900.c:n900_probe() (0x55b918) with phonet0
ofonod[3762]: plugins/nokia-gpio.c:gpio_probe_links() Using /dev/cmt
ofonod[3762]: plugins/nokia-gpio.c:gpio_line_probe() cmt_en: not found
ofonod[3762]: plugins/nokia-gpio.c:gpio_line_probe() cmt_rst_rq: not found
ofonod[3762]: plugins/nokia-gpio.c:gpio_line_probe() cmt_rst: not found
ofonod[3762]: plugins/nokia-gpio.c:gpio_line_probe() cmt_bsi: not found
ofonod[3762]: plugins/nokia-gpio.c:gpio_line_probe() cmt_apeslpx: not found
ofonod[3762]: plugins/nokia-gpio.c:gpio_probe() Modem control GPIO lines are not available
ofonod[3762]: plugins/n900.c:n900_probe() gpio for phonet0: No such device
ofonod[3762]: plugins/upower.c:upower_connect() upower connect
ofonod[3762]: plugins/upower.c:enum_devices_reply() 
ofonod[3762]: plugins/upower.c:parse_devices_reply() 
ofonod[3762]: parse_devices_reply: found 1st battery device: /org/freedesktop/UPower/devices/battery_bq27200_0
ofonod[3762]: plugins/upower.c:enum_devices_reply() parse_devices_reply OK
ofonod[3762]: plugins/upower.c:modemwatch() modem: /n900_0, added: 1
ofonod[3762]: Aborting (signal 11) [ofonod]
```

**Comment by MerlijnWajer** [comment]
I wonder if all the right options in the kernel are enabled. Perhaps we're missing something there?

**Comment by parazyd** [comment]
For reference: https://github.com/maemo-leste/n9xx-linux/raw/pvr-wip/arch/arm/configs/rx51_defconfig

**Comment by pavelmachek** [comment]
Not sure, it might be kernel. But from the log it seems that ofonod got quite far with the init.

There were bugs in upstream ofonod that prevented operation on N900, I'd suggest looking there first.

**Comment by MerlijnWajer** [comment]
OK - do you remember when? I recall I had ofono working on my n900 with Gentoo half a year ago or so. I can check the kernel and ofono version if that helps.

**Comment by MerlijnWajer** [comment]
I reproduced the issue on my N900. I saw this thread: https://github.com/postmarketOS/pmbootstrap/issues/520

Seems like we need to use the latest ofono master.

**Comment by MerlijnWajer** [comment]
Actually, ofono 1.22 should work.

**Comment by MerlijnWajer** [comment]
Our repos now have ofono 1.22 - it does not seem to segfault on start anymore. Can you try again?

**Comment by MerlijnWajer** [comment]
Actually, with nokia-modem probed, it seems to abort in the same way as before.

**Comment by MerlijnWajer** [comment]
When I probe like this: `modprobe nokia-modem pm=1` ofono does not segfault. Our default cmdline sets `pm=0` - not sure why.

@pavelmachek - I think it should work now?

**Comment by MerlijnWajer** [comment]
FWIW I used this setup: https://github.com/postmarketOS/pmbootstrap/issues/520#issuecomment-328076753

**Comment by MerlijnWajer** [comment]
I don't have a sim right now, but I believe these instructions should now just work: http://musicnaut.iki.fi/txt/nokia_modem.txt

**Comment by MerlijnWajer** [comment]
I have tested internet data, works. SMS, works. Started a phone call, other phone dialed. Didn't test any sound.

**Comment by pavelmachek** [comment]
I'm pretty sure sound will not work for voice call (libcmtspeechdata
would be needed for that). If it does, I'll port ofone gui and we'll
have usable phone.

**Comment by pavelmachek** [comment]
Thanks for your help. I'm currently on holidays, so I won't be able to
test it soon.
