### ISSUE TITLE
image-builder offline for more than a month...

### ISSUE THREAD

**Issue by robiwan1** [maemo-leste/bugtracker#612]
Hi guys!
Please reactive the Jenkins image-builder service again, so that all the great improvments can be used...

https://phoenix.maemo.org/view/Images/

br robiwan

**Comment by MerlijnWajer** [comment]
I forgot to start the VMs. But as I did, the machine went down, I'm asking someone go to check on it physically today.

(PS: not on vacation, I'm travelling for work)

**Comment by MerlijnWajer** [comment]
It should all be good now. Thanks for the report.

**Comment by robiwan1** [comment]
...not all. Still no successfull build in jenkins. In all platforms i see a failire in the console output: 

[35m[00m [01;33m[W][00m [22;33mcalled in: mounted devpts[00m
[35m[00m [01;33m[W][00m [22;33mcalled in: Chrooting to execute 'blend-bootstrap-setup' ...[00m
+ exit 1
Build step 'Execute shell' marked build as failure
Skipped archiving because build is not successful
Finished: FAILURE**_

br robiwan

**Comment by robiwan1** [comment]
[image-builder-32bit] offline (https://phoenix.maemo.org/computer/image-builder-32bit/)  (This agent is offline because Jenkins failed to launch the agent process on it. )

**Comment by MerlijnWajer** [comment]
They're migrated to new machines and are all running, fyi
