### ISSUE TITLE
no ambient light sensor driver loaded on pinephone

### ISSUE THREAD

**Issue by norayr** [maemo-leste/bugtracker#613]
on pinephone, with kernel 5.15.13, the ambient light sensor is not detected.

in directory /sys/bus/iio/devices no illuminance files created:

`root@devuan-pinephone:/sys/bus/iio/devices# find . | grep -i lum`

there should be `in_illuminance_input` file, or `in_illuminance_raw` and `in_illuminance_scale` file.

it was there but at some point disappeared.

on droid4 with 5.15.2 kernel it's okay. cannot check other devices.

**Comment by nxdefiant** [comment]
Might be related: https://github.com/maemo-leste/pine64-kernel/pull/2

**Comment by norayr** [comment]
so i flushed the new image.
it had the same 5.15.13 image.
it did not have many apps in the  app manager, because of the key issues.
i already knew it, made apt-get dist-upgrade.

then i also got a new kernel.

with 5.15.21 this issue does not exist.

so thank you, i guess this issue may be closed. i'll close it.

as a sidenote, most of the people who come to maemo-leste today, won't see all available applications in the list. so i hope the new image will be generated asap.
