### ISSUE TITLE
Volume up key no longer triggers Hildon Input Method on Pinephone

### ISSUE THREAD

**Issue by jvanwouw** [maemo-leste/bugtracker#618]
Reproduced on May 22 (without devel repo enabled) and May 29 (with devel repo enabled) images. Works neither in GTK3 apps (e.g. Firefox) nor Qt5 apps (FeatherNotes). Used to work reliably (in Firefox at least) on the Pinephone as of November/December 2021.

**Comment by IMbackK** [comment]
Hi,

Could you check if /usr/share/hildon-desktop/shortcuts.ini exists on your device and looks like this: https://github.com/maemo-leste/leste-config/blob/master/leste-config-pinephone/usr/share/hildon-desktop/shortcuts.ini.leste

Also do you have the vkb acctivated? settings->text input->use virtual keyboard

dose "dbus-send --dest=org.maemo.him / org.maemo.him.set_visible boolean:true" rasie the vkb for you?

dose running "DISPLAY=:0.0 xev" over ssh and pressing vol up or vol down while the device is unlocked generate the keycodes for the volume buttons?

**Comment by IMbackK** [comment]
could someone please try and see if this is still a problem?

**Comment by IMbackK** [comment]
this issue describes intended behavior, if the volume applet is installed it overrides the volume button raising the keyboard with change volume instead.
