### ISSUE TITLE
Droid4: identify batterytype to get charger to work for HV

### ISSUE THREAD

**Issue by buzztiaan** [maemo-leste/bugtracker#621]
I modified the kernel to just always assume its using a EB41 and charge at 4.35V

1183 mAh with the original kernel after training/calibrating a couple times.
1357 mAh with my modified kernel. (will throw on github soon)

about 15% more batterylife , making my days a lot less 'where's my USB powersource'' ;)

**Comment by buzztiaan** [comment]
imho -best- would be to have the cpcap-battery.c code actually detect the right battery, and modify MIN MAX voltages and charge voltages accordingly 

-afaik- nvmem interface for that is broken atm. @IMbackK might know more?

**Comment by buzztiaan** [comment]
BE WARNED

> 13:24:53 < Wizzup> yeah we decided not to do it after we all had several droid4's with batteries as balloons
> 13:25:12 < buZz> with EB41s ?
> 13:27:31 < buZz> or as in, accidentally had the 4.35V charging on a normal lipo that wasnt HV?
> 13:33:23 < Wizzup> no, just having it on 4.35V for proloned times seems to really decrease life time of battery
> 13:33:46 < buZz> oh, right, yeah i assume so, its a battery from 2012 anyway ;)
> 13:34:26 < buZz> its on 4.35V for almost no time though :P charging voltage is 4.35V but when it reaches that it almost directly declares 100% and drops to ~4.3V
> 13:37:27 < buZz> maybe i can try charging only to 4.31V instead, see what the difference in mAh will be
> 14:33:09 < Wizzup> buZz: right but I often keep my d4 plugged in over night
> 14:33:23 < Wizzup> and then suddenly it's 25% of the time (yeah 6 hr sleep :p) on 4.35V
> 14:33:41 < Wizzup> in any case, open a pr and we can discuss the best way

I'll clean up my mod and PR soonish

**Comment by buzztiaan** [comment]
(PR wont be for merging., dont worry, i dont plan to blow up any phone beside my own ;) )

**Comment by buzztiaan** [comment]
the kernel now seems to try to identify the battery to be 89-500029ba0f73 (as seen on https://github.com/maemo-leste/droid4-linux/blob/maemo-5.18/drivers/power/supply/cpcap-battery.c#L426)

But my two EB41 identify as 89-5000385c064b and 89-50003a31240b

nvmem dumps provided here ( pulled from /sys/bus/w1/devices/89-*/89-*/nvmem , after commenting out the omap_hqd from /etc/modprobe.d/blacklist-idle.conf )

https://space.nurdspace.nl/~buzz/89-5000385c064b.nvmem
https://space.nurdspace.nl/~buzz/89-50003a31240b.nvmem

**Comment by IMbackK** [comment]
this is on its way upstream
