### ISSUE TITLE
Image creation failed...

### ISSUE THREAD

**Issue by robiwan1** [maemo-leste/bugtracker#623]
Please update the host key in the build system (jenkins), because the upload of the latest image to maedevu.maemo.org FAILED for N900 (and others)!

````
+ ssh amprolla@maedevu.maemo.org -- mkdir -p images/n900/20220709
Host key verification failed.
+ exit 1
Build step 'Execute shell' marked build as failure
Skipped archiving because build is not successful
Finished: FAILUR
```

br`

**Comment by MerlijnWajer** [comment]
Will take a look, thanks.

**Comment by MerlijnWajer** [comment]
I see what the problem is, I'll try to fix it this week.

**Comment by MerlijnWajer** [comment]
Should be solved now, thanks for reporting.

**Comment by MerlijnWajer** [comment]
Ok, the meta package doesn't want to install, will fix that, but unrelated to the prev errors.
