### ISSUE TITLE
X Terminal window title does not revert back when disconnecting from ssh

### ISSUE THREAD

**Issue by eloydegen** [maemo-leste/bugtracker#624]
When connecting to some ssh server, by executing `ssh user@host`, the title of the X terminal window will change from `X Terminal` to `user@host: ~`. However, when disconnecting this session (either by `exit` or `ctrl+d`), it won't revert back to the former window title.

**Comment by IMbackK** [comment]
hmm weird, cant reproduce this on my end.

What device are you using? are you on devel or stable branch?

**Comment by eloydegen** [comment]
@IMbackK Not sure what happened, but I can't reproduce my issue either. I'll close this issue for now, thanks for trying to reproduce it. I used the latest image that I downloaded yesterday on the Droid 4.
