### ISSUE TITLE
Increase the filesystem size of the images by a few hundred megabytes to allow updates to fit

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#625]
We might have to eventually decide if we want to run `/etc/expandcard.sh` by default, or remind the user about it in a better way.

**Comment by IMbackK** [comment]
For what its worth, salutem DOSE inform the user about /etc/expandcard.sh

**Comment by MerlijnWajer** [comment]
This is done for chimaera
