### ISSUE TITLE
Number display feedback on the Calculator app (pinephone)

### ISSUE THREAD

**Issue by auandaoirekaska** [maemo-leste/bugtracker#629]
This is low priority but in landscape mode when you use the default calculator that comes with the image, it only shows the numbers/symbols you type after you press the key following it. If the numbers and symbols text input would show up as the keys are typed that would be a better behavior.

**Comment by IMbackK** [comment]
Could you make a screenshot of this issue? im not seeing it on droid 4

**Comment by auandaoirekaska** [comment]
https://odysee.com/VID_20220909_102503:2

**Comment by freemangordon** [comment]
Do you use the -devel repo? If not, could you enable it and re-test? There were lots of fixes recently which are still not in -stable.

**Comment by auandaoirekaska** [comment]
> Do you use the -devel repo? If not, could you enable it and re-test? There were lots of fixes recently which are still not in -stable.

Good question, I was on stable. I have now added the -devel repo in my apt sources list, I did not remove the stable one (is that how I'm supposed to do it?). I then apt updated and upgraded, and tried the calculator again. I had to reboot for it to work, but that issue is now resolved.

Thanks!
