### ISSUE TITLE
N900 image builder dependency unmet...

### ISSUE THREAD

**Issue by robiwan1** [maemo-leste/bugtracker#630]
Hi!

I have noticed, that the **leste-image-n900** is NOT build for mor than 2 month now, because of:

`"unmet dependencies: hildon-meta-n900 : Depends: linux-image-omap but it is not installable"
`

Could anybody have a look at this issue?
Thanks a lot!

br
robian

**Comment by MerlijnWajer** [comment]
I've fixed the image builder VM for now, now trying to build the n900 image, let's see if it still fails the same way.

**Comment by MerlijnWajer** [comment]
It looks like somehow `linux-image-omap` wasn't in stable repos anymore, so I'm rebuilding the package now.

**Comment by MerlijnWajer** [comment]
I think the issue should be resolved, the next image should build within the next few hours. Thanks for the report!

**Comment by MerlijnWajer** [comment]
Looks like one finally built successfully.
