### ISSUE TITLE
Package patched X server for droid4

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#64]
This patch needs to be applied, at least until/if it is applied in devuan/debian

https://lists.x.org/archives/xorg-devel/2018-February/055793.html

Then the droid4 should work.

**Comment by parazyd** [comment]
So, I've only built xserver-xorg-core, as that's what I think is patched.
http://maedevu.maemo.org/leste/pool/droid4/x/xorg-server/

Please try just a simple update on your droid4 and let me know if it gets pulled in - and if it works of course.

**Comment by MerlijnWajer** [comment]
Yes, xorg-server-core is the one that matters. We'll also need the appropriate debug and dev packages.

**Comment by MerlijnWajer** [comment]
Will test later today.

**Comment by MerlijnWajer** [comment]
Confirmed - works.
