### ISSUE TITLE
PinePhone: App Manager: allow Apps to be installed when using Wired networking

### ISSUE THREAD

**Issue by dozylynx** [maemo-leste/bugtracker#642]
Steps:
1. Disconnect the phone from Wifi. PinePhone has a dedicated hardware switch for doing this. (Or unplug the router, forget access credentials, etc...)
2. Boot the phone connected to a USB dock that has a wired ethernet connection.
3. Enable the wired ethernet connection at the root prompt: ie. bring up the interface (using ifconfig or similar) and assign an IP address (static or DHCP, whichever to suit your network).
4. In the UI, run "App.manager"

Observed behaviour:
The manager insists on connecting Wifi before Downloads can be accessed. This prevents access to any of the Apps in the Application manager.

In Settings -> Connectivity -> Internet connections, Wired is not detected or offered as an option.

Expected behaviour: it should be possible to use the Application Manager with a connected Wired interface once the interface is up.

An earlier report of a similar request from 2009 is here:
https://talk.maemo.com/showthread.php?t=35073
Is the underlying issue more accurately described as missing support for Wired networking in Connection Manager?

**Comment by sicelo** [comment]
you should be able to install `connui-dummy` then select Dummy Network in the connections.

**Comment by IMbackK** [comment]
yes that works as a workaround, however @dozylynx is correct in the assumption that the root of the problem is that icd dosent support wired connections.

**Comment by dozylynx** [comment]
closing as workaround is available and root issue is in a different component
