### ISSUE TITLE
Port Maemo Leste to Chimaera 

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#644]
sBelow is a list of all packages in Maemo Leste. We need them all ported to `chimaera` / `bullseye`. This issue is here keep track of the porting progress.

Porting / building of core packages:

- [x] maemo-keyring
- [x] libcal
- [x] iphbd
- [x] gtk
- [x] insserv (https://github.com/maemo-leste-upstream-forks/insserv/commits/maemo/chimaera - upstream 1.22 has our fix)
- [x] clutter-0.8
- [x] libmatchbox2
- [x] libhildonmime (PR: https://github.com/maemo-leste/libhildonmime/pull/2)
- [x] cityinfo
- [x] clockd (PR https://github.com/maemo-leste/clockd/pull/7)
- [x] libosso
- [x] icd2-osso-ic-dev
- [x] libconic (needed https://github.com/maemo-leste/libconic/commit/8dadd88d18d753aeeed8d48984966b5cb5d8d2a1, https://github.com/maemo-leste/libconic/commit/b7896f75cd5e2da63655e0ac5103d0df345eaf97, https://github.com/maemo-leste/libconic/commit/9fa5dd501c713fec3090b44f31b5f95b3d509234, https://github.com/maemo-leste/libconic/commit/67667165a7274658f5c5c2205a6ff877fafffa06)
- [x] osso-systemui-dbus-dev
- [X] libdsme (Needed https://github.com/maemo-leste/libdsme/commit/bef88abda97bde15153fc294ebc1658850ddcea1 https://github.com/maemo-leste/libdsme/commit/a13e01eb5cbf4c59b04488f934da0f42cc0c7491)
- [x] statusbar-alarm-dbus-api
- [x] libhildon
- [ ] libhildon3 (skip for now)
- [x] maemo-system-services (Needed python gconf import)
- [x] osso-af-utils
- [x] osso-af-startup
- [x] hildon-initscripts
- [x] osso-af-settings
- [x] ke-recv-extra (Needs https://github.com/maemo-leste/ke-recv-extra/commit/2ae5b70b2c90788def5a6c2c479f9ad71cefbaa2)
- [x] clipboard-manager
- [x] libhildondesktop
- [x] alarmd (https://github.com/maemo-leste/alarmd/pull/2 https://github.com/maemo-leste/alarmd/pull/2)
- [x] maemo-launcher (https://github.com/maemo-leste/bugtracker/issues/298 https://github.com/maemo-leste/maemo-launcher/commit/fd8269193e4f2fdbb85baa1b6c26d3c78e6667c8)
- [x] profiled
- [x] profilesx (needs `libhildonfm2-dev`, `hildon-control-panel-dev`)
- [x] sapwood
- [x] hildon-theme-cacher
- [ ] hildon-theme-alpha (Imported for now.)
- [ ] hildon-theme-beta
- [ ] hildon-theme-devel
- [x] osso-icons
- [x] ui-fonts
- [x] dsme (https://github.com/maemo-leste/dsme/pull/6 https://github.com/maemo-leste/dsme/commit/65805d5d02bd6a2472d780dfe08715889b6c90df https://github.com/maemo-leste/dsme/commit/27a79866ee04b0843fc2f13df9944bbd89f114cc)
- [x] osso-systemui (https://github.com/maemo-leste/osso-systemui/pull/2)
- [x] osso-systemui-powerkeymenu
- [x] osso-systemui-tklock
- [x] osso-systemui-modechange
- [x] osso-systemui-devlock
- [x] osso-systemui-splashscreen-dev
- [x] osso-systemui-modechange-dev
- [x] libdevlock
- [x] osso-app-killer
- [x] codelockui
- [x] hildon-control-panel
- [x] osso-applet-display
- [x] libplayback
- [x] hildon-plugins-notify-sv
- [x] osso-systemui-alarm
- [x] mce **(without our upower atm)**
- [x] osso-bookmark-engine
- [x] epeg
- [x] hildon-thumbnail
- [x] libhildonfm
- [x] hildon-home
- [x] hildon-desktop (https://github.com/maemo-leste/hildon-desktop/pull/20)
- [x] osso-applet-notificationlight
- [x] osso-applet-devicelock
- [x] hildon-status-menu
- [x] osso-xterm
- [x] icd2 https://github.com/maemo-leste/icd2/pull/11#event-7913385869
- [x] theme-default-settings
- [x] hildon-base
- [x] hildon-meta
- [x] leste-config (https://github.com/maemo-leste/leste-config/commit/1d08e6cbaa4eb18d07fc7a29423ac0db1e98d536 and https://github.com/maemo-leste/leste-config/commit/4b8851518d8d523065dc1bb12df8d368de9d0af2)
- [x] eg25-manager
- [x] pinephone-modem-config
- [x] hildon-connectivity-meta
- [x] status-menu-applet-profiles
- [x] xorg-server (https://github.com/maemo-leste-upstream-forks/xorg-server/commits/maemo/chimaera)
- [ ] alsa-lib (skip for now)
- [ ] alsa-utils (skip for now)
- [ ] telepathy-glib (might be able to skip, we only had a memory leak fixed, which was I think upstreamed)
- [ ] libsdl2 (skip for now)
- [x] status-area-applet-battery
- [x] ofono
- [x] atinout
- [x] connui-common
- [x] maemo-security-certman (https://github.com/maemo-leste/maemo-security-certman/commit/ad09b06d0aff368a8c1b74561c877877fbea70be)
- [x] libcomapp
- [x] maemo-security-certman-applet
- [x] connui-internet
- [x] hildon-status-bar-usb
- [x] libicd-network-dummy
- [x] libicd-provider-dummy
- [x] connui-dummy
- [x] libicd-network-usb
- [x] icd2-settings-default
- [x] libusbgx
- [x] wl1251-cal
- [x] maemo-multimedia-tone-generator
- [x] libicd-network-ipv4
- [x] libconbtui
- [x] connui-wlan
- [x] libicd-network-wpasupplicant (https://github.com/maemo-leste/libicd-network-wpasupplicant/commit/c661d4e31cad5e887b3f2ebccd6497b22f9d9715)
- [x] status-area-orientationlock-applet
- [ ] sunxi-linux
- [x] upower (rebased)
- [x] libscconf
- [x] hildon-input-method-framework
- [x] hildon-input-method
- [x] libimlayouts
- [x] libimengines
- [x] hildon-im-vkbrenderer3
- [x] hildon-input-method-configurator
- [x] hildon-input-method-plugins
- [x] osso-applet-textinput
- [x] hildon-input-meta
- [x] mafw
- [x] mafw-shared (https://github.com/maemo-leste/mafw-shared/commit/5208ca6cbf3dca47c42c87551b4167f1b9a63ce5 https://github.com/maemo-leste/mafw-shared/commit/1c6a65da65d2c4299bdb4ed74496956d46b14b19 https://github.com/maemo-leste/mafw-shared/commit/3d1693ecb7e33b19767c579943f11c46099eae61 https://github.com/maemo-leste/mafw-shared/commit/666c17a01f57e61290a705c6df07912b0454839b https://github.com/maemo-leste/mafw-shared/commit/ed462666cf5765ee517c79455176d63f646c071a)
- [x] mafw-iradio-source
- [ ] mafw-upnp-source
- [x] hildon-usb-gadgets (https://github.com/maemo-leste/hildon-usb-gadgets/commit/de8c860d947031da3a8fea6b113e502f19ff6f3f)
- [x] ke-recv
- [x] osso-calculator-engine
- [x] libcmtspeechdata (https://github.com/maemo-leste/libcmtspeechdata/commit/554448c2d5287bd4afd2d2018cee06aeb9f7a8e5)
- [x] droid4-linux
- [x] pine64-kernel
- [x] pine64-uboot
- [x] mapphone-kexecboot-config
- [x] xf86-video-omap
- [x] firmware-ti-bluetooth
- [ ] qrtr (pocophone, skip for now)
- [ ] rmtfs (pocophone, skip for now)
- [ ] pd-mapper (pocophone, skip for now)
- [ ] tqftpserv (pocophone, skip for now)
- [ ] linux-beryllium  (pocophone, skip for now)
- [x] connui-cellular
- [ ] libofono (skip for now, seems not in use)
- [x] libicd-network-ofono
- [x] libglibutil
- [x] libgofono
- [x] hildon-notify
- [x] statusbar-alarm
- [x] rtcom-eventlogger
- [x] rtcom-eventlogger-ui (https://github.com/maemo-leste/bugtracker/issues/676 NEEDS FIXING)
- [x] rtcom-eventlogger-plugins (https://github.com/maemo-leste/rtcom-eventlogger-plugins/commit/6e1fa6ea8628718cb3e5f3fdeda0aee62905f0a3)
- [x] osso-abook
- [x] osso-addressbook (https://github.com/maemo-leste/osso-addressbook/commit/055031f58b4d3bb8eed670379c0c45679018b346)
- [x] osso-abook-home-applet
- [x] pygtk
- [x] python-hildon (needs notify-python import https://github.com/maemo-leste-upstream-forks/notify-python)
- [x] python-osso (https://github.com/maemo-leste/python-osso/commit/7f3cc21d07dd7e4b6c4f51ef4105d6bca261a3c1 https://github.com/maemo-leste/python-osso/commit/f43568cb3676512cf21a97af0efef9c7c1a85acf  and imported cython)
- [x] python-alarm (https://github.com/maemo-leste/python-alarm/commit/361276551cd1f7127b746a5cb4d6376be78be0a7)
- [x] python-hildondesktop
- [x] hildon-application-manager (https://github.com/maemo-leste/hildon-application-manager/commit/8d4a6193c9c25a64b2155dd3a71cf4189615aee7 https://github.com/maemo-leste/hildon-application-manager/commit/c9a3b01f3c39990df33ae5e02928327df50f8615 https://github.com/maemo-leste/hildon-application-manager/commit/d9e3230c970a66589607a18bac979b8da9ea7b42 https://github.com/maemo-leste/hildon-application-manager/commit/d550767bb946723079e87d3c142dcfc985598da6 https://github.com/maemo-leste/hildon-application-manager/commit/fb07a532ddb8fa3f96880188e97e242f3e2c35cc https://github.com/maemo-leste/hildon-application-manager/commit/5ce3388cabe671aff2627818b94616f86a5376de https://github.com/maemo-leste/hildon-application-manager/commit/a5b0591a768155087ffa908da01c609e53c2012b https://github.com/maemo-leste/hildon-application-manager/commit/7acb76a488701bec05fd97d2eca70c06f8514b25)
- [x] hildon-application-manager-settings-standard (https://github.com/maemo-leste/hildon-application-manager-settings-standard/commit/c608184bb22a4b755d4ff1447d72b8a51b0ec652)
- [x] osso-pdf-viewer
- [x] iso-codes-locale-resolver
- [x] libdrm (mesa dep)
- [x] directx-headers (mesa dep)
- [x] libglvnd (not sure if we need it, but our version is newer anyway, so let's use it, also hildon-meta-droid4 depends on our newer version)
- [x] mesa (needs rebase/port, need our own for GLES1 and PVRSGX)
- [x] charge-mode
- [x] fbkeyboard
- [x] sdlgles
- [ ] gl4es (skip for now?)
- [x] osso-games-startup
- [x] hildon-games-wrapper
- [x] hildon-control-panel-personalisation
- [x] hildon-theme-tools
- [x] hildon-theme-layout
- [x] osso-applet-languageregional
- [x] droid4-pm
- [ ] n900-pm
- [x] droid4-battery-calibration
- [x] xkb-data (https://github.com/maemo-leste-upstream-forks/xkb-data/tree/maemo/chimaera)
- [x] qtstyleplugins (https://github.com/maemo-leste/qtstyleplugins/commit/709b6d058aaa196a6af7a6ce951bc675b12595e4)
- [x] qt-platform-maemo (needs rebase/port)
- [x] ti-utils-wilink6 (https://github.com/maemo-leste/ti-utils-wilink6/commit/99b7397e5b95a7badac2159acfb8159706518d56)
- [x] droid4-wlanconfig
- [x] maemo-input-sounds (https://github.com/maemo-leste/maemo-input-sounds/commit/ab5ba88aebb9e6a63612e3714ed7ec99a78dfca5)
- [x] maemo-audio
- [x] iio-sensor-proxy (rebase?)
- [x] dbus-scripts
- [x] libgq-gconf
- [x] clock-ui
- [x] evolution-data-server (rebased patches https://github.com/maemo-leste/evolution-data-server/tree/maemo/chimaera)
- [x] syncevolution (https://github.com/maemo-leste/syncevolution/tree/maemo/chimaera)
- [x] eds-backend-telepathy (https://github.com/maemo-leste/bugtracker/issues/675, https://github.com/maemo-leste/eds-backend-telepathy/commit/b96f28389554f2a1d39d6b8eeef3bd1a66e701fc and https://github.com/maemo-leste/eds-backend-telepathy/commit/5be241157c3c344b80ca39e75b63d4c22a282cbf)
- [x] calendar-backend
- [x] qalendar
- [x] osso-calculator
- [x] clock
- [x] hildon-time-zone-chooser
- [x] applet-datetime
- [x] location-control
- [x] liblocation
- [x] location-daemon
- [x] location-status
- [x] location-ui
- [x] python-location (https://github.com/maemo-leste/python-location/commit/d1e89fad6624c027a11d1317d493ff8efc144ecb https://github.com/maemo-leste/python-location/commit/5be82c0e56def5470ce4b7ae6c460aeaae8bfa87)
- [x] python-conic
- [x] python-mafw
- [x] osso-systemui-splashscreen
- [x] gps-nokia-n900
- [x] pkg-gpsd (https://github.com/maemo-leste-upstream-forks/pkg-gpsd/commits/maemo/chimaera)
- [x] salutem
- [x] sphone
- [x] conversations
- [x] libicd-tor
- [x] tor-network-applet
- [x] libicd-wireguard (https://github.com/maemo-leste/libicd-wireguard/commit/75dfe6a466199bb64058bf42b567bb933721978b, https://github.com/maemo-leste/libicd-wireguard/commit/b227076d74d007ee7ebe6e2e7a85a07e67ff5fd4)
- [x] wireguard-network-applet
- [x] libicd-openvpn
- [x] openvpn-network-applet
- [x] wpeditor
- [x] calendar-ui-widgets
- [x] libmodest-dbus-client
- [x] tinymail (https://github.com/maemo-leste/tinymail/commit/35a1cd7895376c60541226e6aee4744e2746afb7)
- [x] gtkhtml3
- [x] modest (https://github.com/maemo-leste/modest/commit/df9b6478d6ab5b237d0fdc68e39b14483d994aff)
- [x] glib (upstream, maybe skip, maybe rebase)
- [ ] wireguard-tools (skip?)
- [ ] gnome-contacts (upstream, maybe skip, maybe rebase)
- [x] sgx-ddk-um
- [x] maemo-kernel-config
- [x] maemo-statusmenu-volume
- [x] libQuotient
- [x] telepathy-tank
- [x] linux-firmware-pine64-rtl8723-bt
- [x] telepathy-gabble (maybe rebase)
- [x] libaccounts
- [x] rtcom-accounts-ui
- [x] rtcom-accounts-ui-client
- [x] rtcom-accounts-plugins
- [x] rtcom-presence-ui
- [x] cellulard
- [x] iphb-dkms

Notes:

- Imported mce-dev for now using `reprepro -b /srv/repository/leste includedeb chimaera /srv/repository/leste/pool/main/m/mce/mce-dev_1.10.3+2m7_amd64.deb /srv/repository/leste/pool/main/m/mce/mce-dev_1.10.3+2m7_armhf.deb /srv/repository/leste/pool/main/m/mce/mce-dev_1.10.3+2m7_arm64.deb
` (due to circular deps)

Image builder changes: https://github.com/maemo-leste/image-builder/commits/chimaera

Issues:

- [x] Pulseaudio breakage https://github.com/maemo-leste/bugtracker/issues/685

FINALLY:

- [ ] Comment and remove any jobs we skipped, as we clearly don't need them anymore
- [ ] Archive unused repositories and upstream-fork repositories

Obsolete packages:

* ti-omap3-sgx (skip)
* xf86-video-pvrsgx (skip)
* pvr-omap4 (skip)
* hildon-desktop-rotation-support (skip)
*  n9xx-linux
* rtl8723cs (does not exist)

Obsolete forks:

* wpasupplicant (skip, we now have a new enough version)
* libsdl1.2 (not necessary anymore)
* libdri2 (I think this might be mali binary driver related)

* gnome-python (we had this only for gconf, and this is a separate pkg now)

Unused, but probably still want (just not in use currently):

* pulse-core (needs rebasing, skip for now)
* pulseaudio-modules-nemo (skip for now)
* pulseaudio-module-cmtspeech-n9xx (skip for now)
* pulseaudio-policy-enforcement (skip for now)
* libtrace-ohm (skip for now)
* ohm (skip for now)
* libprolog (skip for now)
* libdres-ohm (skip for now)
*ohm-rule-engine (skip for now)
* policy-settings-common (skip for now)
* libresource (skip for now)
* ohm-plugins-misc (skip for now)

**Comment by MerlijnWajer** [comment]
Translations:

- [ ] as-config-applet-l10n
- [ ] calendar-l10n
- [ ] hildon-application-manager-l10n
- [ ] hildon-common-strings-l10n
- [ ] hildon-control-panel-l10n
- [ ] hildon-control-panel-personalisation-l10n
- [ ] hildon-fm-l10n
- [ ] hildon-input-method-l10n
- [ ] hildon-libs-l10n
- [ ] hildon-status-bar-usb-l10n
- [ ] ke-recv-l10n
- [ ] libsignonui-l10n
- [ ] maemo-af-desktop-l10n
- [ ] maesync-l10n
- [ ] mediaplayer-l10n
- [ ] modest-l10n
- [ ] modest-nokiamessaging-plugin-l10n
- [ ] osso-addressbook-l10n
- [ ] osso-applet-accounts-l10n
- [ ] osso-applet-certman-l10n
- [ ] osso-applet-device-l10n
- [ ] osso-applet-memory-l10n
- [ ] osso-applet-screencalibration-l10n
- [ ] osso-applet-textinput-l10n
- [ ] osso-backup-l10n
- [ ] osso-browser-ui-l10n
- [ ] osso-calculator-ui-l10n
- [ ] osso-camera-ui-l10n
- [ ] osso-cities-l10n
- [ ] osso-clock-l10n
- [ ] osso-connectivity-ui-l10n
- [ ] osso-countries-l10n
- [ ] osso-display-l10n
- [ ] osso-dsm-ui-l10n
- [ ] osso-filemanager-l10n
- [ ] osso-fm-transmitter-l10n
- [ ] osso-games-l10n
- [ ] osso-imageviewer-ui-l10n
- [ ] osso-location-ui-l10n
- [ ] osso-notes-l10n
- [ ] osso-pdf-viewer-l10n
- [ ] osso-powerup-shutdown-l10n
- [ ] osso-profiles-l10n
- [ ] osso-rss-feed-reader-l10n
- [ ] osso-sharing-ui-l10n
- [ ] osso-sketch-l10n
- [ ] osso-statusbar-presence-l10n
- [ ] osso-statusbar-sound-l10n
- [ ] osso-suw-l10n
- [ ] osso-system-lock-l10n
- [ ] osso-tutorial-l10n
- [ ] osso-tv-out-l10n
- [ ] osso-uri-l10n
- [ ] policy-l10n
- [ ] rtcom-call-ui-l10n
- [ ] rtcom-messaging-ui-l10n
- [ ] leste-l10n-maint

**Comment by MerlijnWajer** [comment]
List of packages that we "just" import (only `_all.deb`):

- [ ] TBD

**Comment by MerlijnWajer** [comment]
Extras:

- [ ] surf2
- [ ] binaryclock-plugin
- [ ] wifi-signal-applet
- [ ] simple-brightness-applet
- [ ] brainparty
- [ ] brainparty-data
- [ ] scummvm
- [ ] crazyparking
- [ ] osso-mahjong
- [ ] mypaint
- [ ] uae4all
- [ ] sojourner
- [ ] pyfuelpad
- [ ] 9x9-sudoku
- [ ] hildon-theme-marina
- [ ] miku-theme
- [ ] hildon-theme-matrix
- [ ] hildon-theme-okuda
- [ ] maeotp
- [ ] quicknote
- [ ] photolightmeter
- [ ] personal-ip-address
- [ ] countdowntimer
- [ ] mihphoto
- [ ] sigstoped
- [ ] qsigstoped
- [ ] lirios-cmake-shared
- [ ] lirios-fluid
- [ ] lirios-calculator
- [ ] lirios-files
- [ ] unicsy_demo
- [ ] dorian
- [ ] iio-uinput
- [ ] min
- [ ] cal-home-widget
- [ ] desktop-cmd-exec
- [ ] hildon-theme-maemo-org
- [ ] maep
- [ ] cloudgps
- [ ] syncevolution-frontend
- [ ] zkgroup
- [ ] signald
- [ ] libpurple-signald
- [ ] googletest
- [ ] cpu-features
- [ ] sdbus-cpp
- [ ] anbox-image
- [ ] anbox
- [ ] sfeed
- [ ] sfeed-curses
- [ ] aiohttp-socks
- [ ] aiorpcx
- [ ] python-attrs
- [ ] python-ecdsa
- [ ] zbar
- [ ] libsecp256k1
- [ ] protobuf
- [ ] electrum
- [ ] Trojita
- [ ] sync-time-now-widget
- [ ] gpsrecorder
- [ ] qshot
- [ ] braek
- [ ] modrana
- [ ] gpxsee
- [ ] wifi-switcher
- [ ] qtwebbrowser
- [ ] hamsterfiler
- [ ] oricutron
- [ ] lagrange
- [ ] openlara
- [ ] neverball-gles
- [ ] cssufeatures
- [ ] maefat
- [ ] leafpad
- [ ] msid
- [ ] shermans-aquarium-maemo
- [ ] live-wallpaper
- [ ] mstardict

**Comment by sicelo** [comment]
`maeotp` built successfully under Chimaera -  https://phoenix.maemo.org/job/maeotp-binaries/
