### ISSUE TITLE
N900: virbation is broken

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#682]
On kernel 6.1:
`mce: evdevvibrator: No usable force feedback device available, vibration disabled.`

Unfortionally mce is correct here, there is no force feedback capable device available in /dev/input/ . im not sure what driver is supposed to provide this on n900 but it went missing/stopped probing at some point, since i dont use the n900 im not sure when this was.

**Comment by sicelo** [comment]
`CONFIG_INPUT_TWL4030_VIBRA`

**Comment by IMbackK** [comment]
added to kernel
