### ISSUE TITLE
Unclear how to enable Pinephone modem

### ISSUE THREAD

**Issue by vandys** [maemo-leste/bugtracker#695]
Latest build, latest Modem firmware, Wifi works.  Modem is present, can talk to it on USB2.  ofonod is present, but nothing appears to pick up the modem to make phone calls, texts, or mobile data possible?  I installed sphone, and it tells me there's no ModemManager on the dbus.

The release notes claim phone calls are possible, but I don't see how.  I don't see the obvious config switches anywhere to turn on mobile networks, and searches for relevant terms mostly show up obviously irrelevant comments from 2010.

So this is probably just a doc bug.  I didn't find anybody at IRC, sorry for adding noise in the bug DB!

**Comment by freemangordon** [comment]
> So this is probably just a doc bug. I didn't find anybody at IRC, sorry for adding noise in the bug DB!

That is strange, which IRC channel did you try?

**Comment by vandys** [comment]
Aha, my ircII client landed me on a Debian IRC server.  Retrying at irc.libera.chat now...

**Comment by MerlijnWajer** [comment]
The `beowulf` images by default probably still don't have any cellular packages yet. There are some versions of this in `beowulf-devel`, and of course the upcoming `chimaera` release will have it all enabled by default. What image did you dd?

**Comment by vandys** [comment]
If the filename isn't sufficient, I can dig up the download location, too:

maemo-leste-1.0-arm64-pinephone-20230115.img.xz

**Comment by MerlijnWajer** [comment]
You can try this image: https://maedevu.maemo.org/images-devel/pinephone/20230106-chimaera/

This is the unreleased version that does have cellular stuff in it. Best to `apt-get update` and `apt-get dist-upgrade` first thing. Then you'll be more or less on the code that was discussed in the latest news post: sphone works, conversations is not ready yet, there is no telepathy calls yet, sms works only via sphone currently.

**Comment by vandys** [comment]
Thanks!  While there are various problems, this image certainly recognizes my modem.

**Comment by MerlijnWajer** [comment]
Great, please follow up on any problems you're running into. I'm sure there's many, but there might be some that we're not aware of yet.
