### ISSUE TITLE
input method is broken for 'enter' key

### ISSUE THREAD

**Issue by norayr** [maemo-leste/bugtracker#699]
here is the video that illustrates the issue: https://toobnix.org/w/dhb9VMzyGASkiYxmeoYB7G

it looks like that 'enter' key is broken in non-hildonized gtk apps. both when keyboard is triggered by tapping in the input field or hardware key (search on d4).

in the video gedit is used. it is repeatable with any gtk program.

this issue especially harmful for devices without hardware keyboard, because it renders them unusable with non-hildonized programs.

**Comment by freemangordon** [comment]
Fixed in https://github.com/maemo-leste/hildon-input-method-framework/commit/dd1142e8edb0cf50d10b6180bb2fc38331dbe3fe
