### ISSUE TITLE
battery-applet: Preferred devices whitelist

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#70]
We probably need a whitelist of preferred devices. Some devices expose more than a single battery entity in UPower (or rather, UPower finds them), and there is no way to tell which one is the correct one (technology, type, etc - is all the same). We should therefore have a list of "preferred" names, which we prefer to the first generic match.

Not too hard to implement.

**Comment by MerlijnWajer** [comment]
When we implement this, also make sure that `mce` can use the whitelist as well.

**Comment by MerlijnWajer** [comment]
Moved, since I don't think this is too relevant/important atm.

**Comment by MerlijnWajer** [comment]
This is being worked on now by @spinal84 - https://github.com/maemo-leste/status-area-applet-battery/pull/2

**Comment by spinal84** [comment]
Implemented as devices blacklist in MCE / battery applet.

**Comment by MerlijnWajer** [comment]
Cool, we'll have to revisit this at some point and see if we can live without device-specific things, but this is good for now I think!
