### ISSUE TITLE
Can't upgrade hildon-base

### ISSUE THREAD

**Issue by vandys** [maemo-leste/bugtracker#702]
E: This installation run will require temporarily removing the essential package hildon-base:arm64 due to a Conflicts/Pre-Depends loop. This is often bad, but if you really want to do it, activate the APT::Force-LoopBreak option.
E: Reverse conflicts early remove for package 'elogind:arm64' failed

**Comment by MerlijnWajer** [comment]
I believe it would only be removed temporary during the upgrade, meaning that you will still have it installed at the end. We're still making some breaking changes to chimaera, but hopefully this is the last before the release.

**Comment by MerlijnWajer** [comment]
Did this solve your problem? (If so, please let me know, so we can close the ticket)

**Comment by vandys** [comment]
Yes, I used apt -o 'APT::Force-LoopBreak=1' dist-upgrade
and it completed OK.  Actually, it spontaneously rebooted before I could tell it to, but it's been doing that recently anyway.  It did come back, and the SW appears all up to date.  Thanks!

**Comment by MerlijnWajer** [comment]
Thanks. The spontaneous reboots sound bad. Maybe it makes sense to open an issue for that? :)

**Comment by vandys** [comment]
I'm holding off on the reboot thing, hoping to pick up some clues so it's easier to chase.
