### ISSUE TITLE
Changing Shells results in DBUS breaking

### ISSUE THREAD

**Issue by ahmedbodi** [maemo-leste/bugtracker#709]
I changed the shell from bash to xonsh for root and user. Changing it back resolved my issues. (Resulted in the lock button, wifi, etc not working)

boot log output

Starting dbus user session
File /etc/osso-af-init/real-af-dbus line 26
start) 
Syntax error, unmatched ")" at line 26, column 5

**Comment by IMbackK** [comment]
so what is /bin/sh linked to on your system?

**Comment by ahmedbodi** [comment]
/bin/sh is still sh, its just the user's shell is set to xonsh. (this was done by running chsh -s /usr/bin/xonsh

**Comment by IMbackK** [comment]
should be fixed in devel as soon as the package builds
