### ISSUE TITLE
mce: KEY_SCREENLOCK on Droid4?

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#71]
See #65 

The Droid4 has a KEY_POWER, and VOLUME_UP and VOLUME_DOWN, but no KEY_SCREENLOCK.

Personally, I think both KEY_SCREENLOCK and KEY_POWER do useful stuff on the N900 -- I was wondering if we can perhaps consider KEY_POWER "Held" for a longer time as KEY_SCREENLOCK as well? Or the other way around?

Or perhaps KEY_POWER and VOLUME_UP as KEY_SCREENLOCK ?

**Comment by dderby** [comment]
How about single tap KEY_POWER to lock, double tap KEY_POWER to bring up the menu (or the other way around)?

**Comment by freemangordon** [comment]
that's already supported by mce/tklock in one way or another - double-click on power key locks the device, etc.

**Comment by MerlijnWajer** [comment]
What you describe is likely what we need. I'll see if I can get that to work.

**Comment by MerlijnWajer** [comment]
Pressing the power key twice does indeed lock screen, but it can't be used to unlock. That is a problem on the droid4 - you have to open the keyboard slider to then "unlock".

Also -- if anyone still has elogind installed, uninstall it! (It powers off the machine when the press the button...)

**Comment by MerlijnWajer** [comment]
New MCE (`1.8.128.4`) fixes this issue. Use power button once to get power menu, twice to unlock it. When locked, use power button once to get slider.
