### ISSUE TITLE
N900: make 850mhz cpu by default.

### ISSUE THREAD

**Issue by carlosgonz0** [maemo-leste/bugtracker#712]

**Comment by IMbackK** [comment]
no, we will never overclock the or any device by default

**Comment by MerlijnWajer** [comment]
@IMbackK - maybe we can turn this issue into 'how to overclock n900' and keep it open until we have this sorted out, because I don't think we have this in the kernel/dts yet, right?

**Comment by MerlijnWajer** [comment]
Ah, nevermind, I see that we already have this in the kernel
