### ISSUE TITLE
N900: Kernel package (.deb) generation

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#72]
I  think it would be quite nice if we would be able to ship kernel upgrades to our devices, since there's now quite some people trying images with varying kernels (depending on when they installed), so it'd be good to be able to provide updates.

Droid4 is complex - let's start with N900.

**Comment by dderby** [comment]
I can pick this one up if you like.  I've already been building kernel deb packages for the N900.

**Comment by MerlijnWajer** [comment]
Would be nice - I am not sure how to actually proceed, though, from, say, a CI point of view.

I don't know if we need CI, but that's the usual path for debs to enter the repo. We can also import debs manually.

If we do CI, we'll need perhaps a repo per platform-kernel (due to how our CI works).

Perhaps @parazyd also has some ideas.

**Comment by MerlijnWajer** [comment]
Looks like I can't assign the issue to you (as well), maybe you need to be a collaborator on GH first.

**Comment by parazyd** [comment]
Yep, for every platform we need a new Jenkins job and, ideally, a separate git repository.

In `debian/control` we can tell reprepro which repo component to put the deb in.

**Comment by MerlijnWajer** [comment]
We now have `linux-image-n900`. Before you install it, ensure that `/boot/{zImage,uImage}` do not exist (rename them). This is only required once.

@parazyd - I do not know how to proceed, but it seems like building the kernels in jenkins was real painful. So we can perhaps to just do this semi-manually for now?

I'd be fine with that, and just close the ticket.

@parazyd  - perhaps you can chat with @dderby on how to proceed.

**Comment by parazyd** [comment]
I've built it on the ARM build slave manually for now.

I'll try to come up with a script or two to enable triggering this from our jenkins machine and automate the process.

**Comment by MerlijnWajer** [comment]
Once we have the scripts, shall we close the issue?
