### ISSUE TITLE
RFC: battery/charger handling in Leste

### ISSUE THREAD

**Issue by sicelo** [maemo-leste/bugtracker#726]
~`mce`~ Maemo Leste currently monitors the first battery and charger reported by `upower`. in most cases, these are the correct items to monitor.

however, there are devices which may report multiple batteries. a prime example is the pinephone, with the keyboard attachment, which includes a battery that can power the system.

thus, perhaps it is time to rethink our battery/charger handling. i can think of the following options, in order of complexity:

1. use `upower`'s DisplayDevice, which is an aggregation of all supplies that `upower` detects. this is easy to implement, and should be quite robust. Phosh, for example, uses this method. Downside is that you cannot know the state of a specific battery in case you have more than one
2. keep our 'manual' supply monitoring, but process all supplies, ideally displaying an icon for each. Upside is that you can see the state of each battery separately
3. implement both (1) and (2), then provide a configuration option (via gconf?) to switch between the two

What do others think? I could, subject to available time, offer to work on whatever becomes the final decision

**Comment by IMbackK** [comment]
I would like to note that this is not mces wheelhouse at all, the upower code in mce is only used for the notification light all the interfaces of that module are unused. temporarly we do use one of the interfaces for low voltage shutdown that really needs to go somwhere else and i consider this a temporary hack for the benefit of the mapphone bootloader

**Comment by sicelo** [comment]
I know the status item for battery is independent, yes. Ideally, I think, both `mce` and that status item should be interconnected somehow (e.g. use some common library). Right now, depending on the nature of the changes being made, one has to remember to make the same modification in **both** the status item and `mce`.

Based on your reply @IMbackK , it sounds like `mce` should definitely switch to the composite device.

**Comment by IMbackK** [comment]
the mce module should simply be removed entirely, its serves no real purpose. Protecting the battery is the domain of the kernel and or upower and enabling the patterns is a ui descision that should be left to the ui, ie the batter applet.
