### ISSUE TITLE
sphone: enhancement request: change button labels to indicate call ended

### ISSUE THREAD

**Issue by sicelo** [maemo-leste/bugtracker#727]
https://github.com/maemo-leste/sphone/commit/ab23a864abe3ceb6ec55ec37d1c72dd299611bdc made the window linger for a while after a call is ended, to avoid user confusion when the window disappears immediately.

however, it also gives the impression that the call is still ongoing, so some users (myself? ... or users with per second billing on calls) start pressing the Hangup button frantically trying to end the call.

idea: when the call is ended, and while waiting for the 5s to elapse, change the button text from "Hangup" to "Call Ended" or similar text. N9, for example, shows "Disconnecting..."

Less importantly, perhaps deactivate all buttons at that point as well

**Comment by IMbackK** [comment]
this is implemented now, and will be in the next release
