### ISSUE TITLE
enhancement request: wifi icon in status menu: indicate signal strength

### ISSUE THREAD

**Issue by sicelo** [maemo-leste/bugtracker#729]
Just like with the cellular icon, it would be great if the wifi icon indicates the signal strength at a glance. Then users will not need to install something like https://github.com/maemo-leste-extras/wifi-signal-applet/ to get this basic functionality

Possibly useful info for implementation: `gdbus call -y -d com.nokia.icd2 -o /com/nokia/icd2 -m com.nokia.icd2.statistics_req` causes the signal strength to be emitted in `statistics_sig` signal

**Comment by IMbackK** [comment]
yeah, as a stop gap we could simply add that applet as default.
I also think that the simply-brightness-applet is essentially mandatory and should also be in the core install

**Comment by sicelo** [comment]
I personally do not like having lots of icons there (clutter?), so
adding the applet in default installs would be a 'regression' for me :-P

I opened the issue to raise awareness about the possibility, and also to
remind myself to look into implementing it in future if no one else
beats me to it

**Comment by sicelo** [comment]
i understand that having it update on status menu all the time can have power/cpu usage effects. https://github.com/maemo-leste/libicd-network-wpasupplicant/pull/2 will be sufficient for me , since it has the effect of updating the icon that shows up when tapping on the status menu.
