### ISSUE TITLE
wpa_supplicant icd2 plugin

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#73]
Seeing that we're probably going to switch to icd2 soon, we have to look at wpa_supplicant plugin.

There's this thread: http://maemo.org/community/maemo-developers/libicd-network-wpa/?org_openpsa_qbpager_net_nemein_discussion_posts_page=1

I downloaded the repo from http://web.archive.org/web/20090310161342/http://svn.javispedro.com:80/libicd-network-wpa/trunk/

Everything is there, except for `gconf/network-type.xml`

There are also 5 revisions missing (there is a revision 16 somewhere on archive.org, but that's also not a complete snapshot and more useless).

Does anyone else have a more recent version? Or shall we just take inspiration from this repo and start hacking a new one?

**Comment by MerlijnWajer** [comment]
Maybe the guy is still around, and we can just ask him.

**Comment by sicelo** [comment]
Yes, he is around (at least on Twitter - same username)

**Comment by MerlijnWajer** [comment]
Want to direct him to our webpage/maemo-thread and/or IRC? :)

**Comment by sicelo** [comment]
Let me see if I can :)

**Comment by MerlijnWajer** [comment]
See https://garage.maemo.org/projects/libicd-wpa/

**Comment by javispedro** [comment]
Yes, I mirrored everything to the Garage git repository. 

However, take into an account I didn't have much idea how ICD worked at the time, nor there is any GUI for configuring it or anything.

**Comment by MerlijnWajer** [comment]
@javispedro I see - thanks. Do you have any interest in perhaps working on this? We have open source icd2 and also connui.

**Comment by javispedro** [comment]
Sadly no -- too busy.

**Comment by MerlijnWajer** [comment]
I will see if I can have a basic thing working on wednesday.

**Comment by MerlijnWajer** [comment]
Maybe take this https://github.com/community-ssu/libicd-network-wlan and convert it to wpa_supplicant.

**Comment by MerlijnWajer** [comment]
Very much wip, doesn't do anything yet, but compiles, when I verify it does the right things icd2-api wise, I will add in my wpa_supplicant code. https://github.com/maemo-leste/libicd-network-wpasupplicant

**Comment by MerlijnWajer** [comment]
OK, I got it to respond to scans. For my own reference, there are python dbus examples here: https://w1.fi/cgit/hostap/tree/wpa_supplicant/examples

@parazyd - could you reflect on what would be the best way to start wpasupplicant with dbus enabled? It cannot be set from config, and I currently just edited the devuan networking scripts. We need a better solution.

**Comment by MerlijnWajer** [comment]
Oh, and there is the API doc: https://w1.fi/wpa_supplicant/devel/dbus.html

**Comment by MerlijnWajer** [comment]
Made some progress by flensing libicd-network-wlan and adding basic wpa supplicant support. This is just a synthetic test:

![N900 supplicant](https://wizzup.org/n900-icd2-wpasupplicant-initial.png)

Some notes to self:

* https://developer.gnome.org/NetworkManager/stable/settings-802-11-wireless-security.html
* http://techgenix.com/80211i-wpa-rsn-wi-fi-security/

**Comment by MerlijnWajer** [comment]
There is now `libicd-network-wpasupplicant` in the repos. It's less than alpha quality, but if you know how to use it, it works stable. I wiicant` in repo. It's pre-alpha quality, but if you know how to use it, it works quite well. I will be working on making it stable quality - main things right now are missing eap support and the fact that you should *not* use the status area applet to connect to a new, unknown network. Just do it from settings->internet connectivity.

**Comment by MerlijnWajer** [comment]
There are definitely things to improve here still, but I'm going to close this ticket, since I think the state of this plugin is good enough for the alpha.

**Comment by MerlijnWajer** [comment]
Oh, and just for the record, easy-wlan (adding/connecting directly from scan results) should not also work.
