### ISSUE TITLE
Conversation XMPP/Jabber notification sound and light

### ISSUE THREAD

**Issue by ekoninsp** [maemo-leste/bugtracker#739]
Dear Team,
I have used Maemo leste on my devices Nokia N900 and Droid 4, my problem is after setup Voip account (I use xmpp / jabber) most of the time I did'nt get notification when messege received (no sound and also no notification light on led), I should manually open "conversation" to check if any message received. this is happend on both nokia n900 and  droid 4. I have changed manually tone file (taken from original sound and ringtone n900) and put it on ".sound" folder but stil the same.
email is fine and worked as expected (sound, led light, and also home/menu button blinking).

-regards

**Comment by MerlijnWajer** [comment]
This should actually work if you switch to chimaera-devel -- you'll need to restart the device though. Then vibration, persistent notification and sound should work.

**Comment by Arno1103** [comment]
@ekoninsp Notifications, vibration and LED should work in -devel but for ringtones in .sound folder, default permission seems wrong: running chmod +r solved the issue for me.

**Comment by ekoninsp** [comment]
wow... amazing.... #LOL.
thank you @MerlijnWajer  @Arno1103 ... switch into devel really solved the problem....
and also I see many other update in devel... Hopefully Maemo Leste will get better..
Telegram and whatsapp via xmpp also running very well in leste conversation, telegram and WA contact synced without issue.

**Comment by MerlijnWajer** [comment]
We would like to document these kind of setups on the wiki

**Comment by ekoninsp** [comment]
I'm using Slidge on my own server bermano.reiko.cloud for whatsapp transport via xmpp (since maemo 5) :D
or you can use hot-chilli.im (https://hot-chilli.im) since hot-chilli.im also serve whatsapp, telegram, skype, hangout and few more transport layer for free.
but as you know whatsapp via xmpp will break the end to end encryption, so if privacy is your concern running slidge on your own server will be better. v^_^
as additional info, hot-chilli required TLS v1.3, this is not an issue with your leste or telepahty version in leste. but for maemo 5 user need a little trick to get it worked (It seems like TLS has been a topic of conversation on maemo.org for a long time)

**Comment by ekoninsp** [comment]
slidge is already available in the debian repo 64bit, with single package installer for all services(wa, telegram etc), just wondering will the arm32 version be available? or maybe the leste team is interested to built it? :D

**Comment by MerlijnWajer** [comment]
@ekoninsp - getting back to you rather late here, but that's good to hear. For your whatsapp purposes, I suppose you still have an android/ios phone somewhere to manage the account?

**Comment by MerlijnWajer** [comment]
Meanwhile, I'll close the issue, but please feel free to reply here or to make a new issue if you want something packaged
