### ISSUE TITLE
Shutdown Issue and Notification light after update

### ISSUE THREAD

**Issue by ekoninsp** [maemo-leste/bugtracker#749]
Hello team, I found some issues after doing leste update on my droid 4 device (apt update & apt upgrade). 
i am not sure which one is causing the problem, because I see there are so many updates (kernel, mce, hildon etc).

1. My first issue is I can't shutdown properly, if I do "sudo halt", then the device doesn't turn off but reboots (yes, i can turn off the device from kexecmenu | shutdown), but if I see, every time I do halt the mmcblk0p1(/boot) partition is not clearly unmounted, so the next boot always has a check force(fsck), i am worried this will cause corruption if it happens too often.
2. "notification light" and "sound notification" no longer work (previously they worked fine) if I change it from the settings menu | notification light (device on, text message received etc) there is no effect, the led that works is only the charging sign.

Please help how can I solve it, should I start again from a fresh image or a new installation.
apart from the above 2 things everything looks very good at the moment, and thanks to the team, we have a decent conversation with the latest update (there is a context menu).

~regards

**Comment by freemangordon** [comment]
latest omap kernel has shutdown/reboot regression we are yet to find the reason for.

for notifications, now you mention it, there seems to be an issue, @IMbackK - do you have an idea?

**Comment by IMbackK** [comment]
since nothing else related changed, i suspect the kernel update also broke this one, i will investigate tomorrow

**Comment by IMbackK** [comment]
so we are missing the notification light leds due dts changes masking them to the second problem is an easy fix. Im not sure why this would stop sound notification from working.

EDIT: notification sounds seam to work perfectly fine here

**Comment by IMbackK** [comment]
@ekoninsp due to defficancies in our audio setup, notifications are currently played at media volume NOT at the volume set in the profile (besides 0) can you confirm your media volume is non-zero?

**Comment by IMbackK** [comment]
@ekoninsp https://github.com/maemo-leste/droid4-linux/commit/a4c7be3a57dd0372096382942c080178cb99f954 fixes the notification light issue, will take some time to propagate to the repos.

i opened a new bug https://github.com/maemo-leste/bugtracker/issues/750 for the shutdown problem as this is a separate issue.

I cant reproduce any problem with notification sounds, if this issue persists feal free open another bug with this issues specifically.

**Comment by ekoninsp** [comment]
Hallo Team, Thank for the respond..
@IMbackK , Sorry my mistake.. sound notification works fine
