### ISSUE TITLE
3G data support/integration

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#76]
ofono data works, but we need to figure out how to integrate it

**Comment by MerlijnWajer** [comment]
For those interested, this is an helpful guide. http://musicnaut.iki.fi/txt/nokia_modem.txt

On Leste you currently need to `modprobe nokia-modem pm=1` before making the symlink.

**Comment by parazyd** [comment]
@MerlijnWajer Shall we change the N900 kernel cmdline to have `nokia-modem.pm=1`?

**Comment by MerlijnWajer** [comment]
Either that, or just remove it entirely (and have some module config specify it)

**Comment by MerlijnWajer** [comment]
Plan forward is to make ofono/gprs icd2 plugin, wrote up support for connui/gprs and then we should be good to go.

**Comment by MerlijnWajer** [comment]
@jonwil @freemangordon - the current fremantle plugin is closed, and I'm wondering if it makes sense for me to wait on a partial RE of that plugin. I think with some schemas I should be able to just make this plugin with ofono dbus interface and some scripts? Or is there something large I am missing?

I guess for compatiblity reasons it does make sense to know what kind of gconf keys exist, but I can concievably get most of those my main fremantle phone?

**Comment by MerlijnWajer** [comment]
Pasting an old but relevant conversation in here:

<pre>
15:05 < jonwil> The gconf keys its reading are as follows:
15:05 < jonwil> reading/writing
15:06 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_roaming_disabled
15:06 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_attached_timeout
15:06 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_detached_timeout
15:06 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_resumed_timeout
15:07 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_no_coverage_timeout
15:07 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_call_timeout
15:07 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_cs_call_timeout
15:07 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_routing_timeout
15:07 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_location_timeout
15:08 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_roaming_tx_bytes
15:08 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_roaming_rx_bytes
15:08 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_home_tx_bytes
15:08 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_home_rx_bytes
15:08 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_roaming_last_notification
15:09 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_roaming_notification_period
15:10 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_roaming_last_notification
15:10 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_home_notification_period
15:10 < jonwil>  /system/osso/connectivity/network_type/GPRS/gprs_home_last_notification
15:13 < jonwil>  /system/osso/connectivity/IAP/xxx/type
15:13 < jonwil>  /system/osso/connectivity/IAP/xxx/sim_imsi
15:13 < jonwil>  /system/osso/connectivity/IAP/xxx/name
15:17 < jonwil>  /system/osso/connectivity/IAP/xxx/ipv4_autodns
15:17 < jonwil>  /system/osso/connectivity/IAP/xxx/ipv4_dns1
15:17 < jonwil>  /system/osso/connectivity/IAP/xxx/ipv4_dns2
15:18 < jonwil>  /system/osso/connectivity/IAP/xxx/ipv4_type
15:18 < jonwil>  /system/osso/connectivity/IAP/xxx/ipv4_address
15:18 < jonwil>  /system/osso/connectivity/IAP/xxx/gprs_accesspointname
15:18 < jonwil>  /system/osso/connectivity/IAP/xxx/gprs_username
15:19 < jonwil>  /system/osso/connectivity/IAP/xxx/gprs_password
15:20 < jonwil> That's the lot as far as I can see
15:21 < jonwil> Its also using /etc/gprs/icd-gprs-down.sh and /etc/gprs/icd-gprs-up.sh
15:22 < Wizzup> right, thanks!
15:22 < Wizzup> I guess there should also be some package with default APN usernames and passwords...
15:24 < Wizzup> https://wiki.apnchanger.org/Netherlands like this I guess
15:24 < Wizzup> https://wiki.apnchanger.org/Australia
15:24 < jonwil> package operator-wizzard-settings is relavent here
15:25 < Wizzup> great, that's what I was looking for
15:25 < jonwil> also package ota-settings relates too (looks like its for handling settings sent over the air)
15:29 < jonwil> and package gprs-provisioning is also related (it seems to be what creates the IAP and sets all the settings
15:29 < Wizzup> this will be fun...
15:29 < jonwil> The settings it sets under /system/osso/connectivity/IAP/xxx are
15:33 < jonwil> gprs_accesspointname, gprs_username, gprs_password, sim_imsi, name, ipv4_address, ipv4_type, ipv4_dns1, ipv4_dns2, ipv4_autodns, type, ask_password, proxy_http, proxy_http_port, proxy_https, proxy_https_port, proxy_ftp, proxy_ftp_port and proxytype
15:33 < jonwil> I suspect a clone of gprs-provisioning (with appropriate mods) is the way to go
15:47 < jonwil> its gprs-provisioning  that reads the configs in operator-wizard-settings btw
</pre>

**Comment by MerlijnWajer** [comment]
#195 and #196 are also related. We should perhaps also look at the connui code that is used to talk to ofono, this might help a lot.

**Comment by MerlijnWajer** [comment]
We should also look at `operator-wizzard-settings`, `ota-settings` and `gprs-provisioning` packages from Fremantle and see if we can use them (or at least what they do, and if we need them).

**Comment by jonwil** [comment]
operator-wizard-settings holds the fixed settings for operators and should be fine to use as-is (its just text files)
gprs-provisioning is what handles taking the settings from the files in operator-wizard-settings and sets things in gconf.
ota-settings handles taking settings sent over the air and sets settings.

**Comment by jonwil** [comment]
btw I think cloning gprs-provisioning and ota-settings probably need to be cloned.

**Comment by MerlijnWajer** [comment]
Alright, so maybe we'll need to update operator-wizard-settings with new values (later). I will start playing with gdbus(-codegen?) and ofono, see if I can get the basics to work. Then, when we have fremantle gprs plugin re and perhaps also gprs-provisioning and ota-settings, we can try to make it into a nice plugin for icd2.

**Comment by MerlijnWajer** [comment]
On gentoo, probably other distros too, there is also this package: net-misc/mobile-broadband-provider-info-20170310::gentoo - https://wiki.gnome.org/Projects/NetworkManager/MobileBroadband

**Comment by pavelmachek** [comment]
With ofono, it should be possible/easy to create gprs connection. unicsy_demo has code for that.

**Comment by MerlijnWajer** [comment]
Right - I have gotten it to work with mdbus2 as well (per http://musicnaut.iki.fi/txt/nokia_modem.txt). What we need to figure out (or just do/write) here is:

1. write plugin for icd2 to interface with ofono (look at or share with connman, probably)
2. read maemo gconf plugins for gprs
3. reverse UI bits that are not yet FOSS

and then we should have a basic 'clone' of what Maemo on the N900 has for data.

I'm planning to start doing this after we have the alpha ready. I've been wanting to start doing it already, but decided it's better to finish some other things before starting on this. (Of course, don't let me stop anyone else from doing it before I get to it :) ...)

**Comment by pavelmachek** [comment]
One option .. in ofone (from unicsy_demo), you can click "100%" button, then click "inet" button. It should set up GPRS data connection. (Ok, better integration is needed).

**Comment by MerlijnWajer** [comment]
@pavelmachek - we now have the fremantle modem/connection UI, but it still needs porting to ofono, once that is done, I guess icd plugin is next: https://talk.maemo.org/showthread.php?p=1556172#post1556172

**Comment by MerlijnWajer** [comment]
Making quite some progress here: https://github.com/maemo-leste/connui-cellular/compare/ofono-port

**Comment by MerlijnWajer** [comment]
https://wizzup.org/leste-connui-cellular-4g.png

**Comment by MerlijnWajer** [comment]
`libicd-network-ofono` should now activate contexts and set up IP properly.

**Comment by IMbackK** [comment]
This now works (in devel) (altho it is still buggy) the bugs are best addressed in separate issues
