### ISSUE TITLE
Provide a virtual keyboard for the console

### ISSUE THREAD

**Issue by dderby** [maemo-leste/bugtracker#79]
Possible options:
https://github.com/julianwi/fbkeyboard
https://github.com/zrafa/onscreenkeyboard
https://github.com/postmarketOS/osk-sdl

I also found this but I don't know what it's called, where it comes from or if it's open source:
http://musicnaut.iki.fi/img/nokia_770.jpg

**Comment by parazyd** [comment]
We have fbkeyboard in the repositories now.
