### ISSUE TITLE
Remove insserv and startpar packages

### ISSUE THREAD

**Issue by dderby** [maemo-leste/bugtracker#80]
`insserv` and `startpar` packages are made redundant by OpenRC and are incompatible with it.  The correct fix for this would probably be to add them to the `Conflicts` field which would ensure they are removed when the `openrc` package is installed.  This should really be fixed upstream but it might take a while to propagate down to Leste and as we're using OpenRC by default we might want to do something about it.

**Comment by parazyd** [comment]
We can purge them at the final point of the installation.

Devuan might fork OpenRC, and this can be solved, but let's not count on it yet as I alone don't have time to maintain OpenRC in Devuan and would need more people.

**Comment by parazyd** [comment]
Closing, since we've sent a patch to insserv upstream.
