### ISSUE TITLE
sysv-rc package has not been purged

### ISSUE THREAD

**Issue by dderby** [maemo-leste/bugtracker#81]
The `sysv-rc` package was removed (probably when `openrc` was installed) and there may be conf files left behind:

```
root@devuan:~# dpkg -l | grep ^r
rc  sysv-rc                                        2.88dsf-59.9                   all          System-V-like runlevel change mechanism
```

Not critical, but we probably shouldn't have any packages left in this state in the default install.

**Comment by parazyd** [comment]
Resolved in https://github.com/maemo-leste/image-builder/commit/9c6638babd39457cc1e851c555afab57be923df7
