### ISSUE TITLE
Hildon application menu does not display standard Devuan applications

### ISSUE THREAD

**Issue by dderby** [maemo-leste/bugtracker#82]
Standard Devuan applications install `.desktop` files directly under `/usr/share/applications` but Hildon looks for `.desktop` files under `/usr/share/applications/hildon`.

**Comment by MerlijnWajer** [comment]
I've been wondering if this is by design. And if we want to keep it like this.

Often the standard applications do not integrate too well with the small screen and touch (left-click only) input. But I guess for our current audience this is perfectly fine.

**Comment by dderby** [comment]
Fremantle was never designed to use standard applications but I thought that was one of the advantages of rebasing Hildon on top of Devuan.  There are already a few mobile applications in the Debian repositories and others can be used with by connecting an external mouse, via VNC, etc.  I think it would be a good idea to converge all apps into one menu unless there are plans to restrict the installation of standard apps.

We could also enhance the menu to use categories (I believe there was something for Fremantle `Catorize` which did this).  That way we could separate standard apps for Hildon apps.

**Comment by MerlijnWajer** [comment]
Fair enough - I am fine with either solutions. Do others have an opinion? @parazyd @freemangordon

**Comment by android-808** [comment]
Not sure, but Catorize may have had a memory leak.

Standard apps shipped with Devuan I imagine wouldn't make use of the extended desktop specification used in Maemo. Though not required, some apps may make use of it.
https://wiki.maemo.org/Desktop_file_format

**Comment by MerlijnWajer** [comment]
Does someone want to pick this up? Perhaps prepare a patch and see how well it works when we default to standard devuan applications.

**Comment by parazyd** [comment]
@MerlijnWajer @freemangordon Could we just change the path(s) to include `/usr/share/applications` instead of just `/usr/share/applications/hildon`?

**Comment by MerlijnWajer** [comment]
Can we specify more than one path? Then that could be a temporary fix.

**Comment by Juesto** [comment]
does hildon support folders? that should help in distinguishing,  if not perhaps we can make it show /usr/share/applications recursively

**Comment by parazyd** [comment]
Implemented in https://github.com/maemo-leste/hildon-desktop/commit/604d1167860d5750fffe097de121bd7a3e2885f7
