### ISSUE TITLE
Screen does not lock or turn off with lock switch anymore (N900)

### ISSUE THREAD

**Issue by sicelo** [maemo-leste/bugtracker#86]
After the recent upgrade of most packages, the lock switch does not cause the screen to be locked and turned off. It seems that `mce` does not run automatically at boot.

Related: the battery status also does not show up on the menu until it is manually killed and restarted.

Dbus?

**Comment by sicelo** [comment]
23:37 < Wizzup> so the issue seems to be mce or dbus related
23:38 < Wizzup> sicelo: so, what I did, is start mce by hand (mce 
                --force-syslog) then restart hildon-status-menu, and then 
                start (it wasn't running) systemui
23:38 < Wizzup> now it all 'works'
23:38 < Wizzup> going to reboot and see why this happens
23:40 < sicelo> systemui handles lock switch too? i know it handles power 
                button, which wasn't working too
23:40 < Wizzup> apparently.
23:57 < Wizzup> # cat /tmp/session_bus_address.user
23:57 < Wizzup> export DBUS_SESSION_BUS_ADDRESS=
23:57 < Wizzup> seems mce block on this
23:57 < Wizzup>         . /tmp/session_bus_address.user
23:57 < Wizzup>         /usr/sbin/waitdbus session
23:57 < Wizzup> so then the question is why that is not written properly
23:59 <@freemangordon> Wizzup: it is again that dbus shit :(
00:00 < Wizzup> yes, but why
00:00 < Wizzup> I don't understand why it fails
00:00 < Wizzup> seems like /etc/X11/Xsession.d/01dbus doesn't produce the 
                right file
00:00 < Wizzup> as in /tmp/dbus-info is OK
00:00 < Wizzup> but then when it cats it's empty
00:01 <@freemangordon> Wizzup: we hit that back then
00:01 <@freemangordon> thje reason is that stderr is not being flushed
00:02 <@freemangordon> anyway we should get rid of bdus being started by init 
                       system
00:02 <@freemangordon> *dbus
00:02 <@freemangordon> and leave only the one started by xsession
00:03 <@freemangordon> which would mean that mce should be started as part of 
                       xsession as well, or at least it should wait for X

**Comment by MerlijnWajer** [comment]
It seems that apt zealously adds extra init scripts to the default runlevel, causing multiple dbus session busses to run.

This command will fix it for now, after update:

`rm /etc/runlevels/default/{af-base-apps,af-startup,dundee,hulda,ofono}`

I will leave it to apt experts to figure out what to do -- either fix the dbus usage or have these init scripts not be installed.

**Comment by MerlijnWajer** [comment]
Here is a diff of the default-image /etc/runlevels/default and the one after the update:

```
0a1,3
> 
> ./etc/runlevels/default/
> ./etc/runlevels/default/af-base-apps
1a5
> ./etc/runlevels/default/af-startup
8a13
> ./etc/runlevels/default/dundee
10a16
> ./etc/runlevels/default/hulda
14a21
> ./etc/runlevels/default/ofono

```

**Comment by MerlijnWajer** [comment]
@parazyd - want to remove at least `af-startup`? Maybe on the fly also decide the same for `af-base-apps`?

I don't know what dundee and hulda are (yet). ofono can remain, of course.

**Comment by MerlijnWajer** [comment]
@parazyd said that he removed the init scripts from the packages. I had to remove them from my install manually, but once I removed the ones in /etc/init.d/ they did not come back.

Apt still complains:

```
update-rc.d: error: initscript does not exist: /etc/init.d/af-startup
update-rc.d: error: initscript does not exist: /etc/init.d/af-base-apps
```

Once that is fixed we can close the issue I think.

**Comment by MerlijnWajer** [comment]
Should be fixed now. On update (if you had the bad one installed) apt doesn't seem to remove the init scripts, but if you remove them manually (or use a recent image) you should be fine.
