### ISSUE TITLE
Issues VM presents for new users as of now

### ISSUE THREAD

**Issue by Juesto** [maemo-leste/bugtracker#88]
Using maemo-leste-1.0-amd64-virtual-20180207.vdi
Tested with VirtualBox 5.2.6
VM settings: Debian 64-bits or Linux 2.6 / 3.x / 4.x 64 bits. 1GB of RAM, 16MB of VRAM, 3D accel on. No Guest additions (Sluggish X!)
First boot warms about a symblink related to mtab (dont remember)
ACPI shutdown does not work (power button not working/cant test holding power button)
If X does not start up and instead drops into console: try removing -noreset from /etc/init.d/xorg to allow X to retry starting up.
SSH does not have root login enabled
VBox unlike vmware does not display console output properly, especially during shutdown. vmware does
tty encoding is ISO-8859-15 instead of UTF-8 (messed up debconf dialogs, etc)
packages to update: https://ptpb.pw/s4xV recommendation: not upgrade devuan stuff nor install elogind (devuan noise) and not upgrading policykit stuff. (disable the repos to be on the safe side just in case)
sample first upgrade without devuan repositories: https://ptpb.pw/TpOC
Current packages/After upgrade services seem to take too long to start but xorg and hildon does start ok. (aprox. time from startup until i can log in: ~4min https://ptpb.pw/59Rm ) desktop menu doesnt function.

**Comment by android-808** [comment]
Virtual Box 5.2.2, same image as above. 32MB VRAM, 2GB RAM though.
After issues with Guest Additions to start with, I started again from the initial download image and they are now working fine.  Certain updates require reboot (ie Update & Reboot -> Restarts with no X and some console messages - reboot -> Starts OK) but I have installed all updates (Devuan + Leste) up to the end of last week.
Changing to a console to log in as root does sometimes take a while for it to display login prompt but then works fine.

**Comment by Juesto** [comment]
had issues with X at first and i wasn't updating the system, it was hit and miss. -noreset remedied the issue but it still didn't always start up.
starting from two updates ago the services take long to start and it includes mce.

**Comment by android-808** [comment]
Clean install with VBox 5.2.2 as I encountered the issue with initscripts.  First boot no UI, second OK.  Updates installed but terminal won't open in UI.  Guest additions installed, no UI at all now.

Going to try with 5.2.8

**Comment by Juesto** [comment]
mce isn't starting, can you ssh?

**Comment by android-808** [comment]
Don't use ssh so unfortunately haven't tried it.  Check through the issues, there was one that had an issue with initscripts that needed manual intervention if upgraded between a certain time frame.

**Comment by Juesto** [comment]
interesting, will try new image later

**Comment by android-808** [comment]
The VM image hasn't been updated since the the 20180207 release. Upgrading from there should be ok MCE wise

@Juesto Recently I tend to only work on bits every now and again and don't spend as long working on projects when I do.  Too easily distracted.  Might go on irc during the week when I'm around.

**Comment by Juesto** [comment]
okay,  by new image i meant whenever a new one is created.
yes it works fine but with the services weird delay
no problem! see you there ;)

**Comment by Juesto** [comment]
Turns out all platforms were suffering the X not starting issue because fmg forgot about how exec works!

**Comment by MerlijnWajer** [comment]
exec doesn't mean the script waits for the execution. But as I said - yes, removing the `exec` in front of the dsme call in `/etc/init.d/dsme` will fix this issue. @parazyd will do it tonight.

**Comment by Juesto** [comment]
best to use start-stop-daemon but might not work well with dsme on the long run

Update: maemo-leste-1.0-amd64-virtual-20180308 on vmware
VMWare guest tools work nicely but it partially stops working on reboot but it is not really necessary to have the additions.
services "hung" fixed because the image removed some osso-af-startup scripts(?) related issues: #83 #86
