### ISSUE TITLE
Disable lifeguard reset at least until we enter Beta phase

### ISSUE THREAD

**Issue by dderby** [maemo-leste/bugtracker#89]
The lifeguard is supposed to reboot the device when an important system process crashes.  Right now it does more than that.  Resets are triggered when certain processes receive a SIGHUP (e.g. Xorg) or if they are shut down cleanly (e.g. when changing run levels).

This behaviour is annoying and slows down development and testing so it should be disabled, at least until we enter Beta phase.  On the N900 this is usually done with the `no-lifeguard-reset` R&D mode flag but there is no obvious way to disable it on the Droid 4 nor Allwinner devices so we need to disable it at OS level.

I'm not keen on re-enabling it even after Beta to be honest.  I know it was considered normal behaviour in Fremantle but I always thought this was horrible.  It is very aggressive to reset the device when a process crashes and may cause file system inconsistencies, etc.  Eventually we should completely replace the lifeguard with a process supervisor to restart critical processes automatically (not the system!) when they die.  `s6` might be a good option as it already has OpenRC integration.

**Comment by Juesto** [comment]
yes, it's also engaged on VM but nothing happens.
for regular users it's fine. I'd say it's the equivalent of windows.
i agree it's quite aggressive and a better method could be used

**Comment by freemangordon** [comment]
see https://github.com/maemo-leste/dsme/blob/master/modules/lifeguard.c#L821

**Comment by android-808** [comment]
What about making a dev package contain the file defined by FILE_REBOOT_OVERRIDE for now then.  If there are similar files needed to disable other features, could R&D mode features be replaced with a deb?

**Comment by dderby** [comment]
@android-808, the image-builder allows us to [overlay files over rootfs](https://github.com/maemo-leste/image-builder/tree/master/rootfs-overlay).  I think it would be better to place temporary fixes in there rather than create a deb package.

@freemangordon, thanks.  Unfortunately, touching `/etc/no_lg_reboots` does not seem to have any effect.  Changing runlevels still triggers a reboot.

On further testing, sending a SIGHUP to Xorg doesn't actually trigger a reboot on Leste.  It fails to restart and just locks up with a blank screen.  Perhaps if it actually restarted, the lifeguard would kick in.

**Comment by android-808** [comment]
I was thinking more about the second paragraph of the original post. Rather than playing with R&D flags having a package to trigger developer functions. Overlay method works for fresh images but what about in place upgrades? I wouldn't like it if a Dev spends ages trying to track down a specific issue to find a left over file is the culprit.

**Comment by IMbackK** [comment]
this is done
