### ISSUE TITLE
Droid4: Figure out why UPower isn't parsing capacity_level properly

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#90]
UPower should fall back to `capacity_level` if `capacity` is not available. This is (currently) the case on the Droid4. Yet UPower just reports: `Percentage: 0`.

I checked the UPower code and it should do the right thing. Unless our UPower is old, and they only recently added this support. Needs debugging.

If we fix this, then battery applet and mce battery-upower should work on the Droid4.

**Comment by MerlijnWajer** [comment]
Well, I figured it out. It only reads /capacity_level when ... the supplier is not of type battery, really makes you think...

Mailed kernel maintainers, maybe they can expose more properties: https://marc.info/?l=linux-omap&m=152010472624187&w=2 - if chip supports it.

Should probably also bug UPower people.

**Comment by MerlijnWajer** [comment]
I've also sent a mail to the devicekit-dev (upower) ML.

**Comment by MerlijnWajer** [comment]
@parazyd - I think we should just take upower from buster or similar (at least 0.99), fork it here, and build our modified version. I know what changes to make, but not how to proceed otherwise.

**Comment by MerlijnWajer** [comment]
This patch should fix this, against upower 0.99.7:

```From ff098237b1ce9fea4621d34aaeb42836ae87f04a Mon Sep 17 00:00:00 2001
From: Merlijn Wajer <merlijn@wizzup.org>
Date: Mon, 28 May 2018 22:49:24 +0200
Subject: [PATCH] linux/up-device-supply: add capacity_level reading for
 batteries

Not all batteries expose capacity; but they might expose capacity_level.
This makes it possible to get at least some battery percentage on
various mobile phones (like the Motorola Droid 4)
---
 src/linux/up-device-supply.c | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/src/linux/up-device-supply.c b/src/linux/up-device-supply.c
index 11a14e1..5af9a09 100644
--- a/src/linux/up-device-supply.c
+++ b/src/linux/up-device-supply.c
@@ -547,6 +547,7 @@ up_device_supply_refresh_battery (UpDeviceSupply *supply,
        gdouble energy_rate;
        gdouble capacity = 100.0f;
        gdouble percentage = 0.0f;
+       UpDeviceLevel level = UP_DEVICE_LEVEL_NONE;
        gdouble voltage;
        gint64 time_to_empty;
        gint64 time_to_full;
@@ -729,6 +730,8 @@ up_device_supply_refresh_battery (UpDeviceSupply *supply,
                 /* for devices which provide capacity, but not {energy,charge}_now */
                 if (energy < 0.1f && energy_full > 0.0f)
                     energy = energy_full * percentage / 100;
+       } else if (sysfs_file_exists(native_path, "capacity_level")) {
+               percentage = sysfs_get_capacity_level (native_path, &level);
         } else if (energy_full > 0.0f) {
                percentage = 100.0 * energy / energy_full;
                percentage = CLAMP(percentage, 0.0f, 100.0f);
--
2.17.0
```

**Comment by parazyd** [comment]
Applied here: https://github.com/maemo-leste/upower/commit/92d0c98b5259e16bf274a40492c27f821d220eb5

**Comment by MerlijnWajer** [comment]
Let's just close it. I'll re-open it if it seems not fixed.
